### ISSUE TITLE
Attach IDEA sources

### ISSUE THREAD

**Issue by shalupov** [JetBrains/gradle-intellij-plugin#1]
It would be really nice to navigate to IDEA CE sources from plugin sources.

It's possible it would require some IDEA modifications, so better to investigate it early.

**Comment by kaluzki** [comment]
I could not use your plugin:

Error:(2, 0) Cannot add extension with name 'idea', as there is an extension already registered with that name.

changing constants in org.jetbrains.intellij.IntelliJPlugin to


private static final CONFIGURATION_NAME = "ideaplus"
private static final EXTENSION_NAME = "ideaplus"


solved this problem (or is it just a symptom?)

I'm a bloody beginner to gradle, groovy and java at all. I wan't just to write a simple idea-plugin for PhpStorm and integrate it in travis-CI. Maybe you can provide some help for me?

**Comment by zolotov** [comment]
Fixes in 0.0.10
