### ISSUE TITLE
 support of cross product&language build and test

### ISSUE THREAD

**Issue by tuchg** [JetBrains/gradle-intellij-plugin#1001]
At present, there is a lack of an effective cross platform built and testing system.
 I need to use the whole product line (ic-java/kotlin, rd-c#, clion-c/c++, py...) at one time Build tests for. 
At present, the environment can only be switched by adjusting parameters each time,and waitting、downloading、testing、blabala.....failed!
it's a horrible experience.

**Comment by hsz** [comment]
@tuchg I'm not exactly sure of the purpose of your post.
What is your expectation? Could you provide any examples?

**Comment by tuchg** [comment]
@hsz

```kotlin
class CompletionTests : CompletionAutoPopupTestCase() {
  fun `testC#Completion`() {
        myFixture.configureByText("Test.cs", "")
        myFixture.type("System")
    }

    fun `testJavaCompletion`() {
        myFixture.configureByText("Test.java", "")
        myFixture.type("System")
    }

    fun `testKtCompletion`() {
        myFixture.configureByText("Test.kt", "")
        myFixture.type("System")
    }

    fun `testPythonCompletion`() {
        myFixture.configureByText("Test.py", "")
        myFixture.type("System")
    }
}
```
