### ISSUE TITLE
localPath does not work on macOS

### ISSUE THREAD

**Issue by jonnyzzz** [JetBrains/gradle-intellij-plugin#1006]
I download a DMG package of IntelliJ IDEA and try to use that one with the IntelliJ plugin SDK. 
The approach does not work because it is not able to find the `build.txt` in the macOS package (the file is under the `Resources` folder). 

Could you please consider
 - supporting macOS layout
 - let the code automatically detect the `IntelliJ IDEA*.app` folders under the `localPath` and resolve them (actually same for Windows/Linux)

Example `gradle.kts`
```gradle
intellij {
  localPath.set("unpacked IntelliJ DMG")
}
```

**Comment by jonnyzzz** [comment]
Nice, I will try. 

Is that possible to make the IJ SDK plugin figure that out automatically? IIRC in my case, it was only. That is quite painful in Gradle to find a `Contents` directory under an unpacked IDE folder. The `*.app` folder name is not static, it depends on the version and IDE name. 

```
/Users/hsz/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.215
```

**Comment by YannCebron** [comment]
the app folder name can be anything and located anywhere on disk. I don't think we should make any assumptions about these things

**Comment by jonnyzzz** [comment]
I'm exactly asking about that - let's not ask a user to have assumptions on that. Let's make a IJ plugin developer life easier :)

There are only a few lines of code to make the SDK plugin resolve any cases like that. On all supported OS. I have proof of the concept if you need it.

**Comment by hsz** [comment]
The `localPath` property is supposed to be used in the local environment by users who understand the purpose of such configuration.
Because the subdirectories auto-discovering feature may cause more side effects than solve, I'd keep it as it is.
