### ISSUE TITLE
Problems building .jar files with Kotlin/IntelliJ/Gradle from: gradlew build and from IDE

### ISSUE THREAD

**Issue by serge-hulne** [JetBrains/gradle-intellij-plugin#1017]
Hi, I am learning to code apps using Kotlin.

In order to learn Kotlin, I am trying to build console apps and desktop apps.

So far, I can run my hello world apps using gradlew run (or from the IDE).

However, I cannot seem to be able to build a .jar file which is runnable using:

```kotlin App.jar```
or
```java - jar App.jar```

exemple:
```
java -jar demo-jvm-1.0-SNAPSHOT.jar
Error: Unable to initialize main class MainKt
Caused by: java.lang.NoClassDefFoundError: androidx/compose/runtime/Composer
```

PS: I am new with Kotlin, but I am familiar with most of the build tools from all the languages in the top 10 of the TIOBE index.

One thing that puzzles me is why the default app generated by Gradle initor IntelliJ seems to come without a manifest file.
Another thing which I am unsure of is the actual qualified name of the main class : Is it “MainKt” or "projectName.Mainkt"or “org.example.MainKt” or something else (the build.gradel.kts file points to “MainKt” it seems).
When using the menu command: File->Project structure to add “Artifacts”, the main class is not detected by the dialog box.
When I edit a manifest file containing the following:

```
Manifest-Version: 1.0
Main-Class: MainKt
```

the class name MainKt is highlighted in red (with the hint: Cannot resolve class ‘MainKt’).

I am using:
```
Java : openjdk version "18.0.1.1" 2022-04-22
Kotlin: openjdk version "18.0.1.1" 2022-04-22
```

Gradle:
```
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------


Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18.0.1.1 (Homebrew 18.0.1.1+0)
OS:           Mac OS X 12.4 aarch64
```
IntelliJ:

```
IntelliJ IDEA 2022.1.2 (Community Edition)
Build #IC-221.5787.30, built on May 31, 2022
Runtime version: 11.0.15+10-b2043.56 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
    org.jetbrains.kotlin (221-1.7.0-release-281-IJ5591.52)
    org.jetbrains.kotlin-js-inspection-pack-plugin (0.0.9)

Kotlin: 221-1.7.0-release-281-IJ5591.52
```

**Comment by YannCebron** [comment]
This project is only about building plugins targeting the IntelliJ IDEs. Please see https://p5v.medium.com/kotlin-basics-create-executable-kotlin-jars-using-gradle-d17e9a8384b9 regarding your question.

**Comment by serge-hulne** [comment]
Thank you!

**Comment by Mefodys** [comment]
Use ./gradlew packageUberJarForCurrentOS

https://youtrack.jetbrains.com/issue/KT-66494/NoClassDefFoundError-androidx-compose-runtime-Composer-if-try-to-run-Compose-Desktop-jar#focus=Change-27-9459858.0-0
