### ISSUE TITLE
org/jetbrains/intellij/IntelliJPlugin : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by uwolfer** [JetBrains/gradle-intellij-plugin#102]
You have changed `sourceCompatibility` / `targetCompatibility` from 1.6 to 1.8 in 56c5794afd36e31caee90e3f41cf671c63c2258e.

This breaks support for building plugins for older IntelliJ versions. I still release my plugin for IntelliJ 14 which should support JDK 1.6 (some users on OS X require it; I have accidentally released 1.8 target level complied plugin some time ago and there were some complaints).

See: https://travis-ci.org/uwolfer/gerrit-intellij-plugin/builds/133607129#L194

Any strong reasons for not still supporting 1.6 in this plugin?

**Comment by zolotov** [comment]
Indeed you have to run gradle with jre1.8 but you still can use sourceCompatibility/targetCompatibility 1.6 for your plugin.

**Comment by uwolfer** [comment]
Ahh, you are right of course. ;) I used Travis CI config `jdk: openjdk6`. Updating to `oraclejdk8` fixes it.

Thanks.
