### ISSUE TITLE
Plugin Verifier can't find Gateway module

### ISSUE THREAD

**Issue by fioan89** [JetBrains/gradle-intellij-plugin#1027]
I'm working on a [plugin for Gateway](https://github.com/coder/coder-jetbrains) and I have a [Gatway module](https://github.com/coder/coder-jetbrains/blob/72abda5af3332c246d44a7646138f372d58a7317/src/main/resources/META-INF/plugin.xml#L10) declared as a dependency. `buildPlugin` and `runIde` tasks are fine, but `runPluginVerifier`  complains about missing dependencies:

`
Plugin com.coder.gateway:1.0.0 against GW-221.5921.14: 1 missing mandatory dependency. 1 usage of internal API
Missing dependencies:
    com.jetbrains.gateway: Plugin com.jetbrains.gateway is not available in Marketplace https://plugins.jetbrains.com
`

**Comment by hsz** [comment]
@fioan89 Could you please add me to the project?

**Comment by fioan89** [comment]
@hsz seems like I don't have permissions to add new people on the project. Is it ok if I just post the content of the plugin.xml?

**Comment by fioan89** [comment]
`
<idea-plugin>
    <id>com.coder.gateway</id>
    <name>Coder Gateway</name>
    <vendor>Coder</vendor>

    
    
    <depends>com.intellij.modules.platform</depends>
    <depends>com.jetbrains.gateway</depends>
    <extensions defaultExtensionNs="com.intellij">
        <applicationService serviceImplementation="com.coder.gateway.sdk.CoderRestClientService"></applicationService>
        <applicationService serviceImplementation="com.coder.gateway.services.CoderRecentWorkspaceConnectionsService"></applicationService>
    </extensions>
    <extensions defaultExtensionNs="com.jetbrains">
        <gatewayConnector implementation="com.coder.gateway.CoderGatewayMainView"/>
        <gatewayConnectionProvider implementation="com.coder.gateway.CoderGatewayConnectionProvider"/>
    </extensions>
</idea-plugin>

`
# IntelliJ Platform Artifacts Repositories
# -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html
pluginGroup=com.coder.gateway
pluginName=coder-gateway
# SemVer format -> https://semver.org
pluginVersion=1.0.0
# See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
# for insight into build numbers and IntelliJ Platform versions.
pluginSinceBuild=213
pluginUntilBuild=221.*
# IntelliJ Platform Properties -> https://github.com/JetBrains/gradle-intellij-plugin#intellij-platform-properties
# Gateway available build versions https://www.jetbrains.com/intellij-repository/snapshots and https://www.jetbrains.com/intellij-repository/releases
platformType=GW
platformVersion=221.5787.23-CUSTOM-SNAPSHOT
instrumentationCompiler=221.5787.23
platformDownloadSources=true
# Plugin Dependencies -> https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html
# Example: platformPlugins = com.intellij.java, com.jetbrains.php:203.4449.22
platformPlugins=
# Java language level used to compile sources and to generate the files for - Java 11 is required since 2020.3
javaVersion=11
# Gradle Releases -> https://github.com/gradle/gradle/releases
gradleVersion=7.4
# Opt-out flag for bundling Kotlin standard library.
# See https://plugins.jetbrains.com/docs/intellij/kotlin.html#kotlin-standard-library for details.
# suppress inspection "UnusedProperty"
kotlin.stdlib.default.dependency=false
`
This is what I have in the plugin.xml and gradle.properties

**Comment by hsz** [comment]
Looks like this is an issue with Plugin Verifier itself – the `com.jetbrains.gateway` plugin is not supposed to be resolved in JetBrains Marketplace as it is a module available in the GW release. Please ignore it for now.

**Comment by fioan89** [comment]
Thx... I believe a similar issue is raised by Gateway itself when installing the plugin from the disk, though the install is just fine. But I guess this needs to be raised with Gateway.

**Comment by YannCebron** [comment]
please watch https://youtrack.jetbrains.com/issue/MP-4677/Plugin-Verifier-cant-find-Gateway-module-on-Marketplace-bogus-error it's a problem in Plugin Verifier itself
