### ISSUE TITLE
Enable caching in `runPluginVerifier` task

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/gradle-intellij-plugin#1036]
Would be nice if CIs didn't need to re-run the verification if the inputs (plugin zip + IDE versions, assuming only non-snapshots are used) haven't changed.

Actually... AFAICS now in `org.jetbrains.intellij.IntelliJPlugin#configureRunPluginVerifierTask`, `outputs.upToDateWhen { false }` is used (aka "always re-run")... what's the reason for that?

**Comment by YannCebron** [comment]
AFAIU Too many factors. Including, but not limited, to specifying `EAP-SNAPSHOT`, broken download ZIP, usage of `listProductsReleases` to determine list of verification products (can change any time)

**Comment by PawelLipski** [comment]
Okay, that's what I was afraid of ☹️ feel free to close then
