### ISSUE TITLE
`classpath.index` shows up during `test` tasks in `build/classes/` of projects where gradle-intellij-plugin is enabled

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/gradle-intellij-plugin#1039]
**Describe the bug**

That's what I'm getting after running `./gradlew test` ☹️ 
```
$ find . -name classpath.index | xargs sha256sum
b9cb27dd3a72a75925fac834110ca2c61614bfda14e6135e022ee4ce7c77e9cf  ./frontend/base/build/resources/main/classpath.index
cd2a2686b0b01d20db40487437f230d6685d5e1973e7a219e5acb8492085b17d  ./frontend/base/build/classes/java/main/classpath.index
bc359d856f409b614a522c6d6ee5414825737c7292079ccd854a9bff2829633d  ./frontend/base/build/classes/java/test/classpath.index
871b91a4b594b69c5249dcd64d90cbd81567cc07e15d5f7b739171d546c242ab  ./build/resources/main/classpath.index
f99b011154a200f6a287c7aab59f16f2d6d49c0c5548926493ff18d9bb878d3b  ./build/classes/java/test/classpath.index
```

That wouldn't be such a problem... but it heavily messes up Gradle caching :/
* Gradle reports (quite reasonably) that it doesn't know where the classpath.index came from in what's otherwise an **output** directory of `compileJava` or `processResources` task... and hence refrains from using the cached data for this output folders.
* Even worse, classpath.index (with its apparently non-deterministic contents?) effectively disables caching for the tasks that use affected `build/classes/` as **inputs** :/

**To Reproduce**

What `frontend:base` and root project have in common in the above example... is that:
* they've got gradle-intellij-plugin enabled AND
* they've got some tests

I'd assume this two conditions are enough to observe `classpath.index` showing up in `build/classes/`. This warning indicates that `PathClassLoader` (which IIUC generates these classpath.index files) is used for tests in (sub)projects with gradle-intellij-plugin enabled:
```
> Task :test
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "com.intellij.util.lang.PathClassLoader"). To use archived non-system classes, this property must be not be set
```

**Expected behavior**

Well, classpath.index not showing up, or at least showing up **not** in an output directory of any Gradle task other than `test` itself :/

**Environment:**

 - OS: Fedora 36, probably irrelevant tho
 - JDK: `openjdk version "11.0.15" 2022-04-19`
 - Gradle IntelliJ Plugin Version: 1.6.0
 - Gradle Version: 7.4.2

**Workaround**

After `./gradlew test` in CI, run:
```shell
find . -name classpath.index -delete || true
```
This fixes the problem but is hackish at best :/

**Attempted workarounds (seem to have no effect)**

```gradle
      instrumentCode.enabled = false
      instrumentTestCode.enabled = false
      instrumentUiTestCode.enabled = false
      setupInstrumentCode.enabled = false
```
or
```gradle
  test {
    systemProperty "idea.classpath.index.enabled", "false"
  }
```
or
```shell
./gradlew -Didea.classpath.index.enabled=false test
```

**Comment by hsz** [comment]
The new `PathClassLoader` introduced for `221+` unfortunately ignores the `idea.classpath.index.enabled=false` flag, so manual removing of the `classpath.index` files is currently necessary.

I've implemented it with https://github.com/JetBrains/gradle-intellij-plugin/commit/7eec2ba62d6c61bfa9ad8bf1876dfd6dea9a074f

It should be available for testing in the nightly release as soon as this build will finish: https://github.com/JetBrains/gradle-intellij-plugin/actions/runs/2576018618

**Comment by larsgrefer** [comment]
After Updating to IntelliJ Ultimate 2022.3 my Gradle Build randomly fails with errors like this:

```
> Task :foo:jar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':foo:jar'.
> Entry classpath.index is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.6/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

```

Seems like this classpath.index file would be packaged into the libraries jar file

**Comment by larsgrefer** [comment]
This issue seems to be tracked in youtrack aswell: https://youtrack.jetbrains.com/issue/IDEA-305759/Gradle-cannot-handle-classpath.index-duplicates

**Comment by hsz** [comment]
@larsgrefer Please file a new issue and provide more details and a reproducible example.

**Comment by larsgrefer** [comment]
@hsz After a bit more digging, I noticed that this might be the wrong issue tracker. I'm sorry.

I'm just building a "regular" java library/application with Gradle and IntelliJ without explicitly using the _Gradle IntelliJ Plugin_

**Comment by hsz** [comment]
Thanks for the clarification.

**Comment by ericl-billgo** [comment]
FWIW, I also just started getting this issue today. No-one else on my team is having the issue but me and I am fairly certain I am the only one on the latest version of IntelliJ
![Screen Shot 2022-12-05 at 1 14 29 PM](https://user-images.githubusercontent.com/82050188/205734395-3c616afe-e100-4535-a775-2f3d077a15cd.png)
Any workaround? I guess I can always downgrade back to the previous version (hopefully this fixes it).

**Comment by hsz** [comment]
@ericl-billgo Is this actually related to the Gradle IntelliJ Plugin – a tool for creating plugins for IDEs? ;)

**Comment by ericl-billgo** [comment]
@hsz I don't know. All I know is that this is the only place Google sent me when I entered my exact error `Entry classpath.index is a duplicate but no duplicate handling strategy has been set`. Since I am new to Java (but been doing this for 25 years) I am still trying to figure out where to get help. I think my answer is in the link @larsgrefer posted 5 days ago... I will go investigate more.

**Comment by monosoul** [comment]
@ericl-billgo I'm also facing this issue. Add `-Didea.classpath.index.enabled=false` too [IntelliJ's JVM options](https://intellij-support.jetbrains.com/hc/en-us/articles/206544869-Configuring-JVM-options-and-platform-properties), that'll fix it
