### ISSUE TITLE
Cannot use SNAPSHOT plugin's version

### ISSUE THREAD

**Issue by ekudel** [JetBrains/gradle-intellij-plugin#1049]
**Describe the bug**

I'm trying to use 1.6.0-SNAPSHOT version of the plugin. I've added `https://oss.sonatype.org/content/repositories/snapshots/` URL into settings.gradle, but I get the following error:

```
> Could not resolve all files for configuration 'classpath'.
   > Could not resolve org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.6.0-SNAPSHOT.
     Required by:
         unspecified:unspecified:unspecified
      > Could not resolve org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.6.0-SNAPSHOT.
         > Could not get resource 'https://plugins.gradle.org/m2/org/jetbrains/intellij/plugins/gradle-intellij-plugin/1.6.0-SNAPSHOT/gradle-intellij-plugin-1.6.0-SNAPSHOT.pom'.
            > Could not GET 'https://repo.gradle.org/artifactory/jcenter/org/jetbrains/intellij/plugins/gradle-intellij-plugin/1.6.0-SNAPSHOT/gradle-intellij-plugin-1.6.0-SNAPSHOT.pom'. Received status code 409 from server: Conflict
```

The same issue with 1.7.0-SNAPSHOT

**Environment:**
 - OS: macOS 11.1
 - Gradle Version: 7.4.2

**Comment by ekudel** [comment]
@hsz But I've already added the "snapshots" repository as I mentioned (as specified in the documentation). What other configuration is required? "Release" version works well for me.

**Comment by hsz** [comment]
Do you have this custom repository placed before or after `gradlePluginPortal()`?

**Comment by ekudel** [comment]
@hsz Yes:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/6772218/177532913-29726ee0-5762-477a-b935-960cb77fd8c0.png">

**Comment by hsz** [comment]
Looks good. Which version of Java do you use?

**Comment by ekudel** [comment]
11.0.10

**Comment by abrooksv** [comment]
I had the same error, but I use the plugin as a direct dependency in my `build-logic` build to build a "convention" plugin:

build-logic/build.gradle.kts
```
plugins {
    `kotlin-dsl`
}

dependencies {
    implementation(libs.gradleplugin.intellij)
}
```

I had to switch out the group to: `gradleplugin-intellij = { module = "org.jetbrains.intellij:org.jetbrains.intellij.gradle.plugin", version.ref = "intellij-plugin" }`

and add to `build-logic/settings.gradle.kts`
```
dependencyResolutionManagement {
    repositories {
        maven("https://oss.sonatype.org/content/repositories/snapshots/")
        gradlePluginPortal()
    }
```

and standard `settings.gradle.kts`
```
pluginManagement {
    repositories {
        maven("https://oss.sonatype.org/content/repositories/snapshots/")
        gradlePluginPortal()
    }
}
```
