### ISSUE TITLE
External plugins: add classes directory to compile classpath

### ISSUE THREAD

**Issue by baron1405** [JetBrains/gradle-intellij-plugin#105]
Currently, the external plugin support assumes that a plugin will only consist of jars in the `lib` directory. Unfortunately, a number of plugins (e.g. [CheckStyle-IDEA](https://plugins.jetbrains.com/plugin/1065?pr=idea), [BashSupport](https://plugins.jetbrains.com/plugin/4230?pr=idea)) consist of `classes` and `META-INF` directories and may or may not have a `lib` directory. Because these classes are not added to the generated Ivy file, they do not show up on the classpath for running the IDE or executing tests.

**Comment by zolotov** [comment]
Thank you. Fixed. 0.1.6 will be uploaded a bit later

<img width="766" alt="screenshot 2016-06-03 21 00 47" src="https://cloud.githubusercontent.com/assets/140920/15788190/ef2b50be-29ce-11e6-96cc-a4021f1ed16c.png">

**Comment by baron1405** [comment]
Thanks for the great support!
