### ISSUE TITLE
Subproject forced to use `repositories { mavenCentral() }`

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [JetBrains/gradle-intellij-plugin#1058]
Currently there is a new way to indicate the repositories for all projects:

```kotlin
// settings.gradle.kts
dependencyResolutionManagement {
    repositories {
        mavenCentral()
        ...
    }
}
```

But IntelliJ plugin is forcing me to use 

```kotlin
// intellij-plugin-subproject
repositories {
    mavenCentral()
}
```

I would expect that I do not have to provide the repository there.

**Comment by hsz** [comment]
Unfortunately, due to the Gradle issue, it's not possible to use the `dependencyResolutionManagement` by the plugin:
https://github.com/gradle/gradle/issues/15754

**Comment by hsz** [comment]
Duplicate of #776
