### ISSUE TITLE
Introduce jps-plugin project type

### ISSUE THREAD

**Issue by zolotov** [JetBrains/gradle-intellij-plugin#106]
Gradle plugin should be able to distinguish JPS-plugin and exclude from its classpath any IDEA jars but `jps-builders.jar`, `jps-model.jar`, `util.jar` and `some others (todo)`

See for details https://github.com/ignatov/intellij-erlang/issues/727

**Comment by Virtlink** [comment]
I need this as well. And for a separate JPS project the IntelliJ tasks are also not needed. Just the dependencies, I think.

By the way, is there a manual way to add a dependency to IntelliJ for my JPS project for the time being?

**Comment by zolotov** [comment]
This plugin adds IntelliJ dependency to any project. What do you mean by `manual way`?

**Comment by Virtlink** [comment]
Well, I have an IntelliJ project and an JPS project, and a project with functionality common to both. The IntelliJ project will use your plugin, but for the other two projects I think I need only the IntelliJ dependencies and not any of the other features and tasks provided by your plugin. Should I use your plugin there anyway, or is there a manual way to add just the IntelliJ dependency to my Gradle script?

**Comment by zolotov** [comment]
> Should I use your plugin there anyway

I think this is the easiest way. However, you repeat what the plugin does manually. To do this you should add dependency on IDEA in `https://www.jetbrains.com/intellij-repository/releases` repository, download zip, unpack it and attach all needed jars to your project.

**Comment by zolotov** [comment]
In `0.2-SNAPSHOT` `JPS`-type for IDEA dependency is introduced
