### ISSUE TITLE
(🐞) Plugin verifier can't find any versions when the `sinceRelease` is a specific version

### ISSUE THREAD

**Issue by KotlinIsland** [JetBrains/gradle-intellij-plugin#1071]
**Describe the bug**
When I set my `sinceBuild` to some specific build number, the plugin verifier fails explicitly. I would think that if it can't find any matches, it could at least find the explicit number I have specified?

I think it sucks that I have to manually set this property when it could be easily deduced.

If there are no versions to verify against, are the same checks does in the build step against the `intellij.version` property?

**To Reproduce**
```kt
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.7.10"
    id("org.jetbrains.intellij") version "1.7.0"
}
intellij {
    pluginName.set("amung us")
    version.set("222.3345-EAP-CANDIDATE-SNAPSHOT")
    type.set("PC")
}
tasks.patchPluginXml {
    sinceBuild.set("222.3345")  // real life: Build #PC-222.3345.99, built on July 21, 2022
    untilBuild.set("222.*")
}
tasks.runPluginVerifier {
    // if you uncomment this then it will work
    // ideVersions.add("PCC-222.3345.99")
}
```

**Expected behavior**
I would expect the plugin verifier  to find a version to verify against, or to not verify against any version, instead of just failing.

**Environment:**
 - OS: [e.g. macOS]
 - Gradle IntelliJ Plugin Version [e.g. 1.6.0] 1.7
 - Gradle Version [e.g. 7.4.2] 7.5

**Comment by YannCebron** [comment]
Please clarify which versions do you expect to be set automatically, do they appear in the Releases JSON as documented here: https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#runpluginverifier-task-ideversions
