### ISSUE TITLE
SourceSets being added to test CP

### ISSUE THREAD

**Issue by jshiell** [JetBrains/gradle-intellij-plugin#1081]
Hi folks,

In 1.8.0 there is a documented change where all sourcesets are added to the test CP. This is causing me problems with the [checkstyle-idea plugin](https://github.com/jshiell/checkstyle-idea/).

One of the features of the plugin is that we allow users to select multiple versions of the Checkstyle JAR to use, and load these via an appropriate classloader. We're using Gradle sourcesets to isolate the code to do this, and also to isolate a set of tests used to iterate over the supported JARs and test each of them individually. As such, we very definitely don't want this version testing sourceset available to all test tasks, instead linking it to custom test tasks created for each relevant version.

Could you please consider adding more granularity to this feature, so we can control which sourcesets are included, or consider some guidance as to why this exists so I can try and come up with a long-term workaround (if possible)?

Thanks very much!

**Comment by hsz** [comment]
Can you please verify that with `1.13.3`?

**Comment by jshiell** [comment]
It appears to be working perfectly - thanks very much!
