### ISSUE TITLE
Specify project.version in Readme sample build

### ISSUE THREAD

**Issue by mfedko** [JetBrains/gradle-intellij-plugin#11]
Hi,
while migrating .idea format to gradle with your plugin I was getting 
version = unspecified in target plugin.xml (overriding the default set in source plugin.xml)

adding project.version = "0.1.0" fixed the issue,

Please check the sample at https://github.com/mfedko/idea-file-language, am I doing something wrong?

**Comment by zolotov** [comment]
Hi, it's supposed that you will maintain plugin version via gradle, so setting `project.version` in build.gradle is a proper solution.

Anyway, I'll make the changes to restrict patching plugin.xml if `project.version` is undefined.

**Comment by zolotov** [comment]
Fixed in 0.0.25

**Comment by mfedko** [comment]
Thanks!
