### ISSUE TITLE
Plugin realises all tasks in project during Gradle's configuration phase

### ISSUE THREAD

**Issue by 3flex** [JetBrains/gradle-intellij-plugin#1110]
**Describe the bug**
I noticed in a project that uses this plugin that many tasks were created during the configuration phase which seemed unnecessary.

See [this build scan](https://scans.gradle.com/s/5beaggr4bwrdg/performance/configuration?openScriptsAndPlugins=WyJjb2RlLXVuaXQtb3JnLmpldGJyYWlucy5pbnRlbGxpaiJd#code-unit-org.jetbrains.intellij!:sqldelight-idea-plugin) (clicking the icon to right of ":sqldelight-idea-plugin" will show the tasks that were configured in this build by the `org.jetbrains.intellij` plugin. When running `./gradlew help --scan` this should report 0 tasks were created immediately or during configuration.

**To Reproduce**
See link above - alternatively, apply the plugin to any build, and run `./gradlew help --scan` and view the Performance > Configuration page.

**Expected behavior**
0 tasks are created during configuration phase by this plugin.

**Environment:**
 - OS: Windows 11
 - Gradle IntelliJ Plugin Version: 1.6.0 (but applies to 1.9.0, and master branch)
 - Gradle Version: 7.5.1

**Additional context**

**Comment by hsz** [comment]
Thanks! 🚀
