### ISSUE TITLE
Use XDG base directories for temporary files

### ISSUE THREAD

**Issue by aSemy** [JetBrains/gradle-intellij-plugin#1118]
**Describe the bug**

https://github.com/JetBrains/gradle-intellij-plugin/blob/0e1bd547c1aede452ffb6e7af0cf53ea080038e2/src/main/kotlin/org/jetbrains/intellij/tasks/RunPluginVerifierTask.kt#L419-L421

It's a huge bugbear of mine, and others, when the home directory is littered with dot files. [XDG Base directories](https://wiki.archlinux.org/title/XDG_Base_Directory) is a way of avoiding it, but the libraries have to respect the defined variables.

Instead of using `$USER_HOME/.pluginVerifier`...

1. Find the base directory:
   1. If defined, use`$XDG_CACHE_HOME`
   2. else use `$USER_HOME/.cache`
2. base directory + `/pluginVerifier`

**To Reproduce**

**Expected behavior**

gradle-intellij-plugin uses a defined cache directory, not a user-home directory

**Environment:**

n/a

**Additional context**

n/a

**Comment by hsz** [comment]
That makes sense, thanks!
I've added (not yet pushed) relevant changes to https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#runpluginverifier-task-downloaddir

**Comment by aSemy** [comment]
Cool! 

Also, thinking about it, you might want to add explicit instructions to users to manually delete or move the existing directory, since it can be quite large.
