### ISSUE TITLE
Indexed Maven Repositories unable to update

### ISSUE THREAD

**Issue by nelsonni** [JetBrains/gradle-intellij-plugin#112]
I receive the following errors when attempting to import this project into IntelliJ IDEA 2016.1.3:

    This is the error that isn't code but isn't a quotation
    URL: http://dl.bintray.com/jetbrains/intellij-plugin-service
    Type: Remote
    Error: java.io.FileNotFoundException: Resource nexus-maven-repository-index.zip does not exist

The ```http://dl.bintray.com/jetbrains/intellij-plugin-service``` URL appears to exist, but is not correctly configured for nexus-maven indexing.

    URL: http://repo1.maven.org/maven2
    Type: Remote
    Error: java.io.IOException: No space left on device

After allowing this repo to consume 6.8GB of space on my system, it still does not appear to be functioning correctly.

    URL: http://repo.labs.intellij.net/central-proxy
    Type: Remote
    Error: java.io.IOException: Transfer for nexus-maven-repository-index.gz failed

The ```http://repo.labs.intellij.net/central-proxy``` URL and the root ```http://intellij.net``` domain do not exist. The root URL does appear to have a redirect to ```https://www.jetbrains.com/support/```, but that doesn't help resolve the issue.

![maven_repo_errors](https://cloud.githubusercontent.com/assets/6432572/16101575/d215ce68-331b-11e6-8ba4-fdb2ce617946.png)

**Comment by zolotov** [comment]
Hi @henryju ,

You can't index `http://repo.labs.intellij.net/central-proxy`, it's our internal repo, I'll try to fix it.

As for other repositories, it's IntelliJ issue, see https://youtrack.jetbrains.com/issue/IDEA-138029 for details.
