### ISSUE TITLE
how to configure webstorm

### ISSUE THREAD

**Issue by henjue** [JetBrains/gradle-intellij-plugin#113]
I want to test jade in webstorm, how should I configure？

**Comment by zolotov** [comment]
@henjue download WebStorm and use `alternativeIdePath` option. See [README] for details

**Comment by henjue** [comment]
oh.sry!

**Comment by henjue** [comment]
@zolotov 
```gradle
intellij {
    type = 'IU'
    version 'IU-15.0.2'
    pluginName 'vue-for-idea'
    plugins = ['JavaScriptLanguage', 'coffeescript', 'sass', 'CSS']
    downloadSources false
    alternativeIdePath  "/Applications/WebStorm.app"
}
```
But can not use the jade in the webstorm. Dependencies module (Libraries External) in the jade can not see the jar

**Comment by henjue** [comment]
@zolotov 
```gradle
intellij {
    type = 'IU'
    version 'IU-15.0.2'
    pluginName 'vue-for-idea'
    plugins = ['JavaScriptLanguage', 'coffeescript', 'sass', 'CSS','Jade']
    downloadSources false
    alternativeIdePath  "/Applications/WebStorm.app"
}
```
This will not work

**Comment by zolotov** [comment]
> But can not use the jade in the webstorm.

What do you mean by `can not use the jade`? Jade is bundled into WebStorm.

> Dependencies module (Libraries External) in the jade can not see the jar
> This will not work

Both are expected, Jade is not bundled into IDEA

**Comment by henjue** [comment]
I want to use SDK as a webstorm to develop plug-ins, webstorm is supported by jade

**Comment by zolotov** [comment]
I still don't understand what you're going to do

> I want to test jade in webstorm, how should I configure？

Run webstorm, jade plugin is already installed there

> I want to use SDK as a webstorm to develop plug-ins

You cannot use webstorm as an SDK, webstorm is not enough to compile IntelliJ plugin

> webstorm is supported by jade

IDEA also supported by jade

the question is still actual: What do you mean by can not use the jade?
