### ISSUE TITLE
plugin doesn't work with io.spring.dependency-management

### ISSUE THREAD

**Issue by eprst** [JetBrains/gradle-intellij-plugin#114]
Hi. I'm not very sure if this is a bug in intellij or spring plugin.
I'm trying to use https://plugins.gradle.org/plugin/io.spring.dependency-management plugin and dependency resolution breaks for idea as soon as I add it.

I've got a small `build.gradle` which works fine:

> gradle dependencies --configuration compile

    :idea-plugin:dependencies
    
    ------------------------------------------------------------
    Project :idea-plugin
    ------------------------------------------------------------
    
    compile - Dependencies for source set 'main'.
    \--- com.jetbrains:idea:2016.1.3
    
    BUILD SUCCESSFUL

Now if I add just one line: 
```
apply plugin: 'io.spring.dependency-management'
```
It fails with this:

    :idea-plugin:dependencies FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':idea-plugin:dependencies'.
    > Could not resolve all dependencies for configuration 'detachedConfiguration6'.
       > Module version xxx:idea-plugin:0.0.SNAPSHOT, configuration 'detachedConfiguration6' declares a dependency on configuration 'default' which is not declared in the module descriptor for com.jetbrains:idea:2016.1.3

Any ideas? Should I file it to Spring instead?
Thanks!

**Comment by zolotov** [comment]
> Any ideas? 

Unfortunately no.

> Should I file it to Spring instead?

Yes, please. Ping me if the problem on the intellij-plugin side.

**Comment by eprst** [comment]
See https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/93
Suggested workaround works. Not sure if you want to add `default` configuration to generated `ivy.xml` as probably a better workaround, otherwise feel free to close this issue. Thanks!

**Comment by zolotov** [comment]
@eprst thank you, will try to do this

**Comment by zolotov** [comment]
Fixed in 0.1.9 which will be available soon. To make it work you have to remove existing caches (`~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/`)
