### ISSUE TITLE
Build with latest 2022.3 EAP fails

### ISSUE THREAD

**Issue by jansorg** [JetBrains/gradle-intellij-plugin#1153]
**Describe the bug**
I attempted to update my plugin to the latest 2022.3 EAP, `IC-223.6160.11-EAP-SNAPSHOT`.
The build now fails, but was successful with `IC-223.4884.69-EAP-SNAPSHOT`.

Error:
```
Execution failed for task ':plugin:runIde'.
> java.io.FileNotFoundException: /home/jansorg/.gradle-intellij/ideaIC-223.6160.11-EAP-SNAPSHOT/Info.plist (File or directory not found)
```

**To Reproduce**
Update to the new EAP.

**Expected behavior**
Builds and runs

**Environment:**
 - OS: Linux
 - Gradle IntelliJ Plugin Version 1.8.1 (because of https://github.com/JetBrains/gradle-intellij-plugin/issues/1099)
 - Gradle Version: 7.4.2

**Additional context**
I'm on Linux, I suppose the new builds included assets for all platforms, which is now wrongly detected as macOS by the intellij-gradle plugin.

**Comment by LukaszKontowski** [comment]
Adding another issue for gradle-intellij-plugin usage with the `IC-223.6160.11-EAP-SNAPSHOT` build.
Probably this is an issue with IntelliJ itself, **not with the plugin**, but adding a comment here for your interest. 

Original issue: https://youtrack.jetbrains.com/issue/IDEA-303298/macOs-Could-not-initialize-class-comintellijuimacfoundationFoundation-on-223616011-build

Shortened description:
`runIde` task results in IntelliJ startup failure:
- issue appears on `macOs` machine - MacBook Pro 2021 with the Apple M1 Pro chip for the `223.6160.11-EAP-SNAPSHOT` IntelliJ Idea build (community)
- This issue **did not** appear for the previous snapshot build - `223.4884.69-EAP-SNAPSHOT`
- Main error: `Failed to initialize IdeFrameDecorator. Could not initialize class com.intellij.ui.mac.foundation.Foundation`

**Comment by vzmerr** [comment]
I have the same problem as @LukaszKontowski

**Comment by YannCebron** [comment]
please try using Gradle IntelliJ Plugin SNAPSHOT version for now https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#snapshot-release

**Comment by hsz** [comment]
@jansorg Is this issue still relevant?

**Comment by hsz** [comment]
Confirmed by @jansorg as obsolete.
