### ISSUE TITLE
Can't debug `runIde` task because of duplicate jdwp options

### ISSUE THREAD

**Issue by Undin** [JetBrains/gradle-intellij-plugin#1158]
**Describe the bug**
`runIde` task cannot be launched under debugger in IDEA. Gradle shows the following error

```
ERROR: Cannot load this JVM TI agent twice, check your java command line for duplicate jdwp options.
```

It seems [this](https://github.com/JetBrains/gradle-intellij-plugin/commit/c849ad3bccbd977abacff5de0e0c2284cd46c352) commit introduced duplication of `jdwp` option

**To Reproduce**
Just launch `runIde` task under debug in IDEA

**Expected behavior**
Debugging of `runIde` works as previously

**Environment:**
 - OS: macOS 12.5.1
 - Gradle IntelliJ Plugin Version: 1.10.0-SNAPSHOT
 - Gradle Version: 7.5

**Comment by hsz** [comment]
Thanks for reporting. The fix is now available in the `1.10.0-SNAPSHOT`.
