### ISSUE TITLE
Form classes instrumentation always triggers Kotlin recompilation

### ISSUE THREAD

**Issue by matklad** [JetBrains/gradle-intellij-plugin#116]
if I execute `./graldew assemble` twice, I expect the second time to be UP-TO-DATE. This unfortunately does not happen, and Kotlin is always recompiled. Running `./graldew assemble --info` gives the following hint:

```
:compileKotlin (Thread[Daemon worker Thread 2,5,main]) started.
:compileKotlin
Executing task ':compileKotlin' (up-to-date check took 0.035 secs) due to:
  Output file intellij-rust/build/classes/main/org/rust/ide/idea/CargoConfigurationWizardStep.class has changed.
  Output file intellij-rust/build/classes/main/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.class has changed.
  Output file intellij-rust/build/classes/main/org/rust/cargo/project/configurable/RustProjectConfigurable.class has changed.
All input files are considered out-of-date for incremental task ':compileKotlin'.
```

Those are Kotlin classes bound to the GUI designer forms.

**Comment by zolotov** [comment]
Sorry, I doubt I can do anything with this

**Comment by matklad** [comment]
Can't the instrumentation task be skipped if it should be up to date?

**Comment by zolotov** [comment]
Instrumentation task is not task. It's kotlin task out-of-date

**Comment by matklad** [comment]
Hm, maybe `doLast` hook should be used for instrumentation? 

I was able to workaround the issue by using `instrumentCode=false` and inspeat invoking the instrumentation manually in the `doLast`: https://gist.github.com/matklad/0685977255fad061d69bee8fa2a0e4dd

**Comment by matklad** [comment]
Reference: https://discuss.gradle.org/t/how-do-i-configure-bytecode-instrumentation/5930/2

**Comment by zolotov** [comment]
> Hm, maybe doLast hook should be used for instrumentation?

doLast is used for that

**Comment by matklad** [comment]
>doLast is used for that

I mean that if I manually add instrumentation to the `doLast`, [like this](https://gist.github.com/matklad/0685977255fad061d69bee8fa2a0e4dd#file-uglyhack-gradle-L271-L275), then no recompilation happens and everything seem to work fine. If I just use `instrumentCode = true`, then the recompilations do happen. 

Perhaps intellij gradle plugin can provide a function which takes compile task as an argument, and instruments its output? That way the plugin user can add `doLast` to compile tasks manually and avoid spurious recompilation that way?

**Comment by matklad** [comment]
> can try to merge several compilation tasks by its output but not sure it will work well.

Won't something like [this](https://github.com/matklad/gradle-intellij-plugin/commit/8e869c6578a51509957df765567c3b04edae9891) work?

**Comment by zolotov** [comment]
maybe it will. have you tried it?

**Comment by matklad** [comment]
It works for intellij-rust, but don't know gradle well enough to be sure that it always works :)
