### ISSUE TITLE
Publish plugin to multiple channels

### ISSUE THREAD

**Issue by vlasovskikh** [JetBrains/gradle-intellij-plugin#117]
Since adding a new plugin channel to the IDE overrides the default channel, plugin authors have to publish the same builds to multiple channels.

Let's add a way to specify the list of channels used to publish the plugin in addition to the single channel option:

```groovy
intellij {
  publish {
    username 'zolotov'
    password 'password'
    channel 'eap', 'nightly', 'default'
  } 
}
```

We could use "default" as the name for the default channel (no channel=... parameter in HTTP POST).

**Comment by zolotov** [comment]
You can try 0.2.0-SNAPSHOT, see README to know how to use snapshots
