### ISSUE TITLE
Plugin complains about sourceCompatibility when it shouldn't

### ISSUE THREAD

**Issue by ahus1** [JetBrains/gradle-intellij-plugin#1180]
**Describe the bug**

I'm building a plugin with JDK17 to run also on JDK11. I found that building with JDK17 is required to IntelliJ 2022.3+, still everything works fine IntelliJ 2022.2, 2022.3 and earlier when I compile my code with the settings to use JDK11 only. 

```
java {
  targetCompatibility = "11"
  sourceCompatibility = "11"
}
```

The plugin still complains, which is IMHO wrong: 

> The Java configuration specifies sourceCompatibility=11 but IntelliJ Platform 223.7255.1-EAP-SNAPSHOT requires sourceCompatibility=17.

**To Reproduce**

This is used by the AsciiDoc plugin for IntelliJ, see https://github.com/asciidoctor/asciidoctor-intellij-plugin.
An example GitHub action run is here: https://github.com/asciidoctor/asciidoctor-intellij-plugin/actions/runs/3318339887/jobs/5482177110

**Expected behavior**
No warning about using targetCompatibility/sourceCompatibility as long as it is smaller than the JDKs used for the IntelliJ version I target. 
Actually it should warn when I switch those to 17 when I still target older releases. 

**Environment:**
 - OS: Windows
 - Gradle IntelliJ Plugin Version: 1.10.0-SNAPSHOT
 - Gradle Version: 7.3

**Comment by YannCebron** [comment]
why don't you build against the _lowest_ support (minimum) IDE version and its JDK,  e.g. 2022.2 with Java 11? the Gradle plugin can not easily guess that your plugin should also target lower versions than your current target

**Comment by ahus1** [comment]
The new or broken API or exceptions appear usually in EAP versions, that's why I develop with the latest version. The API compatibility I ensure using the pluginVerifier.

The gradle-intellij-plugin could know the minimum version by looking at `idea-version since-build="213.6777.52"` in the plugin.xml, and adjust its error message accordingly.

**Comment by hsz** [comment]
@ahus1 In fact, the message from your first post is correct:

> The Java configuration specifies sourceCompatibility=11 but IntelliJ Platform 223.7255.1-EAP-SNAPSHOT requires sourceCompatibility=17.

You are pointing to `223`, which is compiled with `target=17`, so in your "receiver" plugin, you need to have `sourceCompatibility` set to the same version: `17`.
The `targetCompatibility` is something you want to produce – so `11` if you want to support IDEs that still rely on Java 11.

**Comment by RaymondLam1** [comment]
> @ahus1 In fact, the message from your first post is correct:
> 
> > The Java configuration specifies sourceCompatibility=11 but IntelliJ Platform 223.7255.1-EAP-SNAPSHOT requires sourceCompatibility=17.
> 
> You are pointing to `223`, which is compiled with `target=17`, so in your "receiver" plugin, you need to have `sourceCompatibility` set to the same version: `17`. The `targetCompatibility` is something you want to produce – so `11` if you want to support IDEs that still rely on Java 11.
Excese me, I try it:
```
    withType<JavaCompile> {
        sourceCompatibility = "17"
        targetCompatibility = "11"
    }
```
However I got: `WARNING: Source release 17 requires target release 17`. Where is my configuration wrong? Thank you very much.

**Comment by RaymondLam1** [comment]
> @ahus1 In fact, the message from your first post is correct:
> 
> > The Java configuration specifies sourceCompatibility=11 but IntelliJ Platform 223.7255.1-EAP-SNAPSHOT requires sourceCompatibility=17.
> 
> You are pointing to `223`, which is compiled with `target=17`, so in your "receiver" plugin, you need to have `sourceCompatibility` set to the same version: `17`. The `targetCompatibility` is something you want to produce – so `11` if you want to support IDEs that still rely on Java 11.
Excese me, I try it:

**Comment by hsz** [comment]
@RaymondLam1 What are the since/until build and the platform version you set?

**Comment by RaymondLam1** [comment]
> @RaymondLam1 What are the since/until build and the platform version you set?

it is 
```
        sinceBuild.set("222")
        untilBuild.set("232.*")
```

**Comment by hsz** [comment]
And the platform version?

**Comment by RaymondLam1** [comment]
It's very confusing， I created a new project and executed the same build.gradle.kts, it succeeded. But in my dev project it fails：
