### ISSUE TITLE
Running tests with 2022.3 beta fails with `java.lang.Error: com.intellij.util.lang.PathClassLoader`

### ISSUE THREAD

**Issue by jansorg** [JetBrains/gradle-intellij-plugin#1182]
- Building and running tests against `IC-223.7126.7-EAP-SNAPSHOT` worked fine
- Building and running tests against 2022.3 beta (i.e. `IC-223.7401.7-EAP-SNAPSHOT`) fails with the exception below
- I'm using Gradle plugin `id("org.jetbrains.intellij") version "1.10.0-SNAPSHOT"` and executed with `./gradlew --refresh-dependencies clean build` to pick up the latest version

```
> Task :test
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "com.intellij.util.lang.PathClassLoader"). To use archived non-system classes, this property must not be set
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
Error occurred during initialization of VM
java.lang.Error: com.intellij.util.lang.PathClassLoader
	at java.lang.ClassLoader.initSystemClassLoader(java.base@17.0.5/ClassLoader.java:1995)
	at java.lang.System.initPhase3(java.base@17.0.5/System.java:2246)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.lang.PathClassLoader
	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@17.0.5/BuiltinClassLoader.java:641)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@17.0.5/ClassLoaders.java:188)
	at java.lang.ClassLoader.loadClass(java.base@17.0.5/ClassLoader.java:520)
	at java.lang.Class.forName0(java.base@17.0.5/Native Method)
	at java.lang.Class.forName(java.base@17.0.5/Class.java:467)
	at java.lang.ClassLoader.initSystemClassLoader(java.base@17.0.5/ClassLoader.java:1981)
	at java.lang.System.initPhase3(java.base@17.0.5/System.java:2246)
```

**Comment by jamescatto** [comment]
This problem does not occur in 223.7255.1-EAP-SNAPSHOT

**Comment by hurricup** [comment]
Confirming fix in 223.7255.1-EAP-SNAPSHOT for the perl plugin

**Comment by hsz** [comment]
Thank you for the confirmation.
@jansorg, can you please double-check that on your end that it was IJ issue?

**Comment by jansorg** [comment]
`IC-223.7401.7-EAP-SNAPSHOT` was broken, i.e. the beta build after `223.7255.1-EAP-SNAPSHOT` mentioned above. I'll double-check again that it's broken...

**Comment by jamescatto** [comment]
To confirm @jansorg, this problem was introduced **after** `223.7255.1-EAP-SNAPSHOT`, and so is not fixed yet AFAIK

**Comment by hsz** [comment]
@jansorg @jamescatto  Do you both use Linux?

**Comment by jansorg** [comment]
@hsz I'm using Linux

**Comment by jamescatto** [comment]
@hsz yes, I'm on lunix

**Comment by hsz** [comment]
What is the tests classpath in your cases? You can check it i.e. with:

```
tasks {
    test {
        doFirst {
            println("classpath = ${classpath.files}")
        }
    }
}
```

**Comment by jansorg** [comment]
@hsz Thanks! I can confirm that the latest snapshot is working again.

**Comment by hsz** [comment]
@jamescatto I'm referring to the latest snapshot of this plugin.

**Comment by jamescatto** [comment]
Thanks @hsz I was getting myself confused with gradle caching and a version override mechanism we have. Anyway, it works for me too, thanks!

**Comment by a6dang** [comment]
I might be doing something wrong in my project setup but I'm still seeing this issue when trying to run my tests locally. I'm pulling the snapshot gradle-intellij-plugin via the legacy plugin DSL due to the multi-module nature of my project.

```
dependencies {
            classpath "org.jetbrains.intellij:org.jetbrains.intellij.gradle.plugin:1.10.0-SNAPSHOT"
.
.
}
```

I've tried a few different EAP snapshot versions, including `223.7255.1-EAP-SNAPSHOT` and `223.7571-EAP-CANDIDATE-SNAPSHOT`,  and am seeing it across all of them. Any ideas on what might be off from my setup?
