### ISSUE TITLE
Multimodule project, dependency on sibling with custom configuration

### ISSUE THREAD

**Issue by dmvk** [JetBrains/gradle-intellij-plugin#119]
Hi Guys,

Thanks for an amazing work you are doing!

I'm trying to use " Fine grained control over dependencies" as can be seen over here in official doc: https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:project_jar_dependencies

It works perfectly from the gradle point of view, but Idea is not able to resolve dependencies anymore :(

Concrete example can be seen here:
https://github.com/johnrengelman/shadow/issues/230

Am I missing something? Or is it a missing feature in gradle plugin?

Thanks,
D.

**Comment by zolotov** [comment]
Hi @dmvk, not sure if it's bug in the plugin or not. Could you attach a sample project so I can recreate the issue locally? Thank you.

**Comment by dmvk** [comment]
Fixed the issue by upgrading gradle from 2.13 to 2.14

Thanks,
D.
