### ISSUE TITLE
plugin build is adding synthetic method $$$getFont$$$ to sub classes of SettingsEditor multiple times

### ISSUE THREAD

**Issue by SingingBush** [JetBrains/gradle-intellij-plugin#1193]
The D Language plugin extends SettingsEditor in a few places such as _DlangRunDmdConfigurationEditor_ and _DlangRunDubConfigurationEditor_.  It seems the build process add a synthetic method called **$$$getFont$$$** which is being duplicated. This in turn causes class loader problems when running the plugin.

relates to https://github.com/intellij-dlanguage/intellij-dlanguage/issues/787

with similar reports on youtrack: https://youtrack.jetbrains.com/issue/IDEA-192748/java.lang.ClassFormatError-Duplicate-method-name-getFont

**Comment by SingingBush** [comment]
Hi, I noticed in https://youtrack.jetbrains.com/issue/IDEA-298989/Duplicate-method-name-getFont#focus=Comments-27-6453425.0-0 that commit https://github.com/JetBrains/gradle-intellij-plugin/commit/de337103fee9765c569f2f666c1d7068d4986c61 should fix the duplicated _getFont_ methods. Does this just need a new release?

**Comment by hsz** [comment]
Turned out that this commit 1e3af81ae2b4ed3070939a6b990f7e459aeb6931 is also needed.
All the changes are now available in the `1.10.0-SNAPSHOT` release.
Could you please try it out?
