### ISSUE TITLE
Publish without password in project file

### ISSUE THREAD

**Issue by jansorg** [JetBrains/gradle-intellij-plugin#12]
The publish task looks great - thanks! :)
If possible I would like to have my gradle file in vcs but not the password. Is there any way to ask on the command line for the password or to read it from an env variable or a file? 
This would be safer :)

**Comment by zolotov** [comment]
Hi, thanks for feedback. Actually you can set password in any way you want: pass via environment, system property, or via stdin. Plugin provides a field to fill, security issues are on you.

E.g. this is how we made uploading in go plugin: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/build.gradle

**Comment by zolotov** [comment]
About passing properties: https://docs.gradle.org/current/userguide/build_environment.html
