### ISSUE TITLE
Don't warn on on pre/post instrumentation task for testFixtures, possibly other sourceSets

### ISSUE THREAD

**Issue by bric3** [JetBrains/gradle-intellij-plugin#1214]
**Describe the bug**
Instrumentation fails to ignore or recognize other source sets.

```
> Configure project :modules:core
[gradle-intellij-plugin :modules:corecore] Unexpected instrumentation task name: instrumentTestFixturesCode
[gradle-intellij-plugin :modules:corecore] Unexpected instrumentation task name: postInstrumentTestFixturesCode

```

**To Reproduce**
Steps to reproduce the behavior – provide your build configuration, and/or link to the failing GitHub Action job.

Adding the [plugin `id("java-test-fixtures")`](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures), will add a new source set `testFixtures`, gradle-intellij-plugin (as do other plugins) will react to this and create the above mentioned tasks.

**Expected behavior**
No warnings, I believe testFixtures are part of gradle and should be supported. That said is this really an issue if there are other source sets, like `integrationTests`, etc.

**Environment:**
 - OS: macOS
 - Gradle IntelliJ Plugin Version: 1.9.0
 - Gradle Version: 7.5.1

**Comment by YannCebron** [comment]
#1081 sounds related
