### ISSUE TITLE
Not compatible with Java 7

### ISSUE THREAD

**Issue by nathanabercrombie** [JetBrains/gradle-intellij-plugin#122]
Although the build.gradle has:
`targetCompatibility = 1.7`

Version 0.1.4 (and newer) fail to start with:
`java.lang.UnsupportedClassVersionError: org/jetbrains/intellij/IntelliJPlugin : Unsupported major.minor version 52.0`

The newest that does not fail with this is version 0.0.41.  It looks like the dependence on 1.8 was from this commit: https://github.com/JetBrains/gradle-intellij-plugin/commit/56c5794afd36e31caee90e3f41cf671c63c2258e

Please update the README that java 8 is required

**Comment by zolotov** [comment]
0.2.0-SNAPSHOT is compatible with 1.7
