### ISSUE TITLE
 Could not find launch information for the current OS: Mac OS X (null)

### ISSUE THREAD

**Issue by CoXier** [JetBrains/gradle-intellij-plugin#1230]
**Describe the bug**
I create a empty plugin project. And I set version with build number instead of localPath property.

```
intellij {
    version.set("202.7660.26.42.7486908")
    type.set("AI") // AI means Android Studio
}
```

Then I execute `./gradlew :runIde`. I got an error:

>  What went wrong:
Execution failed for task ':runIde'.
> Could not find launch information for the current OS: Mac OS X (null)

Here is unexpected log:

```
[gradle-intellij-plugin :layout-inspector-v2] Using IDE from remote repository
Downloading https://redirector.gvt1.com/edgedl/android/studio/ide-zips/4.2.2.0/android-studio-ide-202.7486908-linux.tar.gz to /Users/jianxinli/.gradle/.tmp/gradle_download1614075782070470413bin
[gradle-intellij-plugin :layout-inspector-v2] IDE dependency cache directory: /Users/jianxinli/.gradle/caches/modules-2/files-2.1/com.google.android.studio/android-studio/202.7660.26.42.7486908/276e5e191ce65feb633e8efb0f30d138340ae1ab/android-studio-202.7660.26.42.7486908
```

As you see, the plugin download linux package on my mac. Maybe it's not tested on mac devices.

**To Reproduce**
Steps to reproduce the behavior – provide your build configuration, and/or link to the failing GitHub Action job.

**Expected behavior**
Download right platform packages and launch the sandbox.

**Environment:**
 - OS: macOS
 - Gradle IntelliJ Plugin Version "1.10.0"
 - Gradle Version [e.g. 7.4.2]

**Additional context**

**Comment by hsz** [comment]
Thank you, @CoXier!
I've extended it to handling the Mac M1 releases – the fix will be released soon.

**Comment by CoXier** [comment]
> Thank you, @CoXier! I've extended it to handling the Mac M1 releases – the fix will be released soon.

Good job. I miss the M1 release.
