### ISSUE TITLE
Failed to calculate the value of task ':runPluginVerifier' property 'ides'.

### ISSUE THREAD

**Issue by iguissouma** [JetBrains/gradle-intellij-plugin#1233]
**Describe the bug**

I cannot build my plugin because of failing task.

```
Execution failed for task ':runPluginVerifier'.
> Failed to calculate the value of task ':runPluginVerifier' property 'ides'.
   > IDE 'IU-2022.3.2' cannot be downloaded. Please verify the specified IDE version against the products available for testing: https://jb.gg/intellij-platform-builds-list
```

**To Reproduce**
[(https://github.com/iguissouma/nx-console-idea-plugin)](https://github.com/iguissouma/nx-console-idea-plugin)
Build on Github Action is failing or Executing 'runPluginVerifier' locally

**Expected behavior**
The list of ides are available.

**Comment by YannCebron** [comment]
please *always* update to latest version (now, 1.10.0) https://github.com/iguissouma/nx-console-idea-plugin/blob/main/build.gradle.kts#L12 

also other plugins look outdated
