### ISSUE TITLE
Jacoco reports incorrect 0% test coverage in 1.10.0

### ISSUE THREAD

**Issue by magneticB** [JetBrains/gradle-intellij-plugin#1236]
Jacoco test coverage reports incorrect 0% test coverage when using plugin version 1.10.0.  The test coverage reports correctly in the previous 1.9.0 version but it is not working in the latest version.

Could it be a regression of [1065](https://github.com/JetBrains/gradle-intellij-plugin/issues/1065)?

Jacoco is an important tool for measuring test coverage and currently breaks my build unless I disable it.

**Comment by hsz** [comment]
Can you try with `1.11.0-SNAPSHOT` [snapshot release](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#snapshot-release)?

**Comment by magneticB** [comment]
Same problem with 1.11.0-SNAPSHOT

**Comment by hsz** [comment]
Please see: https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin-faq.html#jacoco-reports-0-coverage

**Comment by magneticB** [comment]
Yep that fixed it thank you.
This wasn't required in 2022.2 but 2022.3 and 1.10.0 combination seems to require it.  Thanks again!
