### ISSUE TITLE
Missing Dependencies after Update

### ISSUE THREAD

**Issue by nico-loeber** [JetBrains/gradle-intellij-plugin#1239]
**Describe the bug**
After updating to org.jetbrains.intellij 1.10.0 and gradle 7.6 I encounter an issue with dependency resolution.
When checking out the project and installing the dependency via gradle everything works fine. But you run a git pull that contains a dependecy change all jetbrains dependencies will go lost.

Changing some dependency in my build.gradle.kts sometimes resolves the issue.
I am not sure what is causing it, I can not find any error message.
Even clearing all caches and deleting the build directory doesn't seem to help.
The only way to fix this is to check out the project to a new folder and installing the dependencies from scratch.

![image](https://user-images.githubusercontent.com/18308418/205490651-4dc95bb2-eeaf-44db-b91a-60e0aebc4b1a.png)

**To Reproduce**
- update org.jetbrains.intellij 1.10.0 and gradle to 7.6 
- checkout your repository, and install  its dependencies
- do a remote dependency change to any dependency
- pull this change in your project
- watch how all your auto completion for jetbrains code and gradle tasks are gone

My affected plugin: https://github.com/php-perfect/ddev-intellij-plugin

**Expected behavior**
I would expect the dependencies to update.

**Environment:**
 - OS: Windows 11
 - Java 17
 - Gradle IntelliJ Plugin Version 1.10
 - Gradle Version 7.6.0

**Additional context**
If this issue is not related to the gradle-intellij-plugin I am sorry, but the update to 1.10 was the last notable change I did before this issue occured the first time.
The issue is reproducable by my colleague working on the same repository as well.

Thanks for any help!

**Comment by hsz** [comment]
@nico-loeber  Can you please try with the snapshot release?

**Comment by nico-loeber** [comment]
It seems to work well so far with the Snapshot release. Thanks for the hint @hsz!
But as the error didn't occur on every dependency update, I can not guarantee it is fixed.

**Comment by arturbosch** [comment]
Hi,
we experienced the same issue with 1.10.0 however we had to rollback to 1.9.0 due to 1.10.1 introducing a breaking change in a patch version:

`- Set minimum supported Gradle version from 6.8 to 7.1`

For this project it is not easily possible to migrate to Gradle 7.X asap.
Please do not introduce breaking changes in patch versions, thanks.

**Comment by hsz** [comment]
@arturbosch You're right, apologies.
I'm about to release the `1.10.2` tonight with the reverted minimal Gradle version to unblock you with this dependencies issue.
The next release — `1.11.0` — will require Gradle `7.3`.

**Comment by arturbosch** [comment]
> @arturbosch You're right, apologies. I'm about to release the `1.10.2` tonight with the reverted minimal Gradle version to unblock you with this dependencies issue. The next release — `1.11.0` — will require Gradle `7.3`.

Thank you very much 🙏🏼
