### ISSUE TITLE
Module with no java files fails to package

### ISSUE THREAD

**Issue by nathanabercrombie** [JetBrains/gradle-intellij-plugin#124]
I know that it is not a common case, but thought it worth mentioning:

1. Create a new directory
2. Put a build.gradle in it
3. Apply this plugin (as per instructions in readme)
4. Create a plugin.xml in the resource directory
5. Do NOT create any java files
6. gradle buildPlugin

Expected: plugin should be assembled, though it wont do anything
Actual: the build fails since the 'classes' directory is missing

**Comment by zolotov** [comment]
Cannot recreated. Affected version? Logs?

**Comment by nathanabercrombie** [comment]
Okay, now I cannot reproduce this with a sample.  It may have been some conflict with something else in my gradle projects. Closing this issue, if I come across it again I will try to isolate it.
