### ISSUE TITLE
Gradle deprecation warning about `equals` method of `IdeaDependency`, needs fix by Gradle 8.0 

### ISSUE THREAD

**Issue by YannCebron** [JetBrains/gradle-intellij-plugin#1241]
original report: https://youtrack.jetbrains.com/issue/IDEA-306292/

**What steps will reproduce the problem?**
1.  Use gradle version `7.6-rc-3`
2. Use IntelliJ Gradle Plugin version `1.10.0`
3. Build a IntelliJ Plugin project

**What is the expected result?**

No warnings

**What happens instead?**

Warning in output:
```txt
Using objects as inputs that have a different serialized form but are equal has been deprecated. This is scheduled to be removed in Gradle 8.0. Type 'org.jetbrains.intellij.dependency.IdeaDependency' has a custom implementation for equals(). Declare the property as @Nested instead to expose its properties as inputs. See https://docs.gradle.org/7.6-rc-3/userguide/upgrading_version_7.html#equals_up_to_date_deprecation for more details.
```

**Comment by hsz** [comment]
Sorry for the late follow-up. I have tried it again, and this warning doesn't seem to be present anymore.
Can you please check it on your end before closing the issue?
