### ISSUE TITLE
Could not find launch information for the current OS: Mac OS X (amd64)

### ISSUE THREAD

**Issue by stevemessick** [JetBrains/gradle-intellij-plugin#1246]
After updating the IntelliJ plugin to v1.10 I'm no longer able to launch a debugger from IntelliJ.

> Execution failed for task ':flutter-idea:runIde'.
> &gt; Could not find launch information for the current OS: Mac OS X (amd64)

I tried v1.11-SNAPSHOT (to get #1231) today and that did not work either.

To reproduce the problem you'd probably need the same hardware I have (MacBook Pro, Intel Core I9). Set up a dev environment for the Flutter plugin for IntelliJ (https://github.com/flutter/flutter-intellij/blob/master/CONTRIBUTING.md) then do `bin/plugin test`. You don't actually have to launch IntelliJ to see the same failure message, modulo task name.

**Comment by hsz** [comment]
Please provide the content of the `product-info.json` file of the IDE you use for building the plugin.
You may find it in the Gradle cache in a location similar to:

```
/Users/hsz/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2022.3/4d343cadac04a0a31d70f6f96facfaa7f949df01/ideaIC-2022.3/product-info.json
```

**Comment by stevemessick** [comment]
I followed that path down to `ideaIC`, but that directory is empty.

I don't use an IDE to build the plugin. We have a custom script in the `tool/plugin` directory of the plugin project. I do use IntelliJ to debug the plugin, but that is not currently working.

**Comment by hsz** [comment]
`runIde` task now relies on the configuration provided within the targeted SDK. 
Your custom setup seems to be the point of failure.

Please provide the full configuration setup you use so I could reproduce it locally.

**Comment by stevemessick** [comment]
Sorry for the delay. I'm not sure what you mean by "full configuration setup". I recently had to check out a fresh version of the repo. I tar'd it up; the file is about 16 GB. If there is a way to share that I can try to get it to you. Otherwise, my initial post has a link to the instructions for checking out and configuring it for yourself.

**Comment by hsz** [comment]
@stevemessick Please use the `1.11.0` version released last week. It contains a fix for the case when you point to the local IDE in version 2022.3 on macOS.

**Comment by stevemessick** [comment]
Thanks for the update. Unfortunately, nothing has changed for me. I still get the same error.

**Comment by stevemessick** [comment]
@hsz Actually, the error message is slightly different. The original `amd64` is now `null`.

> &gt; Could not find launch information for the current OS: Mac OS X (null)

**Comment by hsz** [comment]
@stevemessick Which exactly IDE distribution do you point to?

**Comment by stevemessick** [comment]
Good question! My configuration was incorrect. After changing it to use 2022.3.1 the original error re-appeared (with `amd64`).

I updated my IntelliJ to 223.8214.52. I use the `runIde` task to launch the debugger. In my `intellij {...}` block of `build.gradle.kts` I have:
```kotlin
localPath.set("${project.rootDir.absolutePath}/artifacts/$ide")
```
where `ide` is `ideaIC`. The `build.txt` from that directory contains "IC-223.8214.52".

Typically, I run unit tests from the command line. I get the same error there, too.

Would it make a difference now if I use the Linux distro of IntelliJ for compiling? We've always done it that way in the past, since the Mac distro is a *.dmg file. It is the Linux version that I have in the `localPath` path. Obviously, I'm using a Mac for woring on the plugin code.

**Comment by Gustl22** [comment]
Not sure @hsz, but I think this issue is blocking the development of the flutter plugin to be compatible with IntelliJ 2022.3.1 which is stable. Kindly asking for confirming this issue (?)

**Comment by stevemessick** [comment]
@Gustl22 Thanks for checking in! We have a version available for 2022.3, built with 2022.2. I'm having some problems getting a version for 2023.1, though, so it might be blocking support for EAP. I don't yet know exactly what the problem is.

**Comment by Gustl22** [comment]
Ah so https://github.com/flutter/flutter-intellij/pull/6556 is actually released then, but not merged (?). I checked now the **Flutter Plugin 71.3.6** with **IntelliJ IDEA 2022.3.1** and device selector seems to work again.

**Comment by stevemessick** [comment]
Not exactly. I have more work to do on that one. What was released was a temp fix to make using the plugin possible when working on a non-Flutter project.

**Comment by hsz** [comment]
Can you please verify it against the `1.13.1-SNAPSHOT` release?

**Comment by stevemessick** [comment]
That worked, thanks! I'm using these versions now:
```kotlin
  id("org.jetbrains.intellij") version "1.13.1-SNAPSHOT"
  id("org.jetbrains.kotlin.jvm") version "1.8.20-Beta"
```
Closing, since it is fixed.
