### ISSUE TITLE
listBundledPlugins task does not show output again if task is up to date

### ISSUE THREAD

**Issue by 3flex** [JetBrains/gradle-intellij-plugin#1248]
**Describe the bug**
Cannot see output when running `listBundledPlugins` task if the task is up to date.

**To Reproduce**
Run `listBundledPlugins`. See output. Run `listBundledPlugins` again. No output:

```
PS C:\path\IdeaProjects\sqldelight> ./gradlew sqldelight-idea-plugin:listBundledPlugins

BUILD SUCCESSFUL in 5s
6 actionable tasks: 6 up-to-date
```

**Expected behavior**
I can see the console output every time I run the `listBundledPlugins` task, even if it's up to date.

**Environment:**
 - OS: Windows 11
 - Gradle IntelliJ Plugin Version [e.g. 1.6.0]: 1.10.1
 - Gradle Version [e.g. 7.4.2]: 7.6

**Additional context**

**Comment by hsz** [comment]
With the next release, there'll be the `printProductsReleases` task available to always print the result of the `listBundledPlugins` task.
