### ISSUE TITLE
Plugin built with Java 8

### ISSUE THREAD

**Issue by ripla** [JetBrains/gradle-intellij-plugin#125]
It seems that the published version of the plugin is compiled with Java 8? At least after upgrading the plugin to the latest version 0.1.10 (from 0.0.43) results in 

`java.lang.UnsupportedClassVersionError: org/jetbrains/intellij/IntelliJPlugin : Unsupported major.minor version 52.0`

**Comment by zolotov** [comment]
yes, java 8 is required for 0.1.* builds

**Comment by ripla** [comment]
@zolotov could you update the README to reflect that? Currently it states 1.7 as the minumum

**Comment by zolotov** [comment]
@ripla documentation is generated based on sources code, and now source code is 1.7-compatible

**Comment by zolotov** [comment]
#122
