### ISSUE TITLE
Task `runIde` failed when increasing `org.jetbrains.intellij` to version 1.11.0

### ISSUE THREAD

**Issue by david-buderus** [JetBrains/gradle-intellij-plugin#1259]
When upgrading the gradle plugin `org.jetbrains.intellij` to version 1.11.0 we encounter the following error when executing `./gradlew runIde`:

```
Execution failed for task ':instrumentCode'.
> taskdef class com.intellij.ant.InstrumentIdeaExtensions cannot be found
   using the classloader AntClassLoader[/home/david/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2020.1/cbeeb1f1aebd4c9ea8fb5ab990c5904a676fc41a/ideaIC-2020.1/lib/asm-all-7.0.1.jar:/home/david/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2020.1/cbeeb1f1aebd4c9ea8fb5ab990c5904a676fc41a/ideaIC-2020.1/lib/jdom.jar:/home/david/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2020.1/cbeeb1f1aebd4c9ea8fb5ab990c5904a676fc41a/ideaIC-2020.1/lib/forms-1.1-preview.jar:/home/david/Downloads/gradleIntellij/intellij-platform-plugin-template-main/.gradle]
```

When downgrading the gradle plugin `org.jetbrains.intellij` to version 1.10.2 everything works fine.

See the attached minimal example that is based on the [IntelliJ Platform Plugin Template](https://github.com/JetBrains/intellij-platform-plugin-template) [intellij-platform-plugin-template-main.zip](https://github.com/JetBrains/gradle-intellij-plugin/files/10257527/intellij-platform-plugin-template-main.zip).

The problem might be related to the build version that is configured. Everything works fine with version 1.11.0 and the following version setting:

```
pluginSinceBuild = 213
pluginUntilBuild = 223.*
platformType = IC
platformVersion = 2021.3.3
```
But when decreasing the version settings to:
```
pluginSinceBuild = 201
pluginUntilBuild = 223.*
platformType = IC
platformVersion = 2020.1
```
the error described above occurs.

Performed on:
Ubuntu 22.04

**Comment by hsz** [comment]
Duplicate of #1255 – please follow that thread for more details.
