### ISSUE TITLE
Support for Gradle 3.0's Kotlin?

### ISSUE THREAD

**Issue by Jire** [JetBrains/gradle-intellij-plugin#126]

**Comment by zolotov** [comment]
What's the issue exactly?

**Comment by Jire** [comment]
@zolotov How do we setup a project using the Kotlin Gradle?

**Comment by zolotov** [comment]
I have know idea, what's special can be with it?

**Comment by Jire** [comment]
@zolotov The DSL is completely different, along with the file format.

**Comment by zolotov** [comment]
> The DSL is completely different, along with the file format.

So? what exactly should be done in the plugin?

**Comment by zolotov** [comment]
closing due to lack of feedback

**Comment by DemonWav** [comment]
Just for reference, here's an example for how to use this plugin with [Gradle script Kotlin](https://github.com/gradle/gradle-script-kotlin): https://github.com/DemonWav/MinecraftDevIntelliJ/blob/master/build.gradle.kts
