### ISSUE TITLE
Switching branches removes a line from plugin.xml

### ISSUE THREAD

**Issue by rsmckinney** [JetBrains/gradle-intellij-plugin#1261]
Running buildPlugin task removes a line from plugin.xml.

My plugin.xml file has a section like this:
```xml
. . .
    <applicationService serviceInterface="com.intellij.lang.PsiBuilderFactory"
                        serviceImplementation="manifold.ij.extensions.ManPsiBuilderFactoryImpl" overrides="true"/>

    <!--<library.type implementation="manifold.ij.extensions.ManLibraryType"/>-->

<!--    disabled indefinitely, inconsistent wrt downloading manifold etc.  -->
<!--    <frameworkSupport implementation="manifold.ij.extensions.ManSupportProvider"/>-->

    <postStartupActivity implementation="manifold.ij.core.ManStartupActivity" order="first"/>

<!--    <framework.type implementation="manifold.ij.extensions.ManFrameworkType"/>-->
    <java.elementFinder implementation="manifold.ij.extensions.ManTypeFinder" order="first, before java"/>
    <java.shortNamesCache implementation="manifold.ij.extensions.ManShortNamesCache"/>
. . .
```
When I run buildPlugin it quietly removes the following line:
```xml
<postStartupActivity implementation="manifold.ij.core.ManStartupActivity" order="first"/>
```

If I instead put the line after the comments, it works ok.  This has caused a lot of pain.

Using gradle intellij plugin version 1.10.1

**Comment by rsmckinney** [comment]
Correction:

The buildPlugin task is NOT the culprit.  It appears these are the steps:
- run intellij, open project, and checkout master branch, there are no local changes
- from intellij UI checkout an earlier branch from master branch
- after IJ settles the plugin.xml file is modified matching a blank line from the master branch's version of plugin.xml, this is wrongly done by intellij, there should be no local changes 
- rollback that weird change and get this - Error:unable to unlink old 'src/main/resources/META-INF/plugin.xml': Invalid argument
- manually rollback the change so that there are no local changes
- now switch back to the master branch
- again intellij wrongly modifies the plugin.xml file, this time silently removing the line as described above

Not sure where to log this error, please advise.  Thanks.

**Comment by YannCebron** [comment]
sounds like VCS system problem in IDE, please report in https://youtrack.jetbrains.com/issues/IDEA
