### ISSUE TITLE
Unzipping idea zip right into repo

### ISSUE THREAD

**Issue by da1z** [JetBrains/gradle-intellij-plugin#127]
Hello
I have custom idea build which I store in custom maven repo in network folder(\\name\mavenrepo). When I am building my plugin the intellij idea plugin unzipping my idea zip in the same folder where it is located in maven repo. How can I set it up to download idea zip to Gradle cache or somewhere else to machine where plugin is being built?

Thanks

**Comment by zolotov** [comment]
Hi,

I'm not sure, I need to debug it, how did you create your custom maven repo?

**Comment by da1z** [comment]
It just network folder, where I published custom idea build with maven-publish Gradle plugin.

**Comment by da1z** [comment]
If you specify repo as http:// then everything works good. This issue occurs only if you you repo path like \\\\servername\maven

**Comment by zolotov** [comment]
try `intellij.ideaDependencyCachePath` option in the new snapshot. See README to find out how to use snapshot versions
