### ISSUE TITLE
Gradle configuration cache breaks form instrumentation

### ISSUE THREAD

**Issue by YannCebron** [JetBrains/gradle-intellij-plugin#1283]
**Describe the bug**

Instrumented form class breaks on 2nd `runIde` invocation

original report https://youtrack.jetbrains.com/issue/IDEA-310211 contains sample project and workaround to disable caching which makes it work again

**Environment:**
 - OS: any
 - Gradle IntelliJ Plugin Version 1.11.0/1.12.0
 - Gradle Version 7.5.1, 7.6.0 is also affected

**Comment by hsz** [comment]
Fix available in the latest `1.12.3-SNAPSHOT` release — will be available in the upcoming release.

Note, if you work on a multi-module project, and your submodule uses Gradle IntelliJ Plugin, to use instrumented jar, please use:

 ```
dependencies {
    implementation(project(":submodule", "instrumentedJar"))
}
```
