### ISSUE TITLE
Add ARM64 support for intellij-gradle-plugin

### ISSUE THREAD

**Issue by rogerhu** [JetBrains/gradle-intellij-plugin#1287]
**Is your feature request related to a problem? Please describe.**

I'm trying to use the IntelliJ Gradle plugin with Android Studio Electric Eel:

```
intellij {
  type = "AI"
  version = "221.6008.13.2211.9477386"
}
```

Even I I have to set `os.arch` as my property, I think there is a hard-code check for the -linux.

https://github.com/JetBrains/gradle-intellij-plugin/blob/37cef2c46f6bdf6530f431fbe1855732a910a172/src/main/kotlin/org/jetbrains/intellij/dependency/IdeaDependencyManager.kt#L348

**Describe the solution you'd like**

The code should not be hardcoded to -linux and determine the architecture/type?

https://github.com/JetBrains/gradle-intellij-plugin/blob/37cef2c46f6bdf6530f431fbe1855732a910a172/src/main/kotlin/org/jetbrains/intellij/tasks/RunPluginVerifierTask.kt#L549-L550

**Describe alternatives you've considered**

Copying code from https://github.com/gradle/gradle-profiler/blob/bca64e8a173cb969c1e280b8fe634ffe6ace0dd0/buildSrc/src/main/kotlin/profiler.android-studio-setup.gradle.kts to perform the same behavior.

**Additional context**

Stack trace when running on an M1 laptop:

```
> Failed to query the value of task ':tooling:idea-toolkit:public:prepareSandbox' property 'pluginDependencies'.
   > Could not resolve all files for configuration ':tooling:idea-toolkit:public:z50_ideaPlugins'.
      > Could not find lib/javacpp-1.5.7-linux-x86_64-android-studio-AI-221.6008.13.2211.9477386-unzipped.com.jetbrains.plugins.jar (unzipped.com.jetbrains.plugins:android:android-studio-AI-221.6008.13.2211.9477386).
        Searched in the following locations:
            file:/Users/rogerh/.gradle/caches/modules-2/files-2.1/com.google.android.studio/android-studio/221.6008.13.2211.9477386/132ff7de19537764d788ee68d3f238aea1040c5/android-studio-221.6008.13.2211.9477386/plugins/android/lib/javacpp-1.5.7-linux-x86_64.jar
            file:/Users/rogerh/.gradle/caches/modules-2/files-2.1/com.google.android.studio/android-studio/221.6008.13.2211.9477386/132ff7de19537764d788ee68d3f238aea1040c5/android-studio-221.6008.13.2211.9477386/lib/javacpp-1.5.7-linux-x86_64.jar
            file:/Users/rogerh/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins/android-android-studio-AI-221.6008.13.2211.9477386/lib/javacpp-1.5.7-linux-x86_64.jar
      > Could not find lib/ffmpeg-5.0-1.5.7-linux-x86_64-android-studio-AI-221.6008.13.2211.9477386-unzipped.com.jetbrains.plugins.jar (unzipped.com.jetbrains.plugins:android:android-studio-AI-221.6008.13.2211.9477386).
        Searched in the following locations:
            file:/Users/rogerh/.gradle/caches/modules-2/files-2.1/com.google.android.studio/android-studio/221.6008.13.2211.9477386/132ff7de19537764d788ee68d3f238aea1040c5/android-studio-221.6008.13.2211.9477386/plugins/android/lib/ffmpeg-5.0-1.5.7-linux-x86_64.jar
            file:/Users/rogerh/.gradle/caches/modules-2/files-2.1/com.google.android.studio/android-studio/221.6008.13.2211.9477386/132ff7de19537764d788ee68d3f238aea1040c5/android-studio-221.6008.13.2211.9477386/lib/ffmpeg-5.0-1.5.7-linux-x86_64.jar
            file:/Users/rogerh/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins/android-android-studio-AI-221.6008.13.2211.9477386/lib/ffmpeg-5.0-1.5.7-linux-x86_64.jar

* Try:
```

**Comment by Undin** [comment]
@rogerhu what version of gradle plugin do you use? The proper support was implemented in #1231 and available since 1.10.1

**Comment by rogerhu** [comment]
I tried 1.10.2. I think it triggers the verifier is still hard-coded to -linux?

https://github.com/JetBrains/gradle-intellij-plugin/blob/37cef2c46f6bdf6530f431fbe1855732a910a172/src/main/kotlin/org/jetbrains/intellij/tasks/RunPluginVerifierTask.kt#L549-L550

**Comment by Undin** [comment]
I don't think so. Of course, if you don't call a verifier task youself

But I probably know how to solve your problem. The plugin has a cache of libraries for each IDE and plugin (including Android Studio). And if it exists (even built by an old version of the plugin), the plugin relies on it during dependency resolution. I suppose you tried to use old plugin version before where only linux version of AS was downloaded. The plugin created library cache (with linux specific libraries), and now it fails because your local AS build for mac doesn't contain linux-specific libraries (as expected, of course)

Let's try to clear the cache. It's located in `~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins`. Just drop the whole `unzipped.com.jetbrains.plugins` dir for simplicity and the plugin will rebuild the cache

**Comment by rogerhu** [comment]
Ok good point!  Thanks for the guidance.

**Comment by rogerhu** [comment]
Closing for now.
