### ISSUE TITLE
taskdef class com.intellij.ant.InstrumentIdeaExtensions cannot be found

### ISSUE THREAD

**Issue by stevemessick** [JetBrains/gradle-intellij-plugin#1288]
This and #1246 are blocking the Flutter plugin for IntelliJ from being released for 2023.1 EAP. It is possible #1246 is fixed although still open. I was hoping to test that.

I'm using Gradle 7.5.

I updated the IntelliJ plugin for Gradle from 1.9.0 to 1.12.0 and got this error.

>   * What went wrong:
  Execution failed for task ':flutter-idea:instrumentCode'.
  > taskdef class com.intellij.ant.InstrumentIdeaExtensions cannot be found
     using the classloader AntClassLoader[]

**Comment by hsz** [comment]
Fixed in `1.13.1-SNAPSHOT`

**Comment by hsz** [comment]
@caiqichang Please migrate to IntelliJ Platform Gradle Plugin 2.x in the first place.
