### ISSUE TITLE
Using unexisting configuration leads to downloading IDEA EAP SNAPSHOT

### ISSUE THREAD

**Issue by raniejade** [JetBrains/gradle-intellij-plugin#129]
I have the following configuration:

```gradle
intellij {
    version = '2016.1'
    type = 'IC'
    updateSinceUntilBuild = false
    plugins = ['org.jetbrains.kotlin:1.0.3-release-IJ2016.1-103']
    downloadSources = true
}
```

I'm not using the EAP snapshot, so why is it triggering a download?
```
$ ./gradlew clean buildPlugin
Download https://www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/LATEST-EAP-SNAPSHOT/ideaIC-LATEST-EAP-SNAPSHOT.zip
> Configuring > 1/1 projects > 3.30 MB/262.05 MB downloaded^C%      
```

**Comment by zolotov** [comment]
> I'm not using the EAP snapshot

obviously you're using EAP and you are not using `2016.1` version. 

Provided information is not enough to found out what's configured wrong.

**Comment by raniejade** [comment]
Here's my build.gradle file https://github.com/raniejade/spek-idea-plugin/blob/master/build.gradle.

> intellij.version defines the version of IDEA distribution that should be used as a dependency. The option accepts build numbers, version numbers and two meta values LATEST-EAP-SNAPSHOT, LATEST-TRUNK-SNAPSHOT. 
Value may have IC- or IU- prefix in order to define IDEA distribution type. 

Can you guide me into setting my build to use `2016.1` and not the eap snapshot?

```gradle
intellij {
    version = '2016.1'
    type = 'IC'
    updateSinceUntilBuild = false
    plugins = ['org.jetbrains.kotlin:1.0.3-release-IJ2016.1-103']
    downloadSources = true
}
```

**Comment by zolotov** [comment]
Works fine for me. Here is the output:

```
~/dev/intellij-plugins/spek-idea-plugin  (master) ᐅ ./gradlew --info buildPlugin
Starting Build
Settings evaluated using settings file '/Users/zolotov/dev/intellij-plugins/spek-idea-plugin/settings.gradle'.
Projects loaded. Root project using build file '/Users/zolotov/dev/intellij-plugins/spek-idea-plugin/build.gradle'.
Included projects: [root project 'spek-idea-plugin']
Evaluating root project 'spek-idea-plugin' using build file '/Users/zolotov/dev/intellij-plugins/spek-idea-plugin/build.gradle'.
Configuring IntelliJ IDEA gradle plugin
Configuring IntelliJ IDEA dependency
Failed to get resource: HEAD. [HTTP HTTP/1.1 500 Internal Server Error: https://jetbrains.jfrog.io/jetbrains/spek-snapshots/com/jetbrains/intellij/idea/ideaIC/2016.1/ideaIC-2016.1.pom]
Adding IntelliJ IDEA sources repository
Failed to get resource: HEAD. [HTTP HTTP/1.1 500 Internal Server Error: https://jetbrains.jfrog.io/jetbrains/spek-snapshots/com/jetbrains/intellij/idea/ideaIC/2016.1/ideaIC-2016.1.pom]
IntelliJ IDEA IC-145.258.11 is used for building
```

145.258.11 is 2016.1

**Comment by raniejade** [comment]
I see, using the `compileOnly` (introduced in gradle 2.12) configuration breaks stuff. 

With this I always download the eap.
```gradle
dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
    compile "org.jetbrains.kotlin:kotlin-runtime:$kotlinVersion"
    compileOnly 'org.junit.platform:junit-platform-launcher:1.0.0-M2'

    spek "org.jetbrains.spek:spek-junit-platform-engine:1.0.0-SNAPSHOT"
    spek 'org.junit.platform:junit-platform-launcher:1.0.0-M2'
}
```

Using `compile` instead of `compileOnly` fixes it somehow.
```gradle
dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
    compile "org.jetbrains.kotlin:kotlin-runtime:$kotlinVersion"
    compile 'org.junit.platform:junit-platform-launcher:1.0.0-M2'

    spek "org.jetbrains.spek:spek-junit-platform-engine:1.0.0-SNAPSHOT"
    spek 'org.junit.platform:junit-platform-launcher:1.0.0-M2'
}
```

**Comment by zolotov** [comment]
Still nothing :( I've changed `compile` to `compileOnly` and I have the same output

**Comment by zolotov** [comment]
Found it. If I change `compile` to `compileOnly111111`, I get the same behaviour you describe.

I think you have an old gradle wrapper which has no support for `compileOnly` configurations. So you have to update gradle wrapper anyway if you want `compileOnly` dependencies.

I'll try to figure out why gradle plugin reacts in this strange way.

**Comment by zolotov** [comment]
Well, looks like it's gradle's pecularity. Actually I believe you'll get an exception as soon as EAP will be downloaded. But it's better to move downloading after the possible exception, the issue #123 is about it

**Comment by TomasYu** [comment]
`buildscript {

    ext.kotlin_version = '1.0.4'

    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "net.ltgt.gradle:gradle-apt-plugin:0.9"
    }
}

plugins {
    id "org.jetbrains.intellij" version "0.1.10"
}

sourceCompatibility = 1.8
targetCompatibility = 1.8



apply plugin: 'java'
apply plugin: 'kotlin'


repositories {
    mavenCentral()
    jcenter()
}

sourceSets {
    main {
        resources {
            exclude 'website/adb_operations_popup.png'
            exclude 'website/find_actions.png'
            exclude 'website/debug_howto.png'
        }
    }

    main.java.srcDirs += 'build/generated/source/kapt/main'
}

kapt {
    generateStubs = true
}

if (!hasProperty('StudioCompilePath')) {
    throw new GradleException("No StudioCompilePath value was set, please create gradle.properties file")
}

intellij {
    version 'IC-171.3780.95' // this value is not important, as long as you can compile
    Windows 8.1 6.3
    pluginName 'adb_idea'
    updateSinceUntilBuild false

    intellij.alternativeIdePath = project.hasProperty("StudioRunPath") ? StudioRunPath : StudioCompilePath
}

group 'com.developerphil.intellij.plugin.adbidea'

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib:${kotlin_version}"
    compile "org.jetbrains.kotlin:kotlin-runtime:${kotlin_version}"
    compileOnly fileTree(dir: "$StudioCompilePath/plugins/android/lib", include: ['*.jar'])
    compileOnly fileTree(dir: "$StudioCompilePath/lib", include: ['*.jar'])
    compile 'com.google.dagger:dagger:2.6'
    kapt "com.google.dagger:dagger-compiler:2.6"

    testCompile 'junit:junit:4.12'
    testCompile fileTree(dir: "$StudioCompilePath/plugins/android/lib", include: ['*.jar'])
    testCompile fileTree(dir: "$StudioCompilePath/lib", include: ['*.jar'])
    testCompile "org.mockito:mockito-core:1.+"
    testCompile "com.google.truth:truth:0.30"


}

configurations {
    compile.exclude module: 'idea'
}

task(verifySetup) << {

    def ideaJar = "$StudioCompilePath/lib/idea.jar"
    if (!file(ideaJar).exists()) {
        throw new GradleException("$ideaJar not found, set StudioCompilePath in gradle.properties")
    }
}


compileJava.dependsOn verifySetup
`


Starting a Gradle Daemon (subsequent builds will be faster)
Download https://www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/LATEST-EAP-SNAPSHOT/ideaIC-LATEST-EAP-SNAPSHOT.zip
> > > > > > > > > > > > > Configuring > 1/1 projects > 1.76 MB/352.01 MB downloaded终止批处理操作吗(Y/N)? Y


why download https://www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/LATEST-EAP-SNAPSHOT/ideaIC-LATEST-EAP-SNAPSHOT.zip?
