### ISSUE TITLE
SNAPSHOT: Exclude strategy when building jar fails

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/gradle-intellij-plugin#1303]
**Describe the bug**
Use (1.12.1/2-) SNAPSHOT with this [commit](https://github.com/JetBrains/gradle-intellij-plugin/commit/e32fb153fe944986e73dd89369ca70ebddf18703)

```
> Entry app/softwork/kobol/intellij/CobolReferenceContributor.class is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/8.0-rc-2/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

**To Reproduce**
I tried to create a reproducer but I am unable to reproduce it with a simple project.
https://scans.gradle.com/s/4do5n36ocrwhs

**Expected behavior**
Working build.

**Environment:**
 - Gradle IntelliJ Plugin Version: 1.12.1-SNAPSHOT / 1.12.2-SNAPSHOT
 - Gradle Version: 8.0-rc2

**Comment by hfhbd** [comment]
Workaround: 
```
tasks.jar {
  duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
```
You should not reconfigure (user)/existing tasks. Instead, create your own tasks, configure them, and use this output for your instrumentation tests.

**Comment by hsz** [comment]
Thank you for reporting, Philip!
I bet your sources aren't available for the local debug session.

I was about to mention the workaround you just posted, but you were faster.

The problem with the Jar task — which is also the reason for the latest commit you linked — is that the instrumented classes are packed together with the "raw" compiled classes when using the include strategy.
That leads to the situation where JVM ignores the latter classes in the runtime, so GUI forms aren't rendered or JetBrains annotations get ignored.

**Comment by hfhbd** [comment]
Yeah, there are closed-source.

I see, only a guess, what about creating your own jar task and adding the instrumentation classes to this jar only for your tests?

**Comment by hsz** [comment]
@hfhbd I have explored all the possibilities. I created a custom `instrumentJar` task that puts instrumented classes first place and applies the original `Jar` task content over it with the `EXCLUDE` strategy used.
With this approach, the `prepareSandbox` task is able to switch to the custom jar artifact, but it makes things cocanwhen it comes to the multi-modules project.
Now, to include a submodule in your configuration, it's required to go with:

```
dependencies {
    implementation(project(":submodule", "instrumentedJar"))
}
```

Can you please test the latest snapshot?

**Comment by hfhbd** [comment]
Works with 1.12.3-SNAPSHOT, workaround isn't needed anymore.
