### ISSUE TITLE
I cannot find lastest version in https://plugins.gradle.org/m2/org/jetbrains/intellij/org.jetbrains.intellij.gradle.plugin/

### ISSUE THREAD

**Issue by yioyin** [JetBrains/gradle-intellij-plugin#1321]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yioyin** [comment]
> 具体什么是“最新”版本？

Thank you for your reply.
When targeting 2022.3+ IDE releases, using Gradle IntelliJ Plugin version 1.10.1 or higher is required.
The latest version in the repository(https://plugins.gradle.org/m2/) is 1.9.0.
So I can't get the Gradle IntelliJ Plugin version that Intellij 2022.3+ needs.
Please push versions 1.9.0-1.13.0 to the repository(https://plugins.gradle.org/m2/).

**Comment by hsz** [comment]
The URL you've provided in the issue title isn't the valid one. Instead, use:

> https://plugins.gradle.org/m2/org/jetbrains/intellij/plugins/gradle-intellij-plugin/

**Comment by yioyin** [comment]
> The URL you've provided in the issue title isn't the valid one. Instead, use:
> 
> > https://plugins.gradle.org/m2/org/jetbrains/intellij/plugins/gradle-intellij-plugin/

https://plugins.gradle.org/m2/org/jetbrains/intellij/plugins/gradle-intellij-plugin/
This url has the same problem with the url in my issue title

**Comment by hsz** [comment]
But everything is already in place, i.e., https://plugins.gradle.org/m2/org/jetbrains/intellij/plugins/gradle-intellij-plugin/1.13.0/
