### ISSUE TITLE
Please provide option to skip http link check.

### ISSUE THREAD

**Issue by meiMingle** [JetBrains/gradle-intellij-plugin#1324]
**Is your feature request related to a problem? Please describe.**
See [Failed Action](https://github.com/meiMingle/TSvnPwd-intellij/actions/runs/4250689639/jobs/7392098785).
For some reason, I have to keep http links in the description, but I didn't find a configurable option for this in the plugin's documentation.

**Describe the solution you'd like**
Please provide option to skip http link check.

**Describe alternatives you've considered**

**Additional context**

**Comment by meiMingle** [comment]
Disable verifyPlugin task is not what I want, because I still want checks other than this to run.In addition, the website pointed to by the link is not under my control, and it is unreachable to persuade the website administrator to switch to https

**Comment by YannCebron** [comment]
Then please use https://tinyurl.com/app or similar service. Plugin description with HTTP link will not be accepted on JetBrains Marketplace.
