### ISSUE TITLE
Could not find launch information for the current OS: Mac OS X (amd64)

### ISSUE THREAD

**Issue by stevemessick** [JetBrains/gradle-intellij-plugin#1328]
I'm not sure if this is the same problem as #1246 or not. I thought that was fixed, but I may have not tested it properly. I'm using 1.13.1-SNAPSHOT.

When I try to launch IntelliJ in the debugger with the Flutter plugin sources, I get this error:
```
Execution failed for task ':flutter-idea:runIde'.
> Could not find launch information for the current OS: Mac OS X (amd64)
```
I get the same error when I try to run unit tests.

I think you can reproduce the problem without too much trouble.
- Install the [Flutter plugin](https://github.com/flutter/flutter-intellij) source from GitHub
- Patch in this PR: https://github.com/flutter/flutter-intellij/pull/6651
- From the command line, `cd` to that directory
- `bin/plugin setup`
- `./gradlew test`

**Comment by hsz** [comment]
The IDE you use for running doesn't contain the proper `product-info.json` file relevant to your OS.
Could you please provide the content of that file? An example path is:

```
/Users/hsz/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2022.3.1/2a2986db4e11c3d378b4d1c8b9fd040cd6d99802/ideaIC-2022.3.1/product-info.json
```

**Comment by stevemessick** [comment]
I see what the problem is. Thanks! I know how to fix it.
