### ISSUE TITLE
IDE distribution gets downloaded on project sync with Gradle files

### ISSUE THREAD

**Issue by technoir42** [JetBrains/gradle-intellij-plugin#1339]
**Describe the bug**
We have a large Gradle project with many modules. One of the modules is an Android Studio plugin where `org.jetbrains.intellij` is applied.
When syncing Android Studio project with Gradle files, IDE distribution gets downloaded prematurely.

**To Reproduce**
Open any sample IDEA plugin project in Android Studio for the first time.

**Expected behavior**
IDE distribution gets downloaded only when a module with `org.jetbrains.intellij` plugin gets built.

**Environment:**
 - Android Studio Electric Eel | 2022.1.1
 - Gradle IntelliJ Plugin Version 1.13.1

**Additional context**
-

**Comment by hsz** [comment]
This is because you require a specific SDK for development, which IDE uses for auto-completion, so it gets downloaded.
You have to treat it as a regular project dependency.
