### ISSUE TITLE
Plugin dependency compatibility issues

### ISSUE THREAD

**Issue by Turbo87** [JetBrains/gradle-intellij-plugin#134]
I'm using the following Gradle file:

```groovy
intellij {
    type = 'IU'
    version = '2016.2'
    plugins = ['JavaScriptLanguage', 'CSS', 'com.dmarcotte.handlebars:162.80']
}
```

but when running `./gradlew runIdea` I'm seeing this error:

```
Plugin com.dmarcotte.handlebars:162.80 is not compatible to IU-162.1121.32
```

https://plugins.jetbrains.com/plugin/6884 states that the compatible builds are `162.80—162.*` so `2016.2 = 162.1121.32` should work fine.

I'm not sure if that is indeed a bug in the Gradle plugin or if I'm doing some else wrong, but I can't seem to make it work for `2016.2`.

Note that it works fine with `2016.1` and `145.9` of the Handlebars plugin.

/cc @denofevil

**Comment by zolotov** [comment]
Please try 0.2-SNAPSHOT, there are some fixes in this field. See README to know how to use SNAPSHOT builds

**Comment by Turbo87** [comment]
that seems to work, thanks!

I did see the following error after updating the plugin though:

```
Could not read entry ':prepareSandbox' from cache taskArtifacts.bin (/Users/tbn/Code/intellij-emberjs/.gradle/2.14.1/taskArtifacts/taskArtifacts.bin).
> org.jetbrains.intellij.dependency.PluginDependency; local class incompatible: stream classdesc serialVersionUID = 2952204855539725202, local class serialVersionUID = 560590560477762714
```

it went away once I removed the cached `taskArtifacts.bin` file.

**Comment by zolotov** [comment]
cannot recreate on switching from 0.1.10 to 0.2-snapshot. what was the version you used before&

**Comment by Turbo87** [comment]
I think it was 0.1.9 before.

**Comment by zolotov** [comment]
cannot recreate :(
