### ISSUE TITLE
Can not build project

### ISSUE THREAD

**Issue by eddumelendez** [JetBrains/gradle-intellij-plugin#1340]
**Describe the bug**
Using IntelliJ 2023.1 beta 2 (with Gradle bundled 231.8109.2) I got `Build not found: BuildId(buildRoot=/Users/eddumelendez/Downloads/git/testcontainers-java/buildSrc)`. However, when using Intellij 2022.3.2 (with Gradle bundled 223.8617.56) the project is built correctly.

This is the [project](https://github.com/testcontainers/testcontainers-java)

**To Reproduce**
Download https://github.com/testcontainers/testcontainers-java and open it in Intellij 2023.1 beta 2

**Expected behavior**
Open the project successfully and render the modules in the Gradle tab.

**Environment:**
 - OS: macOS
 - Gradle IntelliJ Plugin Version: IntelliJ 2023.1 beta 2 (with Gradle bundled 231.8109.2)  
 - Gradle Version: 8.0.2

**Additional context**

**Comment by hsz** [comment]
@eddumelendez, this repository is related to the Gradle IntelliJ Plugin — a Gradle plugin for building plugins for IntelliJ-based IDEs; not the Gradle plugin that exists within the IDE.

Please report your issue on YouTrack: git@github.com:testcontainers/testcontainers-java.git
