### ISSUE TITLE
Disable patchPluginXml (or gradle at all?)

### ISSUE THREAD

**Issue by stokito** [JetBrains/gradle-intellij-plugin#1344]
I don't want to use the Gradle plugin at all and I already have a proper plugin.xml.
But it looks like I can't build anymore my plugin without the gradle plugin. Right?

I was able somehow to configure it but the patchPluginXml messed my plugin.xml
First of all I with to build for the 2023.1 Beta but when I set

    intellij {
        version.set("2023.1")
        type.set("IC")
    }

The build fails because the artifact wasn't yet uploaded to maven central
https://mvnrepository.com/artifact/com.jetbrains.intellij.idea/ideaIC
Should I add some another repo?

Next I configured the patchPluginXml section

    patchPluginXml {
        sinceBuild.set("223")
    }

And I mean that my plugin's version was tested on the `223` version but it also should work in future and the untilBuild is not set intentionally. But the patchPluginXml anyway set until "223.*" e.g. my plugin not works in the 2023.1 Beta. So I just can't leave the untilBuild empty and I'll need to rebuild and republish the plugin for the next IntelliJ version. I can't spent my time on this.

I removed the whole patchPluginXml section but it still generated the since/until while I not asked to.

**Comment by hsz** [comment]
> The build fails because the artifact wasn't yet uploaded to maven central

SDKs aren't published to Maven Central but hosted in IntelliJ Maven Repository: https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

> `sinceBuild.set("223")`

You shouldn't set the `sinceBuild` to the version lower than the target SDK you use to build the plugin.

What you could set is:

```
intellij {
    version.set("2022.3.3")
    type.set("IC")
}

patchPluginXml {
    sinceBuild.set("223")
    untilBuild.set("231.*")
}
```

and verify with `runPluginVerifier` that there are no compatibility issues reported before publishing.

**Comment by YannCebron** [comment]
Please see https://plugins.jetbrains.com/docs/intellij/configuring-plugin-project.html

**Comment by stokito** [comment]
@hsz 
> You shouldn't set the sinceBuild to the version lower than the target SDK you use to build the plugin.
This will implicitly set untilBuild but I don't want to do this. I have plugins that didn't updated for years and they still working. I just don't know the until build

**Comment by hsz** [comment]
You can bypass that by setting an empty string to the `untilBuild` property, but it isn't recommended approach.

**Comment by stokito** [comment]
thank you, you answered all my questions
