### ISSUE TITLE
Hide warning about missing plugin.xml

### ISSUE THREAD

**Issue by Virtlink** [JetBrains/gradle-intellij-plugin#135]
I have applied this plugin to some projects that depend on IntelliJ but aren't IntelliJ plugins (i.e. they don't have a `plugin.xml` file). For these projects I get this warning:

> plugin.xml with 'idea-plugin' root is not found. IntelliJ specific tasks will be unavailable for project.

It would be nice if an option could be added to hide this warning for these projects, like `isPlugin = false`. This explicitly states that the project is not supposed to have a `plugin.xml` file and doesn't need the IntelliJ specific tasks, hiding the warning.

**Comment by nathanabercrombie** [comment]
@zolotov has posted in the past that in a future version, maybe in 2.0, the different parts of the plugin will be able to be applied independently.  So you would be able to apply the dependencies without having to apply the tasks, and I think that would solve the problem you are having.

**Comment by Virtlink** [comment]
Well that's okay. It's not urgent or anything. I am @zolotov extremely grateful for this plugin and all the effort he has spent on it. Without it I couldn't even do my master's research.

**Comment by zolotov** [comment]
@nathanabercrombie is right, I'm going to get rid of `project.afterEvaluate` while instantiating tasks and make tasks independent. I mean you will still in need of plugin.xml but only for executing particular tasks. I've done this for publishing and patching `plugin.xml` tasks, and I hope to do the same for the rest 3 tasks in a week or two.

**Comment by zolotov** [comment]
Fixed in 0.2-SNAPSHOT
