### ISSUE TITLE
How can I remove a task trigger?

### ISSUE THREAD

**Issue by ZakTaccardi** [JetBrains/gradle-intellij-plugin#1355]
I've added a task with a task trigger. 
```kts
idea.project.settings {
    taskTriggers {
        beforeSync(tasks.named("myTask"))
    }
}
```

How can I remove it programmatically?

**Comment by YannCebron** [comment]
how is this related to Gradle IntelliJ Plugin?

**Comment by yihtserns** [comment]
**NOTE**: Task Trigger is from https://github.com/JetBrains/gradle-idea-ext-plugin, not this plugin.

**Comment by hsz** [comment]
Gradle IntelliJ Plugin 1.x uses the Idea Ext to add this _Task Activation_ entry.
