### ISSUE TITLE
can't access diagrams api

### ISSUE THREAD

**Issue by eprst** [JetBrains/gradle-intellij-plugin#136]
There seems to be no way to build a plugin with UML diagrams support. Specifying 
```
type IU
plugins [ 'com.intellij.diagram' ]
```
(Plugin ID taken from plugins/uml/lib/uml-support.jar!/META-INF/plugin.xml) 
gives an error:

> Error:Cannot find builtin plugin com.intellij.diagram for IDE: ~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/2016.2/ed0e4e1f81b55ba0671088eb640580d2f562a547/ideaIU-2016.2

**Comment by zolotov** [comment]
use just `uml`
