### ISSUE TITLE
Could not resolve all files for configuration ':detachedConfiguration1'

### ISSUE THREAD

**Issue by rdzhaoxin** [JetBrains/gradle-intellij-plugin#1371]
**Describe the bug**
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Failed to transform app.jar to match attributes {artifactType=classpath-entry-snapshot, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for ClasspathEntrySnapshotTransform: /$home/.m2/repository/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/231.8109.175/6f24e7c3f8e3f3afd44014d4ade3aba8d78676d6/ideaIU-231.8109.175/lib/app.jar.
         > Java heap space

**To Reproduce**

**Expected behavior**

**Environment:**
 - OS: [e.g. macOS]
 - Gradle IntelliJ Plugin Version [1.13.3]
 - Gradle Version [Gradle 8.1]

**Additional context**
plugins {
    id("java")
    id("org.jetbrains.kotlin.jvm") version "1.8.20"
    id("org.jetbrains.intellij") version "1.13.3"
}

**Comment by hsz** [comment]
See: https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin-faq.html#kotlin-compiler-throws-out-of-memory-java-heap-space-error
