### ISSUE TITLE
Cant install/publish plugin

### ISSUE THREAD

**Issue by robohorse** [JetBrains/gradle-intellij-plugin#138]
Hello!

There is my build.gradle file https://github.com/robohorse/RoboPOJOGenerator/blob/master/build.gradle

I have success completed task runIdea, but i cant install my plugin on current version 2016.3.
“Plugin is incompatible with this installation” error occurs.

I unzipped gradle-built archive and it has different structure, than archive, created by intellij by default plugin builder. Is it reason to fail and could you fix it plz?

**Comment by robohorse** [comment]
ok, the problem was in version: IC-2016.2 was solved my problem. But there is another question: how about Android Studio?

**Comment by shiraji** [comment]
intellij.alternativeIdePath

**Comment by zolotov** [comment]
> Is it reason to fail and could you fix it plz?

no, it's not the reason

> “Plugin is incompatible with this installation” error occurs.

This literally means that plugin is incompatible with the IDE. It has nothing to do with `gradle-intellij-plugin`
