### ISSUE TITLE
Kotlin Compiler Can Not See Scala Code When using Gradle

### ISSUE THREAD

**Issue by 06needhamt** [JetBrains/gradle-intellij-plugin#139]
The Koltin compiler can not resolve references within Scala files at compile time when using the Gradle Build System. However all Scala references are correctly resolved when using the standard IDEA build System. So for now we can not reference any Scala code from within the plugin until this issue is resolved

**Comment by zolotov** [comment]
How is this related to gradle-intellij-plugin?

**Comment by 06needhamt** [comment]
I'm not sure exactly what this is related to but this issue only occurred after I switched over to using gradle to build my plugin

**Comment by zolotov** [comment]
I bet you use a dozen of other plugins as well. This plugin does not compile kotlin or scala or anything else, I don't see how it can lead to the problem you have.
