### ISSUE TITLE
Support plugin.jetbrains.com dependencies

### ISSUE THREAD

**Issue by zolotov** [JetBrains/gradle-intellij-plugin#14]
Add ability to depend on plugins from jetbrains plugins repository.

**Comment by AmailP** [comment]
+1

**Comment by Turbo87** [comment]
@zolotov can this be done manually at the moment somehow? do you have any idea how this could be implemented?

**Comment by zolotov** [comment]
@Turbo87 sure it can be done manually. Essentially, you should do 2 things:

1. attach plugin's jars as compile dependency
1. add plugin's jars to sandbox

So manual setup might looks like following:

1. Download plugin zip or jar (manually or with gradle)
1. Copy JAR or unzip ZIP it to intellij.sandboxDirectory/plugins/
1. Add Dependency

```
dependencies {
    // jar plugin
   compile files("${intellij.sandboxDirectory}"/plugins/myCustomPluginName.jar")

    // zip plugin
   compile files("${intellij.sandboxDirectory}"/plugins/myCustomPluginName/classes")
   runtime fileTree(dir: "${intellij.sandboxDirectory}"/plugins/myCustomPluginName/", include: '*.jar')
}
```

I didn't try this code, but it looks like valid :)

**Comment by Turbo87** [comment]
@zolotov is JetBrains exposing the plugin jar or zip files through some API? from the links in the plugin repo it looks quite complicated to find and download the corresponding files automatically.

**Comment by zolotov** [comment]
@Turbo87 

https://plugins.jetbrains.com/plugins/list/
https://plugins.jetbrains.com/plugins/list/?pluginId=5047

**Comment by Turbo87** [comment]
awesome, that's what I was looking for :)

**Comment by Turbo87** [comment]
hmm it seems like I was a bit too fast with my response... where are the actual download links in those XML files?

**Comment by Turbo87** [comment]
I've tried it the manual way but I'm not sure if it works entirely as expected. Specifically I'd like to work with the [Handlebars](https://github.com/JetBrains/intellij-plugins/tree/master/handlebars) plugin code inside of [intellij-emberjs](https://github.com/Turbo87/intellij-emberjs).

I've downloaded https://plugins.jetbrains.com/plugin/download?pr=&updateId=21801 as `handlebars.zip` and extracted that into the `plugins` folder of the sandbox. When I run `./gradlew runIdea` I can now see the plugin being active.

I've added `files("${intellij.sandboxDirectory}/plugins/handlebars/lib/handlebars.jar")` to the `dependencies` section of my `build.gradle` file and I can see in IntelliJ that it picked up the dependency and is showing the Handlebars classes in an external library.

However when I call `./gradlew buildPlugin` the `handlebars.jar` file gets packaged into my own plugin's zip file and I don't think that it is supposed to be that way.

Also note that in my `plugin.xml` file I'm using `<depends optional="true">com.dmarcotte.handlebars</depends>` so the dependency on the Handlebars plugin should be optional. It might make sense to extract the plugin to a folder outside of the sandbox, use that for the dependency and only copy it into the sandbox if it should actually be used by `runIdea`.

BTW I've found https://github.com/michel-kraemer/gradle-download-task to simplify the zip file download

**Comment by zolotov** [comment]
> hmm it seems like I was a bit too fast with my response... where are the actual download links in those XML files?

I don't know yet.

> However when I call ./gradlew buildPlugin the handlebars.jar file gets packaged into my own plugin's zip file and I don't think that it is supposed to be that way.

Forgot to mention. Also you have to add all jars from plugin to ignored files:

```
intellij.intellijFiles.addAll(files(...))
```

>  if it should actually be used by runIdea.

What to you mean?

**Comment by Turbo87** [comment]
> > if it should actually be used by runIdea.

> What to you mean?

Since my plugin only optionally uses the other plugin I would need to test both cases: with and without the other plugin installed. I do always need to compile my plugin with the other plugin but I don't always want the other plugin to be installed in the IDE.

**Comment by zolotov** [comment]
> Since my plugin only optionally uses the other plugin I would need to test both cases: with and without the other plugin installed. I do always need to compile my plugin with the other plugin but I don't always want the other plugin to be installed in the IDE.

I understand that. How should user tell the plugin whether it should copy plugin-dependency or not?

**Comment by Turbo87** [comment]
one idea is to have an `optionalPlugins` property similar to the `plugins` property, that will download, extract and attach the dependencies, but won't add them to the sandbox.

maybe for convenience we could then also add `installOptionalPlugins` and `uninstallOptionalPlugins` tasks that add/remove the plugins to/from the sandbox.

**Comment by zolotov** [comment]
Thanks for suggestions. Yet another option: enable plugins depending on its declaration in `intellij` block, like

```groovy
intellij {
  plugin id: 5047, channel: 'alpha', enabled: false
}

**Comment by Turbo87** [comment]
yes, something like that sounds good. I guess having `enabled = true` as the default would make sense too.

**Comment by Turbo87** [comment]
https://github.com/Turbo87/intellij-emberjs/commit/96511401fdd98ce79236eb36bead3ee326811901 seems to work quite fine. I guess what's left now is generalizing this approach and automating it as part of the plugin.

**Comment by zolotov** [comment]
Looks good. Thank you for the experiment, will use it for implementing this in the plugin.

**Comment by gmandnepr** [comment]
Interested in this feature.

At the moment my workaround is
```
configurations {
    provided
}
sourceSets {
    main { compileClasspath += configurations.provided }
}
dependencies {
    provided fileTree(dir: 'libs', include: '*.jar')
}
```
Dependency is not included into result plugin jar. However it is optional and has to be installed in sandbox via plugins settings

**Comment by Turbo87** [comment]
closed as in solved or closed as in not going to happen? 😉

**Comment by zolotov** [comment]
@Turbo87 closed as solved, should work in `0.1.3` (it's not stable yet though). See README for details.

**Comment by Turbo87** [comment]
awesome, thanks!

**Comment by zolotov** [comment]
thank to @gmandnepr

**Comment by martin-linha** [comment]
> hmm it seems like I was a bit too fast with my response... where are the actual download links in those XML files?


> I don't know yet.

After some debugging of IntelliJ CE it seems that url to download any plugin from JetBrains repo is like

https://plugins.jetbrains.com/pluginManager/?action=download&id=AceJump&build=IC-162.539.11

**Comment by zolotov** [comment]
@martin-linha there is no need to debug anything, it's implemented and can be found in code of the plugin
