### ISSUE TITLE
Since Build property is overwrite

### ISSUE THREAD

**Issue by gengjiawen** [JetBrains/gradle-intellij-plugin#142]
Currently I am migrate a plugin to gradle, but I find the since-build property I write in xml will overwirte to latest. You can check the file: 
https://github.com/gengjiawen/GsonFormat/blob/e65a98e4cb75023604436eac6bde8ad885495984/src/main/resources/META-INF/plugin.xml

Enviroment: 
OS: Mac 
JDK: 1.8
Gradle: 3.1
Gradle-IntelliJ-Plugin: IC-2016.2.5

Is this a bug or do i miss something?

**Comment by zolotov** [comment]
You missed README. Please take a look at `updateSinceUntilBuild` option. Also since 0.2-SNAPSHOT you can modify `patchPluginXmlFiles` task.

At last, it's not recommended to use your own since/until builds.

**Comment by gengjiawen** [comment]
@zolotov But this plugin run in android studio too.If I don't write the since/until, it will not work on studio.I noticed the `patchPluginXmlFiles` task but I don't want to use snapshot version.And I do missed `updateSinceUntilBuild` part.Will checkout it.Thanks.

**Comment by zolotov** [comment]
> But this plugin run in android studio too

It's even funnier because there is NO Android Studio 107.120 build

**Comment by gengjiawen** [comment]
But it do works.And sqldelight use something similar too.
You can check it here https://github.com/square/sqldelight/blob/master/sqldelight-studio-plugin/src/main/resources/META-INF/plugin.xml.

**Comment by zolotov** [comment]
> But it do works.

I didn't say that it should, I said that using `107` builds doesn't make any sense and that it is antipattern.

**Comment by gengjiawen** [comment]
I admit it's hack :).Probobaly someday we can using this plugin develop for IntelliJ IDEA and Android  Studio simultaneously.
And `updateSinceUntilBuild` works fine.
Thanks again.
