### ISSUE TITLE
plugin.xml with 'idea-plugin' root is not found

### ISSUE THREAD

**Issue by aleksandra-majchrzak** [JetBrains/gradle-intellij-plugin#144]
I've created a plugin project and tried to apply gradle-intellij-plugin to it. I followed instruction [here](http://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/prerequisites.html) (point 1.3) with modifications on build.gradle file, but when I run `gradle cleanIdea` I get warning `plugin.xml with 'idea-plugin' root is not found. IntelliJ specific tasks will be unavailable for :project_name` and when i run `gradle runIdea` I get also `Task 'runIdea' not found in root project 'project_name'. Some candidates are: 'idea'.`

My build.gradle file is:

```
buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    id "org.jetbrains.intellij" version "0.1.10"
}

apply plugin: 'idea'
apply plugin: 'org.jetbrains.intellij'
apply plugin: 'java'

intellij {
    version 'IC-2016.1' //IntelliJ IDEA dependency
    plugins 'coverage' //Bundled plugin dependencies
    pluginName 'Plugin display name here'
}

group 'org.jetbrains'
version '1.2' // Plugin version 
```

Do I do something wrong? How else should I integrate this plugin with a standard plugin project? Any help would be appreciated.

**Comment by zolotov** [comment]
> I get warning plugin.xml with 'idea-plugin' root is not found. IntelliJ specific tasks will be unavailable for :project_name

The warning is quite descriptive. Where is you plugin.xml placed?

**Comment by aleksandra-majchrzak** [comment]
My project structure (autogenerated by InelliJ) looks like this:

```
-Project_name
  | .idea
  | out
  | resources
    | META-INF
      - plugin.xml
  | src
    - NewAction.java
  | Project_name.iml
- External Libraries
```

I tried putting build.gradle in main project directory / src directory / resources directory / META-INF directory- none of this worked.

**Comment by zolotov** [comment]
> My project structure (autogenerated by InelliJ) looks like this:

You should not mix up different approaches to develop plugins. You either create `IntelliJ IDEA Plugin` module and follow [correspinding tutorial](http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/prerequisites.html) and use autogenerated project structure. Or follow [the tutorial you have mentioned before](http://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/prerequisites.html) and create a Gradle module. In both cases, `META-INF/plugin.xml` should be placed under any `resources root`.
