### ISSUE TITLE
Execution failed for task ':instrumentCode'. > taskdef class com.intellij.ant.InstrumentIdeaExtensions cannot be found

### ISSUE THREAD

**Issue by nthykier** [JetBrains/gradle-intellij-plugin#1440]
**Describe the bug**
[Trying to upgrade from 1.3.3 to 1.5.0 (via dependabot)](https://github.com/nthykier/IDEA-debpkg/pull/127), my CI triggers the following errors:

```
FAILURE: Build failed with an exception.
> Task :instrumentCode FAILED

* What went wrong:
> Task :classpathIndexCleanup
Execution failed for task ':instrumentCode'.
> taskdef class com.intellij.ant.InstrumentIdeaExtensions cannot be found
   using the classloader AntClassLoader[]
```

CI link: https://github.com/nthykier/IDEA-debpkg/actions/runs/5699760782/job/15448987085

The project is set to using gradlew 8.2.1.

I have no clue what would trigger this crash (I do not feel I am using any exotic configuration of the IntelliJ gradle plugin).  I am deliberately using 2022.2 as platformVersion to keep backwards compatibility with older versions of IDEA (I target 2021.2 - 2023.2  at the moment). Not sure if that is related/relevant.

**To Reproduce**
CI link: https://github.com/nthykier/IDEA-debpkg/actions/runs/5699760782/job/15448987085

**Expected behavior**

**Environment:**
 - OS: GitHub CI
 - Gradle IntelliJ Plugin Version: 1.5.0 (upgrade from 1.3.3)
 - Gradle Version: 8.2.1

**Comment by YannCebron** [comment]
1. Please run Gradle task "build setup - wrapper" twice on your project to update `gradlew|.bat` files
2. You build against `platformVersion = 2022.2` but specify explicitly _lower_ minimum compatibility `pluginSinceBuild = 212` (2021.2), these two should always be aligned
3. there's obsolete Gradle version entry here https://github.com/nthykier/IDEA-debpkg/blob/main/gradle.properties#L16

**Comment by hsz** [comment]
As @YannCebron said — Gradle didn't get updated, and the since-build doesn't match the platform version. Below you'll find a patch with relevant changes:

```
Subject: [PATCH] cleanup
---
Index: gradle.properties
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>ISO-8859-1
===================================================================
diff --git a/gradle.properties b/gradle.properties
--- a/gradle.properties	(revision e35b49e00c628129d4f391d08e6af464d25ce2a2)
+++ b/gradle.properties	(date 1690904088036)
@@ -8,10 +8,10 @@
 pluginUntilBuild = 232.*
 
 platformType = IC
-platformVersion = 2022.2
+platformVersion = 2021.2
 platformDownloadSources = true
 
 # Plugin Verifier integration -> https://github.com/JetBrains/gradle-intellij-plugin#plugin-verifier-dsl
 pluginVerifierIdeVersions = 2021.2, 2022.3, 2023.2
-gradleVersion=7.3
+gradleVersion=8.2.1
 javaVersion=11
Index: build.gradle.kts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/build.gradle.kts b/build.gradle.kts
--- a/build.gradle.kts	(revision e35b49e00c628129d4f391d08e6af464d25ce2a2)
+++ b/build.gradle.kts	(date 1690898145563)
@@ -5,7 +5,7 @@
     // Java support
     id("java")
     // gradle-intellij-plugin - read more: https://github.com/JetBrains/gradle-intellij-plugin
-    id("org.jetbrains.intellij") version "1.13.3"
+    id("org.jetbrains.intellij") version "1.15.0"
     // gradle-changelog-plugin - read more: https://github.com/JetBrains/gradle-changelog-plugin
     id("org.jetbrains.changelog") version "2.1.2"
 }
```

Having that applies, run `wrapper` task twice. However, I was not able to reproduce your issue.

**Comment by nthykier** [comment]
> 1. Please run Gradle task "build setup - wrapper" twice on your project to update `gradlew|.bat` files
> 
>     2. You build against `platformVersion = 2022.2` but specify explicitly _lower_ minimum compatibility `pluginSinceBuild = 212` (2021.2), these two should always be aligned
> 
>     3. there's obsolete Gradle version entry here https://github.com/nthykier/IDEA-debpkg/blob/main/gradle.properties#L16

Thanks for the review. The two first were news to me - thanks for making me aware of those.

@hsz: Thanks for the patch version of the changes. Appreciate it.

Indeed, with these changes the dependabot PR indeed goes through (or it would, if the GH actions were not stuck in some Post-action, but that is another issue that I will fight separately). Thanks for the help. :)
