### ISSUE TITLE
How can I generate checksum files when building a plugin?

### ISSUE THREAD

**Issue by maiqingqiang** [JetBrains/gradle-intellij-plugin#1444]
How can I generate checksum files when building a plugin?🧐

**Comment by maiqingqiang** [comment]
> Please clarify your question.

Hello, I would like to generate a SHA-256 file hash. Additionally, I intend to have the SHA-256 file hash generated concurrently during the plugin build process.

Currently, I am utilizing the following command to generate the SHA-256 hash: 
```bash
shasum --algorithm Go.ORM.Helper-1.2.2-signed.zip
```
https://github.com/maiqingqiang/go-orm-helper/releases/download/v1.2.2/Go.ORM.Helper-1.2.2-signed.zip.sha256

**Comment by hsz** [comment]
Basically, you should create a custom `Exec` task and define it as a next step after building the plugin.

See Gradle docs: https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Exec.html
