### ISSUE TITLE
Snapshot build: `coroutines-javaagent.jar is not a directory`

### ISSUE THREAD

**Issue by jansorg** [JetBrains/gradle-intellij-plugin#1456]
### What happened?

I'm seeing this exception with 1.15.1-SNAPSHOT, but not with 1.15.0:

```
A problem was found with the configuration of task ':core-lang-x:test' (type 'Test').
  - Type 'org.gradle.api.tasks.testing.Test' property 'jvmArgumentProviders.$0.coroutinesJavaAgentPath' directory '/home/project/core-lang-x/build/tmp/initializeIntelliJPlugin/coroutines-javaagent.jar' is not a directory.
```

### Steps to reproduce

use the snapshot?

### Gradle IntelliJ Plugin version

1.15.1-SNAPSHOT

### Gradle version

Gradle Wrapper 7.6.2

### Operating System

Linux

**Comment by hsz** [comment]
Could you please try to refresh the `1.15.1-SNAPSHOT` version?

**Comment by jansorg** [comment]
Thanks! That seems to have fixed it...
What does this Java agent do?

**Comment by hsz** [comment]
This is a Kotlin Coroutines agent required for enabling coroutines debugging in the IDE Debugger, like better preview and details.
See: https://youtrack.jetbrains.com/issue/IDEA-322730

IDEA SDK strips down the `MANIFEST.MF` file from the kotlin-coroutines library when bundling third-party libraries, which points to the suitable agent class.
I'm basically creating this file on a dummy jar, so I can properly configure JVM.
