### ISSUE TITLE
Builtin plugins found on OSX and Windows, but missing on Linux

### ISSUE THREAD

**Issue by Turbo87** [JetBrains/gradle-intellij-plugin#146]
I'm developing my IntelliJ plugin on OSX and have CI setup for Windows (AppVeyor) and Linux (TravisCI). I've added the `YAML` plugin to the IntelliJ Gradle plugin config and everything works fine on OSX and Windows/AppVeyor, but on Linux Travis tells me:

```
Cannot find builtin plugin YAML for IDE: /home/travis/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/2016.2/ed0e4e1f81b55ba0671088eb640580d2f562a547/ideaIU-2016.2
```

(see https://travis-ci.org/Turbo87/intellij-emberjs/jobs/173055027 and https://github.com/Turbo87/intellij-emberjs/pull/90)

any clue what's going on here? the `JavaScriptLanguage` and `CSS` plugins seem to work fine.

**Comment by zolotov** [comment]
linux has case-sensitive FS and there is no plugin named YAML

**Comment by Turbo87** [comment]
@zolotov what about https://github.com/JetBrains/intellij-community/blob/master/plugins/yaml/resources/META-INF/plugin.xml#L2 ?

If I used `org.jetbrains.plugins.yaml` instead in the Gradle file it doesn't work on any platform.

**Comment by zolotov** [comment]
it's `yaml`

**Comment by Turbo87** [comment]
I might be doing something wrong, but this is what I get when I change it from `YAML` to `yaml`:

```
$ ./gradlew clean test

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':runtime'.
> Could not resolve org.jetbrains.plugins:yaml:2016.2.
  Required by:
      :intellij-emberjs:2016.2.1-12
   > Could not resolve org.jetbrains.plugins:yaml:2016.2.
      > inconsistent module metadata found. Descriptor: com.jetbrains:idea:2016.2 Errors: bad group: expected='org.jetbrains.plugins' found='com.jetbrains'
        bad module name: expected='yaml' found='idea'
   > Could not resolve org.jetbrains.plugins:yaml:2016.2.
      > inconsistent module metadata found. Descriptor: org.jetbrains.plugins:JavaScriptLanguage:2016.2 Errors: bad module name: expected='yaml' found='JavaScriptLanguage'
   > Could not resolve org.jetbrains.plugins:yaml:2016.2.
      > inconsistent module metadata found. Descriptor: org.jetbrains.plugins:CSS:2016.2 Errors: bad module name: expected='yaml' found='CSS'
   > Could not resolve org.jetbrains.plugins:yaml:2016.2.
      > inconsistent module metadata found. Descriptor: org.jetbrains.plugins:YAML:2016.2 Errors: bad module name: expected='yaml' found='YAML'
   > Could not resolve org.jetbrains.plugins:yaml:2016.2.
      > inconsistent module metadata found. Descriptor: org.jetbrains.plugins:com.dmarcotte.handlebars:162.80 Errors: bad module name: expected='yaml' found='com.dmarcotte.handlebars'
        bad version: expected='2016.2' found='162.80'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.688 secs
```

**Comment by zolotov** [comment]
> org.jetbrains.plugins:yaml

it's just `yaml`. Just like you use it on Mac but lowercase. The only reason it works now on Windows and Mac is that both use case-insensitive file system.

**Comment by Turbo87** [comment]
I've run `rm -rf /Users/tbn/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/2016.2/` to remove the cached IntelliJ files, but I'm still hitting the error above when I'm trying to use `yaml` on OSX. Funny enough `yaml` works fine on TravisCI and AppVeyor now. Are there any other caches that could cause this? Removing the sandbox didn't help either.

**Comment by zolotov** [comment]
Yes, `~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/plugins.jetbrains.com/`

**Comment by Turbo87** [comment]
that seem to have worked. thanks a lot! 👍
