### ISSUE TITLE
Problem with class field initialization, Swing UI Designer

### ISSUE THREAD

**Issue by Ariel5yang** [JetBrains/gradle-intellij-plugin#1468]
### What happened?

there are many page made using swing ui designer in my plugin, In 2023.1 with plugin version 1.10.0 gralde 7.2 everything worked well,then i upgade the plugin version to 1.15.0, and upgrade the gradle to 8.2.1，then the form defined fields is null

java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "javax.swing.JLabel.setIcon(javax.swing.Icon)" because "this.authStatusLabel" is null
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:448)

### Steps to reproduce

gradle runIde

### Gradle IntelliJ Plugin version

1.15.0

### Gradle version

8.2.1

### Operating System

Windows

**Comment by YannCebron** [comment]
Please provide link to your project. And note that instrumentation for GUI forms written in Kotlin is not supported.
