### ISSUE TITLE
Tests fail when 'org.jetbrains.idea.maven' dependency is present

### ISSUE THREAD

**Issue by yorlov** [JetBrains/gradle-intellij-plugin#1470]
### What happened?

I have a [small test project](https://github.com/yorlov/ij-sample-addon), the tests of which are failing. 

But if I remove the `org.jetbrains.idea.maven` dependency from `plugin.xml`, everything starts working. 

In the real project, I need this dependency for the implementation of functionality

### Steps to reproduce

Run `gradle test`

### Gradle IntelliJ Plugin version

1.15.0

### Gradle version

8.3

### Operating System

macOS

**Comment by hsz** [comment]
Thanks for reporting, Yuri!
I was able to reproduce the issue — looks like Maven affects how PSI is resolved.
However, this issue is not directly related to the Gradle IntelliJ Plugin.

Did you try to debug that with PSI Viewer?

Please file an issue in [YouTrack](https://youtrack.jetbrains.com) so relevant team could pick up this case, thanks!

**Comment by yorlov** [comment]
Hello @hsz
        
I hope this message finds you well. I am writing to kindly request your assistance [regarding a ticket escalation in the JetBrains tracker](https://youtrack.jetbrains.com/issue/IDEA-334393/Tests-fail-when-org.jetbrains.idea.maven-dependency-is-present).
        
It has been a couple of weeks since I submitted a ticket, but unfortunately, there hasn't been any response or action taken on it. I understand that everyone's busy but your assistance in accelerating this process or providing me any updates about the situation would be greatly appreciated.
        
Thank you in advance for your time and support on this matter.

**Comment by hsz** [comment]
@yorlov The team already picked up this issue. The problem is reproduced, and further investigation is ongoing. Sorry for the delays. I'll keep an eye on it!
