### ISSUE TITLE
`jvmArgumentProviders.$0.coroutinesJavaAgentPath` specifies file `.../build/tmp/initializeIntelliJPlugin/coroutines-javaagent.jar` which doesn't exist

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/gradle-intellij-plugin#1476]
### What happened?

For Gradle 8.4 and gradle-intellij-plugin 1.16.0, `test` task fails on subprojects where gradle-intellij-plugin is enabled.

Is there a mechanism to disable the configuration related to debugging coroutines for the projects that don't need it? 🤔 
Or maybe Gradle 8.4 is simply not yet supported?

### Relevant log output or stack trace

```shell
> Task :backend:impl:test FAILED

> Task :frontend:ui:impl:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':backend:impl:test' (type 'Test').
  - Type 'org.gradle.api.tasks.testing.Test' property 'jvmArgumentProviders.$0.coroutinesJavaAgentPath' specifies file '/Users/pawel_lipski/git-machete-intellij-plugin/backend/impl/build/tmp/initializeIntelliJPlugin/coroutines-javaagent.jar' which doesn't exist.

    Reason: An input file was expected to be present but it doesn't exist.

    Possible solutions:
      1. Make sure the file exists before the task is called.
      2. Make sure that the task which produces the file is declared as an input.

    For more information, please refer to https://docs.gradle.org/8.4/userguide/validation_problems.html#input_file_does_not_exist in the Gradle documentation.
```

### Steps to reproduce

Branch https://github.com/VirtusLab/git-machete-intellij-plugin/tree/fix-1744-gradle-8.4, then `./gradlew :backend:impl:test` or `./gradlew frontend:ui:impl:test`.

### Gradle IntelliJ Plugin version

1.16.0

### Gradle version

8.4

### Operating System

macOS

### Link to build, i.e. failing GitHub Action job

https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/9578/workflows/c9ec394b-b1c8-4dee-b4d0-9fe1504a3f21/jobs/10012

**Comment by PawelLipski** [comment]
Okay, the problem was that I disabled `initializeIntelliJPlugin`, which fills up the missing file :trollface:

**Comment by JojOatXGME** [comment]
When running `clean test` during the same Gradle execution, I can observe the same error even without disabling `:initializeIntelliJPlugin`. Looks like `:clean` may be executed after `:initializeIntelliJPlugin`. I wrote a more elaborate comment at https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1491#issuecomment-2028521484.
