### ISSUE TITLE
Error listing Products Releases

### ISSUE THREAD

**Issue by johmara** [JetBrains/gradle-intellij-plugin#1477]
### What happened?

When trying to update to version `1.16.0` the `PrintProductReleases` gradle task was including EA versions.

In this case intellij 2023.3 is released but Rider 2023.3 is not. 

### Relevant log output or stack trace

```shell
> Task :printProductsReleases
IC-2023.3
IC-2023.2.2
IC-2023.1.5
IC-2022.3.3
RD-2023.3
RD-2023.2.2
RD-2023.1.4
RD-2022.3.3
```

### Steps to reproduce

Update build numbers:
pluginSinceBuild = 223
pluginUntilBuild = 233.*

### Gradle IntelliJ Plugin version

1.16.0

### Gradle version

8.4

### Operating System

Windows

### Link to build, i.e. failing GitHub Action job

https://github.com/isselab/HAnS/actions/runs/6470372581/job/17566586666

**Comment by hsz** [comment]
Note for self: `RD-2023.3` is available in the snapshots channel.
However, Rider's EAP releases are called `2023.3-SNAPSHOT`, not `2023.3-EAP-SNAPSHOT`. An adjustment for Rider is required.
