### ISSUE TITLE
Lack of 'one model' solution

### ISSUE THREAD

**Issue by fitermay** [JetBrains/gradle-intellij-plugin#149]
I don't know where best to report this.  Some of these are gradle plugin problems, some of them are gradle-plugin problems. 

 There should be a way to generate the entire project from the gradle model. Ideally, the user just imports the project from gradle and the entire IDEA project model is fully generated.  This is currently not the case.

1) There is no way to add facets from the gradle build -- my plugin has python modules for example and there is no way for me to specify in my gradle model to add a facet to the idea project
2) After auto import IDEA 'make' and gradle build should produce the same result. This is currently not the case
3) The gradle intellij plugin should be able to produce a lightweight dev build.  This build should not produce the jar artifact.  This seems to be possible in older versions of the plugin, but not the snapshot version.
4) Hotswap doesn't work with gradle builds. 
5) If the build does generate a JAR artifact, this artifact should be added to IDEA artifacts

**Comment by zolotov** [comment]
> 1. There is no way to add facets from the gradle build -- my plugin has python modules for example and there is no way for me to specify in my gradle model to add a facet to the idea project

This plugin knows nothing about facets or intellij project model in general and shouldn't know anything about it. Report to Gradle (https://docs.gradle.org/current/userguide/idea_plugin.html) or to IntelliJ (https://youtrack.jetbrains.com)

> 2. After auto import IDEA 'make' and gradle build should produce the same result. This is currently not the case

This plugin has nothing to do with IDEA and can be used in any other IDE or editor. It doesn't compile anything. File an issue at IntelliJ tracker. It's better to provide more details there, since it's not clear what `it's not the case` means.

> 3. The gradle intellij plugin should be able to produce a lightweight dev build. 

What does it mean?

> This build should not produce the jar artifact. 

Why is that?

> 4. Hotswap doesn't work with gradle builds.

The plugin doesn't compile anything and doesn't do hotswap. Works fine for me in IDEA though. If it doesn't work for you – file an issue to the instrument that you use for hotswap.

> 5. If the build does generate a JAR artifact, this artifact should be added to IDEA artifacts

No. See the first bullet

**Comment by fitermay** [comment]
Yes, some of these are gradle plugin issues. I am simply giving feedback as a user on the overall experience. Since it says you work for JetBrains I was assuming you can direct the problem to the appropriate developer.

About the dev build. The plugin should be able to generate a dev build and run configuration that is able to run directly against the compile output. When developing and debugging the extra steps to produce the complete artifact add extra time to the build but do not seem to be necessary.

**Comment by fitermay** [comment]
I am using IDEA to build. Hotswap doesn't work for me with the gradle build. At least it dorsn't prompt me to reload classes. Do you perhaps hotswap manually?

**Comment by zolotov** [comment]
>  Since it says you work for JetBrains I was assuming you can direct the problem to the appropriate developer.

As a developer at JetBrains I've pointed you to places where you can give the feedback and to get competent answers and solutions of the problems. "it doesn't work" and " it's not the case" are not good messages to pass them to somebody. Apparently these messages will require additional information and I'm not going to be a mediator, please speak directly to responsible people via Gradle and IntelliJ issues trackers.

> The plugin should be able to generate a dev build and run configuration that is able to run directly against the compile output. 

The only configuration you really need is `gradle runIdea`. Actually, you can avoid creating run configuration at all, just use `run gradle task` action.

It runs directly on compiled output, why do you think it's not?

> When developing and debugging the extra steps to produce the complete artifact add extra time to the build but do not seem to be necessary.

Running/debugging doesn't require building the complete artifact, in other words `runIdea` task doesn't depend on `buildPlugin` task.

> I am using IDEA to build. Hotswap doesn't work for me with the gradle build. At least it doesn't prompt me to reload classes. Do you perhaps hotswap manually?

I'm using IDEA too. I make hotswap by simple recompiling a particular file. If it doesn't work for you – file an issue to intellij issue tracker.

**Comment by fitermay** [comment]
When running 'runIdea' against the latest snapshot of the grade-intellij plugin, the following tasks are executed:
[ task ':compileKotlin', task ':compileJava', task ':copyMainKotlinClasses', task ':patchPluginXml', task ':processResources', task ':classes', task ':jar', task ':prepareSandbox', task ':runIdea']

The 'jar' task here seems to be unnecessary. 
Also, the compile output is not added to the classpath.
Perhaps you're using a different version?

**Comment by zolotov** [comment]
> The 'jar' task here seems to be unnecessary.

It is necessary

> Also, the compile output is not added to the classpath.

Because it shouldn't be there

**Comment by zolotov** [comment]
Closing due to lack of issues related to gradle-intellij-plugin itself
