### ISSUE TITLE
IDE sources are not attached if you use IU for compilation starting with 2023.2

### ISSUE THREAD

**Issue by Undin** [JetBrains/gradle-intellij-plugin#1490]
### What happened?

Starting with 2023.2, if you use IU for compilation, development IDE doesn't show platform sources, only for LSP related code. As I can see, the source jar is just not attached for IU 2023.2. Probably it's because of attached lsp api sources.

| IU 2023.1 | IC 2023.2 | IU 2023.2 |
| - | - | - |
| <img width="1472" alt="IU-2023 1" src="https://github.com/JetBrains/gradle-intellij-plugin/assets/2539310/a8eec46c-6e1a-47ca-8ca6-8cc60130cc78"> | <img width="1472" alt="IC-2023 2" src="https://github.com/JetBrains/gradle-intellij-plugin/assets/2539310/337c6ee3-e44a-4660-a603-9d0f74c0e7e2"> | <img width="1472" alt="IU-2023 2" src="https://github.com/JetBrains/gradle-intellij-plugin/assets/2539310/31649251-03ed-404f-ba09-487ce9032ed7"> |

It makes plugin development for IU much harder, especially taking into account that more and more code in the platform is written in Kotlin and IntelliJ IDEA doesn't show decompiled Kollin code for class files, so you neither can see implementation nor put breakpoint for debugging in Kotlin files

### Steps to reproduce

Open [this](https://github.com/Undin/ide-sources/tree/08442060ad82b81957ae00a8d53986720f08d051) repo in IDE and try navigating to any platform class, for example, `DynamicBundle`

### Gradle IntelliJ Plugin version

1.16.0

### Gradle version

8.4

### Operating System

macOS

**Comment by YannCebron** [comment]
Have you configured IDE as described here? https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#ide-configuration

**Comment by Undin** [comment]
@YannCebron yes. All things are checked in IU 2023.2.3 with Java 17

**Comment by Undin** [comment]
BTW Gradle settings in 2023.3 don't contain `Download sources for dependencies` option

<img width="1094" alt="Screenshot 2023-11-13 at 11 34 25" src="https://github.com/JetBrains/gradle-intellij-plugin/assets/2539310/4c12a941-6e38-40ee-939a-7302902ddbfd">

**Comment by hsz** [comment]
With 2023.3, it was moved to `Settings | Advanced Settings`

See: https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#attaching-sources

**Comment by Undin** [comment]
@hsz do I understand correctly that you checked exactly this setup and it is not reproducible for you?
Because it works for neither with 2023.2 nor with 2023.3 for me with all [necessary options](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#attaching-sources) enabled

**Comment by hsz** [comment]
FTR: https://youtrack.jetbrains.com/issue/IDEA-332969/When-dependency-has-several-matching-source-jars-only-one-is-attached#focus=Comments-27-9312030.0-0
