### ISSUE TITLE
DependenciesDownloader eagerly resolves dependencies

### ISSUE THREAD

**Issue by tylerbertrand** [JetBrains/gradle-intellij-plugin#1494]
### What happened?

DependenciesDownloader is eagerly resolving dependencies by calling `.files` on the detached configuration.

https://github.com/JetBrains/gradle-intellij-plugin/blob/a10fd139467dd34c8e292296b563edfed14fea9d/src/main/kotlin/org/jetbrains/intellij/utils/DependenciesDownloader.kt#L73

[Dependency resolution during configuration should be avoided](https://docs.gradle.org/current/userguide/performance.html#avoid_dependency_resolution_during_configuration), as dependency resolution is expensive, and the configuration phase runs on every build.

### Steps to reproduce

Execute `./gradlew help` in a build using gradle-intellij-plugin, check the build scan ([link to build scan showing the issue surfacing itself in apollo-kotlin](https://ge.solutions-team.gradle.com/s/qqlhmmctb5bhy/performance/dependency-resolution?toggled=dependency-resolution-configuration-user-initiated#dependency-resolution-configuration-user-initiated)), and see that dependencies have been eagerly resolved by gradle-intellij-plugin at configuration time.

### Gradle IntelliJ Plugin version

1.16.0

### Gradle version

8.5-rc1

### Operating System

None

### Link to build, i.e. failing GitHub Action job

https://ge.solutions-team.gradle.com/s/qqlhmmctb5bhy/performance/dependency-resolution?toggled=dependency-resolution-configuration-user-initiated#dependency-resolution-configuration-user-initiated

**Comment by hsz** [comment]
With the 2.0 release, the whole dependencies and repositories management has been rewritten. Dependencies won't be resolved that way anymore.

**Comment by DreierF** [comment]
@hsz Do you have any estimation on when 2.0 will the released?

**Comment by hsz** [comment]
EAP should be available this year.

**Comment by YannCebron** [comment]
Obsolete with 2.x https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-dependencies-extension.html
