### ISSUE TITLE
PatchPluginXmlTask wrongly escapes changeNotes tags inside CDATA block

### ISSUE THREAD

**Issue by missingdays** [JetBrains/gradle-intellij-plugin#1498]
### What happened?

PatchPluginXmlTask wrongly escapes changeNotes tags inside CDATA block, see below

### Steps to reproduce

Have the following task
```kotlin
        withType<PatchPluginXmlTask> {
            changeNotes.set(releaseNotes)
        }
```

where `releaseNotes` are
```kotlin
val releaseNotes = """<![CDATA[
<a href="123">123</a>
]]>"""
```

In the resulting `plugin.xml`, change-notes section will contain the html with escaped values
```xml
  <change-notes>&lt;![CDATA[
&lt;a href="123"&gt;123&lt;/a&gt;
]]&gt;</change-notes>
```

However, according to docs, html inside CDATA block is valid in change-notes

https://plugins.jetbrains.com/docs/intellij/plugin-configuration-file.html#idea-plugin__change-notes

### Gradle IntelliJ Plugin version

1.16.0

### Gradle version

8.3

### Operating System

Windows

**Comment by missingdays** [comment]
Can this behavior at least be made optional?

**Comment by hsz** [comment]
Thanks for creating this ticket, Evgeny!

The content passed to `<change-notes>` and `<description>` elements is now wrapped with `<![CDATA[ ... ]]>` by default.

It's possible to turn that off with:

```
tasks {
    patchPluginXml {
        useCDATA = false
    }
}
```
