### ISSUE TITLE
Strange problem occurs when setting ssl parameters for ftp

### ISSUE THREAD

**Issue by zoulejiu** [JetBrains/gradle-intellij-plugin#1503]
### What happened?

1. Each time you click to run the plug-in, the first ftp connection is displayed.
522 SSL connection failed; session reuse required: see require_ssl_reuse option in vsftpd.conf man page
But when I click the runlde plug-in again, it returns to normal
I don't understand what's wrong
Below is my code example:

### Relevant log output or stack trace

```shell
USER *******
331 Please specify the password.
PASS *******
230 Login successful.
TYPE I
200 Switching to Binary mode.
CWD /var/ftp/test
250 Directory successfully changed.
PBSZ 0
200 PBSZ set to 0.
PROT P
200 PROT now Private.
SYST
215 UNIX Type: L8
PASV
227 Entering Passive Mode (xx,x,4x,46,195,90).
LIST
150 Here comes the directory listing.
522 SSL connection failed; session reuse required: see require_ssl_reuse option in vsftpd.conf man page
0
```

### Steps to reproduce

`
import org.apache.commons.net.PrintCommandListener;
import org.apache.commons.net.ftp.FTPClient;
import org.apache.commons.net.ftp.FTPFile;
import org.apache.commons.net.ftp.FTPSClient;
import org.apache.commons.net.util.TrustManagerUtils;
import org.ssh.apache.commons.vfs2.provider.ftp.FtpFileType;

import javax.net.ssl.SSLSession;
import javax.net.ssl.SSLSessionContext;
import javax.net.ssl.SSLSocket;
import java.io.IOException;
import java.io.PrintWriter;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.net.MalformedURLException;
import java.net.Socket;
import java.util.Locale;

public class SSLSessionReuseFTPSClient extends FTPSClient {
    @Override
    protected void _prepareDataSocket_(final Socket socket) throws IOException {
        if (socket instanceof SSLSocket) {
            SSLSession session = ((SSLSocket) this._socket_).getSession();
            SSLSessionContext context = session.getSessionContext();
            try {
                Field sessionHostPortCache = context.getClass().getDeclaredField("sessionHostPortCache");
                sessionHostPortCache.setAccessible(true);
                Object cache = sessionHostPortCache.get(context);
                Method putMethod = cache.getClass().getDeclaredMethod("put", Object.class, Object.class);
                putMethod.setAccessible(true);
                Class<? extends Socket> socketClass = socket.getClass();
                Method getHostMethod;
                try {
                    getHostMethod = socketClass.getMethod("getPeerHost");
                } catch (NoSuchMethodException var11) {
                    getHostMethod = socketClass.getDeclaredMethod("getHost");
                }
                getHostMethod.setAccessible(true);
                Object host = getHostMethod.invoke(socket);
                String key = String.format("%s:%s", host, socket.getPort()).toLowerCase(Locale.ROOT);
                putMethod.invoke(cache, key, session);
            } catch (Exception var12) {
                throw new IOException(var12);
            }
        }
    }

    public static void main(String[] args) {
        SSLSessionReuseFTPSClient ftpClient = new SSLSessionReuseFTPSClient();
        try {
            ftpClient.addProtocolCommandListener(new PrintCommandListener(new PrintWriter(System.out),true));

            // 设置jdk属性
//            System.setProperty("jdk.tls.useExtendedMasterSecret", "false");
            System.setProperty("jdk.tls.useExtendedMasterSecret", String.valueOf(false));
            // If true, the client will send a session ticket extension in the ClientHello for TLS 1.2 and earlier.
            // Set to false as statless session resumption breaks session reuse in FTPS
            System.setProperty("jdk.tls.client.enableSessionTicketExtension", String.valueOf(false));
            ftpClient.setTrustManager(TrustManagerUtils.getValidateServerCertificateTrustManager());
            // 设置编码
            ftpClient.setControlEncoding("UTF-8");
            // 连接ftp服务器 ip和端口
            ftpClient.connect("xxxxxx", 21);
            // 登录ftp服务器 用户名和用户密码
            ftpClient.login("ftptest", "password");
            // 被动模式
            ftpClient.enterLocalPassiveMode();
            // 文件类型FtpFileType.BINARY; FTPClient.STREAM_TRANSFER_MODE
            FtpFileType fileType =    FtpFileType.BINARY;
            ftpClient.setFileType(2);
            // 私密连接
            ftpClient.execPROT("P");
            // PBSZ命令必须在PROT命令之后
            ftpClient.execPBSZ(0);
            // 设置工作目录
            FTPFile[] ftpFiles = ftpClient.listFiles();
            System.out.println(ftpFiles.length);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}`

### Gradle IntelliJ Plugin version

1.16.1

### Gradle version

8.3

### Operating System

None

**Comment by hsz** [comment]
How is this issue related to the Gradle IntelliJ Plugin?
