### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by saikek** [JetBrains/gradle-intellij-plugin#152]
There seems to be the issue that very few logs are displayed when i run 

`gradle runIdea` compared to usual run->plugin way.

Is there a fast way to fix it ?

**Comment by zolotov** [comment]
see `build/idea-sandbox/system/log/` directory. you can also attach logs in run configuration

<img width="1074" alt="screenshot 2016-11-24 11 08 53" src="https://cloud.githubusercontent.com/assets/140920/20590812/68d23c12-b236-11e6-86ac-5a68200fc671.png">
