### ISSUE TITLE
Wrong IDE platform prefix

### ISSUE THREAD

**Issue by Undin** [JetBrains/gradle-intellij-plugin#1525]
### What happened?

Starting with 2023.3.2 IDE launched by `RunIdeBase` task has the wrong platform prefix, it's always `JetBrainsClient`.
It happens because [this](https://github.com/JetBrains/gradle-intellij-plugin/blob/a759cecfe7e68aa0360e25586cb2e2ed2f517b16/src/main/kotlin/org/jetbrains/intellij/tasks/RunIdeBase.kt#L283-L288) code finds `-Didea.platform.prefix=JetBrainsClient` param in `bin/jetbrains_client.sh` file of IDE artifact and it considers `JetBrainsClient` as IDE platform prefix.

As a result, any checks based on platform prefix, for example, all checks in `com.intellij.util.PlatformUtils`, work unexpectedly for such IDE instances.

### Steps to reproduce

Add `val platformPrefix = PlatformUtils.getPlatformPrefix()` anywhere using 2023.3.2 IDE builds and check value

### Gradle IntelliJ Plugin version

1.16.1

### Gradle version

8.5

### Operating System

macOS

**Comment by hsz** [comment]
The issue is caused by improper shell script scanning to discover the platform prefix.
This should not happen, as `2022.3` explicitly provides such value through the `product-info.json` file.
Added proper platform version check.
