### ISSUE TITLE
Native libraries are not copied from resources/lib into <plugin name>/lib in buildPlugin task

### ISSUE THREAD

**Issue by BossyMr** [JetBrains/gradle-intellij-plugin#1544]
### What happened?

When running the buildPlugin task, native libraries located in resouces/lib are not moved into the outer <plugin name>/lib folder. As a result, these native libraries are not found by the PluginClassLoader, which only searches in the <plugin name>/lib. The task correctly copies jar libraries found in resources/lib.

### Steps to reproduce

Create a new plugin, and put a native library (either a .dll or .so) into the resouces/lib directory. Run the buildPlugin task and observe that the libraries are not present in <plugin name>/lib, but are still left in the /lib folder inside the plugin jar. 

### Gradle IntelliJ Plugin version

1.17.1

### Gradle version

8.5

### Operating System

Windows

### Link to build, i.e. failing GitHub Action job

https://github.com/BossyMr/intellij-rapid

**Comment by YannCebron** [comment]
See https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin-faq.html#how-to-add-a-custom-file-inside-plugin-distribution

**Comment by BossyMr** [comment]
Thank you, that solved the issue!
