### ISSUE TITLE
Add vendor info field to the `PatchPluginXmlTask`

### ISSUE THREAD

**Issue by rwqwr** [JetBrains/gradle-intellij-plugin#1559]
### Describe the need of your request

It would be nice to have `vendorName`, `vendorEmail` and `vendorUrl` fields available for configuration in the [`PatchPluginXmlTask`](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/kotlin/org/jetbrains/intellij/tasks/PatchPluginXmlTask.kt) gradle task. Adding these fields would allow more flexibility to configure values directly from the gradle file, similar to what is done for [maven-publish](https://docs.gradle.org/current/userguide/publishing_maven.html). In addition to flexibility, the new fields can be reused in other tasks, for example, when creating the updatePlugins.xml file for publishing. 

### Proposed solution

Add new fields `vendorName`, `vendorEmail`, `vendorUrl` to the [`PatchPluginXmlTask`](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/kotlin/org/jetbrains/intellij/tasks/PatchPluginXmlTask.kt) gradle task, the values of which will be inserted into the final plugin.xml file

**Comment by YannCebron** [comment]
This will be available in 2.x (currently in EAP), see https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-tasks.html#patchPluginXml-vendorName
