### ISSUE TITLE
Doesn't respect 'compileOnly' configuration

### ISSUE THREAD

**Issue by nathanabercrombie** [JetBrains/gradle-intellij-plugin#156]
I am building a plugin for Android Studio.  I need access to the plugin: 'org.jetbrains.android:android:10.2.2.0' which is provided by android studio.  Using the plugins block:

    intellij.plugins = ['org.jetbrains.android:android:10.2.2.0']

Fails with

    Cannot find plugin org.jetbrains.android:android:10.2.2.0 at http://plugins.jetbrains.com

However, if I host the jar in my own maven repo, and add dependency using compileOnly:

    dependencies {
        compileOnly 'org.jetbrains.android:android:10.2.2.0'
    }

then it builds just fine, but the Gradle Intellij Plugin includes this jar in the final zip.  This means that when installed, there will be two copies of this jar, possibly conflicting.  That is bad.

What is the solution for this?  I think the Gradle Intellij Plugin should respect "compileOnly" policy, and not include that in the final zip.  It should include any in the "compile" configuration in the final zip.

**Comment by nathanabercrombie** [comment]
My workaround now is to just disable the `buildPlugin` task, and write my own tasks that create the equivalent zip.  It respects the compileOnly vs compile distinction.

    task preparePlugin {
        description = "Prepares the directory structure of the plugin"
        dependsOn jar

        inputs.files jar.getArchivePath()
        outputs.files PLUGIN_DIRECTORY

        doLast {
            mkdir(PLUGIN_DIRECTORY)

            // Android studio expects all the files to be nested in an inner directory
            def innerPluginDirectory = new File(PLUGIN_DIRECTORY, "plugin")

            // and the classes to then be nested in a classes directory
            def pluginClassesDirectory = new File(innerPluginDirectory, "classes")
            mkdir(pluginClassesDirectory)

            copy {
                from zipTree(jar.getArchivePath())
                into pluginClassesDirectory
            }

            // But then, it wants the META-INF to be on the top level
            def oldMetaDir = new File(PLUGIN_DIRECTORY, "/plugin/classes/META-INF")
            def newMetaDir = new File(PLUGIN_DIRECTORY, "/plugin/META-INF")
            oldMetaDir.renameTo(newMetaDir)

            // And we can include any other jars in the libs directory
            def libDirectory = new File(innerPluginDirectory, "libs")

            // Find some that we want from the compile configuration
            def files = configurations.compile.files { dep ->
                // We want to ignore the idea jar, which is added by gradle intellij plugin automatically
                if ("com.jetbrains:idea" == "${dep.group}:${dep.name}") {
                    return false
                }

                // We want to keep the rest
                return true
            }

            // Copy them in
            copy {
                from files
                into libDirectory
            }
        }
    }

    task assembleZip(type: Zip) {
        description = "Assembles the plugin zip"
        dependsOn preparePlugin

        from fileTree(PLUGIN_DIRECTORY)
        archiveName = FINAL_ZIP_NAME
    }

**Comment by zolotov** [comment]
Depends on what gradle-intellij-plugin version you use, I can suggest simpler workaround

**Comment by zolotov** [comment]
speaking of the initial issue. `android` plugin is the bundle one, right? so you can depend on it just like that:

```
intellij {
  plugins = ['andoid']
}
```

**Comment by nathanabercrombie** [comment]
So, how would I have figured out that `'android'` was the right string to use there?  If I open one of the jars, I see:

    <name>Android Support</name>
    <id>org.jetbrains.android</id>
    <version>10.1.3.0</version>

Which leads me to believe it should be `'org.jetbrains.android:android:10.1.3.0'`

**Comment by nathanabercrombie** [comment]
You resolved the core issue, I changed the title to reflect the other issue.  Any dependencies in 'compileOnly' should not be bundled in the zip

**Comment by zolotov** [comment]
> Is it because its in the directory 'android'?

That's right, for bundled plugins their directory name is used. Indeed, I should mention it in the documentation.

> Does that mean to include the groovy plugin, you use 'Groovy'?

Yes

> Or is it case insensitive?

Depends on the file system, it is case sensitive for example on `ext4`

**Comment by zolotov** [comment]
Cannot recreate this. This might be result of #145, e.g. you had `compile` dependency, built the plugin (so jar was copied to sandbox), then change to `compileOnly` and built one more time. In this scenario the jar won't be deleted automatically because of #145 and I'm about to fix it.
