### ISSUE TITLE
Please add 2016.3.1 to the releases repository

### ISSUE THREAD

**Issue by baron1405** [JetBrains/gradle-intellij-plugin#157]
Can you or someone at JetBrains upload 2016.3.1 ideaIC to https://www.jetbrains.com/intellij-repository/releases. Thanks!

**Comment by zolotov** [comment]
It was not even officially published when you created an issue, it will be uploaded automatically in a day or so

**Comment by baron1405** [comment]
OK, but when I go to the https://www.jetbrains.com/idea/download (i.e. the official JetBrains IDEA download site) I see 2016.3.1.
