### ISSUE TITLE
Possible to have runIdea open the surrounding project?

### ISSUE THREAD

**Issue by breandan** [JetBrains/gradle-intellij-plugin#162]
I would like to use this plugin to generate a fully-configured IDE as the Gradle build artifact for a project. For example, when someone wants to contribute to a project, all they would need to do is run `git clone git@github.com:my-project folder-name; cd folder-name; ./gradlew runIdea -project .` and this would open the IDE with the surrounding project ready to go. Is this currently possible and if not, would you consider adding this as a feature?

**Comment by breandan** [comment]
Looks like IntelliJ IDEA has some [command line options](https://www.jetbrains.com/help/idea/2016.3/opening-files-from-command-line.html). It would be nice to allow users to pass a project path in through the DSL to avoid navigating menu options after `./gradlew runIdea` - IDE just opens the project with the plugin loaded.

**Comment by breandan** [comment]
I have a prototype of the `project <path>` DSL working locally, but the only issue is that IntelliJ IDEA does not detect JAVA_HOME when freshly installed without a prior sandbox. This requires the user to manually exit the initial Gradle import wizard and configure the global JDK. If the user needs to configure the IDE via the GUI, this somewhat defeats the purpose. Wondering if there is a way to supply this setting via a command line flag, or write it to the sandbox?

**Comment by zolotov** [comment]
Won't fix, see explanation there in PR #164. 

The plugin is responsible for configuring IDEA SDK and running the IDEA, any other configuration of IDEA is on client's Gradle build. Fortunately. Gradle is very customizable.
