### ISSUE TITLE
Plugin should use compileOnly instead of compile configuration for IDEA dependency

### ISSUE THREAD

**Issue by madisp** [JetBrains/gradle-intellij-plugin#168]
The current IDEA dependency leaks transitively from the project so it's hard to create a multi-module project where multiple modules depend on IDEA.

Also a lot of tools for shading / obfuscating include everything on the compile config default, pulling in the full IDEA dependency when doing so.

Gradle has a facility for this exact case - the `compileOnly` configuration (emphasis mine):

> Compile-only dependencies address a number of use cases, including:
> * Dependencies required at compile time but never required at runtime, such as source-only annotations or annotation processors;
> * Dependencies required at compile time but required at runtime only when using certain features, a.k.a. optional dependencies;
> * __Dependencies whose API is required at compile time but whose implementation is to be provided by a consuming library, application or runtime environment.__

(from https://blog.gradle.org/introducing-compile-only-dependencies)

**Comment by madisp** [comment]
I can submit a patch for this too

**Comment by zolotov** [comment]
Could you please elaborate what exactly is hard on creating a multi-module project and how setting `compileOnly` dependency solves it.

Anyway, it seems reasonable, the only thing I concern about is that `compileOnly` configuration works since Gradle 2.12 only.

**Comment by zolotov** [comment]
PR is always welcome :)

**Comment by madisp** [comment]
Created a PR which has a fallback for older Gradle versions and tested this out with the BashSupport project (Gradle 2.9) - dependency is added to `compile` configuration as expected. 

Regarding the multi-module projects, we have a weird setup that might be just us - we have a main plugin module that depends on a bunch of compatibility modules where the latter reference a different IDE version each. Right now the main module can only depend on the compatibility ones with `{ transitive = false }` as otherwise the compile classpath would be littered with multiple entries.
