### ISSUE TITLE
patchPluginXml task strips CDATA from plugin.xml

### ISSUE THREAD

**Issue by 0legg** [JetBrains/gradle-intellij-plugin#175]
When I'm trying to use `buildPlugin` task, every `CDATA` inside `plugin.xml` is stripped, and sometimes according tags braces are encoded (not every time).

**Comment by zolotov** [comment]
What's wrong with it?

**Comment by 0legg** [comment]
I'm not sure about rendering inside IDE, but it can really break formatting. So, instead of section
`<change-notes><![CDATA[
        <b>0.0.1</b>
        <ul>
            <li>Initial release</li>
        </ul>
    ]]>
    </change-notes>`
I have this:
`<change-notes>
        <b>0.0.1</b>
        <ul>
            <li>Initial release</li>
        </ul>
    </change-notes>`
or this:
`&lt;change-notes&gt;
        &lt;b&gt;0.0.1&lt;/b&gt;
        &lt;ul&gt;
            &lt;li&gt;Initial release&lt;/li&gt;
        &lt;/ul&gt;
    &lt;/change-notes&gt;`

**Comment by zolotov** [comment]
You may check this in IDE, but it looks like absolutely valid xml to me that will be rendered in the same way as xml with CDATA.

> &lt;change-notes&gt; 

This was outer of CDATA, was it also converted?

**Comment by 0legg** [comment]
Well, `<![CDATA[ <b>0.0.1</b> <ul> <li>Initial release</li> </ul> ]]> ` is a string body; and ` <b>0.0.1</b> <ul> <li>Initial release</li> </ul> ` are nested XML tags, and I don't think they are equivalent, and will be rendered the same way. I can possibly have another HTML structure that probably will break the XML (for example — have `</change-notes>` inside CDATA).

**Comment by zolotov** [comment]
hold on, initially you said that 

`<![CDATA[ <b>0.0.1</b> <ul> <li>Initial release</li> </ul> ]]>`

replaced by

`&lt;b&gt;0.0.1&lt;/b&gt; &lt;ul&gt; &lt;li&gt;Initial release&lt;/li&gt; &lt;/ul&gt; `

This is completely valid replacement.

> I can possibly have another HTML structure that probably will break the XML (for example — have </change-notes> inside CDATA).

It won't break anything becuase `<` and `>` will be escaped.

**Comment by 0legg** [comment]
Yes, replacement with html encoding is valid, but in some cases (if I'll find steps to 100% reproduce — I'll provide it) plugin was just stripping `CDATA` part, leaving all tags inside it.

**Comment by zolotov** [comment]
Ok then, closing for now, please ping me if you'll be able to recreate this
