### ISSUE TITLE
Extension of type 'IntelliJPluginExtension' does not exist

### ISSUE THREAD

**Issue by SeanCai** [JetBrains/gradle-intellij-plugin#176]
version:0.2.2 and 0.2.0-SNAPSHOT (gradle version 3.2.1 and 3.3)
Extension of type 'IntelliJPluginExtension' does not exist. Currently registered extension types: [DefaultExtraPropertiesExtension, DefaultArtifactPublicationSet_Decorated, ReportingExtension_Decorated, KaptExtension_Decorated, DefaultPublishingExtension_Decorated]

0.2.1 is ok

**Comment by zolotov** [comment]
Attach stacktrace please and project to recreate the issue if possible.

**Comment by zolotov** [comment]
closing due to lack of feedback
