### ISSUE TITLE
Ability to pass system properties to runIdea and test tasks

### ISSUE THREAD

**Issue by zolotov** [JetBrains/gradle-intellij-plugin#18]
Workaround:

```
afterEvaluate {
  tasks.getByName('runIdea') {
    systemProperty 'name', 'value'
  }
}
```

**Comment by amolenaar** [comment]
How about jvmArgs?

    runIdea {
        jvmArgs += "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5007"
    }

(unless there's an alternative to running IDEA in debug mode :) )

**Comment by zolotov** [comment]
@amolenaar Eclipse, NetBeans and IDEA support running gradle tasks in debug mode. 

E.g.:
<img width="460" alt="screenshot 2015-10-29 01 12 35" src="https://cloud.githubusercontent.com/assets/140920/10954556/36f0f776-835f-11e5-8b17-4fdd7847292f.png">

Also, since `runIdea` is just JavaExec task, you can specify jvmArgs in following way:
```
afterEvaluate {
    tasks.getByName('runIdea') {
        jvmArgs('-myArgs')
    }
}
```

I don't see any reasons to add some extra syntax sugar for this so far.

**Comment by amolenaar** [comment]
Thanks @zolotov, I did not consider this option.
