### ISSUE TITLE
Include additional resource files to plugin zip

### ISSUE THREAD

**Issue by holgerbrandl** [JetBrains/gradle-intellij-plugin#180]
It there a way to instruct the gradle-intellij-plugin to include additional resource files when preparing a plugin-zip? Everything until the zipping works fine with me.

Layout after running gradle-intellij-plugin
```
root 
  - lib/myplugin.jar
```

Intended layout
```
root 
  - lib/myplugin.jar
  - some_dir/helper_file.txt
  - other_helper.txt
```
Those files should not be embedded into the jar since I need them as actual files in the clients' filesystem after my plugin has been installed.

Among the provided examples on your README.md I could find no guide how to do so.

**Comment by zolotov** [comment]
Hi. The request has nothing to do with `gradle-intellij-plugin` and should be addressed to `Gradle` itself.

`jar` task is responsible for packing your classes and resources into a jar. See [its documentation](https://docs.gradle.org/current/userguide/java_plugin.html#sec:jar) and [reference](https://docs.gradle.org/current/dsl/org.gradle.jvm.tasks.Jar.html).

`prepareSandbox` of `gradle-intellij-plugin` task is just a `Sync` task and can be modified as a simple `Sync` task. See [its docs](https://docs.gradle.org/current/userguide/working_with_files.html#sec:sync_task) and [reference](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Sync.html) as well.

**Comment by holgerbrandl** [comment]
Sorry for the tracker spam. Actually the jar is totally fine, but the final .zip under `build/distributions` should include certain resource files. Could you point me to the  task which is building the plugin.zip?

**Comment by zolotov** [comment]
I've already did: `prepareSandbox` is that you need

**Comment by holgerbrandl** [comment]
I'll have a look. Thanks for your help.
