### ISSUE TITLE
updated dependencies are not used until their predecessors are deleted from /build

### ISSUE THREAD

**Issue by Trolldemorted** [JetBrains/gradle-intellij-plugin#187]
I have set up my plugin with gradle as described [here in 1.3](http://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/prerequisites.html), and have added dependencies like this:

```
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.11'
    compile "org.tub.eveamcp:codegen:1.0.6"
    compile "org.codeartisans.thirdparties.swing:org-openide-util:8.6.2"
    compile "org.netbeans.api:org-netbeans-api-annotations-common:RELEASE802"
}
```

Now if i update the reference of a dependency (e.g. replacing `"org.tub.eveamcp:codegen:1.0.6"` with `"org.tub.eveamcp:codegen:1.0.7"`, gradle downloads the new version, copies it to `/build/idea-sandbox/plugins/Intellij-Eve/lib`, but it does not delete the old one.

I could live with some outdated jars hanging around there, but apparently the older versions are loaded with a higher priority, and thus i have to delete the old jar everytime i update a dependency to see my changes in action.

Is this a bug, or am i just doing it wrong?

**Comment by zolotov** [comment]
Plugin version?

**Comment by Trolldemorted** [comment]
Gradle plugin version: 171.3780.52
Intellij version: IDEA Community 2017.1 Build #IC-171.3780.52, built on March 15, 2017
OS: W10 Pro N

**Comment by zolotov** [comment]
It is Gradle plugin for IDE.

What's the version of the very this gradle plugin, that you're trying to configure and that you use to prepare IDEA sandbox?

**Comment by Trolldemorted** [comment]
I am sorry, but there appears to be some misunterstanding.

I have followed your link from `Getting started` in your readme, which lead me [here](http://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/prerequisites.html), checked that i have the gradle plugin installed just like in the screenshot, and continued with the rest of the instructions.

Is there a second Gradle plugin, and where can i find instructions on how to install and use it?

**Comment by zolotov** [comment]
This is the issue tracker of `gradle-intellij-plugin` for Gradle. Apparently, you use `gradle-intellij-plugin` for preparing plugin's sandbox. So what's the version of `gradle-intellij-plugin` do you use?

**Comment by zolotov** [comment]
If you just copy-pasted `build.gradle`, the you use `0.1.10` version which is very old one.
Please try to  figure out what's going on in `build.gradle` and try the latest version of the plugin. The latest vesion is stated in README.

Closing for now. Ping me if you still expirience problems in incremental `prepareSandbox` running after that.

**Comment by Trolldemorted** [comment]
Now i understand! Upgrading to 0.2.5 solved this issue, thanks a lot!

You should update your documentation, though - why does it point new devs to such old versions of your plugins with known issues like that?

**Comment by zolotov** [comment]
You're welcome. The doc is just a sample of using gradle, it doesn't force you to use any particular version of any dependency. Choosing dependencies, their versions and learning gradle is on developer.
