### ISSUE TITLE
Test Results Print Twice

### ISSUE THREAD

**Issue by perryprog** [JetBrains/gradle-intellij-plugin#194]
After running my run configuration which does just runs my gradle test task, I get any errors twice (this is just an example project):
```
Too few invocations for:

3 * service.print1()   (0 invocations)

Unmatched invocations (ordered by similarity):

None

Too few invocations for:

3 * service.print2()   (0 invocations)

Unmatched invocations (ordered by similarity):

None

Too few invocations for:

2 * service.print3()   (0 invocations)

Unmatched invocations (ordered by similarity):

None


Too few invocations for:

3 * service.print1()   (0 invocations)

Unmatched invocations (ordered by similarity):

None

Too few invocations for:

3 * service.print2()   (0 invocations)

Unmatched invocations (ordered by similarity):

None

Too few invocations for:

2 * service.print3()   (0 invocations)

Unmatched invocations (ordered by similarity):

None

```

That is the only part that gets repeated. Also, if I macular If you need anymore information just ask!

Please keep in mind that I am mostly new to Gradle and Groovy. Thanks!

**Comment by zolotov** [comment]
Hi Perry,

How this is related to `gradle-intellij-plguin`? Do use use it? How to recreate the issue?

**Comment by perryprog** [comment]
@zolotov Yes, sorry for the briefness, I was a bit rushed. Here are some screenshots. (Again this is a sample project)

<img width="2007" alt="screen shot 2017-04-25 at 6 23 45 am" src="https://cloud.githubusercontent.com/assets/12972285/25380887/d169ccca-297f-11e7-8960-297f0527afbe.png">

Steps to recreate:

1. Create a new directory and `cd` into it
2. Run `gradle init --type groovy-library`
3. Open IntelliJ, and open it as a new Gradle project, with settings like so.
<img width="946" alt="screen shot 2017-04-25 at 6 28 50 am" src="https://cloud.githubusercontent.com/assets/12972285/25381094/7c5fbd60-2980-11e7-97bd-ae58b9497c01.png">

4. Create a new run configuration that looks like this.
<img width="1066" alt="screen shot 2017-04-25 at 6 30 45 am" src="https://cloud.githubusercontent.com/assets/12972285/25381174/bfa5ee5a-2980-11e7-85c1-198d736db38a.png">

5. Change the default someLibraryMethod returns true test to
```
then:
        result == false
```
6. Run the Test configuration
7. You should get you're results twice. I am able to recreate this consistently.

**Comment by zolotov** [comment]
I don't see any usage of `gradle-intellij-plugin`. File an issue at IntelliJ's issue tracker: https://youtrack.jetbrains.com

**Comment by perryprog** [comment]
@zolotov Uhh... what now?

I figured `gradle-intellij-plugin` was the one causing the problem since that's how I imported the project and how I also created the Test run configuration. Also, if I disable `gradle-intellij-plugin` then I cannot run the tests, as `gradle-intellij-plugin` is required to run a Gradle task.

What am I missing here?

**Comment by zolotov** [comment]
You're missing the readme of the project. `gradle-intellij-plugin` is a plugin for gradle to develop IntelliJ Platform plugins. You **don't use it**.

**Comment by perryprog** [comment]
@zolotov Oh! I am so, so, sorry! I just saw the title of the repo and assume this was correct.....

I hope I didn't waste you're time!

**Comment by zolotov** [comment]
No problem. Please file an issue at Intellij Issue Tracker
