### ISSUE TITLE
alternativeIdePath to IDEA ultimate still runs a Community Edition version

### ISSUE THREAD

**Issue by SingingBush** [JetBrains/gradle-intellij-plugin#195]
I'm working on a plugin that requires `com.intellij.css` which isn't available in the plugin repo and cannot be used with Community Edition. 

Therefore I tried setting `alternativeIdePath` to my local Intellij Ultimate installation `alternativeIdePath '/Applications/IntelliJ\\ IDEA.app/Contents/MacOS/idea'` and have also tried `alternativeIdePath ''` (as README states empty value uses the IDE that was used for compiling) but when Intellij boots up it's the community version and the plugin will not work as `com.intellij.css` isn't available.

**Comment by zolotov** [comment]
Why don't you just use Ultimate for compiling? See `intellij.version` and `intllij.type` in README.

>  I tried setting alternativeIdePath to my local Intellij Ultimate installation alternativeIdePath '/Applications/IntelliJ\\ IDEA.app/Contents/MacOS/idea'

I believe it should be `'/Applications/IntelliJ\\ IDEA.app/` and I'm sure there was a log message about invalid path.

**Comment by SingingBush** [comment]
thanks zolotov, I think `type 'IU'` will do what I need. 

btw I've since noticed that `localPath` will complain about an invalid path but it seems `alternativeIdePath` doesn't. Then again it's possible that localPath shouldn't be complaing as I've tried about every variation of my path to the installed version on OSX.
