### ISSUE TITLE
specified local path is invalid

### ISSUE THREAD

**Issue by SingingBush** [JetBrains/gradle-intellij-plugin#196]
none of the following work although it's the correct install location on OSX:

```
localPath '/Applications/IntelliJ\\ IDEA.app/Contents/MacOS/idea'
localPath '/Applications/IntelliJ\\ IDEA.app/'
localPath '/Applications/IntelliJ\\ IDEA.app'
```

but the gradle plugin didn't complain when using same path for `alternativeIdePath`

**Comment by zolotov** [comment]
please stop create issues. if you have questions, ask in existing issue or welcome to gitter.

1. why do you need \\<space> in path?
2. why don't you use ultimate for compile?
3. show build output

**Comment by SingingBush** [comment]
this isn't a question it's letting you know of a problem with the plugin. 

my original issue #195 was resolved by using `type 'IU'` and I am able to do what I need. I created this issue as a bug report because the localPath parameter will not accept a perfectly valid path.

I have `\` because there's a space in the path and besides using `localPath '/Applications/IntelliJ IDEA.app'` does not work either. 

using `localPath '/Applications/IntelliJ IDEA.app/'` I get

```
* What went wrong:
A problem occurred configuring root project 'Intellij Diet Plugin'.
> Failed to notify project evaluation listener.
   > /Applications/IntelliJ IDEA.app/build.txt (No such file or directory)
```

and using `localPath '/Applications/IntelliJ\\ IDEA.app/'` I get

```
* What went wrong:
A problem occurred configuring root project 'Intellij Diet Plugin'.
> Specified localPath '/Applications/IntelliJ\ IDEA.app/' is not path to IntelliJ IDE
```

feel free to close if you want. this bug isn't a blocker for me

**Comment by zolotov** [comment]
>  accept a perfectly valid path.

Apparently it's not.

> I have \ because there's a space in the path and besides using 

It's just a Groovy/Java string, you do not need to escape anything besides backslash and quotes. The filename doesn't contains backslashes.

>    > /Applications/IntelliJ IDEA.app/build.txt (No such file or directory)

The message is quite descriptive. It expects the directory with a `build.txt` file in it. I believe it will work with ` /Applications/IntelliJ IDEA.app/Contents`. This can be inferred by the gradle plugin, though.

> Specified localPath '/Applications/IntelliJ\ IDEA.app/' is not path to IntelliJ IDE

IntelliJ\ IDEA.app directory doesn't exist, so the message is quite right as well.
