### ISSUE TITLE
Set intelliJ's Java Heap Memory?

### ISSUE THREAD

**Issue by soywiz** [JetBrains/gradle-intellij-plugin#197]
I'm creating a plugin that requires extra memory for running/performing some tasks. So I need to increase memory usage.

The instance used for debugging already has increased memory changing the `idea64.exe.vmoptions`. But don't know how to increase the instance that is being tested.
I have tried increasing gradle's memory, but it doesn't seems to work either:

```
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
```

Any tips on this? Thanks in advance.

**Comment by zolotov** [comment]
See [Test task documentation](https://docs.gradle.org/3.4.1/dsl/org.gradle.api.tasks.testing.Test.html).

For debugging see [Java Exec task documentation](https://docs.gradle.org/3.4.1/dsl/org.gradle.api.tasks.JavaExec.html) sicne `runIde` task *is* `JavaExec`

**Comment by soywiz** [comment]
Great. Worked liek a charm!

```
runIde {
	maxHeapSize = "2g"
}
```
