### ISSUE TITLE
Publishing plugin to an Enterprise Repository

### ISSUE THREAD

**Issue by capitancuernos** [JetBrains/gradle-intellij-plugin#198]
Hi,

Is there any way to achieve this?

As far as I know, _publishPlugin_ task is designed to publish only to JetBrains's public repository. What I need is a way to tell gradle to build my plugin and then publish it to my private enterprise repository.

Thanks in advance.

**Comment by yole** [comment]
A "private enterprise repository" is just an .xml file on a Web server. There is no general way to publish a plugin to one; the specific way to publish it depends on your setup. It's entirely possible to automate publishing such an .xml file via a Gradle build, but you'll need to implement this yourself.

**Comment by zolotov** [comment]
Closing the issue. The previous answer is absolutely correct.
