### ISSUE TITLE
How not to pack annotations.jar to plugin artifact?

### ISSUE THREAD

**Issue by shalupov** [JetBrains/gradle-intellij-plugin#20]
https://github.com/shalupov/idea-cloudformation uses some kind of 'provided' dependencies as discussed on the Internets. It looks like this:

```
    configurations {
        provided
        compile.extendsFrom provided
    }

    dependencies {
        provided 'org.jetbrains:annotations:13.0'
    }
```

What's the best way not to pack it into plugin's zip?

**Comment by zolotov** [comment]
There is not way, all compile dependencies (and compile extends provided) will be packed.

As for annotations, IDEA SDK already contains it, do you really need to attach them as separate dependency?

**Comment by shalupov** [comment]
I'm not. Ok, I'll just exclude it.
