### ISSUE TITLE
Gradle import does not honor system properties from gradle.properties.

### ISSUE THREAD

**Issue by sureshg** [JetBrains/gradle-intellij-plugin#200]
Gradle refresh action is failing if you have any system properties referenced in the plugins section. I am using the following Gradle script, which references a system property (`systemProp`) defined in `gradle.properties`

```
import org.gradle.script.lang.kotlin.*
buildscript {
    repositories {
        gradleScriptKotlin()
    }
}
plugins {
    val kotlinVersion = System.getProperty("kotlin.version")
    id("org.jetbrains.kotlin.jvm") version kotlinVersion
}
repositories {
    gradleScriptKotlin()
}

dependencies {
    compile(gradleScriptKotlinApi())
    compile("org.jetbrains.kotlin:kotlin-stdlib-jre8")
}
```

gradle.properties

```
org.gradle.script.lang.kotlin.accessors.auto=true

# App properties
appAuthor=OneOps
appVersion=0.1.0

# Misc system properties
systemProp.kotlin.version=1.1.2-2
```

I could able to build the same form CLI, but if you try to run any action or refresh the project from IntelliJ, it doesn't honor the system properties and fails with the following error (basically can't load the plugin as that system property is empty)

<img width="789" alt="screen shot 2017-05-17 at 3 36 45 pm" src="https://cloud.githubusercontent.com/assets/356994/26179348/17e7d508-3b18-11e7-8ce6-73dc3a9fd91f.png">

**Comment by zolotov** [comment]
This project is a plugin *for Gradle* that for building plugins for IntelliJ platform. It has nothing to do with supporting Gradle *in IDEA*. Please forward the request to https://youtrack.jetbrains.com
