### ISSUE TITLE
Debug running Plugin

### ISSUE THREAD

**Issue by kingsleyh** [JetBrains/gradle-intellij-plugin#206]
Hi

How can I breakpoint and debug when ./gradlew runIde - At the moment it just runs the IDE with the plugin installed but I want to debug it and stop on breakpoints etc.

I thought maybe it could be done with the remote debugger but I can't find anywhere to put the jvm args for the remote debugger in the gradle config

**Comment by Minecrell** [comment]
If you create a Gradle run configuration within your IntelliJ IDEA project that just runs the `runIde` Gradle task you can run it in debug mode as usual.

**Comment by zolotov** [comment]
`runIde` is just a [JavaExec](https://docs.gradle.org/3.4/dsl/org.gradle.api.tasks.JavaExec.html) task, see documentation to know how to pass arguments there.

It's easier to use IDE for debug, though: https://github.com/JetBrains/gradle-intellij-plugin/issues/9#issuecomment-139237985

**Comment by kingsleyh** [comment]
ah ok thanks - I  right clicked the runIde task in the gradle side panel in intellij and used the debug option there - I didn't know that existed! thanks again :)
