### ISSUE TITLE
NPE calling intellij.version or intellij.type before it is set

### ISSUE THREAD

**Issue by baron1405** [JetBrains/gradle-intellij-plugin#208]
The getVersion() and getType() methods in IntelliJPluginExtension throw an NPE because they attempt to call the startsWith on version before checking if it is null.

**Comment by zolotov** [comment]
Yes, but the version is set in the same time as the extension is added to the gradle model. Does this somehow affect you?

**Comment by baron1405** [comment]
I suspect this is due to my extending your extension. After I apply the intellij plugin, I am extending your extension with my own:
```
project.intellij.extensions.create('sdk', IdeaSdkExtension, project)
```
where IdeaSdkExtension is my own class. This is legal in Gradle but obviously a corner case. I am unclear why your initialization is lost when I do this extending.

**Comment by zolotov** [comment]
I can move the initialization directly to the fields declarations, hope this will help

**Comment by baron1405** [comment]
Works great now, thanks!
