### ISSUE TITLE
How do I add my resource file in the lib directory

### ISSUE THREAD

**Issue by jiqimaogou** [JetBrains/gradle-intellij-plugin#209]

**Comment by zolotov** [comment]
`prepareSandbox` of `gradle-intellij-plugin` task is just a `Sync` task and can be modified as a simple `Sync` task. See [its docs](https://docs.gradle.org/current/userguide/working_with_files.html#sec:sync_task) and [reference](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Sync.html) as well.

Something like following should work:

```
prepareSandbox {
  from('yourFile') { into "${intellij.pluginName}/lib/" }
}
```
