### ISSUE TITLE
Proxy intellij repo

### ISSUE THREAD

**Issue by kovacserik** [JetBrains/gradle-intellij-plugin#211]
Hi,
Is it possible to proxy https://www.jetbrains.com/intellij-repository/releases repository?

**Comment by zolotov** [comment]
I don't see any reason why you cannot do this. What's the question exactly?

**Comment by zolotov** [comment]
Closing due to lack of feedback

**Comment by todylu** [comment]
Is `https://www.jetbrains.com/intellij-repository/...`  closed? 
I tried to install `gradle.plugin.org.jetbrains.intellij.plugins:gradle-intellij-plugin:0.2.15`, but I can't download `idealC-LATEST-EAP-SNAPSHOT.zip` from this website.
Could you move the dependencies from `https://www.jetbrains.com/intellij-repository/...` to `http://dl.bintray.com/jetbrains/...` ?

**Comment by zolotov** [comment]
> Is https://www.jetbrains.com/intellij-repository/... closed?

No.

>  but I can't download idealC-LATEST-EAP-SNAPSHOT.zip from this website.

You don't need to download anything manually

> Could you move the dependencies from https://www.jetbrains.com/intellij-repository/... to http://dl.bintray.com/jetbrains/... ?

No.

**Comment by kovacserik** [comment]
Thanks it's working.
