### ISSUE TITLE
"JetBrains IDE Support" messages appearing in every Chrome window/tab

### ISSUE THREAD

**Issue by Sfshaza** [JetBrains/gradle-intellij-plugin#212]
When you use the JetBrains extension in Chrome to run DDC-produced JavaScript in debug mode, you see a big yellow disconcerting message at the top of EVERY tab, window, even hangouts.

We need to eradicate this. 

A sample screenshot is included.

![screen shot 2017-07-14 at 2 45 32 pm](https://user-images.githubusercontent.com/6293442/28232093-c3d96bfc-68a3-11e7-8e7d-3f5416e49e45.png)

**Comment by Sfshaza** [comment]
Cc'ing @kwalrath and @filiph.

**Comment by zolotov** [comment]
Gradle-IntelliJ-plugin has nothing to do with chrome or JavaScript. Please use IntelliJ issue tracker instead: https://youtrack.jetbrains.com
