### ISSUE TITLE
Build Plugin for multiple Intellij types / versions

### ISSUE THREAD

**Issue by dotCipher** [JetBrains/gradle-intellij-plugin#213]
It seems that the plugin only allows you to build plugins targeting a single intellij type (`IC`/`IU`) and a single version.  For example, using the block:
```
intellij {
    version 'IC-2017.1.1'
}
```
The plugin gives me the error:  **Plugin 'my-plugin' is incompatible with this installation** when trying to install in Intellij Ultimate.

Is there a good way to build a plugin for multiple types / versions?  I looked at [a](https://github.com/JetBrains/ideavim/blob/master/build.gradle#L34) [few](https://github.com/minecraft-dev/MinecraftDev/blob/dev/gradle.properties#L11) [of](https://github.com/Turbo87/intellij-emberjs/blob/master/build.gradle#L46) the examples listed in the README.md, but I was unable to determine how to build for multiple versions.

**Comment by zolotov** [comment]
> It seems that the plugin only allows you to build plugins targeting a single intellij type 

No, compatibility depends only on depends-tags in your plugin.xml or since/until version numbers
