### ISSUE TITLE
Cannot download dependencies from https://www.jetbrains.com/intellij-repository/... 

### ISSUE THREAD

**Issue by todylu** [JetBrains/gradle-intellij-plugin#216]
#211 
Is `https://www.jetbrains.com/intellij-repository/...` closed?
I tried to install `gradle.plugin.org.jetbrains.intellij.plugins:gradle-intellij-plugin:0.2.15`, but I can't download `idealC-LATEST-EAP-SNAPSHOT.zip` from this website.
Could you move the dependencies from `https://www.jetbrains.com/intellij-repository/...` to `http://dl.bintray.com/jetbrains/...` ?

**Comment by todylu** [comment]
OK, I configure `intellij.localPath` to workaround it.

**Comment by zolotov** [comment]
https://github.com/JetBrains/gradle-intellij-plugin/issues/211#issuecomment-318588168
