### ISSUE TITLE
Fail to perform 'buildPlugin' task for 'Appcode' plugin

### ISSUE THREAD

**Issue by gosp** [JetBrains/gradle-intellij-plugin#217]
Hi, I try to develop plugin for 'appcode' using gradle,
my `build.gradle` is:
```
intellij {
    localPath '/Applications/AppCode.app'
    alternativeIdePath '/Applications/AppCode.app'
    type 'OC'
    downloadSources false
}
```
It can generate a gradle dependency: 'com.jetbrains:ideaLocal:OC-171.4694.27' which contains all of jar in `/Applications/AppCode.app/Contents`.
the whole progress seems perfect. But when I run `buildPlugin`, I get the following error:
```
:instrumentCode
Gradle now uses separate output directories for each JVM language, but this build assumes
a single directory for all classes from a source set. This behaviour has been deprecated and is 
scheduled to be removed in Gradle 5.0
:instrumentCode FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':instrumentCode'.
> taskdef class com.intellij.ant.InstrumentIdeaExtensions cannot be found
   using the classloader AntClassLoader[/Applications/AppCode.app/Contents/lib/jdom.jar:
/Applications/AppCode.app/Contents/lib/jgoodies-forms.jar]
```

**Comment by gosp** [comment]
I found two jars are missing from the error log:
```
14:21:19.562 [DEBUG] [org.gradle.api.internal.project.ant.AntLoggingAdapter] dropping /Applications/AppCode.app/Contents/lib/javac2.jar from path as it doesn't exist
14:21:19.563 [DEBUG] [org.gradle.api.internal.project.ant.AntLoggingAdapter] dropping /Applications/AppCode.app/Contents/lib/asm-all.jar from path as it doesn't exist
14:21:19.563 [DEBUG] [org.gradle.api.internal.project.ant.AntLoggingAdapter] Adding reference: java2.loader
```

so my workaround way is: 
```
cp ~/Downloads/javac2.jar /Applications/AppCode.app/Contents/lib/.
cp ~/Downloads/asm-all.jar /Applications/AppCode.app/Contents/lib/.
```
It works.
But, please tell me the official solution.

**Comment by zolotov** [comment]
Official solution is NOT to use AppCode as an SDK, you should use IDEA

**Comment by gosp** [comment]
But I need parse specific PSI struct of Appcode, such as `com.jetbrains.cidr.xcode.strings.OCStringsFileImpl`, so I MUST use AppCode as SDK, right?

Now I skip instrument task via `intellij.instrumentCode=false`, So I don't need copy extra jar into Appcode anymore

**Comment by zolotov** [comment]
> so I MUST use AppCode as SDK, right?

No, you just should add obj-c specific jar from AppCode distribution as a `compileOnly`  dependency. Build plugins still must be done with IntelliJ IDEA.
