### ISSUE TITLE
How to exclude jar contained by IDEA SDK?

### ISSUE THREAD

**Issue by todylu** [JetBrains/gradle-intellij-plugin#218]
My plugin depends on `antlr-runtime-4.7.jar`. There is `antlr-runtime-4.5.3.jar` contained in IDEA 2017.1 SDK.
From [Doc](http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_class_loaders.html), Plugin Classloader supports the same name jar which is used by the IDE.
But the same name jar would cause compilation error. How I exclude it from SDK?

**Comment by zolotov** [comment]
> There is antlr-runtime-4.5.3.jar contained in IDEA 2017.1 SDK.

There is not `antlr-runtime` in IDEA 2017.1 SDK, I don't know how you included it.

**Comment by todylu** [comment]
sorry. `antlr-runtime-5.3` is contained in `android` plugin, my plugin depends on `android` plugin.

**Comment by zolotov** [comment]
while compiling you can exclude anything from compile configuration. E.g. see https://discuss.gradle.org/t/how-to-exclude-file-dependency-in-compile-configuration-from-the-runtime-configuration/5316/4
