### ISSUE TITLE
Task `publishPlugin` fails without any particular exception

### ISSUE THREAD

**Issue by ghostbuster91** [JetBrains/gradle-intellij-plugin#225]
Hi,

The full message I get is:
```
FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':publishPlugin'.

> Failed to upload plugin
```

What is interesting here is that plugin is actually being uploaded to repository, at least it was last time.

The plugin is open-source and is being deploy from travis CI
Here is the build without error message:
https://travis-ci.org/elpassion/mainframer-intellij-plugin/builds/271402496#L64
_You might need to expand the after success command (`test "$TRAVIS_BRANCH" == "master" && ./gradlew publishPlugin -PpublishChannel=Stable`) at the bottom to see the full output_

Do you have any clue why this is happening?

**Comment by zolotov** [comment]
```
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by zolotov** [comment]
Also, you use outdated version of gradle-intellij-plugin

**Comment by ghostbuster91** [comment]
It is 'almost' not possible for me to run `publish` task locally because only the travis knows credentials and they are encrypted. In such case I think I will try to update.

**Comment by zolotov** [comment]
Apparently, I need a diagnostic info (at least an exception) to see what's wrong. I'm closing the issue until diagnostic info is available.
