### ISSUE TITLE
Specified intellij verison no effect, keep downloading LATEST-EAP-SNAPSHOT/maven-metadata.xml

### ISSUE THREAD

**Issue by conanchen** [JetBrains/gradle-intellij-plugin#228]
i have intellij module defined with version 'IC-2016.3' , but when i update build.gradle and refresh, I find IDEA will keep checking the LATEST-EAP-SNAPSHOT stuff in Gradle task.  Which slow down the compiling ...

intellij {
    version 'IC-2016.3' //IntelliJ IDEA 2016.3 dependency; for a full list of IntelliJ IDEA releases
    // please see https://www.jetbrains.com/intellij-repository/releases
    plugins 'coverage' //Bundled plugin dependencies
    pluginName 'live-sexyeditor'
}

**Comment by zolotov** [comment]
Likely the version it's not set on configuration phase, provide the full build.gradle

**Comment by conanchen** [comment]
refer to here: [](https://github.com/conanchen/live-sexyeditor/blob/master/build.gradle)
The compiler is happy if I comment out these secions in the above build.gralde, 
also com.jetbrains:ideaIC:2016.3 is on the list of  External Libraries:
//    jooqRuntime('com.h2database:h2:1.4.193') {
//jooq {

If I uncomment out the above two sections, intellij will keep trying to download LATEST-EAP-SNAPSHOT.

**Comment by conanchen** [comment]
ok now, that was my mistake:)
i forgot to add this line : 
apply plugin: 'nu.studer.jooq'

**Comment by zolotov** [comment]
I don't know how jooq plugin can affect intellij-plugin :(
