### ISSUE TITLE
Can't create new task based on RunIdeaTask

### ISSUE THREAD

**Issue by Virtlink** [JetBrains/gradle-intellij-plugin#23]
I'm trying to debug a JPS plugin that's used in an IntelliJ plugin. To do this, I must provide the JVM argument `-Dcompiler.process.debug.port=5005` to the IntelliJ process. This causes IntelliJ to wait for a debugger to connect to port 5005. I can do this:

```
afterEvaluate {
    tasks.getByName('runIdea') {
        jvmArgs += "-Dcompiler.process.debug.port=5005"
    }
}
```

But I want to do this in a separate task only, so I can still use `runIdea` without having to connect a debugger. So I tried this instead:

```
task("debugIdea", type: org.jetbrains.intellij.RunIdeaTask) {
    jvmArgs = ["-Dcompiler.process.debug.port=5005"]
}
```

But then I get an error about redefining `runIdea`, even though I'm naming it `debugIdea`.

> Cannot add task ':runIdea' as a task with that name already exists.

How can I keep `runIdea` as is, but create a new task `debugIdea` with the JVM arguments I want?

**Comment by zolotov** [comment]
0.0.28 will be uploaded soon. Then you can do something like this:

```
afterEvaluate {
    task("debugIdea", type: org.jetbrains.intellij.RunIdeaTask, group: 'intellij', dependsOn: 'prepareSandbox') {
        jvmArgs += ["-Dcompiler.process.debug.port=5005"]
    }
}
```

JFY, intellij idea doesn't like (doesn't show in Gradle tool window) tasks from group `other` with the `idea`-word in name, so it's better to set any other group for debug task or change its name.

Also, `afterEvaluate` is still needed, I hope I'll get rid of that in future.

**Comment by Virtlink** [comment]
Thank you very much for your quick fix and response! I'll test it as soon as your plugin update has been published.

**Comment by zolotov** [comment]
0.0.28 plublished

**Comment by Virtlink** [comment]
It works just as I wanted, thanks!
