### ISSUE TITLE
Internal hack for test classes doesn't appear to function anymore.

### ISSUE THREAD

**Issue by JakeWharton** [JetBrains/gradle-intellij-plugin#230]
You can reproduce with branch `jakew/update-kotlin/2017-08-25` of https://github.com/square/sqldelight by running `./gradlew :sqldelight-studio-plugin:compileTestKotlin`. This will fail as the test classes are not able to reference `internal` members of the main source set.

I'm not sure what needs changed, but I believe this code was handling some previous support for this functionality:

https://github.com/JetBrains/gradle-intellij-plugin/blob/4c0ac24f357aedbb237a20d3fc4e45f17749a439/src/main/groovy/org/jetbrains/intellij/IntelliJPlugin.groovy#L288-L305

**Comment by zolotov** [comment]
Hi Jake, thank you for the issue. Please tell me what plugin version you use, I'll try to recreate the issue.

**Comment by JakeWharton** [comment]
It occurs both on 0.2.5 (what the project was already using) and 0.2.17
(which I updated to in an attempt to fix it).

**Comment by zolotov** [comment]
Sorry for such a long delay. So what should I do to build your project?

```
~/TestData/sqldelight  (jakew/update-kotlin/2017-08-25) ᐅ ./gradlew :sqldelight-studio-plugin:assemble

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':sqldelight-runtime'.
> Failed to notify project evaluation listener.
   > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
   > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
```

Is there any project sample that doesn't require additional configuration?

**Comment by JakeWharton** [comment]
I can try and create one. Currently it requires the Android SDK which is
what that message is about.

**Comment by zolotov** [comment]
I would be great, thanks

**Comment by JakeWharton** [comment]
It's taken me a while, but I _finally_ circled back to this. You can reproduce this with the examples in this repo by applying the following patch (via `git apply the.patch`):
```diff
diff --git a/examples/kotlin-plugin/src/main/kotlin/org/intellij/examples/kotlin/plugin/Something.kt b/examples/kotlin-plugin/src/main/kotlin/org/intellij/examples/kotlin/plugin/Something.kt
new file mode 100644
index 0000000..6eaeb7e
--- /dev/null
+++ b/examples/kotlin-plugin/src/main/kotlin/org/intellij/examples/kotlin/plugin/Something.kt
@@ -0,0 +1,7 @@
+package org.intellij.examples.kotlin.plugin
+
+internal class Something private constructor() {
+  companion object {
+    fun getInstance(): Something = Something()
+  }
+}
diff --git a/examples/kotlin-plugin/src/test/kotlin/org/intellij/examples/kotlin/plugin/SomethingTest.kt b/examples/kotlin-plugin/src/test/kotlin/org/intellij/examples/kotlin/plugin/SomethingTest.kt
new file mode 100644
index 0000000..734edd3
--- /dev/null
+++ b/examples/kotlin-plugin/src/test/kotlin/org/intellij/examples/kotlin/plugin/SomethingTest.kt
@@ -0,0 +1,9 @@
+package org.intellij.examples.kotlin.plugin
+
+import org.junit.Test
+
+class SomethingTest {
+  @Test fun accessInternal() {
+    Something.getInstance()
+  }
+}
```
You can observe failure by running `cd examples && ./gradlew --configure-on-demand :kotlin-plugin:build` once the patch has been applied.

The failure is
```
> Task :kotlin-plugin:compileKotlin
e: /Users/jakew/dev/JetBrains/gradle-intellij-plugin/examples/kotlin-plugin/src/test/kotlin/org/intellij/examples/kotlin/plugin/SomethingTest.kt: (7, 5): Cannot access 'Something': it is internal in 'plugin'
e: /Users/jakew/dev/JetBrains/gradle-intellij-plugin/examples/kotlin-plugin/src/test/kotlin/org/intellij/examples/kotlin/plugin/SomethingTest.kt: (7, 15): Cannot access 'Something': it is internal in 'plugin'

> Task :kotlin-plugin:compileTestKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kotlin-plugin:compileTestKotlin'.
> Compilation error. See log for more details
```

**Comment by JakeWharton** [comment]
This appears to be tied to `instrumentCode` as setting it to `false` succeeds.

**Comment by abrooksv** [comment]
Is there any known workaround for this?

**Comment by zolotov** [comment]
@abrooksv no and I'm afraid `jakew/update-kotlin/2017-08-25` branch doesn't exist anymore :( Do you have a simple reproducible sample?

**Comment by abrooksv** [comment]
Looking at the above patch to this repo's examples should show it if it has instrumentCode set to true. If not I can get something made when I get back from vacation next week.

**Comment by zolotov** [comment]
ah, right, I think it was sqldelight repo

**Comment by abrooksv** [comment]
Were you able to replicate the issue @zolotov?

**Comment by abrooksv** [comment]
@zolotov This should remove the hack right? https://youtrack.jetbrains.com/issue/KT-20760

**Comment by abrooksv** [comment]
This doesnt seem to be an issue anymore with 1.3.61

**Comment by zolotov** [comment]
@abrooksv thanks, deleted
