### ISSUE TITLE
Differences between IntellijVersions

### ISSUE THREAD

**Issue by kovacserik** [JetBrains/gradle-intellij-plugin#237]
Hi, 

I'd have one question regarding the versions of the intellij:
https://www.jetbrains.com/intellij-repository/releases

What is the difference between 173.2941.3 and 2017.2.5 version?
Thanks

**Comment by zolotov** [comment]
I didn't understand the question. What do you want to know exactly? `git diff` of these builds?

**Comment by kovacserik** [comment]
yes, git diff of those builds. thanks

**Comment by zolotov** [comment]
https://github.com/JetBrains/intellij-community/compare/173.2941...172.4343
