### ISSUE TITLE
Invent a way to keep plugins installed in debug IDEA instance

### ISSUE THREAD

**Issue by zolotov** [JetBrains/gradle-intellij-plugin#24]
From https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1951 and https://github.com/alexeykudinkin/intellij-rust/issues/106

**Comment by zolotov** [comment]
Fixed in 0.0.29

**Comment by Turbo87** [comment]
awesome, thanks!

**Comment by Turbo87** [comment]
I'm also using this in https://github.com/Turbo87/intellij-emberjs btw. works really well!

**Comment by zolotov** [comment]
@Turbo87 nice to hear. Thank you for feedback
