### ISSUE TITLE
How can I require the PHP plugin

### ISSUE THREAD

**Issue by cedricziel** [JetBrains/gradle-intellij-plugin#242]
Hi there,

I'm struggeling for a good time now, to find a working combination that would allow a successful build.

How do I need to amend the following build-script, to have the PHP Plugin available both on compile time and in the intellij execution context?

```groovy
buildscript {
    repositories {
        mavenCentral()

        maven { url 'http://dl.bintray.com/jetbrains/intellij-plugin-service' }
        maven { url 'https://plugins.jetbrains.com/maven' }
    }
}

plugins {
    id "org.jetbrains.intellij" version "0.2.17"
}

dependencies {
    compile 'com.jetbrains.plugins:php:172.4155.41@jar'
}

apply plugin: 'idea'
apply plugin: 'org.jetbrains.intellij'
apply plugin: 'java'

intellij {
    version 'IU-2017.2.5'
    plugins = ['coverage', 'com.jetbrains.php:172.4155.41']
    pluginName 'plugin_name_goes_here'
}

group 'com.example'
version '1.2'
```

Thank you!

**Comment by zolotov** [comment]
Nothing to add, `plugins = ['com.jetbrains.php:172.4155.41']` is enough. `compile 'com.jetbrains.plugins:php:172.4155.41@jar'` is redundant.

See/attach gradle logs to figure out why plugin is not loaded

**Comment by cedricziel** [comment]
Great, thx for the quick answer! :tada: 

It's a partial success: 

Now I have a successful local build, but a failing travis build. Hm.

If you care to take a look:
https://github.com/cedricziel/idea-php-typo3-plugin/tree/gradle-modernization

and

https://travis-ci.org/cedricziel/idea-php-typo3-plugin/builds/291482060#L515

**Comment by zolotov** [comment]
Actually, no ideas. Might be a glitch on plugins.jetbrains.com or something. From the point of view of gradle-intellij-plugin, there is no any difference between running locally and on Travis. Maybe `--info` logging could help.

**Comment by zolotov** [comment]
I tried it locally and it failed. The reason is in following code:

```

dependencies {
    compile 'com.jetbrains.plugins:php:172.4155.41@jar'
}
```

And the error is quite descriptive:

```
Resource missing. [HTTP GET: https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/plugins/com.jetbrains.php/172.4155.41/com.jetbrains.php-172.4155.41.pom]
Resource missing. [HTTP HEAD: https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/plugins/com.jetbrains.php/172.4155.41/com.jetbrains.php-172.4155.41.jar]

FAILURE: Build failed with an exception.
```

Not sure why you inserted it in the first place, but I think you should just delete `dependency` block and `plugins.jetbrains.com` repository.

**Comment by cedricziel** [comment]
Huh, I could swear I committed and pushed exactly that. Sorry for wasting your time and thx for the quick response though!

**Comment by zolotov** [comment]
No problem, good to know it works now
