### ISSUE TITLE
Which intellij idea version does Android Studio 3.0 use?

### ISSUE THREAD

**Issue by kovacserik** [JetBrains/gradle-intellij-plugin#245]
I'm developing a custom Android Studio plugin, and I use some specific API-s.

For building this plugin I use gradle-intellij-plugin.

in my build.gradle I have:

intellij {
    version '2017.1.2'
    pluginName 'MyPlugin'
    plugins 'android'
    updateSinceUntilBuild false
    sandboxDirectory = "${rootProject.rootDir}/idea-sandbox"
}

With Android Studio 2.3.3 this is working fine, with the new 3.0 there are some "no such method error"

**Comment by zolotov** [comment]
I don't know, maybe there is no such version of IDEA that corresponds to Android Studio 3.0 in term of android-specific API.

If android-specific API was changed, it's better to ask Android Studio developers.
