### ISSUE TITLE
Support gradle/kotlin-dsl

### ISSUE THREAD

**Issue by joelhandwell** [JetBrains/gradle-intellij-plugin#249]
Not sure if it's right place to report this issue, but [gradle/kotlin-dsl](https://github.com/gradle/kotlin-dsl)  is not working out of the box in idea as reported in https://github.com/gradle/kotlin-dsl/issues/313

**Comment by zolotov** [comment]
Hi, it's not the right place. I think https://youtrack.jetbrains.com/v2/issue/KT-20521 is what you need
