### ISSUE TITLE
Simple Plugin Example

### ISSUE THREAD

**Issue by pgibber** [JetBrains/gradle-intellij-plugin#250]
Hello,

I tried using your simple plugin example for the gradle plugin but I having trouble getting it to work with IntelliJ 2017.2.6. My gradle  wrapper version is gradle-3.5-rc-2. What should build.gradle file look like? I am "successfully" creating a .jar file, the terminal shows no errors. When I install the plugin in Intellij I get an error saying that "Plugin 'my-plugin' is not compatible with this installation". Any insight you may have would be helpful. Thanks.

[build.gradle.txt](https://github.com/JetBrains/gradle-intellij-plugin/files/1479855/build.gradle.txt)

[HelloAction.java.txt](https://github.com/JetBrains/gradle-intellij-plugin/files/1479858/HelloAction.java.txt)

[plugin.xml.txt](https://github.com/JetBrains/gradle-intellij-plugin/files/1479871/plugin.xml.txt)

**Comment by zolotov** [comment]
First of all, gradle-intellij-plugin you use is outdated.

How did you build this jar? Does it work with `runIde` task?

**Comment by pgibber** [comment]
I have been building the building the .jar file by running the buildPlugin command that is inside Intellij's Gradle pane. When I run runIde or runIdea, a new separate instance of IntelliJ Idea Community Edition Public Edition 2017.3 to appear, which seems strange since I am using IntelliJ Idea Ultimate 2017.2. When this instance first appears, I am asked to create or open a project. I can use the greeting app for a short bit if I first create a new project from this separate IntelliJ Idea Community Edition instance before this instance freezes. Trying to open a project, the IntelliJ Idea Community Edition freezes immediately. This freezing may be a separate issue?

Either way running buildPlugin produces the .jar file, and runIde produces a .jar file. When I install either .jar file. from within IntelliJ, I get the aforementioned error "Plugin 'my-plugin' is not compatible with this installation.

Do you think I need to update the built-in gradle wrapper version? If so, how do I do this? Thanks for the quick response.

**Comment by pgibber** [comment]
I changed the build.gradle file to reflect what you said and I still get the community edition appearing. I also updated the gradle plugin version.
[build.gradle.txt](https://github.com/JetBrains/gradle-intellij-plugin/files/1482550/build.gradle.txt)

**Comment by zolotov** [comment]
how you run it exactly?

**Comment by pgibber** [comment]
I am using the default gradle wrapper. With the files I sent you, I click on IntelliJ's gradle pane and right click and run runIde.
![image](https://user-images.githubusercontent.com/11323082/32955956-80cec844-cb85-11e7-922d-adea61584747.png)

**Comment by zolotov** [comment]
you defined plugin for `subprojects` but run action on the root project.
