### ISSUE TITLE
Error during test execution

### ISSUE THREAD

**Issue by kovacserik** [JetBrains/gradle-intellij-plugin#251]
If I want to execute a LightPlatformTestCase I got the following error:

java.lang.AssertionError: Problems found loading plugins:<p/>Plugin "Groovy" was not loaded: required plugin "com.intellij.properties" not installed.<p/>Plugin "Gradle" was not loaded: required plugin "com.intellij.properties" not installed.<p/>Plugin "Android Support" was not loaded: required plugin "com.intellij.properties" not installed.

My build.gradle:

intellij {
    version intellijVersion
    pluginName 'MyPlugin'
    plugins = ['android', 'junit', 'gradle', 'Groovy']
    updateSinceUntilBuild false
}

Do I miss something?

**Comment by zolotov** [comment]
what's the plugin version you use?

**Comment by zolotov** [comment]
closing due to lack of feedback

**Comment by donnerpeter** [comment]
Changing to `intellij.plugins = ["Groovy", "properties"]` in build.gradle seems to help.
