### ISSUE TITLE
The expanded classes and META-INF directories are not included in the distribution

### ISSUE THREAD

**Issue by rhdunn** [JetBrains/gradle-intellij-plugin#252]
Since version 0.2.0 of the plugin, and still with the current version 0.2.17, running `gradle buildPlugin` results in the following top-level directories:

    lib

compared to:

    classes
    lib
    META-INF

This is breaking my plugin from resolving resources when installed in IntelliJ using the class loader.

**Comment by zolotov** [comment]
The layout with a single `lib` directory is completely valid and supported by Intellij PluginClassLoader for years. I don't have any intentions to change it.
