### ISSUE TITLE
runtimeOnly but no error in editor

### ISSUE THREAD

**Issue by robstoll** [JetBrains/gradle-intellij-plugin#253]
I changed a dependency from compile to runtimeOnly but sad enough, the editor does not show up an error that the corresponding dependency is now no longer available at compile time.
When I run gradle (from within intellij) then I get the expected error `Unresolved reference:`

**Comment by zolotov** [comment]
Hi. I'm not sure it's related to gradle-intellij-plugin, please provide more details: version of the plugin, build.gradle, steps to reprodice

**Comment by robstoll** [comment]
I just closed my laptop, will post the version of the plugin later on. But you can already checkout the following commit and undo the change in CharSequenceContainsRegexAssertionsSpec -- you should get an error since en_UK is a only runtime dependency.
https://github.com/robstoll/atrium/commit/dd5e319653c3d7fe3b40f4c23b447c89e02801f8

**Comment by zolotov** [comment]
Sorry, I think you mixed up the issue tracker. Please you https://youtrack.jetbrains.com instead

**Comment by robstoll** [comment]
Wuups, I did, thanks for the hint
