### ISSUE TITLE
Code Hot Swapping while debugging through Gradle

### ISSUE THREAD

**Issue by cypressious** [JetBrains/gradle-intellij-plugin#254]
Is there a way for hot-swapping code changes during debugging?

**Comment by zolotov** [comment]
Sure, it works out of the box. What's wrong with the hotswap for you?

**Comment by cypressious** [comment]
When debugging the https://github.com/JetBrains/kotlin/ project, hotswapping seems to fail. 

Just to minize confusion, the expected workflow is debugging the Gradle task `runIde`. And when I want to make changes, I run the `:myModule:compileX` task, right?

**Comment by zolotov** [comment]
https://github.com/JetBrains/kotlin/ doesn't use `gradle-intellij-plugin`, so it's better ask them how to configure hotswap for that project.

> Just to minize confusion, the expected workflow is debugging the Gradle task runIde. And when I want to make changes, I run the :myModule:compileX task, right?

Not sure about the second part, I use `Recompile file` IDE action from Build menu to HotSwap the current file.

**Comment by cypressious** [comment]
Oh sorry, I naively assumed they were using it.

**Comment by zolotov** [comment]
No problem, sorry I can't help
