### ISSUE TITLE
Launch IDE with local plugin dependency

### ISSUE THREAD

**Issue by Undin** [JetBrains/gradle-intellij-plugin#258]
Currently, gradle-intellij-plugin allows adding a dependency on some other plugin. And if plugin dependency is bundled or from plugin repo, new instance of IDE (launched by `runIde` task) has this plugin installed. But when dependency is another local plugin project, IDE instance doesn't have it.

It would be great to support this case.

For example, it would be useful for [intellij-rust](https://github.com/intellij-rust/intellij-rust) plugin where rust plugin has dependency on toml plugin

**Comment by zolotov** [comment]
There is a `composite-plugin` example and it works as expected. Please check Rust build script.

**Comment by Undin** [comment]
Sorry for slow response
Looks like this feature works only with `0.3.0-SNAPSHOT` version and doesn't work with `0.2.18`
Do I understand correctly that #238 brought the fix to make this feature work but current stable plugin version doesn't contain it?

**Comment by zolotov** [comment]
@Undin it looks so

**Comment by Undin** [comment]
Is there any estimation when this feature will be landed in stable?

**Comment by zolotov** [comment]
not really, you can try backport it to 0.2 branch

**Comment by zolotov** [comment]
duplicates #238
