### ISSUE TITLE
JetBrains Toolbox applications cannot be used as alternativeIdePath

### ISSUE THREAD

**Issue by kiiadi** [JetBrains/gradle-intellij-plugin#259]
When trying to launch `runIde` which points to the path of a JetBrains application that has been installed via the JetBrains Toolbox on Mac I get the following error:

```
Execution failed for task ':runIde'.
> java.io.FileNotFoundException: /Users/xxxx/Applications/JetBrains Toolbox/PyCharm Professional.app/Contents/build.txt (No such file or directory)
```

There is no `build.txt` in that directory although it seems like the plugin is expecting one to be present.

**Comment by zolotov** [comment]
Are you sure that PyCharm is located there? Toolbox installs applications in `~/Libraries/Application Support` by default

**Comment by kiiadi** [comment]
@zolotov that seems to work - thanks!

**Comment by AlecStrong** [comment]
I'm seeing this now as well while using toolbox, and there is no `.app` in `~/Libraries/Application Support` to point too. There is the one in `~/Applications/Jetbrains Toolbox/Android Studio.app` but that is the one that gives me the build.txt problem

**Comment by zolotov** [comment]
@AlecStrong it's wrong location, open settings of the Android Studio in the Toolbox to see the proper installation location, it will look like `/home/zolotov/.local/share/JetBrains/Toolbox/apps/Goland/ch-0/183.2312`

**Comment by AlecStrong** [comment]
perfect thank you!
