### ISSUE TITLE
The Build Script Snippet for Gradle < 2.1 is wrong

### ISSUE THREAD

**Issue by simontunnat** [JetBrains/gradle-intellij-plugin#26]
The line

    classpath group: 'org.jetbrains', name: 'gradle-intellij-plugin', version: '0.0.27'

is not working and will give 404 errors.

After some research I found that it should instead be

    classpath 'gradle.plugin.org.jetbrains:gradle-intellij-plugin:0.0.28'

Source:
https://plugins.gradle.org/plugin/org.jetbrains.intellij

**Comment by zolotov** [comment]
Thanks!

**Comment by simontunnat** [comment]
Thank you.
