### ISSUE TITLE
how can i use localPath '/Applications/IntelliJ IDEA.app'

### ISSUE THREAD

**Issue by guhan121** [JetBrains/gradle-intellij-plugin#260]
if i modify examples/build.gradle
`
subprojects {
    apply plugin: 'java'
    apply plugin: 'org.jetbrains.intellij'
    
    intellij {
//        version '2016.3.1'
        localPath '/Applications/IntelliJ IDEA.app'
    }
}
`

and modify settings.gradle
`
bogon:examples qiantao$ cat settings.gradle 
//include 'simple-plugin', 'composite-plugin', 'plugin-with-dependencies', 'rider-plugin', 'kotlin-plugin'
//include 'composite-plugin:subplugin', 'custom-runide-task'
//includeBuild '..'
include 'simple-plugin'
include 'kotlin-plugin'
`
but when sync gradle tasks.

gradle download idea like down
`
bogon:HelloWorldPlugin qiantao$ gradle tasks
Starting a Gradle Daemon (subsequent builds will be faster)
Download https://www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/LATEST-EAP-SNAPSHOT/ideaIC-LATEST-EAP-SNAPSHOT.zip
> Configuring > 1/1 projects > 1.26 MB/450.52 MB downloaded^Cbogon:HelloWorldPlugin qiantao$ 
`

could i use localPath without download?

**Comment by zolotov** [comment]
Enable info logging please and try again
