### ISSUE TITLE
Add getJavaHome method to JbreResolver

### ISSUE THREAD

**Issue by baron1405** [JetBrains/gradle-intellij-plugin#265]
Hi @zolotov, I see that the 0.3.0 release of the plugin will provide the ability to run the IDE using the JetBrains JRE. For a project at my company, I plan to use the JbreResolver to download the JetBrains JDK (rather than JRE) to register in the IDE as the SDK used to build a plugin and run it in the IDE sandbox. For this use case, I will need the Java home path of the downloaded JDK. The JbreResolver already knows this so it would be great if you could provide a getter for the root of the downloaded JDK/JRE (i.e. its Java home path which is `new File(cacheDirectoryPath, artifactName)`). This would be a lot cleaner for me than taking the path returned by the resolve method and doing `../../..` on it. Thanks for considering this feature request.

**Comment by zolotov** [comment]
Hi @baron1405,

Sounds good to me. PR is welcome :)

**Comment by baron1405** [comment]
Submitted PR #267

I decided that returning a data object from the resolve method would be cleaner than a getter and provide more flexibility.

**Comment by zolotov** [comment]
Looks great. Merged
