### ISSUE TITLE
runIdea should not skip when 'up-to-date'

### ISSUE THREAD

**Issue by patflynn** [JetBrains/gradle-intellij-plugin#27]
Surprisingly, even though runIdea extends from JavaExec, I'm finding on my project that repeated invocations of runIdea do nothing because it is 'up-to-date'.  

Making this change: https://github.com/GoogleCloudPlatform/gcloud-intellij/pull/235/files fixed it for us.

Are we configuring this wrong somehow or does this plugin need to explicitly configure that runIdea should have outputs.upToDateWhen { false }?

**Comment by zolotov** [comment]
Wow, didn't see that. Will investigate, thanks.

**Comment by zolotov** [comment]
Indeed, I did not foresee the consequences of my previous changes, sorry about that. Fixed in 0.0.30, will publish in a minute.
