### ISSUE TITLE
IJ gradle plugin fails with JAR dependency from Ultimate not found error

### ISSUE THREAD

**Issue by ivanporty** [JetBrains/gradle-intellij-plugin#278]
Very simple configuration to reproduce is here:
https://github.com/ivanporty/intellij-gradle-plugin-test

Just run:
`./gradlew compileJava`

Fails with:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find lib/duplicates-groovy.jar (org.jetbrains.plugins:Groovy:2018.1-withSources).
  Searched in the following locations:
      .gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2018.1/d082978a55b398ef544e7daee1dd6228b88dbfc1/ideaIC-2018.1/plugins/Groovy/lib/duplicates-groovy.jar
      .gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/plugins.jetbrains.com/Groovy-2018.1-withSources/lib/duplicates-groovy.jar
      .gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2018.1/41575d90c6dfac0e36e5c9328b89ad85de1da2c1/ideaIC-2018.1-sources.jar/lib/duplicates-groovy-2018.1-withSources.jar

**Comment by zolotov** [comment]
Cannot recreate :man_shrugging: 

Try to remove `~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2018.1/d082978a55b398ef544e7daee1dd6228b88dbfc1/ideaIC-2018.1/ideaIC-2018.1-withKotlin-withSources.xml`

**Comment by ivanporty** [comment]
You're right, cannot reproduce on a completely clean machine. I guess the specific problem was in previous version and then it stuck in the cache. Was this specific XML you mentioned a cause of that issue and then it was fixed I assume?

**Comment by zolotov** [comment]
> Was this specific XML you mentioned a cause of that issue and then it was fixed I assume?

This XML contains all jars that gradle looks for while building. So yes, the xml is the reason of the problem. But I don't really understand how `duplicates-groovy.jar` got there. This jar is a part of `Groovy` plugin from the IntelliJ IDEA Ultimate.

**Comment by zolotov** [comment]
I got it now, will try to recreate this

**Comment by zolotov** [comment]
Recreated. The workaround is to delete `~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/plugins.jetbrains.com/Groovy-2018.1-withSources.xml`

**Comment by nalbion** [comment]
@zolotov any chance you can help with this issue?  seems like a similar error message

https://github.com/OpenASR/idear/issues/51
https://travis-ci.com/OpenASR/idear/jobs/130280990

```
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find AceJump/lib/AceJump-3.5.0.jar (org.jetbrains.plugins:AceJump:3.5.0).
     Searched in the following locations:
         file:/home/nalbion/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/be099a2c25b1e63cae5d05f7f53b3e4fb9a9c551/ideaIC-LATEST-EAP-SNAPSHOT/plugins/AceJump/AceJump/lib/AceJump-3.5.0.jar
         file:/home/nalbion/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/plugins.jetbrains.com/AceJump-3.5.0/AceJump/lib/AceJump-3.5.0.jar
         file:/home/nalbion/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/c3a421e20746601f882c100d5f35be5e25627af0/ideaIC-LATEST-EAP-SNAPSHOT-sources.jar/AceJump/lib/AceJump-3.5.0-3.5.0.jar
```

I can reproduce with a simple Dockerfile:
```
FROM java:8

COPY . /idear
WORKDIR /idear
RUN ./gradlew buildPlugin
```
