### ISSUE TITLE
Plugin cannot download SDK

### ISSUE THREAD

**Issue by baron1405** [JetBrains/gradle-intellij-plugin#279]
I am getting a 404 when the plugin tries to download an SDK. For example, the following gives a 404:
https://www.jetbrains.com/~urlswitch/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIU/2018.1.2/ideaIU-2018.1.2.zip

whereas the following works:
https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIU/2018.1.2/ideaIU-2018.1.2.zip

Did something change?

**Comment by baron1405** [comment]
Appears to have been resolved.

**Comment by zolotov** [comment]
It was a temporary problem, sorry about that.
