### ISSUE TITLE
Does not support compiling for IntelliJ Idea 13.x

### ISSUE THREAD

**Issue by sergeykad** [JetBrains/gradle-intellij-plugin#28]
Fails on `:compileJava` with `typedef class com.intellij.ant.ClassFilterAnnotationRegexp cannot be found`
The class is present in 14.x versions of javac2.jar but not in the earlier ones.

**Comment by zolotov** [comment]
Well, yes, it doesn't. Actually there is no 13.x version at https://www.jetbrains.com/intellij-repository/releases so it's not about one particular class. I'm not going to handle this in any way in the nearest future. Do you really need this?

**Comment by sergeykad** [comment]
I have to support 13.x since it is relatively new version and there are still many people using it. IntelliJ 14 was realized on March 24th, 2015.
There are some early 14.x versions in the repository, like 139.1.20, but the plugin does not support them either.

**Comment by sergeykad** [comment]
I found a workaround for the compilation error. Adding `intellij.instrumentCode false` solves it. It probably worth to do it automatically inside the plugin if `com.intellij.ant.ClassFilterAnnotationRegexp' is missing.

**Comment by zolotov** [comment]
> It probably worth to do it automatically inside the plugin if `com.intellij.ant.ClassFilterAnnotationRegexp' is missing.

It makes sense, thanks for suggestion. Will try to implement.

**Comment by sergeykad** [comment]
Setting `intellij.instrumentCode false` causes too much issues down the line. Can one of the following be done:
* Manually add javac2.jar to the classpath of IntelliJInstrumentCodeAction. I tried replacing the jar in the relevant folder with one from IDEA 14 and it works, but I prefer to do it via Gradle configuration.
* Implement the code instrumentation in the pre IDEA 14 compatible manner. The functionality is present in the IDEA 13 itself, so it should be possible to run it from Gradle.

Thanks in advance.

**Comment by zolotov** [comment]
Fixed in 0.0.32. For IDEA SDKs before 14.0 notnull-instrumentation is disabled, forms compilation should work.
