### ISSUE TITLE
Local  plugin file dependency stopped working in 0.3.0

### ISSUE THREAD

**Issue by jansorg** [JetBrains/gradle-intellij-plugin#281]
I'm using local files as plugin dependency.
It's working with `0.2.20`, but stopped working with `0.3.0` and `0.3.1`.

This is what I'm doing:
```
// resolves to a file path which exists on disk, it's working with 0.2.20
myPlugins << new File(System.getenv('pycharmPlugin')) << 'coverage'
// ...

intellij {
        plugins = myPlugins
        // ...
    }
```

Running this with 0.3.1 fails:
- myPlugins contains `File("/home/user/plugin-source/cache/python-2018.1.181.3007.14/python/lib/python.jar")` and `coverage`

Last lines from `gradle clean build`
```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find python.jar (org.jetbrains.plugins:Pythonid:2018.1.181.3007.14).
  Searched in the following locations:
      file:/home/user/plugin-source/cache/ideaIU-181.3494.3/plugins/Pythonid/python.jar
      file:/home/user/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/plugins.jetbrains.com/Pythonid-2018.1.181.3007.14/python.jar
```

It seems that:
- `/home/user/plugin-source/cache/python-2018.1.181.3007.14/python/lib/python.jar` is resolved and accepted as plugin dependency, ID is `Pythonid`
- For unknown reasons the dependency is then searched at `/home/user/plugin-source/cache/ideaIU-181.3494.3/plugins/Pythonid/python.jar` (i.e. inside the configured JDK), which doesn't exist.

Was there some change in the plugin resolution between `0.2.20` and `0.3.0`?

Thank you for any help you may offer! 
If you need more information, please let me know.

**Comment by zolotov** [comment]
> myPlugins contains File("/home/user/plugin-source/cache/python-2018.1.181.3007.14/python/lib/python.jar") and coverage

Local paths to plugins were never supported, only bundled and from the repo (see the documentation), it's just a coincidence that it worked for you. You can attach such dependencies as a simple dependency.

**Comment by jansorg** [comment]
Thanks!
For the record: if you have a plugin on disk and would like to include it as a plugin dependency, then use something like `dependencies.implementation fileset('/path/to/plugin.jar')`
