### ISSUE TITLE
Issue build warning when plugin dependency is outdated

### ISSUE THREAD

**Issue by breandan** [JetBrains/gradle-intellij-plugin#282]
It would be nice to have a build notification when a new plugin dependency version becomes available on the Plugin Repository so developers don't need to manually check for the latest available version.

**Comment by zolotov** [comment]
I think it's a feature request for Gradle itself, not for the plugin

**Comment by breandan** [comment]
Not talking about Gradle Plugins, but IntelliJ Platform Plugins (via the IntelliJ Plugin Repository).

**Comment by breandan** [comment]
It would also be nice to have some kind of validation or autocomplete for plugin dependencies, like [Gradle dependencies](https://stackoverflow.com/questions/26986526/using-autosuggest-on-dependency-jars-that-are-downloaded-by-gradle). The error raised in openasr/idear#51 was not especially helpful.

**Comment by YannCebron** [comment]
note that a new release of plugin might not necessarily still be compatible with current target platform

**Comment by breandan** [comment]
Similarly, the a new release of the target platform may not be compatible with the plugin version as specified by `until-build`. Since the `intellij.version` property defaults to `LATEST_EAP_SNAPSHOT`, it would be prudent to warn or fail the build in either case.

**Comment by YannCebron** [comment]
I've added this RFE to issue handling it in IDE directly: https://youtrack.jetbrains.com/issue/IDEA-252797
(IMHO this fits better in workflow)
