### ISSUE TITLE
Retrofit 400 error during publishPlugin

### ISSUE THREAD

**Issue by etanshaul** [JetBrains/gradle-intellij-plugin#288]
Tested using same builds of my plugin that previously published successfully. 

```
9:03:30.123 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.RuntimeException: Failed to upload plugin
09:03:30.123 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 44 more
09:03:30.123 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: retrofit.RetrofitError: 400 
09:03:30.123 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at retrofit.RetrofitError.httpError(RetrofitError.java:40)
09:03:30.123 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
09:03:30.123 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
09:03:30.123 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.jetbrains.intellij.pluginRepository.$Proxy107.uploadByXmlId(Unknown Source)
09:03:30.123 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.uploadPlugin(pluginRepositoryRest.kt:95)
09:03:30.123 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance$uploadPlugin.call(Unknown Source)
```

**Comment by mikhailvink** [comment]
There is a note next to the button: "License URL should be provided", that's why it's not possible to upload the update. We should definitely communicate it more clear, I'll create an internal issue now.

As of the recent GDPR-related changes, a license URL must be provided for all plugins in the plugins repository, so please add a license URL on the edit plugin page (below the update upload).

**Comment by mikhailvink** [comment]
And we have published additional information here: https://blog.jetbrains.com/platform/2018/05/legal-news-plugin-license-is-required-for-all-plugins/

**Comment by etanshaul** [comment]
thanks @mikhailvink.

I think the UI on the repo page could be improved to better indicate this. E.g. it wasn't clear at all that the form was in error due to a missing license.

In any case, this isn't the repo to track that so I'll close.

**Comment by etanshaul** [comment]
actually, better error messages from the publish task would have saved a lot of headache. maybe we can improve that and track here?

**Comment by cursive-ide** [comment]
Yes, even if this is surfaced on the plugin repo UI, it also needs to be shown when the Gradle task fails. Since I've been using Gradle, I never use the UI to upload any more.

**Comment by ermadan** [comment]
Is there any way to specify license URL when using Gradle publish task?

**Comment by cursive-ide** [comment]
@ermadan You don't have to specify it on every publish, just once in the repo UI and then publishing will work from Gradle.

**Comment by zolotov** [comment]
`gradle-intellij-plugin` 0.3.3 shows correct error message. Please upgrade if needed.

```
:compileJava UP-TO-DATE
:patchPluginXml UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:instrumentCode UP-TO-DATE
:postInstrumentCode
:jar UP-TO-DATE
:prepareSandbox UP-TO-DATE
:buildPlugin UP-TO-DATE
:verifyPlugin
Failed to upload plugin: Plugin license url must be set to upload plugin update
:publishPlugin FAILED
```
