### ISSUE TITLE
Gradle doesn't apply gradle.properties to the publish section

### ISSUE THREAD

**Issue by LukBukkit** [JetBrains/gradle-intellij-plugin#292]
Hello,
when I try to publish my plugin there's the error that username and password aren't found, but I setup it up according to [your guide](http://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/deployment.html#add-your-account-credentials). I tried it both in IDEA and in the console and the errors is always the same. Other properties from the properties file work, but not the username and password ones. 
It works when I use the apply command inside the publish section.

**Comment by zolotov** [comment]
Hi, 

The guide is basically wrong. You can set username and password in `gradle.properties`, but you still need to refer these variables in `build.gradle` in `publishPlugin` task:

```
publishUsername=user
publishPassword=123
```

```
publishPlugin {
  username publishUsername
  password publishPassword
}
```

I recommend you also to read `README.md` and Gradle tutorial.
