### ISSUE TITLE
Clean IntelliJ "out" dir

### ISSUE THREAD

**Issue by neokyle1** [JetBrains/gradle-intellij-plugin#294]
Since IntelliJ now uses the "out" dir to store build files, I am wondering if this plugin should handle cleaning that dir by appending logic to the default clean task.

```
clean {
    delete 'out'
}
```

**Comment by zolotov** [comment]
The plugin has nothing to do with idea’s compilation process. You can use any other output directory in idea, or not use idea compilation at all, or you can even use any other ide.

**Comment by neokyle1** [comment]
Whops, sorry got this repo confused with the gradle idea plugin.
