### ISSUE TITLE
alternativeIdePath should support HOME variable

### ISSUE THREAD

**Issue by SingingBush** [JetBrains/gradle-intellij-plugin#297]
It would be convenient to be able to use `~/` or `$HOME` but I get:

`Cannot find alternate SDK path: ~/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5281.33. Default IDEA will be used`

`Cannot find alternate SDK path: $HOME/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5281.33. Default IDEA will be used`

It's worth noting that as a workaround I can use:

```
alternativeIdePath "$System.env.HOME/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5281.33/"
```

**Comment by zolotov** [comment]
Thank you for the suggestion, but I'd avoid adding the functionality that can be easily implemented with a groovy (build.gradle is a groovy script after all), sorry. File paths are interpreted with a builtin Gradle method `Project#file` and I think it's better to stick with it.
