### ISSUE TITLE
plugin.xml is missing from generated jar and jar in zip

### ISSUE THREAD

**Issue by VladRassokhin** [JetBrains/gradle-intellij-plugin#3]
[See project](https://github.com/VladRassokhin/intellij-hcl), `plugin.xml` located in directory `META-INF` under sources root. 
Using plugin version `0.0.13`

**Comment by zolotov** [comment]
For java-plugin plugin.xml must be placed in resources directory, otherwise it won't be copied to output. it's not gradle-intellij-plugin issue.
