### ISSUE TITLE
Not clear error about missing plugin.xml

### ISSUE THREAD

**Issue by sergeykad** [JetBrains/gradle-intellij-plugin#30]
The plugin expects the *plugin.xml* file to be located in *src\main\resources* directory and complains if it is not there.
However IntelliJ by default creates the file under root folder of project. I also was unable to find any documentation where the plugin expects to find the *plugin.xml* file. 
I know that it is Gradle methodology to put any resource files under *src\main\resources*, but IntelliJ does not use it by default and I was not sure if my project will work correctly in IntelliJ if I move the file.

**Comment by zolotov** [comment]
> The plugin expects the plugin.xml file to be located in src\main\resources directory and complains if it is not there.

Not really, the plugin expects that plugin.xml will be under resources root, not exactly under `src/main/resources`. It's configurable in Gradle.

> However IntelliJ by default creates the file under root folder of project. I also was unable to find any documentation where the plugin expects to find the plugin.xml file. 

IntelliJ by default doesn't create a gradle project. Anyway, I'm going to add documentation about gradle-intellij-plugin at http://www.jetbrains.org/intellij/sdk/docs/index.html eventually and will try to mention proper location of plugin.xml. Thanks for feedback.
