### ISSUE TITLE
How to write plugin that use YAML

### ISSUE THREAD

**Issue by lusarz** [JetBrains/gradle-intellij-plugin#302]
Hello, I'd like to write plugin that works with [YML files](https://github.com/JetBrains/intellij-community/blob/e809b76cba9ed44866a068ae829940316e9bef93/plugins/yaml/src/org/jetbrains/yaml/psi/YAMLFile.java), but got trouble to configure it. I'm getting error:
    
    Cannot find builtin plugin org.intellij.yaml for IDE: /home/lukasz/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/LATEST-TRUNK-SNAPSHOT/da196b03dca4021f356970c694bf4fb2d3c6780a/ideaIU-LATEST-TRUNK-SNAPSHOT
 
Here is my corresponding `build.gradle` configuration:

    plugins {
        id 'java'
        id 'org.jetbrains.intellij' version '0.3.4'
    }
    
    group 'pl.softarea'
    version '1.0'

    sourceCompatibility = 1.8

    repositories {
        mavenCentral()
        maven { url 'http://dl.bintray.com/jetbrains/intellij-plugin-service' }
    }

    dependencies {
        testCompile group: 'junit', name: 'junit', version: '4.12'
    }

    intellij {
        version 'IU-LATEST-TRUNK-SNAPSHOT'
        updateSinceUntilBuild false
        plugins = ['JavaScriptLanguage', 'org.intellij.yaml']
    }

**Comment by zolotov** [comment]
apparently there is not `org.intelij.yaml` in the IDEA but there is `yaml` one

**Comment by lusarz** [comment]
True, it helped me. Thanks @zolotov, you saved me a few hours of investigation.

**Comment by zolotov** [comment]
you're welcome. I think I should rephrase the documentation a bit.
