### ISSUE TITLE
IntelliJ cannot find icon declared in plugin.xml

### ISSUE THREAD

**Issue by sergeykad** [JetBrains/gradle-intellij-plugin#31]
After I switched to building my plugin using *gradle-intellij-plugin* I started  getting errors that icon declared in plugin.xml for actions `<group>` cannot be found. The configuration I use is sumular to one in [http://www.jetbrains.org/intellij/sdk/docs/basics/action_system.html](http://www.jetbrains.org/intellij/sdk/docs/basics/action_system.html)
Can it be due to the fact that my plugin classes are stored now in *classes* directory inside the plugin jar instead of being packed in a separated jar?

**Comment by zolotov** [comment]
>  started getting errors that icon declared in plugin.xml for actions <group> cannot be found. 

What kind of error? Where is your icons is placed? 
What IDEA version do you use for developing and what version you've set in build.gradle?

> Can it be due to the fact that my plugin classes are stored now in classes directory inside the plugin jar instead of being packed in a separated jar?

Unlikely.

**Comment by sergeykad** [comment]
`RuntimeException: Can't find icon in 'foo/bar/AppIcon16x16.png' near class com.intellij.openapi.actionSystem.DefaultActionGroup: Can't find icon in 'foo/bar/AppIcon16x16.png' near class com.intellij.openapi.actionSystem.DefaultActionGroup`

The icon is for right click menu in the project window. Both development and Gradle use version 13.1.6

The configuration is written like this:
``` XML		
<actions>
	<group id="My.Menu" text="MyPlugin" description="MyPlugin menu" popup="true" icon="foo/bar/AppIcon16x16.png">
		
		<!-- more configuration here -->
		
	</group>
</actions>
```

**Comment by zolotov** [comment]
> Where is your icons is placed?

**Comment by sergeykad** [comment]
The icon is for right click menu in the project window. 
I noticed that icons for `<action>`s inside the `<group>` are loaded. I tried switching the `icon` attribute between group and action and got the same result. Works in action, but not in group.

I also have icons loaded programmatically in my `JPanel`  implementation class and I got errors there too.

**Comment by zolotov** [comment]
Please tell the path to the icon file

**Comment by sergeykad** [comment]
It is in `src\main\resources\foo\bar\`

**Comment by zolotov** [comment]
and what's the path of icon file in sandbox `build/idea-sandbox/plugins/<pluignName>`?

**Comment by sergeykad** [comment]
It is in `build\idea-sandbox\plugins\MyPlugin\classes\foo\bar` folder

**Comment by zolotov** [comment]
Thanks. I recreated this. 

As a workaround add following code in `build.gradle`

```
afterEvaluate {
  tasks.getByName('runIdea') {
    systemProperty 'idea.is.internal', 'false'
  }
}
```

**Comment by zolotov** [comment]
The fix will appear only in IDEA 15.1

**Comment by sergeykad** [comment]
Thanks, it solved the icons problem.

Do you mean that workaround is required unless I am building plugin for IDEA 15.1 and up?

**Comment by zolotov** [comment]
That's right, it's impossible now to use internal mode and set icons via xml simultaneously.

Yet another workaroud: creating class for defined group (extends DefaultActionGroup), and set icon there:

```java
  public void update(AnActionEvent e) {
    e.getPresentation().setIcon(IconFinder.find(...));
  }
```

**Comment by zolotov** [comment]
Since 0.0.32 the first workaround is simpler:

```groovy
intellij {
  systemProperty 'idea.is.internal', 'false'
}
```
