### ISSUE TITLE
publishPlugin FAILED, error 404

### ISSUE THREAD

**Issue by Jdruwe** [JetBrains/gradle-intellij-plugin#311]
I am trying to publish my intellij plugin but I get a 404, this is my logging: https://pastebin.com/bL3MY84X, is some service maybe down? I also see the following error `Plugin verification: Plugin descriptor plugin.xml does not include any module dependency tags. The plugin is assumed to be a legacy plugin and is loaded only in IntelliJ IDEA.
`, how can I fix that?

**Comment by zolotov** [comment]
The first time you should upload plugin manually.
As for the warning, see http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html for details

**Comment by Jdruwe** [comment]
That is not really clear from the docu found at: http://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/deployment.html. It seems like there is a lot of repetition between the build.gradle file and plugin file.

**Comment by zolotov** [comment]
Feel free to make a PR to a doc page.

Repetitions like what?

**Comment by Jdruwe** [comment]
I am sorry I was wrong about the repetitions (I get the system now), I am now looking into manually uploading my plugin for the first time as I now lack the 'Prepare Plugin Module <module name> for Deployment' option DevKit provided back in the past.

**Comment by zolotov** [comment]
‘buildPlugin’ task prepares a zip file in ‘build/distributions’ for uploading, no need to use that action

**Comment by Jdruwe** [comment]
Thank you so much @zolotov and sorry for my noob questions ;) This can be closed now.

**Comment by zolotov** [comment]
No worries. Thanks for the update

**Comment by jingtuo** [comment]
> I am trying to publish my intellij plugin but I get a 404, this is my logging: https://pastebin.com/bL3MY84X, is some service maybe down? I also see the following error `Plugin verification: Plugin descriptor plugin.xml does not include any module dependency tags. The plugin is assumed to be a legacy plugin and is loaded only in IntelliJ IDEA. `, how can I fix that?

I have the same problem. Can you tell me the steps to solve it?
