### ISSUE TITLE
IDEA Import misconfigures output path of module for sourceSet marked as generated

### ISSUE THREAD

**Issue by dansanduleac** [JetBrains/gradle-intellij-plugin#319]
When importing with separate module per source set, this code (using gradle 4.10):

```groovy
apply plugin: 'java'
apply plugin: 'idea'

sourceSets {
  generated
}

afterEvaluate {
  plugins.withType(IdeaPlugin).configureEach { plugin ->
    def module = plugin.model.module
    module.sourceDirs += sourceSets.generated.allJava.srcDirs // whether or not I do this is irrelevant
    module.generatedSourceDirs += sourceSets.generated.java.srcDirs
  }
}
```

Leads to the `generated` sourceSet's module having the wrong output path, and one that clashes with the `test` sourceSet's one, preventing me from even compiling after import until I change it manually: 

![image](https://user-images.githubusercontent.com/222827/45756722-7badeb80-bc19-11e8-93ec-309ccbdb2fa9.png)

![image](https://user-images.githubusercontent.com/222827/45757050-65ecf600-bc1a-11e8-946c-7981e545787d.png)

Note: if I add more sourceSets, asnd don't add their srcDirs to `module.generatedSourceDirs`, then they get imported fine.

Also, if I don't configure `IdeaPlugin` at all, they all get imported fine. This configuration is necessary however in order to make `./gradlew idea` work.

Using latest IntelliJ:
IntelliJ IDEA 2018.3 EAP (Ultimate Edition)
Build #IU-183.2407.10, built on September 12, 2018
IntelliJ IDEA EAP User
Expiration date: October 12, 2018
JRE: 1.8.0_152-release-1293-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by zolotov** [comment]
this plugin is made for building IntelliJ plugins, it has nothing to do with importing IDEA projects (it's better to ask at https://youtrack.jetbrains.com) or with generating Project model (it's better to ask at http://github.com/gradle).
