### ISSUE TITLE
NPE while composing  UI elements

### ISSUE THREAD

**Issue by sergeykad** [JetBrains/gradle-intellij-plugin#32]
I have code in constructor of a class that implements `JPanel` that calls ` add(topLevelPanel, BorderLayout.CENTER);` There is associated IDEA `form` class too.

It fails with the following error:
```
[  41285]  ERROR - plication.impl.ApplicationImpl - null
java.lang.NullPointerException
        at java.awt.Container.addImpl(Container.java:1090)
        at java.awt.Container.add(Container.java:966)
```

IDEA 13.1.6, Java 1.6

The same code worked fine then build using IDE.

**Comment by zolotov** [comment]
From #28:

> I found a workaround for the compilation error. Adding intellij.instrumentCode false solves it

From README:

> intellij.instrumentCode defines whether plugin should instrument java classes with nullability assertions. Also it might be required for compiling forms created by IntelliJ GUI designer.

**Comment by zolotov** [comment]
As a workaround you can use `source code` format for gui designer or do not use intellij gui designer at all
![Uploading Screenshot 2015-11-26 14.26.35.png…]()

**Comment by sergeykad** [comment]
Setting GUI designer to `source code` did not change anything.
How do I make IDEA to generate this source code for all the existing forms?

**Comment by zolotov** [comment]
Build | Rebuild project

**Comment by sergeykad** [comment]
Thanks. That did the trick.
