### ISSUE TITLE
Plugin should declare dependency on groovy plugin.

### ISSUE THREAD

**Issue by cblades** [JetBrains/gradle-intellij-plugin#327]
The Gradle plugin depends on the groovy plugin, and if the groovy plugin is disabled, the gradle plugin will cause run context menus to fail (and display "Nothing Here").

**Comment by zolotov** [comment]
the plugin does depend on groovy: `compile localGroovy()`

**Comment by zolotov** [comment]
> the gradle plugin will cause run context menus to fail (and display "Nothing Here").

If you're talking about IDE, it's on you to configure it. Plugin has nothing to do with any IDE, it's plugin for Gradle, not for IDE.
