### ISSUE TITLE
Multiple downloads ideaIC-LATEST-EAP-SNAPSHOT.zip 

### ISSUE THREAD

**Issue by xncHung** [JetBrains/gradle-intellij-plugin#328]
I have two intelij plugin projects and I have downloaded the ideaIC-LATEST-EAP-SNAPSHOT.zip in one project , I can find it in the .gradle cache path,but in another project ,gradle has not use that cache, it download the zip file again! it's size is more than 400M ,what should I do to tell gradle to use the cache but not download?

**Comment by zolotov** [comment]
Snapshots tend to be updated. Use fix version of you don't want to download new versions

**Comment by BorzdeG** [comment]
Is it not possible to do it like in other dependencies - check once a day? And for an online update, use the "--refresh-dependencies" parameter

**Comment by zolotov** [comment]
There are no differences from other gradle dependencies

**Comment by zolotov** [comment]
Sorry, I don’t understand why are you posting it here. ideaIC is a pure gradle dependency that is downloaded by gradle using gradle rules. This plugins doesn’t invent this rules and doesn’t even try to reimplement then

**Comment by BorzdeG** [comment]
This is rather a refinement for @xncHung to look at the configuration of your Gradle projects, in addition to what you said.

**Comment by zolotov** [comment]
Got it. Thanks for details, the link may help indeed

**Comment by xncHung** [comment]
> Snapshots tend to be updated. Use fixed version if you don't want to download new versions

I tried to tell Gradle to force a special version with this script:
```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'com.jetbrains') {
            details.useVersion '183-EAP-SNAPSHOT'
            details.because 'the zip is too big'
        }

    }
}
```
but it didn't work...

**Comment by zolotov** [comment]
To tell to use specific version you should just set intellij.version property. See the readme for details

Btw, 183-snapshot version is also a snapshot and will be updated every single day

**Comment by xncHung** [comment]
> To tell to use specific version you should just set intellij.version property. See the readme for details
> 
> Btw, 183-snapshot version is also a snapshot and will be updated every single day
thanks for reply,it has worked!
