### ISSUE TITLE
How to use a JetBrains jre from local folder instead of downloading it from BitTray?

### ISSUE THREAD

**Issue by jtonic** [JetBrains/gradle-intellij-plugin#329]
Using gradle-intellij-plugin in a restrictive environment is quite a pain.
All plugin examples from the readme.md consider that all go fine with downloading intellij idea stuff from the internet (intellij idea, jetbrains jre and specific plugins).
This is not the case when a firewall is in place.
I am trying to have all these locally, and I can say it is not an easy task at all.
For instance I have

```groovy
runIde {
    // ...
     jbreVersion "jbrex8u152b1136.29"
    // ..
}
```
and the following exception occurred when I ran gradlew runIde:
Cannot download JetBrains Java Runtime jbrex8u152b1136.29_osx_x64

Is there a way to instruct the gradle-intellij-plugin to grab the jetbrains jre from a project local path?

**Comment by zolotov** [comment]
Just set `executable` property https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html
