### ISSUE TITLE
Test events were not received

### ISSUE THREAD

**Issue by dlsniper** [JetBrains/gradle-intellij-plugin#33]
Hi, from time to time the Gradle doesn't seem to want to run the tests. Restarting IDEA seems to do the trick and tests are running again. I've checked the logs and nothing there and I'm not sure if the screenshot will help either (I'm running the Go plugin test suite, to be sure there's no confusion).
![snapshot146](https://cloud.githubusercontent.com/assets/607868/11430110/c6264292-9481-11e5-993e-9d732eb1cbc5.png)

Please let me know if I can help out with anything else.

**Comment by zolotov** [comment]
This is expected behaviour. Since you haven't changed any class `test` task is up-to-date. You can invoke `cleanTest` before to avoid this.

**Comment by jtonic** [comment]
Hi,
I encountered the same issue with junit 5 kotlin project.
And for me tests were changed but Idea prompted me with the same message.
Any clue on this?

**Comment by jtonic** [comment]
Hi,

I also noticed those:
1. If I ran the test with the junit run configuration suggested by Idea in the context many all is fine.
2. but if I ran the gradle suggested run configuration I ran into this issue no matter test files has been changed or not.

**Comment by jtonic** [comment]
I forgot to mention that I used the latest EAP version of idea which is Public Review:

IntelliJ IDEA 2017.3 EAP (Ultimate Edition)
Build #IU-173.3415.22, built on October 25, 2017
IntelliJ IDEA EAP User
Expiration date: November 24, 2017
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13

I think this issue has to be reopen for idea 2017.3, junit 5, gradle, kotlin.

**Comment by zolotov** [comment]
@jtonic this tracker has nothing to do with IDEA. Please use https://youtrack.jetbrains.com.

Also, probably the issue also has nothing to do with IDEA and I recommend you to check whether Gradle task works as expected in a terminal first.

**Comment by jtonic** [comment]
@Zoltov.

Thank you for your reply.
I am going to register this (if it isn't already) in youtrack.
With the ./gradlew command everything is fine.

Kind regards.

**Comment by JamesXNelson** [comment]
Seeing strange behavior along the same lines over here...

The same code on a different machine runs np every time.
We even altered the generated test run config to run `clean` and `cleanTest` before running.

The _gradle daemon logs show the test being run_, along w/ a bunch of `<ijLog>` entries, clearly showing all the tests being run.  However, the IDE just spins until it's over, no output, and then claims "test events not received".

```
<ijLog><event type='beforeSuite'><ijLogEol/>
  <test id='2.1' parentId=':Blah:test'><ijLogEol/>
    <descriptor name='Gradle Test Executor 2' className='' /><ijLogEol/>
  </test><ijLogEol/>
</event></ijLog>
```

**Comment by JamesXNelson** [comment]
Should I open a new issue (and should it be in this tracker?)

**Comment by zolotov** [comment]
@JamesXNelson this project is about `gradle-intellij-plugin`, if you don't use it, it's a wrong tracker. If you use, I need your build.gradle and all configuration related to `gradle-intellij-plugin`.

**Comment by JamesXNelson** [comment]
ok, this is indeed the wrong tracker.  thanks, and sorry for the noise.
