### ISSUE TITLE
Way to change default vm options?

### ISSUE THREAD

**Issue by linbaiye** [JetBrains/gradle-intellij-plugin#331]
Hi there,
How can I change default vm options when starting IDE, I put an option into the build.gradle file hoping to overwrite the original one of apple.laf.useScreenMenuBar like this:

runIde {
    jvmArgs '-Djdk.util.zip.ensureTrailingSlash=false -Dapple.laf.useScreenMenuBar=false'
}

However I got two options: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin/java **-Dapple.laf.useScreenMenuBar=true** -Didea.classpath.index.enabled=false -Didea.config.path=/Users/lintao/Work/idea-projects/yobatis-idea/build/idea-sandbox/config -Didea.is.internal=true -Didea.platform.prefix=Idea -Didea.plugins.path=/Users/lintao/Work/idea-projects/yobatis-idea/build/idea-sandbox/plugins -Didea.required.plugins.id=org.nalby -Didea.smooth.progress=false -Didea.system.path=/Users/lintao/Work/idea-projects/yobatis-idea/build/idea-sandbox/system -Djdk.util.zip.ensureTrailingSlash=false **-Dapple.laf.useScreenMenuBar=false**

and I doubt that the vm still sets apple.laf.useScreenMenuBar as true, what should I do to delete the original option?

**Comment by zolotov** [comment]
Answered on the forum, likely you're using old version of the `gradle-intellij-plugin`

**Comment by linbaiye** [comment]
Hi zolotov, much appreciate.
