### ISSUE TITLE
Exclude some IDEA jar files

### ISSUE THREAD

**Issue by Undin** [JetBrains/gradle-intellij-plugin#333]
Is there a convenient way to exclude some jar files (which come from IDEA distribution) from project dependencies?
Use case: IntelliJ Rust is supposed to work not only in IDEA but in CLion too. Default set of IDEA dependencies brings `parentOfType` extension method declared in `java-impl.jar`. As expected using it leads to `NoClassDefFoundError` outside of IDEA (for example, in CLion) because CLion doesn't contain `java-impl.jar`. At the same time, we have to compile with IDEA because we have some code only for IDEA.

It's rather hard to catch using of such methods while code writing and review especially for external contributors. 

Of course, we can find such jars in classpath and exclude them manually
For example, in this way
```kotlin
afterEvaluate {
    val mainSourseSet = sourceSets.getByName("main")
    val mainClassPath = mainSourseSet.compileClasspath
    val excludedJars = mainClassPath.filter { it.name == "java-impl.jar" || it.name == "java-api.jar" }
    mainSourseSet.compileClasspath = mainClassPath - excludedJars
}
```
But it not convenient because IDEA doesn't "understand" these excludes and thinks that these jars are still in dependencies and suggests items from them while completion. So I can find out that I use wrong methods only after compilation

**Comment by zolotov** [comment]
You can disable adding any intellij jars via `intellij.configureDefaultDependencies` and use `intellijPlugin` or `intellijPlugin` functions in `dependencies` block. But these are not documented features and may be changed in any future versions.

see https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/groovy/org/jetbrains/intellij/IntelliJPlugin.groovy#L124
