### ISSUE TITLE
Force Gradle to run tests when building plugin?

### ISSUE THREAD

**Issue by breandan** [JetBrains/gradle-intellij-plugin#339]
How do I force Gradle to run tests when building the plugin? For example with `RunIdeTask`, the following is possible in the Kotlin DSL:

```
withType<RunIdeTask> {
  dependsOn("test")
}
```

But there is no `BuildIdeTask`? I would have thought that `RunIdeTask` would depend on `BuildPluginTask`, but apparently this is not the case?

**Comment by zolotov** [comment]
You can refer the task by name, not by type. I know nothing about kotlin dsl but I'm sure you can find in the documentation how to do it

**Comment by breandan** [comment]
Makes sense, thanks! If anyone else has this issue, the correct syntax is:

```
tasks.named("buildPlugin") {
  dependsOn("test")
}
```
