### ISSUE TITLE
Support Grammar-Kit 

### ISSUE THREAD

**Issue by iviews-ja** [JetBrains/gradle-intellij-plugin#34]
Support for Grammar-Kit (https://github.com/JetBrains/Grammar-Kit) would be wonderful :) 
If would support plugin development and building If the gradle plugin used my grammar-kit and jflex files to generate the lexer and parser :)

**Comment by zolotov** [comment]
If I implemented it in plugin, you still needed to configure bnf and flex files. I don't think that it will be shorter than creating generate tasks on client's side.

**Comment by iviews-ja** [comment]
I see. For me it would be faster to use configure two files instead of googling and experimenting how to tell gradle to generate source code from the grammar and to tell jflex to generate the lexer code. As you can see I have no idea of gradle but love the plugin build automation :)
Close the issue if you think it should be solved by plugin authors...

**Comment by zolotov** [comment]
Ok, thanks. I'll think about it

**Comment by Turbo87** [comment]
I guess it would not be a bad idea to have support for Grammar-Kit in some plugin, but I don't think it should be **this** plugin. It's easy to use multiple plugins in Gradle and having a dedicated Grammar-Kit plugin sounds like a good idea also for use-cases outside of IntelliJ plugins.

**Comment by sjamesr** [comment]
@zolotov it would be nice to be able to run the GrammarKit parser generator as part of continuous integration (without having to check in the generated files). Apparently there are already plugins to use JFlex from Gradle, so that could be outside the scope of this plugin.

**Comment by zolotov** [comment]
@sjamesr indeed, I still think that it could be part of some other plugin.

**Comment by mplushnikov** [comment]
+1 for this functionality. 
I is very annoying to figure out how to setup multiple gradle task to generate Parser and Lexer classes

**Comment by matklad** [comment]
Here is [how we execute] Jflex and Grammar Kit as a part of build of intellij-rust.

[how we execute]: https://github.com/intellij-rust/intellij-rust/blob/9826d047c329ce5cf7ec924676dc872da9a9f15d/build.gradle#L122-L158

Unfortunately Grammar Kit is not published on maven, so we have to commit `grammar-kit.jar` to the repository.

**Comment by jonnyzzz** [comment]
Running a grammar kit from gradle (maybe as additional plugin) looks good to make it easier to bootstrap a new plugin
+1

**Comment by matklad** [comment]
There's https://github.com/hurricup/gradle-grammar-kit-plugin now :tada:
