### ISSUE TITLE
Could not download ideaIC.zip

### ISSUE THREAD

**Issue by XieEDeHeiShou** [JetBrains/gradle-intellij-plugin#345]
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'warning-as-error'.
> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Could not download ideaIC.zip (com.jetbrains.intellij.idea:ideaIC:LATEST-EAP-SNAPSHOT)
      > Could not get resource 'https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/LATEST-EAP-SNAPSHOT/ideaIC-LATEST-EAP-SNAPSHOT.zip'.
         > Read timed out
```

I'm planing to develop a plugin, so I create a gradle, java, IntelliJ plugin project. Then it generate a build.gradle file which applying this gradle plugin, and I wait for a long time to init the project, finaly, it told me `Read timed out`.
The default setting seems to be un-suitable for everyone (look around the issues, there are many of them plain about this), the essential dependency should be published to other public repository, or make your repository server more avaliable to us.
And since the gradle plugin is add by you (IDEA), it's your responseblity to add more comment to told user how to config it or where the document is in the build.gradle file, but you didn't.

I've configed the localPath as a workaround now, but, that is just a workaround.

**Comment by zolotov** [comment]
What exactly you’re suggesting to change in the plugin? What exactly the settings doesn’t fit for you or any other user?

**Comment by XieEDeHeiShou** [comment]
~Sorry, I just cannot download the fat zip dependency success even one time.~
Before I reply this comment, I add `114.114.114.114` and `8.8.8.8` as primary and secondary DNS server, then tried again on my personal computer in my home. Finally download `ideaIC-2018.3.2` and `ideaIc-LATEST-EAP-SNAPSHOT` success, it takes 9 minute and 27 second for gradle to finish build.

<br/>

> What exactly you’re suggesting to change in the plugin? 

Can you please split that fat zip to a collection of small files? By this, we could only download missing files one by one rather than a huge file one time.
I see the biggest zip under ${IDEA_HOME}/lib is nearly 90+Mb, still much smaller than 400+Mb. I mean, it's more easier to retry even download fail.

>  What exactly the settings doesn’t fit for you or any other user?

I was pretend to say that you didn't left the chance for user to config which repository to use, then I see [extension.intellijRepo](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/groovy/org/jetbrains/intellij/IntelliJPlugin.groovy#L164) is not mentioned in README, I was wrong. Please document it to README.

**Comment by zolotov** [comment]
> Can you please split that fat zip to a collection of small files? By this, we could only download missing files one by one rather than a huge file one time.

We're splitting it into dedicated maven artifacts and already extracted some of the core parts. When we finish, it will the end of this plugin, because after that you'll be able to build IntelliJ plugin using pure Gradle.
Unfortunately, it will take a lot of time to split entire IDEA into separate dependencies.

> I was pretend to say that you didn't left the chance for user to config which repository to use, then I see extension.intellijRepo is not mentioned in README, I was wrong. Please document it to README.

ok

**Comment by m1a0yu3** [comment]
@zolotov any update？

**Comment by zolotov** [comment]
@m1a0yu3 on what? Please read the comments

**Comment by Nicksxs** [comment]
@zolotov  could i download it myself，and put it to the right place,
but i need to know the directory to put
