### ISSUE TITLE
Bundled plugins sources won't get attached automatically

### ISSUE THREAD

**Issue by Camork** [JetBrains/gradle-intellij-plugin#346]
I found the Changed.md had fixed this issuse, but not work actually (build with the lastest code)

**Comment by Camork** [comment]
IU-2018.3.2 and IC-2018.3.2 get same result.

**Comment by zolotov** [comment]
What version of the plugin?

**Comment by Camork** [comment]
0.5 snapshot, i also tried the plugin built from master branch.

**Comment by zolotov** [comment]
try to remove `~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/plugins.jetbrains.com/*.xml` files. Does it help?

**Comment by Camork** [comment]
Not work, are you sure this work in your side?
#### Reproduce steps:
A gradle project with build.gradle:
````
buildscript {
    dependencies {
        classpath "org.jetbrains.intellij.plugins:gradle-intellij-plugin:0.4.0"
    }
    repositories {
        mavenLocal()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
}

plugins {
    id 'java'
}

apply plugin: "org.jetbrains.intellij"

intellij {
    plugins  "gradle", "Groovy", "java-i18n","junit", "maven","properties"
    version "IC-2018.3.2"
}

````
After refresh gradle project in Intellij Idea and go to Project structure, in Modules ->Dependencies Tab, 
double click `Gradle: com.jetbrains:ideaIC:2018.3.2` and it has a `Sources` column linked to `./gradle/cache/**`, 
but double click `Gradle: unzipped.com.jetbrains.plugins:gradle:unzipped.com.jetbrains.plugins:ideaIC-2018.3.2-withSources`, no Sources tab here.

Then i tried to use Gradle tooling api to look inside:
Groovy script:
````
import org.gradle.tooling.GradleConnector
import org.gradle.tooling.ProjectConnection
import org.gradle.tooling.model.GradleModuleVersion
import org.gradle.tooling.model.idea.IdeaProject

ProjectConnection connection = GradleConnector
		.newConnector()
		.forProjectDirectory(new File("Your plugin project"))
		.connect()

try {
	IdeaProject project = connection.getModel(IdeaProject.class)
	project.getModules().each {
		it.dependencies.each {
			GradleModuleVersion moduleVersion = it.gradleModuleVersion
			if (moduleVersion != null) {
				System.out.println("$moduleVersion.group:$moduleVersion.name")
				System.out.println(it.source)
			}
		}
	}
} finally {
	connection.close()
}
````

Output fragment: 
````
com.jetbrains:ideaIC
C:\Users\liferay\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2018.3.2\a342a5dfa3b2e721e5edbdbc140163c4e16f7fac\ideaIC-2018.3.2-sources.jar
unzipped.com.jetbrains.plugins:gradle
null
unzipped.com.jetbrains.plugins:Groovy
null
````

**Comment by zolotov** [comment]
recreated and fixed. please wait for 0.4.1, I think it will take an hour to deploy it

**Comment by Camork** [comment]
Thanks, it works 👍
