### ISSUE TITLE
Allow for sources to be downloaded for non-bundled plugins

### ISSUE THREAD

**Issue by abrooksv** [JetBrains/gradle-intellij-plugin#349]
Python Community Edition is technically open source as well as other non-bundled plugins (Scala, Android, etc). It would be nice to be able to get the sources for these as well.

Can publishPlugin allow for opt-ing into uploading source artifact as well and extending the plugin repository Maven interface to support source classifiers?

(I know this is beyond scope of what is capable right now, but wanted to attack this from the gradle side first to get your opinion before opening YouTrack for the update site)

**Comment by abrooksv** [comment]
Related YT: https://youtrack.jetbrains.com/issue/MP-2182

**Comment by YannCebron** [comment]
https://youtrack.jetbrains.com/issue/MP-2787

**Comment by YannCebron** [comment]
solved by #786
