### ISSUE TITLE
Ivy repository is not updated for SNAPSHOT builds

### ISSUE THREAD

**Issue by artspb** [JetBrains/gradle-intellij-plugin#354]
There's an internal Ivy repository for IDEA and its plugins. If a SNAPSHOT version of IDEA is used the repository is not updated even though libraries can have different versions in different builds. The only workaround I found is to remove `~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea`.

**Comment by zolotov** [comment]
I think the diagnose is wrong: ivy repo is store inside the unpacked IDEA dependency, as soon as a snapshot is updated, there is be ivy repo from the previous version.
Please provide exact steps to recreate the issue

**Comment by artspb** [comment]
>this is also not true, there are many ivy repositories for each IDEA version and each plugin

Yes, the problem is that 191-SNAPSHOT is a single version so the repo is not updated when the content of the snapshot is changed. I'll provide the steps ASAP.

**Comment by zolotov** [comment]
> Yes, the problem is that 191-SNAPSHOT is a single version so the repo is not updated when the content of the snapshot is changed.

As I said, it's stored inside unpacked IDEA. If the dependency changed, the entire repo is removed.

> I'll provide the steps ASAP.

Looking forward to.

**Comment by artspb** [comment]
Steps to reproduce:
1. Use IDEA Ultimate 191-SNAPSHOT (191.2597) with DatabaseTools which include `dekaf-single-2.0.0.386.jar`.
2. Run build, everything works.
3. Update IDEA on a server to 191.3731 where DatabaseTools use `dekaf-single-2.0.0.387.jar`.
4. Run build, get `Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find lib/dekaf-single-2.0.0.386-unzipped.com.jetbrains.plugins.jar (unzipped.com.jetbrains.plugins:DatabaseTools:ideaIU-191-SNAPSHOT).`

My investigation showed that `~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins/DatabaseTools-ideaIU-191-SNAPSHOT-withSources.xml` contained the old versions of the livarary (`dekaf-single-2.0.0.386.jar`) while on a disk there was already the new one (`dekaf-single-2.0.0.387.jar`). Removing this file helped as it was re-created with a proper version. But of course this diagnose can be wrong.

I was able to reproduce it both locally and on TeacmCity (I can provide you with appropriate builds).

**Comment by zolotov** [comment]
Ah, so the problem in builtin plugins repositories. It does make sense now. Not easy to fix though

**Comment by zolotov** [comment]
@artspb could you please test the next SNAPSHOT verison?

**Comment by artspb** [comment]
Sure, will do.

**Comment by artspb** [comment]
Works like a charm, thanks.
