### ISSUE TITLE
Plugin id with space

### ISSUE THREAD

**Issue by matkoch** [JetBrains/gradle-intellij-plugin#357]
The plugin id for the [TeamCity plugin](https://plugins.jetbrains.com/plugin/1820-teamcity) is `Jetbrains TeamCity Plugin`. This seems to cause issues. I believe so because I don't have issues resolving any other plugin.

Output is:

```
Could not GET 'https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-plugin-service/com/jetbrains/plugins/Jetbrains%20TeamCity%20Plugin/2018.2.60977/Jetbrains%20TeamCity%20Plugin-2018.2.60977.pom'.
Enable Gradle 'offline mode' and sync project
```

**Comment by zolotov** [comment]
it's not supposed to be found in https://cache-redirector.jetbrains.com/jetbrains.bintray.com. Please show your build.script

**Comment by matkoch** [comment]
https://github.com/nuke-build/resharper/blob/feature/teamcity/build.gradle

**Comment by zolotov** [comment]
fixed by @shalupov on the server side
