### ISSUE TITLE
JBRE version not detected when using alternativeIdePath (MacOS)

### ISSUE THREAD

**Issue by utikeev** [JetBrains/gradle-intellij-plugin#358]
I'm developing plugin for PyCharm and stumbled onto the next problem. When I use `alternativeIdePath` it runs PyCharm under the system JVM. That, for example, leads to non-working menu.
I looked up into the code of the plugin and found that the JBRE version is detected via looking the parameter `jdkBuild` in file `dependencies.txt` in the root folder of IDE ([link to the method](https://github.com/JetBrains/gradle-intellij-plugin/blob/3c68a8bd7c/src/main/groovy/org/jetbrains/intellij/Utils.groovy#L248)).
I opened that folder and there was no such file. After its creation manually with the content:
```
jdkBuild=jbrex8u152b1343.26
```
PyCharm opened using the correct JVM.

OS: MacOS Mojave 10.14.2
PyCharm is installed via JetBrains Toolbox. Maybe it has something to do with the way IDE's are installed on Mac or with the Toolbox installation?

**Comment by zolotov** [comment]
good catch, thanks

> After its creation manually with the content:

The more appropriate workaround is to set this version in your `build.gradle`:

```
runIde { jbreVersion 'jbrex8u152b1343.26' }
```

**Comment by utikeev** [comment]
Yeah, I also have tried this one, it also works :)

**Comment by abrooksv** [comment]
Is there a website akin to https://www.jetbrains.com/intellij-repository/snapshots to see the latest version number of JBRE?

**Comment by zolotov** [comment]
@abrooksv https://bintray.com/jetbrains/intellij-jdk
