### ISSUE TITLE
Avoid IDEA downloading while importing gradle project

### ISSUE THREAD

**Issue by zolotov** [JetBrains/gradle-intellij-plugin#36]

**Comment by YannCebron** [comment]
duplicate of #123?

**Comment by zolotov** [comment]
Not exactly. I'm not even sure it's possible to implement. We cannot avoid downloading while importing as in this case you'll get a project with a lot of red code because of missing dependencies. Probably, the idea was to avoid modal downloading process while opening the project, I'm not sure whether it's still the case.

**Comment by YannCebron** [comment]
gradle import is not modal anymore

**Comment by zolotov** [comment]
thanks. I think it can be closed then
