### ISSUE TITLE
inconsistent compile classpath across hosts

### ISSUE THREAD

**Issue by wisechengyi** [JetBrains/gradle-intellij-plugin#366]
Some sample build scan comparison showing the order is inconsistent: builds came from different hosts on the same SHA. This causes users to miss the remote cache.
![screen shot 2019-02-09 at 3 19 20 pm](https://user-images.githubusercontent.com/596358/52527491-19b05a00-2c7e-11e9-9c7f-f18aa6130ae9.png)

So we are using the following to work around the issue:
```
afterEvaluate {
    sourceSets.main.compileClasspath = files(sourceSets.main.compileClasspath.sort())
}
```

Our relevant usage:
```
    intellij {
        version 'IC-2017.1'
        downloadSources true
        updateSinceUntilBuild false
        sameSinceUntilBuild false
    }
```

**Comment by zolotov** [comment]
Hi,

Please attach the content of `~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.1/<hash>/ideaIC-2017.1/ideaIC-2017.1-withKotlin-withSources.xml` that are created on both machines

**Comment by zolotov** [comment]
closing due to lack of feedback
