### ISSUE TITLE
IC sources not attached for IU classes

### ISSUE THREAD

**Issue by Turbo87** [JetBrains/gradle-intellij-plugin#37]
I'm using this plugin with the IU version because I depend on the Javascript plugin. The IU jar files are included when I open the project in IntelliJ, but the IC source files that get downloaded alongside the IU classes are not attached properly. Whenever I refresh the Gradle model I have to attach the sources manually, which quickly gets annoying. It would be awesome if there was a way in which the plugin would handle this for me.

**Comment by zolotov** [comment]
Should work. What version of IDEA do you use and what version of IU do you use?

**Comment by Turbo87** [comment]
https://github.com/Turbo87/intellij-emberjs/blob/master/build.gradle#L27

and I use the latest EAP of IntelliJ Ultimate (15.0.2 RC) for working on the project.

**Comment by Turbo87** [comment]
awesome, thanks!

**Comment by Turbo87** [comment]
@zolotov it seems that with a recent update to v0.2.12 of this plugin the automatic attachment/download of IC sources for IU stopped working again. any ideas how to fix this?

**Comment by Turbo87** [comment]
nevermind, I was being stupid... 🙈
