### ISSUE TITLE
Startup Error: Unable to detect graphics environment

### ISSUE THREAD

**Issue by breandan** [JetBrains/gradle-intellij-plugin#375]
When running `./gradlew buildPlugin` inside Docker on [this project](https://github.com/duckietown/hatchery), I receive an error, [`Startup Error: Unable to detect graphics environment`](https://gist.github.com/breandan/a2df257f75d755efe6e6c212af8066ee) as described in #368. Although `build/idea-sandbox/system/log` does not exist [as suggested](https://github.com/JetBrains/gradle-intellij-plugin/issues/368#issuecomment-471272658) by @artspb, [here](https://gist.github.com/breandan/372217b81d5fce5e3a563e0a30628b62) are the contents of `build/idea-sandbox/system-test/testlog/idea.log`. 

To reproduce, run the following command:

```
git clone git@github.com:duckietown/hatchery.git && \
cd hatchery && \
git checkout 94e9a33a35e23241198cd5f799b0e548b40b523b && \
docker build -t hatchery .
```

**Comment by breandan** [comment]
I am was able to fix this issue [by downgrading](https://github.com/duckietown/hatchery/commit/c28e408e2dc54076636def2d139cbb0c75b6dffb) to version [`0.4.0`](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/CHANGES.md#040) of the gradle-intellij-plugin.

**Comment by zolotov** [comment]
@breandan you can just disable buildSearchableOptions task, that's the entire workaround

**Comment by artspb** [comment]
@breandan Thank you for the reproducible case, I found the cause. It's possible to override arguments of `buildSearchableOptions` via the `runIde` task (see [here](https://github.com/duckietown/hatchery/blob/master/build.gradle.kts#L116)). It's definitely a bug, I'll look how to fix it.

**Comment by artspb** [comment]
In the meantime, you can do `tasks.findByName("runIde")` instead of `tasks.withType<RunIdeTask>`.
