### ISSUE TITLE
Support naming ZIP artifact for :buildPlugin task

### ISSUE THREAD

**Issue by breandan** [JetBrains/gradle-intellij-plugin#377]
It would be nice to specify the name of the ZIP file produced by `:buildPlugin`. A few versions ago, it simply produced a `<plugin_name>.zip` artifact in the `build/libs` directory, but now it appends the version number at the end of the filename, which breaks TeamCity's [pattern for accessing build artifacts](https://confluence.jetbrains.com/display/TCD9/Patterns+For+Accessing+Build+Artifacts). It would be nice to override this behavior with a property like `artifactName = "/somedirectory/somename.zip"`. Otherwise, I guess it is possible to copy the file in a new Gradle task.

**Comment by zolotov** [comment]
`buildPlugin` is a ZipTask, you free to set any output name according to ZipTask documentation

**Comment by zolotov** [comment]
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Zip.html

**Comment by breandan** [comment]
I see, thank you!
