### ISSUE TITLE
Could not find com.jetbrains.intellij.idea with specific intellij.version

### ISSUE THREAD

**Issue by Flanker32** [JetBrains/gradle-intellij-plugin#378]
Can't find the idea with specific build version(like 191.6183.62), though it could work when intellij.version was set to  'LATEST-EAP-SNAPSHOT'.

Gradle plugin version : 0.4.5

```
   > Could not find com.jetbrains.intellij.idea:ideaIC:191.6183.62.
     Searched in the following locations:
       - file:/jenkinshome/jenkins/workspace/Azure_Toolkits_for_Java/AzureToolsManager_PR/.repository/com/jetbrains/intellij/idea/ideaIC/191.6183.62/ideaIC-191.6183.62.pom
       - file:/jenkinshome/jenkins/workspace/Azure_Toolkits_for_Java/AzureToolsManager_PR/.repository/com/jetbrains/intellij/idea/ideaIC/191.6183.62/ideaIC-191.6183.62.jar
       - file:/var/lib/jenkins/.m2/repository/com/jetbrains/intellij/idea/ideaIC/191.6183.62/ideaIC-191.6183.62.pom
       - file:/var/lib/jenkins/.m2/repository/com/jetbrains/intellij/idea/ideaIC/191.6183.62/ideaIC-191.6183.62.jar
       - https://repo.maven.apache.org/maven2/com/jetbrains/intellij/idea/ideaIC/191.6183.62/ideaIC-191.6183.62.pom
       - https://repo.maven.apache.org/maven2/com/jetbrains/intellij/idea/ideaIC/191.6183.62/ideaIC-191.6183.62.jar
       - https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/191.6183.62/ideaIC-191.6183.62.pom
       - https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/191.6183.62/ideaIC-191.6183.62.jar
```

**Comment by zolotov** [comment]
it should not be there, it's not the release. You can use `191.6183.62-EAP-SNAPSHOT` though

**Comment by Eskibear** [comment]
> it should not be there, it's not the release. You can use `191.6183.62-EAP-SNAPSHOT` though

It doesn't convince me. As mentioned in the [READE DSL section](https://github.com/JetBrains/gradle-intellij-plugin#setup-dsl), the `version` also accepts `build#` and `version#`. And previous EAP builds worked. See below:

This one doesn't work:
https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/191.6183.62/ideaIC-191.6183.62.pom

This one works:
https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/191.4212.41/ideaIC-191.4212.41.pom

So has there been any change of the publishing location?

**Comment by Eskibear** [comment]
@zolotov Is the README out-of-date?

**Comment by zolotov** [comment]
I'm not trying to convince you about anything. Yes, the `version` accepts build number but there is no IDE release with 191.6183.62 build number. That's just the fact.

**Comment by Eskibear** [comment]
Thank you @zolotov for articulation. Suggest to add example `191.6183.62-EAP-SNAPSHOT` in README, to eliminate confusion.

@Flanker32 Just use `191.6183.62-EAP-SNAPSHOT` as suggested.
