### ISSUE TITLE
CL-191.6183.77 sources

### ISSUE THREAD

**Issue by goodandrewsoft** [JetBrains/gradle-intellij-plugin#381]
Where get sources for CL-191.6183.77 ?

**Comment by goodandrewsoft** [comment]
Also, how increase -Xmx in [this](https://github.com/JetBrains/gradle-intellij-plugin/blob/84223bd6455305a92eb6aa92b517a1e0d55fe988/src/main/groovy/org/jetbrains/intellij/Utils.groovy#L107)

**Comment by zolotov** [comment]
CLion is the closed-sources product.

> Also, how increase -Xmx in this

See [FAQ](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/FAQ.md#how-to-modify-jvmarguments-of-runide-task)
