### ISSUE TITLE
Use pluginManager API to resolve plugins versions from repository

### ISSUE THREAD

**Issue by AmailP** [JetBrains/gradle-intellij-plugin#386]
By making use of the `pluginManager` API, similarly to what is already done [in the `sbt-idea-plugin`](https://github.com/JetBrains/sbt-idea-plugin/blob/master/src/main/scala/org/jetbrains/sbtidea/tasks/download/IdeaPluginResolver.scala) it would be possible to make optional the version parameter of the `plugins` string, e.g.:
`org.plugin.id[:version][@channel]`

**Comment by zolotov** [comment]
It's not clear. how version is this supposed to be optional? what is `pluginManager` API? never heard of this

**Comment by AmailP** [comment]
Please have a look at the provided link:
https://github.com/JetBrains/sbt-idea-plugin/blob/master/src/main/scala/org/jetbrains/sbtidea/tasks/download/IdeaPluginResolver.scala

The API used is the following:
`https://plugins.jetbrains.com/pluginManager`

Basically it seems to give the correct plugin for a given version of the IDE `build=IC-xx.yyyy`

**Comment by zolotov** [comment]
Ah, got it. Sorry, not in the plan, this approach (using the random version of dependencies) will make builds unstable, this is not what I'd like to see in the plugin.

**Comment by AmailP** [comment]
Hey @zolotov,

fair enough that the default should be a stable version.

Nevertheless I think that having the possibility of specifying a version label (e.g. `org.plugin.id:LATEST`) to get an automatic version would be a nice feature, especially in the early development phase of a plugin.

**Comment by zolotov** [comment]
> especially in the early development phase of a plugin.

You set a dependency on IDE version and on plugin version. That's it. Your plugin should not be affected by actions of others like updating the dependency. It doesn't matter what phase your plugin is in.

> It is actually very similar to the support that the gradle-intellij-plugin has already for LATEST-EAP-SNAPSHOT.

You're right. And I don't like `LATEST-EAP-SNAPSHOT` as well for the same reason. I'd rather remove this version than add one more instability factor.
