### ISSUE TITLE
JetBrains Annotations runtime instrumentation only?

### ISSUE THREAD

**Issue by NoICE** [JetBrains/gradle-intellij-plugin#387]
Hello, is there any way to use this plugin's instrumentation capabilities - runtime checks for org.jetbrains.annotations.NotNull/Nullable annotations as a gradle plugin only?

If I add this to my build.gradle:

```groovy
plugins {
    id "org.jetbrains.intellij" version "0.3.9"
}

intellij {
    instrumentCode = true
    downloadSources = false
}
```

it should provide these assertions automatically, right?
But this also downloads 400MB jar. I want to build smallest jar possible for docker container.
I don't want to download the whole idea just for null assertions. Is there any way to use only the code instrumentation part?

**Comment by zolotov** [comment]
Not with this plugin, but you can implement your own plugin. See `IntelliJInstrumentCodeTask`, it doesn't need to download 400 MB.

> But this also downloads 400MB jar. I want to build smallest jar possible for docker container.

I didn't understand this one. Downloading 400 MB doesn't affect the size of you target jar.

**Comment by NoICE** [comment]
> Not with this plugin, but you can implement your own plugin. See `IntelliJInstrumentCodeTask`, it doesn't need to download 400 MB.

Thank you, I'll take a look.

> 
> > But this also downloads 400MB jar. I want to build smallest jar possible for docker container.
> 
> I didn't understand this one. Downloading 400 MB doesn't affect the size of you target jar.

Yes, it doesn't affect your target jar if you use multistage builds (which I do).
But if you change your build.gradle, you invalidate docker cache and the whole 400MB needs to be downloaded again to that docker layer. (Without using extra docker volumes for gradle cache and/or extra jar cache proxies.)

**Comment by zolotov** [comment]
Got it. Then yes, try to extract instrumentation task into another plugin, it should work just fine for new versions of IDE

**Comment by Frederik-Baetens** [comment]
Hi, should this still work? I tried adding the snippet as above to the build.gradle of one of my subprojects, and made sure assertions are enabled, but i get no error/failed assertions when putting `@NotNull Window hi = null;` in code that i know that executes.

**Comment by zolotov** [comment]
> Hi, should this still work?

yes

```
@NotNull Window hi = null; `
```

@Frederik-Baetens the snippet looks senseless to me, I cannot imagine how it can possibly be instrumented. Check it with parameter/return annotation.

**Comment by Frederik-Baetens** [comment]
Thank you so much, checking return values does work!
