### ISSUE TITLE
Gradle-intellij-plugin 0.4.7 not compatible with Gradle 5.4-rc1

### ISSUE THREAD

**Issue by cesar1000** [JetBrains/gradle-intellij-plugin#388]
Gradle 5.4-rc1 updated [IvyDescriptorFileGenerator](https://github.com/gradle/gradle/blob/master/subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publisher/IvyDescriptorFileGenerator.java#L80) again in 5.4-rc1, causing the configuration of the plugin to fail.

**Comment by zolotov** [comment]
thanks
