### ISSUE TITLE
Graceful handling of 404 errors when publishing a new plugin

### ISSUE THREAD

**Issue by yole** [JetBrains/gradle-intellij-plugin#389]
Right now, if you try to upload a new plugin, you get a 404 error with three screenfuls of HTML and no clue how to proceed. The plugin should detect this situation and inform the user that the plugin needs to be uploaded manually (and provide instructions how to do that).

**Comment by zolotov** [comment]
relates to https://github.com/JetBrains/plugin-repository-rest-client/issues/11

**Comment by gilday** [comment]
This just helped me out - thanks!
