### ISSUE TITLE
IU evaluation period not reset after deleting sandbox

### ISSUE THREAD

**Issue by Turbo87** [JetBrains/gradle-intellij-plugin#39]
I think I've read somewhere that deleting the sandbox should reset the evaluation period of IntelliJ Ultimate. It seems to partly work as the splash screen is actually showing a new date 30 days in the future, but once the application started it complains that the evaluation period has expired and quits immediately.

This is not a big issue since I have an open source license for IU, but it is certainly annoying having to enter the activation code over and over again after removing the sandbox for other reasons.

**Comment by zolotov** [comment]
Well, it's kind of by design. Sandbox is a place where all settings are stored, including licensing information, I don't think that it could be fixed in any way. The question is what're the reasons of removing sandbox?

**Comment by Turbo87** [comment]
I guess it's related to #19. But then again if the sandbox includes the licensing information why is IU still quitting on me when I clean the sandbox?

**Comment by zolotov** [comment]
Don't know. Will investigate, thanks for report.

**Comment by zolotov** [comment]
Cannot recreate, manual removing `build/idea-sandbox` directory resets evaluation period for me.

**Comment by Turbo87** [comment]
@zolotov on the splash screen it also looks like the evaluation period is renewed, but after a few seconds the IDE then complains again about it being expired. This is on OSX with IntelliJ Ultimate 15 if it matters.

**Comment by zolotov** [comment]
@Turbo87 ok, will try to investigate it deeper :)

**Comment by Turbo87** [comment]
I've not been able to reproduce this anymore lately. I'll reopen if I hit it again.

**Comment by zolotov** [comment]
Ok, thanks for update

**Comment by makepanic** [comment]
Hi,
I'm seeing the same issue when trying to run `gradlew runIdea` in the [intellij-emberjs](https://github.com/Turbo87/intellij-emberjs) repo.
I've previously ran it around 6/28/17 and it worked back then.
I guess the EAP license coudln't renew and simply expired.

I've alreay tried to delete the sandbox directory, gradle cache and git repo but nothing worked.
I have a valid ultimate key which i also tried to copy into the sandbox directory but it sadly didn't work.

See the screenshot on what appears after I run `gradlew runIdea`

![20171016-201049](https://user-images.githubusercontent.com/1205444/31629301-809a8808-b2b3-11e7-8ce0-174d671fba92.png)

Are there any additional location where the sandbox EAP stores data?

**Comment by zolotov** [comment]
@makepanic Hi! It's not the same issue. You're using EAP, which is expired (not your license, but EAP). You should switch to the newer EAP or to release build.

**Comment by Turbo87** [comment]
Right, that makes sense. What expiration date do the EAP builds have?

**Comment by zolotov** [comment]
@Turbo87 30-60 days usually. Do you think you faced the same issue? I didn't realize back then that it might be an expired EAP :)

**Comment by makepanic** [comment]
Thank you 👍 
Using the latest versions fixed my issue.

**Comment by Turbo87** [comment]
I think it was something unrelated, but I'm not really sure. Great to see this resolved anyway. :)
