### ISSUE TITLE
Fatal error building searchable options

### ISSUE THREAD

**Issue by ice1000** [JetBrains/gradle-intellij-plugin#394]
I'm building my project on AppVeyor CI, where I can stably reproduce a fatal error. These are the recent build logs:

+ https://ci.appveyor.com/project/ice1000/intellij-owo/builds/24773545
+ https://ci.appveyor.com/project/ice1000/intellij-owo/builds/24773286

I suppose it's related to the new 2019.2 IntelliJ platform.
I don't know much about this, but it just happened.

I can build fine locally using 2019.1

**Comment by zolotov** [comment]
from the log:

> I suppose it's related to the new 2019.2 IntelliJ platform.

Why? 2019.2 is not available for external users (it wasn't when you created the issue at least).

from the logs:

```
# An error report file with more information is saved as:
# C:\Users\appveyor\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\LATEST-EAP-SNAPSHOT\1d66e6ca8e5aa855c0e5c45b0596d7a72bd5fe4f\ideaIC-LATEST-EAP-SNAPSHOT\bin\hs_err_pid108.log
```

Have you looked at it?

**Comment by ice1000** [comment]
I cannot open the logs ATM, but I'll try (by adding that file as an artifact).

**Comment by ice1000** [comment]
> Why? 2019.2 is not available for external users (it wasn't when you created the issue at least).

Nope. Without a `version` specified, gradle will download 2019.2 IDEA on CIs.

**Comment by zolotov** [comment]
Without a version it downloads latest eap, latest eap is 2018.1 eap, which is likely cannot be started right now, as eap license is already expired. Thus the plugin cannot be started. Try to specify the version

**Comment by ice1000** [comment]
According to https://ci.appveyor.com/project/ice1000/intellij-owo#L362, 192.4205.45 is used without version specified.

(Still trying to figure out how to make the build pass and get the log file)

**Comment by ice1000** [comment]
Now you can access it on: https://ci.appveyor.com/project/ice1000/intellij-owo/builds/24822832/artifacts

For convenience, I've uploaded it for you: [hs_err_pid1512.log](https://github.com/JetBrains/gradle-intellij-plugin/files/3221061/hs_err_pid1512.log)

**Comment by zolotov** [comment]
> According to https://ci.appveyor.com/project/ice1000/intellij-owo#L362, 192.4205.45 is used without version specified.

I don't see this

> For convenience, I've uploaded it for you: hs_err_pid1512.log

Thanks. It looks like https://youtrack.jetbrains.com/issue/JBR-1382, closing in favor of that issue.

**Comment by ice1000** [comment]
Thank you!

**Comment by ice1000** [comment]
> I don't see this

Ah because the content of the link was updated. I've pushed more commits that triggers new builds, overwriting the old content.
FYI you can see 192 in
![image](https://user-images.githubusercontent.com/16398479/58389487-c7523980-7fdf-11e9-9ed0-19db0c9f1702.png)
(https://ci.appveyor.com/project/ice1000/intellij-owo/builds/24822773)
