### ISSUE TITLE
build searchable options should use the correct JBR runtime.

### ISSUE THREAD

**Issue by rhdunn** [JetBrains/gradle-intellij-plugin#397]
When attempting to build a plugin using gradle-intellij-plugin 0.4.8 for the latest EAP snapshot for 2019.2, the buildSearchableOptions task uses JBR for Java 8 intead of JBR for Java 11. On Windows, this results in an EXCEPTION_ACCESS_VIOLATION, per https://youtrack.jetbrains.com/issue/JBR-1550.

NOTE: It would be useful to say `jbrVersion: 8` or `jbrVersion: 11` and provide that in the Setup DSL, so it can be shared between the buildSearchableOptions and runIde tasks.

**Comment by zolotov** [comment]
> the buildSearchableOptions task uses JBR for Java 8 

Why do you think so?

**Comment by rhdunn** [comment]
> > the buildSearchableOptions task uses JBR for Java 8
> 
> Why do you think so?

The travis build contains the lines:
```
> Task :prepareSandbox
Download https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-jbr/jbrx-8u212-linux-x64-b1566.8.tar.gz
> Task :buildSearchableOptions
```
so it is downloading JBR 8. From the exception log attachment on https://youtrack.jetbrains.com/issue/JBR-1550, it has:

    Dynamic libraries:
    0x00007ff6dfd40000 - 0x00007ff6dfd71000 	C:\Users\rhdunn\.gradle\caches\modules-2\files-2.1\com.jetbrains\jbre\jbrx-8u212-windows-x64-b1566.7\jre\bin\java.exe

so is using the downloaded version of the JBR in the buildSearchableOptions, not the version of Java on the JAVA_HOME path.

I'm trying to figure out how to get that task to use JBR 11.

> > NOTE: It would be useful to say jbrVersion: 8 or jbrVersion: 11
> 
> `jbrVersion: 8` or `jbrVersion: 11` don't make any sense, we have plenty of different version of jbr, not only 8 or 11: https://bintray.com/jetbrains/intellij-jbr.

I know there are different versions of JBR 8/11. My issue is that if I specify a specific version, I will need to keep that version in sync with the IntelliJ build. I would like to be able to say something along the lines of:

    jbrVersion = if (idea_version <= 191) 8 else 11

> You have an entire power of Gradle to set any java you want for `JavaExec` tasks (runIde and buildSearchableOptions are both JavaExec tasks).
> 
> Also, see https://github.com/JetBrains/gradle-intellij-plugin#running-dsl

Then what is the point of the jbrVersion properties?

**Comment by zolotov** [comment]
> The travis build contains the lines:

👌, this means that downloaded IDEA points to this java as a bundled one. Works as indented, `runIde` will use the same java.

> so is using the downloaded version of the JBR in the buildSearchableOptions, not the version of Java on the JAVA_HOME path.

As intended.

> My issue is that if I specify a specific version, I will need to keep that version in sync with the IntelliJ build.

Why? I'd say you should not keep in sync Java that you use for build and Java you use to run ide or to collect searchable options.

> I would like to be able to say something along the lines of

You can say it as described in  https://github.com/JetBrains/gradle-intellij-plugin#running-dsl

> Then what is the point of the jbrVersion properties?

![image](https://user-images.githubusercontent.com/140920/58902072-15b3b680-870b-11e9-928f-ed7da06136bb.png)

Entry point is `RunIde` task, both `runIde` and `buildSearchableOptions` are `RunIde` tasks.

**Comment by rhdunn** [comment]
Ok, so the issue is more a documentation one. I was assuming from that document that it only applied to `runIde` and did not include `buildSearchableOptions`.

**Comment by zolotov** [comment]
Ok, I will add `buildSearchableOptions` there

**Comment by rhdunn** [comment]
Thanks.
