### ISSUE TITLE
Cannot debug the instance started with runIdea

### ISSUE THREAD

**Issue by sergeykad** [JetBrains/gradle-intellij-plugin#40]
I am starting Gradle with debug parameters and getting `Listening for transport dt_socket at address: 5005` message, but I cannot start at breakpoints inside the IDEA instance started with *runIdea*

What is the recommended way to debug plugins?

**Comment by zolotov** [comment]
I didn't understand. 

> I am starting Gradle with debug parameters

What parameters? And where did you add them?

> but I cannot start at breakpoints inside the IDEA instance started with runIdea

Have you attached with remote debug to gradle?

> What is the recommended way to debug plugins?

In the same way as for other applications: via run configurations (without debug-parameters and remote debug)

**Comment by zolotov** [comment]
https://github.com/JetBrains/gradle-intellij-plugin/issues/9#issuecomment-139237985

**Comment by sergeykad** [comment]
I have environment variable `GRADLE_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005`

I am attaching remote debugger to Gradle successfully, but it ignores breakpoints.
Is it possible that IDEA is launched in a separate JVM?

P.S. After I configured plugin build to run via Gradle run/debug buttons in the IDE start new IDEA instance without the plugin.
