### ISSUE TITLE
Does not have java plugin when running tests

### ISSUE THREAD

**Issue by ice1000** [JetBrains/gradle-intellij-plugin#406]
I have `setPlugins("java")` but my build still fails on [Travis CI](https://travis-ci.org/owo-lang/intellij-dtlc/jobs/553781454#L1275), saying that missing essential plugins.

This might be a bug of gradle-intellij-plugin.

**Comment by Undin** [comment]
@ice1000 Maybe it's because you set `java` plugin under `!isCI` condition?
https://github.com/owo-lang/intellij-dtlc/blame/master/build.gradle.kts#L71-L74

**Comment by ice1000** [comment]
Oh! Nice catch! Sorry for the shitpost!
