### ISSUE TITLE
RunIde task need all setup tasks to be executed before by default

### ISSUE THREAD

**Issue by ArtsiomCh** [JetBrains/gradle-intellij-plugin#410]
gradle-intellij-plugin:0.5.0-SNAPSHOT
Still having same issue mentioned at [cooment to 409](https://github.com/JetBrains/gradle-intellij-plugin/issues/409#issuecomment-510957275):
```
task runCLion_191(type: RunIdeTask){
    ideaDirectory '.../CLion/ch-0/191.7141.37/'
}
```
Will do:
```
1:14:31 PM: Executing task 'runCLion_191'...
> Task :runCLion_191
```
To make source code recompile, build new jar, prepare sanbox, etc. I have to explicitly add `dependsOn(prepareSandbox)`:
```
task runCLion_191(type: RunIdeTask){
    dependsOn(prepareSandbox)
    ideaDirectory '.../CLion/ch-0/191.7141.37/'
}
```
That will do:
```
1:22:32 PM: Executing task 'runCLion_191'...

> Task :compileJava UP-TO-DATE
> Task :patchPluginXml UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :instrumentCode UP-TO-DATE
> Task :postInstrumentCode
> Task :jar UP-TO-DATE
> Task :prepareSandbox UP-TO-DATE
> Task :runCLion_191
```

**Comment by zolotov** [comment]
I don't think the plugin should affect the flow of user-defined tasks. You may want to create your own `prepareSandboxForCLion` tasks and depend on it instead of built-in `prepareSandbox` task, gradle-intellij-plugin should not make you rerun `prepareSandbox` in this case.

**Comment by ArtsiomCh** [comment]
Hmmm... That has sense, but doesn't it make inconsistent behavior for runIde task and RunIde tasks?:
```
1:34:00 PM: Executing task 'runIde'...

> Task :compileJava UP-TO-DATE
> Task :patchPluginXml UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :instrumentCode UP-TO-DATE
> Task :postInstrumentCode
> Task :jar UP-TO-DATE
> Task :prepareSandbox UP-TO-DATE
> Task :runIde
```
And it's hard to imaging (also still possible) someone really need execute RunIde task without recompiling code, assempling new jar, clean senbox, etc.

**Comment by zolotov** [comment]
> doesn't it make inconsistent behavior for runIde task and RunIde tasks?:

If you add these tasks, it's on you to keep the consistency.

> And it's hard to imaging (also still possible) someone really need execute RunIde task without recompiling code, assempling new jar, clean senbox, etc.

This is not about running without recompiling, this is about running with different prepareSandbox task, which may require assembling different jars, which may require compiling different sources. The plugin provides you sensible default. If you want to go further, you have to control your own task graph.

**Comment by ArtsiomCh** [comment]
I see what you mean and that makes sense.
Just would like to explain my confusion as a newbie: When I create a new `RunIde` task I expected it would behave the same way as `runIde` by default and will do something differently only if I explicitly say so. 
Considering corner case like `task myRunIde(type: RunIdeTask){}`  I expect it just do the same as `runIde` task until I specify different behavior inside closure.
