### ISSUE TITLE
Downloading an IDEA is not working

### ISSUE THREAD

**Issue by aivinog1** [JetBrains/gradle-intellij-plugin#411]
See this: https://travis-ci.org/aivinog1/0pdd-idea-plugin/builds/561436742?utm_source=github_status&utm_medium=notification

> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Could not resolve com.jetbrains.intellij.idea:ideaIC:2019.1.3.
     Required by:
         project :
      > Could not resolve com.jetbrains.intellij.idea:ideaIC:2019.1.3.
         > Could not get resource 'https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2019.1.3/ideaIC-2019.1.3.pom'.
            > Could not GET 'https://dt9qhxywftqdz.cloudfront.net/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2019.1.3/ideaIC-2019.1.3.pom'.
               > dt9qhxywftqdz.cloudfront.net: Name or service not known
I've checked out, domain `dt9qhxywftqdz.cloudfront.net` does not exist. 

A project configuration could be seen here: https://github.com/aivinog1/0pdd-idea-plugin/pull/27

**Comment by zolotov** [comment]
should work now, please try again

**Comment by aivinog1** [comment]
@zolotov It works, thanks!

**Comment by crdev** [comment]
This seems to be happening again as of January 1, 2020:

```
A problem occurred configuring root project 'bamboo-soy'.
> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Could not resolve com.jetbrains.intellij.idea:ideaIC:2019.2.
     Required by:
         project :
      > Could not resolve com.jetbrains.intellij.idea:ideaIC:2019.2.
         > Could not get resource 'https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2019.2/ideaIC-2019.2.pom'.
            > Could not GET 'https://d2cico3c979uwg.cloudfront.net/com/jetbrains/intellij/idea/ideaIC/2019.2/ideaIC-2019.2.pom'.
               > d2cico3c979uwg.cloudfront.net: Name or service not known
```

**Comment by crdev** [comment]
Is fixed now, looks like some network setup glitch.
