### ISSUE TITLE
PatchPluginXml Task strips comments from plugin.xml

### ISSUE THREAD

**Issue by amynbe** [JetBrains/gradle-intellij-plugin#412]
I have free text comments as well as valid xml elements commented out in my plugin.xml that I'd like to keep. Could you possibly make PatchPluginXml Task not delete them?

**Comment by zolotov** [comment]
What free text comment are? Please provide an example of what you want to keep.

**Comment by amynbe** [comment]
My phrasing was bad, i would just like to keep all xml comments

**Comment by zolotov** [comment]
And why do you need them in the result binary?

**Comment by amynbe** [comment]
Because I'm editing it in place. I might be following the wrong approach
here. I'll investigate more to find out what's the correct way to work
with PatchPluginXml task.

**Comment by zolotov** [comment]
> Because I'm editing it in place

I don't understand. Do you edit it inside an already compiled jar? It does sound wrong. I'm sorry, I don't see any good reason for doing this. Won't fix.
