### ISSUE TITLE
Util.getBuiltinJbrVersion should allow getting secondJreBuild

### ISSUE THREAD

**Issue by baron1405** [JetBrains/gradle-intellij-plugin#413]
Currently the Util.getBuiltinJbrVersion method returns the jdkBuild version from the dependencies.txt file. Given that some plugin build may wish to use Java 8 instead of Java 11 or vice versa, the getBuiltinJbrVersion method should allow using the BBR specified by the secondJreBuild property. This could be an optional parameter on the method (e.g. useSecondary=false).

One use case is that I would like to be able to specify the JBR used in runIde (i.e. use the primary or secondary JBR).

**Comment by zolotov** [comment]
I believe secondary jre will always be a temporary thing and I don't really want to introduce a new syntax for this. I think java 8 will be dropped soon and dependency.txt won't have it anymore.

**Comment by YannCebron** [comment]
this is kinda obsolete now as we require Java 11

**Comment by zolotov** [comment]
at some point IJ will migrate to Java 14 or 15, so I'd keep the issue

**Comment by baron1405** [comment]
I closed the issue before reading @zolotov 's comment. I defer to his judgement on the status of this issue.

**Comment by YannCebron** [comment]
Given that `runIde` task now has dedicated `jbrVersion` parameter (https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#runide-task-jbrversion), is this still actual?

**Comment by baron1405** [comment]
This is no longer a factor given only a single JRE is used in IntelliJ at
this point.
