### ISSUE TITLE
Broken classpath with IDEA 192

### ISSUE THREAD

**Issue by Abnaxos** [JetBrains/gradle-intellij-plugin#414]
When trying to compile against IDEA 192, the classpath is not setup correctly. This applies to both specifying an IDEA version and localPath. Reproduced with 2019.2 (192.5728.98) IC.

Example:

```
public PsiType collectionOf(PsiType componentType) {
       ^
symbol:   class PsiType
location: class IdeaAdaptor
```

**Comment by ArtsiomCh** [comment]
Similar issue reproduced with IC-192.5728.98 for `localPath` case:
`    localPath '.../Toolbox/apps/IDEA-C/ch-2/192.5728.98'`
Trying to run tests using LightCodeInsightFixtureTestCase:
```
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.PsiElementFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
```
Quick research: 
191 -> 192 some .jars been moved from `/lib` to `/plugins/***/lib` (in my case /plugins/java/lib). 
As a result, in gradle-intellij-plugin `IdeaDependency#collectJarFiles()` do not collect all needed jars:
```
...
        if (classes.isDirectory()) {
            File lib = new File(classes, "lib")
            if (lib.isDirectory()) {
                return Utils.collectJars(lib, { file ->
                    return withKotlin || !IdeaDependencyManager.isKotlinRuntime(file.name - '.jar')
                }, false).sort()
            }
        }
...
```

The temporary solution is connecting those needed jars manually. In my case, I just created the symbolic link to `{local_IDEA}/plugins/java/lib` named `lib-test` and then connect it in dependencies through `testCompile fileTree('lib-test')`.

**Comment by zolotov** [comment]
not a bug. all you need is add java plugin: `intellij { plugins = ['java'] }`
details: https://blog.jetbrains.com/platform/2019/06/java-functionality-extracted-as-a-plugin/
