### ISSUE TITLE
ability to specify the path to locally installed JDK in jbrVersion

### ISSUE THREAD

**Issue by ArtsiomCh** [JetBrains/gradle-intellij-plugin#415]
Another nice to have option would be the ability to specify the path to locally installed JDK (from IDE distribution).

PS Latest avaliable Java11 version at [BinTray](https://bintray.com/jetbrains/intellij-jdk) is `11_0_2b164` (last update Feb 2019) while latest Idea (192) use `11.0.3+12-b304.10`
> jbrVersion .... All JetBrains Java versions are available at BinTray.

**Comment by ArtsiomCh** [comment]
Any updates?
Just got a bug in production cause CLion 193 with jbr 11.0.4 behave differently then CLion 193 with last available jbr for RunIde (11_0_2b164): https://github.com/ArtsiomCh/CMake/issues/7#issue-499874766

**Comment by zolotov** [comment]
1. Contributions are very welcome.
2. IDEs don't bundle JDK, only JRE. And by default `gradle-intellij-plugin` uses the bundled one. This is a reasonable default and I don't understand why would you change it.
3. I don't understand how https://github.com/ArtsiomCh/CMake/issues/7 is related here. `jbrVersion` is runtime only (this is why you set it in `runIde` task). It doesn't affect the compilation result.
4. Last JBR update was yesterday: https://bintray.com/beta/#/jetbrains/intellij-jbr?tab=packages, I'll update the link in README.

As a result, I'm not convinced it's needed change.

**Comment by ArtsiomCh** [comment]
1. Yeah... looks like the only way to make it work is to fork it and fix it... 
2. I wish. RunIde task just uses default java installed on my PC:
```
IntelliJ IDEA 2019.2.3 (Community Edition)
Build #IC-192.6817.14, built on September 24, 2019
Runtime version: 1.8.0_201-b09 amd64
VM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Linux 4.4.0-164-generic
```
So I have to explicitly set jbrVersion to 11:
```
class RunIdeTaskJbr11 extends RunIdeTask {
    RunIdeTaskJbr11(){
        jbrVersion '11_0_2b159'
    }
}
```
3. You are right. jbrVersion is not related to this issue. Everything is even worse: `Custom Properties` and `Custom VM options` are not taken from `ideaDirectory` and are gray and not readable/editable. Its definitely not taken from `ideaDirectory` as for CLion 193 EAP should be `-Djdk.attach.allowAttachSelf=true` (the real reason for my issue) and in instance running from this plugin it's not specified (like for no EAP). 
So we have a different setup for real production and a test version of IDE. 
4. Thank you! Readme link definitely needs to be updated (For example to get bundled to 192.6817.14 jbr we have to set `jbrVersion '11_0_4b304.69'`).

**Comment by zolotov** [comment]
2. it means something wrong with the configuration. Attach the `./gradlew :runIde --info` output.

> Everything is even worse: Custom Properties and Custom VM options are not taken from ideaDirectory and are gray and not readable/editable

It's expected while running from sources. Custom properties and VM options are taken from your `runIde` task configuration. Production options are not good for development as e.g. they disable some debug stuff, omit stack traces which makes profiling unusable, hide errors.

**Comment by zolotov** [comment]
closing due to lack of feedback
