### ISSUE TITLE
 How to package kotlin project to jar correctly and keep the kit method work

### ISSUE THREAD

**Issue by tangcent** [JetBrains/gradle-intellij-plugin#416]
- I want to use the kit method in the jar package.But even though I did a lot of trials, all failed.
Although I can find these kit methods in the jar package, but these can not be imported and used、invoked.

- My build.gradle: https://github.com/tangcent/intellij-kotlin/blob/master/build.gradle
- I use it like this: 
https://github.com/tangcent/easy-api/tree/master/idea-plugin/libs
https://github.com/tangcent/easy-api/blob/24549d7f6ae1b556a6f041d7a9bbad2a9b8b7a12/idea-plugin/build.gradle#L86

- I did find the kit class in the jar
![image](https://user-images.githubusercontent.com/17569144/62346598-48bad080-b529-11e9-97b5-57f972791316.png)
But it can not be imported
![image](https://user-images.githubusercontent.com/17569144/62346952-997ef900-b52a-11e9-8356-cfce37347fb4.png)

- I failed to google any useful information about this issue. I am not sure I can get help here. 
I will be extremely grateful if anyone can give me some help. Feel free to close this issue

**Comment by zolotov** [comment]
Sorry I don't understand what you're trying to archive. You show the content of some kotlin.jar (what it is? why you need) but I don't see how you attach it to the compile classpath. Why would compiler or IDE use it?

**Comment by tangcent** [comment]
> Why would compiler or IDE use it?
- I am sorry that intellij-kotlin.jar is not the Officially provided. I am developing several IDEA plugins, including two open source and one enterprise private.
So I want to write code which is basic and unrelated business to [intellij-kotlin](https://github.com/tangcent/intellij-kotlin).Then I package it to a jar And the jar will be used by several project.

>  What I am trying to achieve?
- I am trying to achieve all classes at intellij-kotlin, I did found all classes at the jar.
I can use the vast majority of them.  But when I try to using the method like this [fun Any.getPropertyValue(propertyName: String): Any?](https://github.com/tangcent/intellij-kotlin/blob/6eb2310891ff8f12e3cd7eda48e61c300d4e9004/src/main/kotlin/com/itangcent/intellij/util/AnyExtension.kt#L8-L13) in the jar. It can not be imported or used、invoked、compiled.

> How I attach it to the compile classpath?
- I tried to use `compile fileTree(dir: 'libs', include: ['*.jar'])`， Now I attach it to the compile classpath by this:
```
repositories {
    flatDir {
        dirs 'libs'
    }
    mavenCentral()
}
...

dependencies {
...
    compile name: 'intellij-kotlin'
}
```

**Comment by halirutan** [comment]
@tangcent Just FYI: I'm also using two libraries that reside in my project folder. I did not need to use `flatdir` and I have simply included them with (note, I'm using Kotlin DSL)

```
dependencies {
  compile(kotlin("stdlib-jdk8"))
  compile(files("lib/org.eclipse.egit.github.core-2.1.5.jar"))
  runtime(files("lib/usages.jar"))
}
```

I don't really think the problem lies there though. But the thing is that you can try to look through the decompiled code simply by navigating to the jar. So you "go to the declaration" of one of the methods that you *can* use from your jar. Then you verify in the project tool window that you are indeed in the right location inside your `libs` folder and look through all the things that are provided by the jar.

**Comment by tangcent** [comment]
That's what I'm wondering about.
- The origin file: https://github.com/tangcent/intellij-kotlin/blob/master/src/main/kotlin/com/itangcent/intellij/util/AnyExtension.kt
- It is shown in the jar as `AnyExtensionKt.class`
- I tried to it by:
`com.itangcent.intellij.util.getPropertyValue`
`com.itangcent.intellij.util.AnyExtension.getPropertyValue`
`com.itangcent.intellij.util.AnyExtensionKt.getPropertyValue`
All above are shown in red in IDEA, and the action "go to the declaration" not work.

-I was troubled for a long time. Thank you for your information.

**Comment by halirutan** [comment]
@tangcent First, you should join [our IntelliJ plugin devs chat](https://gitter.im/IntelliJ-Plugin-Developers/Lobby) where we can easily discuss such things. I'm still not convinced that this has anything to do with the IntelliJ Gradle Plugin.

Have you tried to 

1. Delete the import statement
2. Go to your decompiled extension function and use "Copy Reference"
3. Insert this fully qualified name you get from it

**Comment by tangcent** [comment]
- That's actually what I did! Go to the decompiled extension function and use "Copy Reference"
Then paste the qualified name.
- I also think that this situation has nothing to do with `IntelliJ Gradle Plugin`. I just don't know where to get help for it.
- I will try to join IntelliJ plugin devs chat later.It is really helpful for me.Thank you very much.

**Comment by sylhare** [comment]
Hey @tangcent I am going through the same issue and was wondering if you had found the solution for it?
Thanks 😉

**Comment by tangcent** [comment]
@sylhare 

See https://kotlinlang.org/docs/reference/using-gradle.html
If you configured  your `build.gradle` correctly.
You will find a `***.kotlin_module` in the jar you packaged just like the `stdlib`.
![image](https://user-images.githubusercontent.com/17569144/81878008-4fe33480-95b9-11ea-91d2-f46b5ae33c87.png)
The trouble I had before was that the `***.kotlin_module` was missing.

---

The configuration snippet I'm currently using:

```gradle
buildscript {
    ext.kotlin_version = '1.3.50'

    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

plugins {
    //https://mvnrepository.com/artifact/org.jetbrains.kotlin.jvm/org.jetbrains.kotlin.jvm.gradle.plugin
    id 'org.jetbrains.kotlin.jvm' version '1.3.50'

    //https://mvnrepository.com/artifact/org.jetbrains.intellij/org.jetbrains.intellij.gradle.plugin
    id "org.jetbrains.intellij" version "0.4.10"
}

apply plugin: 'kotlin'
apply plugin: 'idea'

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from 'build/docs/javadoc'
}

task sourcesJar(type: Jar) {
    classifier = 'sources'
    from sourceSets.main.allSource
}

jar {
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}

```

**Comment by sylhare** [comment]
Thanks a lot!!
