### ISSUE TITLE
add(capture<? extends javax.swing.JButton>) in List cannot be applied to (javax.swing.JButton)

### ISSUE THREAD

**Issue by SoftwareKing** [JetBrains/gradle-intellij-plugin#417]
when CodeDialog extends DialogWrapper:
![image](https://user-images.githubusercontent.com/6858857/62517010-0959f000-b859-11e9-9833-f36fc110e848.png)

**Comment by zolotov** [comment]
1. this repo is about gradle plugin, not intellij API. For further questions use https://youtrack.jetbrains.com
2. won't fix as it's intended. this method is for creating buttons panel, not for populating a list of buttons, you should use `com.intellij.openapi.ui.DialogWrapper#createActions` instead.
