### ISSUE TITLE
a task with `idea` in the name will not be created

### ISSUE THREAD

**Issue by ArtsiomCh** [JetBrains/gradle-intellij-plugin#422]
If a new task (type: RunIdeTask) has `idea` in the name it's not created.
For example, next task creation will be silently ignored:
`task runIdea_192_5728(type: RunIdeTask){...}`

**Comment by zolotov** [comment]
works fine for me

![image](https://user-images.githubusercontent.com/140920/64447070-26e1da00-d0e3-11e9-9916-7e77a5af759c.png)

**Comment by ArtsiomCh** [comment]
Hmmm, very strange. I still not able to create any `*Idea*` task (but no problems creating `*Iddea*`):
![image](https://user-images.githubusercontent.com/14268320/64466452-27c53c80-d0e0-11e9-8bcf-aa323eb7377f.png)

Maybe it's because I create new tasks inside `subprojects{}`?... 
Could you please try to create `*Idea*` task at https://github.com/ArtsiomCh/CMake/blob/master/build.gradle ?

**Comment by zolotov** [comment]
I'm pretty sure the task is created and you can run it.
Regarding its representation in IDEA Gradle tool window, please file a bug report at https://youtrack.jetbrains.com.
