### ISSUE TITLE
Incorrect null handling in DownloadActionWrapper.execut

### ISSUE THREAD

**Issue by baron1405** [JetBrains/gradle-intellij-plugin#423]
In the `DownloadActionWrapper.execute` method, the `dest` property is read and tested for being `null`. If the `dest` property is `null`, it will cause an NPE on line 18 where it is dereferenced to obtain the absolute path.

**Comment by baron1405** [comment]
A followup observation is that the code would be simpler if you made the class a utility class (e.g. Download) with a single method (e.g. get, download). That way you do not need the setting and re-setting of dest. You only appear to use the class as a utility (i.e. new DownloadActionWrapper(...).execute()).

**Comment by zolotov** [comment]
> would be simpler if you made the class a utility class 

it was a copy-paste from IntelliJ so the idea was not to change it to grab changes from there if needed.

And.. it hasn't been needed for couple years already :)

Thanks!
