### ISSUE TITLE
Cannot load resource

### ISSUE THREAD

**Issue by oemergenc** [JetBrains/gradle-intellij-plugin#425]
Hey, 

is there anything i am missing in loading a custom resource file (simple .properties file).
The project layout is like the following:
```
└── src
    ├── main
    │   ├── java
    │   │   └── de
    │   │       └── myproject
    │   │           └── mypackage
    │   │               └── HelloAction.java
    │   └── resources
    │       ├── META-INF
    │       │   └── plugin.xml
    │       └── my.properties
```

I am trying to load the file my.properties using the following code:
```
InputStream resourceStream = Thread.currentThread().getContextClassLoader().getResourceAsStream("my.properties");
```

However the resourceStream is always null. I also tried to copy the file into the libs folder and tried to add the file manually to the classpath. Unfortunately both did not work.
As far as a i know gradle, everything from the resource directory should be accessible on the classpath, shouldn't it?

The Project can be found here, it is based on the official getting started tutorial:
https://github.com/oemergenc/simple-intellij-plugin

**Comment by zolotov** [comment]
gradle has nothing to do with the way how classes are loaded from jars. You can easily debug classloading. 

in your particular case, you're trying to use classloader of Thread class for loading plugin-specific file. It's not allowed, you can access only to your plugin's classes. Just use your own class-loader: `getClass().getResourcesAsStream("/my.properties")`. Also, do not forget slash before.

**Comment by oemergenc** [comment]
Hey, thanks for the clarification and your answer.

Unfortunately, this code comes from a third party library and was simplified by myself. 
The code for loading the external resource properties file lays in a third party library, which i would like to include in my idea plugin. I just encapsulated the code to better demonstrate what my current problem is.

Is there any other way, you can think of, so that i can make this code working?

**Comment by zolotov** [comment]
I don't think so. You can try to read your class/resources using plugin's classloader and then try to load your class/resource to root class-loader. Not sure it's possible, though.

**Comment by oemergenc** [comment]
For anyone experiencing the same problem. I solved it by using the using the Classloader of the thirdparty class containing the code above and setting it on the current thread. Something like the following:
```        Thread.currentThread().setContextClassLoader(org.your.clazz.ProblemCode.class.getClassLoader());
InputStream resourceStream = Thread.currentThread().getContextClassLoader().getResourceAsStream("my.properties");
```
