### ISSUE TITLE
Idea 2019.2.1 JPS plugin missing classes

### ISSUE THREAD

**Issue by lastrix** [JetBrains/gradle-intellij-plugin#428]
File lib/jps-builders.jar no longer exist inside ideaIC.zip distribution, thus breaking any jps plugin.
The file could be found inside plugins/java/lib/

**Comment by zolotov** [comment]
What the version of Gradle plugin do you use? What's the build output?

**Comment by lastrix** [comment]
0.4.10, there is no build output since classes 
org.jetbrains.jps.incremental.BuilderService
org.jetbrains.jps.incremental.TargetBuilder
Not found in classpath.

Also, all classes that belong to java-related plugins are no longer accessible, like java-impl.jar is missing, because this file is moved from lib/ into plugins/java/lib

**Comment by zolotov** [comment]
> no build output since classes

It can't be. Invoke `./gradlew compileJava`

**Comment by lastrix** [comment]
![image](https://user-images.githubusercontent.com/677198/64266103-b305cd00-cf3c-11e9-8fea-b7a96f3a0502.png)
![image](https://user-images.githubusercontent.com/677198/64266108-b600bd80-cf3c-11e9-9ed9-81ad3b9efb67.png)
[output.txt](https://github.com/JetBrains/gradle-intellij-plugin/files/3575073/output.txt)

**Comment by lastrix** [comment]
I had no message about                         if (it.text() == 'com.intellij.modules.java') {
                            throw new BuildException("The project depends on `com.intellij.modules.java` module but doesn't declare a compile dependency on it.\n" +
                                    "Please delete `depends` tag from $file.absolutePath or add `java` plugin to Gradle dependencies (e.g. intellij { plugins = ['java'] })", null)
                        }

Adding  intellij { plugins = ['java'] }) solved compilation issues.
