### ISSUE TITLE
Incompatible change of buildPlugin task

### ISSUE THREAD

**Issue by vedun-z** [JetBrains/gradle-intellij-plugin#429]
The following code for adding some stuff to the plugin:

```
    tasks.prepareSandbox {
        from("stuff")
    }
```

doesn't work as before

**Comment by zolotov** [comment]
what silent means? do not depend on snapshots if you are not ready to change of the behavior.

coping additional files during the `buildPlugin` task is weird, why would you do this?

**Comment by vedun-z** [comment]
silent means there is no explicit note in commit message about that change.

Because I need to include some additional stuff into my plugin. In my case we have some bundled script which we want to execute from plugin.

**Comment by zolotov** [comment]
> In my case we have some bundled script which we want to execute from plugin.

But why do you do this during buildPlugin task? Does it mean that these scripts don't work at all when you do `runIde` task?

**Comment by zolotov** [comment]
> silent means there is no explicit note in commit message about that change.

Still don't get it, what do you think would be a better commit message?

**Comment by vedun-z** [comment]
we are copying them during `prepareSandbox` task as well.

**Comment by zolotov** [comment]
ok, changed the description

**Comment by vedun-z** [comment]
> Still don't get it, what do you think would be a better commit message?

add a note after the main commit message like:

`buildPlugin#into` is targeting `lib` directory.

 So, you could find a commit which breaks your code without looking into the commit change.

**Comment by zolotov** [comment]
I think you're inventing an unexisting problem. It was a single commit with the code for a month. And I don't think it makes sense to repeat the code inside the commit message.
