### ISSUE TITLE
How to install in Community 2019.2?

### ISSUE THREAD

**Issue by ninovanhooff** [JetBrains/gradle-intellij-plugin#432]
Im on Ubuntu 18.04 and installed Idea Community 2019.2 through the Toolbox.

This gives me the following environment:

IntelliJ IDEA 2019.2.2 (Community Edition)
Build #IC-192.6603.28, built on September 6, 2019
Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-27-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1908M
Cores: 4
Registry: 
Non-Bundled Plugins: org.jetbrains.idea.grammar, org.jetbrains.kotlin, com.github.shiraji.ipgwizard

The only plugin I can find in the marketplace for the search term "gradle intellij" is "gradle-intellij-plugin-wizard"

Is the bleeding edge too new for this plugin? If so, what is the currently supported version at this moment?

**Comment by zolotov** [comment]
This is not plugin for the IntelliJ IDEA, it's plugin for Gradle.

You don't need to install Gradle plugin in IntelliJ IDEA, it is bundled there
