### ISSUE TITLE
runIde runs IDEA twice

### ISSUE THREAD

**Issue by ignatov** [JetBrains/gradle-intellij-plugin#433]
1. Get the latest version of https://github.com/ignatov/intellij-erlang
1. Run IDEA with `./gradlew runIde`
1. Quit it with Cmd+Q
1. Get the second version of IDEA

**Comment by zolotov** [comment]
not a bug, you have two projects inside. `runIde` runs task for both projects. Use `:runIde` instead

**Comment by ignatov** [comment]
Thanks!
