### ISSUE TITLE
Error publishing a plugin for Custom Plugin upload

### ISSUE THREAD

**Issue by Harsh2402** [JetBrains/gradle-intellij-plugin#434]
I have created one custom plugin and works well in testing mode.

I need to upload my plugin in JetBrains, So I have created the zip file and upload it.

I got the following error while uploading the zip file.

Can anyone help to fix this?

![Screenshot 2019-09-23 at 6 10 03 PM](https://user-images.githubusercontent.com/20766131/65427618-51949800-de30-11e9-8b83-b9cd24f288c8.png)

**Comment by satamas** [comment]
'Plugin descriptor is not found' means that something is wrong with your zip archive and we can't find [plugin descriptor](https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_configuration_file.html). 
If you will provide me with zip archive you are trying to upload, I will be able to tell what's wrong exactly.

**Comment by Harsh2402** [comment]
@satamas 
Thanks for the replay, I have shared the details to you on mail.
