### ISSUE TITLE
bug: "pluginName" value is not used for the distributive ZIP file name

### ISSUE THREAD

**Issue by alexeyOnGitHub** [JetBrains/gradle-intellij-plugin#436]
using plugin version 0.4.10.

according to README file, 

> pluginName - The name of the target zip-archive and defines the name of plugin artifact.

**name of the target zip-archive**

so I expect the final ZIP file name to be equal to the value in "pluginName" with ".zip" suffix, while in fact the zip file name is always equal to project name, and pluginName only affects the **folder name** inside the ZIP file.

**Comment by ArtsiomCh** [comment]
Looks like the problem persist in 0.4.18 as well.

**Comment by zolotov** [comment]
@ArtsiomCh works fine for me. please file a new issue with details
