### ISSUE TITLE
"Used by" section for the Readme file

### ISSUE THREAD

**Issue by Turbo87** [JetBrains/gradle-intellij-plugin#44]
It might make sense to list a number of open source IntelliJ plugins that are known to use this project. That way others can quickly get an understanding of how it can be used on a real project.

This is the list of plugins I've found so far:

- https://github.com/breandan/idear
- https://github.com/GoogleCloudPlatform/gcloud-intellij
- https://github.com/go-lang-plugin-org/go-lang-idea-plugin
- https://github.com/ignatov/intellij-erlang
- https://github.com/intellij-rust/intellij-rust
- https://github.com/jansorg/BashSupport
- https://github.com/pedrovgs/AndroidWiFiADB
- https://github.com/SonarSource/sonar-intellij
- https://github.com/Turbo87/intellij-emberjs
- https://github.com/VladRassokhin/intellij-hcl

**Comment by Turbo87** [comment]
actually even more that I hadn't found on the first search: https://github.com/search?utf8=%E2%9C%93&q=%22apply+plugin%3A+org.jetbrains.intellij%22&type=Code

**Comment by zolotov** [comment]
Thanks, added to README

**Comment by winterDroid** [comment]
My plugin uses it as well: https://github.com/winterDroid/android-drawable-importer-intellij-plugin

**Comment by zolotov** [comment]
@winterDroid feel free to make a PR with changes in README
