### ISSUE TITLE
gradle always download LATEST-EAP-SNAPSHOT of java-compiler-ant-tasks when use localPath

### ISSUE THREAD

**Issue by sunnysnowhi** [JetBrains/gradle-intellij-plugin#443]
When I use gradle to build intellij plugin and use localPath config like this:
intellij {
    localPath 'D:\\Program Files\\JetBrains\\PyCharm Community Edition 2018.3'
}

The gradle always download the java-compiler-ant-tasks-LATEST-EAP-SNAPSHOT.jar,  not the specific version such as java-compiler-ant-tasks-192.5728.105.jar.

How can let gradle do not download the latest version ?  My maven reposity is in my compony network which can not connect the internet,  and I can only put specific version like java-compiler-ant-tasks-192.5728.105.jar in my maven repository, because the maven repository only accepte release version.

Thanks

**Comment by zolotov** [comment]
PyCharm Community Edition 2018.3 cannot have 192.5728.105 build number, your expectations are wrong.

We do not have compiler build for 183.* builds

> How can let gradle do not download the latest version ? 

see the documentation: https://github.com/jetbrains/gradle-intellij-plugin#instrumenting-dsl

**Comment by sunnysnowhi** [comment]
@zolotov sorry,  the version number in my question is just an example.   Actually, I use 2019.2 not 2018.3
intellij {
    localPath 'D:\Program Files\JetBrains\PyCharm Community Edition 2019.2'
}
And the question is :  the gradle always download the java-compiler-ant-tasks-LATEST-EAP-SNAPSHOT.jar, not the specific version such as java-compiler-ant-tasks-192.5728.105.jar

When I use config like this:
intellij {
    version 'PC-2019.2'
    type 'PC'
}
 the gradle will download the java-compiler-ant-tasks-192.5728.105.jar

So why this two kind of config download different jar ?  Thanks

**Comment by zolotov** [comment]
should be fixed in the next 0.5-snapshot, please check it in few hours
