### ISSUE TITLE
Document recommended versions for targeting a particular IntelliJ version

### ISSUE THREAD

**Issue by fcurts** [JetBrains/gradle-intellij-plugin#449]
I'm writing an IntelliJ plugin and would like to support IntelliJ 2019.1 and above.

I haven't been able to find a combination of (gradle-intellij-plugin, gradle-grammar-kit-plugin, grammar-kit) versions that works together with `intellij { ideVersion = "2019.1" }`. Instead I'm getting `NoSuchMethodError`, `NullPointerException`, etc. at plugin build time.

Please document which versions are recommended (and known to work together) when targeting a particular IntelliJ version.

It would also be beneficial to document which Kotlin, Gradle, and JFlex versions to use when targeting a particular IntelliJ version. For example, I'm using Kotlin 1.3.11 because that's what ships with 2019.1, but now I can't use Gradle 6 because `kotlin-gradle-plugin:1.3.11` isn't compatible with Gradle 6 (`NoClassDefFoundError`). Also I can't use `jflex-1.7.0-2` because then the code generated by Grammar Kit 2019.3 won't compile anymore.

A related issue is that I can't separately specify which IDE version to build against and which one is used by the `runIde` task. For example, GrammarKit 2019.3 requires `intellij { ideVersion = "2019.3" }` (otherwise `NullPointerException` during parser generation) but I do want to develop against 2019.1. For now I work around by setting `runIde { ideDirectory = "..." }` but that's cumbersome (not automatically downloaded, etc.).

**Comment by zolotov** [comment]
> intellij { ideVersion = "2019.1" }

You mean `intellij { version = "2019.1" }`, right?

>  Instead I'm getting NoSuchMethodError, NullPointerException, etc. at plugin build time.

Class names of exception are not enough for understanding what's going on.

> Please document which versions are recommended (and known to work together) when targeting a particular IntelliJ version.

Which version of what?

> It would also be beneficial to document which Kotlin, Gradle

Kotlin any, Gradle greater than 3 (I use the latest one always, now 6), JFlex any

> For example, I'm using Kotlin 1.3.11 because that's what ships with 2019.1

It makes sense to reduce the distribution size of the plugin.

> I can't use Gradle 6 because kotlin-gradle-plugin:1.3.11 isn't compatible with Gradle 6 (NoClassDefFoundError)

I know nothing about kotlin but I believe you can use gradle plugin higher version than version of compiler/stdlib. If it doesn't then I think it's documentation matter for kotlin plugin, not for gradle-intellij-plugin.

> Also I can't use jflex-1.7.0-2 because then the code generated by Grammar Kit 2019.3 won't compile anymore.

I think this is a question to grammarkit plugin, I know nothing about it.

> A related issue is that I can't separately specify which IDE version to build against and which one is used by the runIde task

Makes sense, please file a separate feature request for it. PR is also welcome, though.

**Comment by fcurts** [comment]
> > intellij { ideVersion = "2019.1" }
> 
> You mean `intellij { version = "2019.1" }`, right?

Correct.

> 
> > Instead I'm getting NoSuchMethodError, NullPointerException, etc. at plugin build time.
> 
> Class names of exception are not enough for understanding what's going on.

Sure, this is just to demonstrate that version guidance is really needed because most version combinations don't work, and there is no documentation saying *if* they should work.

> 
> > Please document which versions are recommended (and known to work together) when targeting a particular IntelliJ version.
> 
> Which version of what?

```
When writing plugins for IntelliJ 2019.1, we recommend you use these versions,
which are known to work together and with IntelliJ 2019.1:

(when building with gradle)
gradle: xxx
gradle-intellij-plugin: xxx

(when using grammar kit)
grammar-kit: xxx
jflex: xxx

(when using grammar kit and gradle)
gradle-grammar-kit-plugin: xxx

(when implementing the plugin in kotlin)
kotlin: xxx
```

If this is the wrong place for such documentation, then perhaps it can be added to the IntelliJ plugin dev documentation. (JetBrains can make a more informed decision on this than me.)

**Comment by zolotov** [comment]
> (when building with gradle)
> gradle: xxx
> gradle-intellij-plugin: xxx

![image](https://user-images.githubusercontent.com/140920/70380386-42d26300-1900-11ea-9eff-7d17e861a705.png)

There are no other recommendations. gradle-intellij-plugin doesn't care what versions of grammarkit, kotlin or intellij version you use.

> JetBrains can make a more informed decision on this than me.

I don't think so. Only you can decide what build/generation tool or language you want to use and which versions of IDE you consider as compatible.

**Comment by fcurts** [comment]
Please try to think from the plugin developer's perspective. I've tried many reasonable combinations and all of them fail with obscure exceptions. Other developers have had similar experiences. Providing no guidance on *known good version combinations* simply means to leave plugin developers in the dark.

As I said, perhaps the plugin dev documentation is a better place for this kind of documentation, in which case I'd hope that you forward this issue to the right place (or tell me where to report it).

**Comment by zolotov** [comment]
From the user-perspective, there are dozens of tools that I can use for building plugin, and none of them is required. Building matrix like this doesn't make any sense to me, really.

In fact, the only tool I need is gradle and there is recommendation about it. There are *no* any other recommendations and other tools of my choice can be checked for compatibility with my current configuration by there own documentation.

> I'd hope that you forward this issue to the right place (or tell me where to report it).

You can make a PR to https://github.com/JetBrains/intellij-sdk-docs. I'm not sure how to file issues there. @YannCebron?

**Comment by fcurts** [comment]
> Obscurity of exception is completely another issue. If you think they are not clear enough, file an issue about it for the tool that throws the.

These exceptions arise out of *incompatibility* between *dependent libraries* that neither *document* nor *check* compatibility requirements.

**Comment by zolotov** [comment]
So? Is this the reason to keep them as is? None of the possible compatibility tables will help you with these exceptions. If they are obscure – they should be handled. If they are clear – deal with them. Nothing to document here.

**Comment by fcurts** [comment]
The compatibility tables will avoid these exceptions (esp. if they are backed by automated tests) and will avoid the need to try countless combinations until I find one for which no exception occurs. Documenting "known compatible versions" or "recommended versions" is a common solution to this difficult problem.

**Comment by zolotov** [comment]
It looks like you know what to do and I'm not. So please feel free to make a PR to sdk docs. I'm pretty sure `gradle-intellij-plugin` has nothing to do with it.

**Comment by fcurts** [comment]
I'll give you an example for how this is related to `gradle-intellij-plugin`: When I changed `intellij { version = "..." }`, I was very surprised to find that parser generation with `gradle-grammar-kit-plugin` broke. While you may consider this a `gradle-grammar-kit-plugin` problem, as a plugin developer, it's difficult to tell what the dependencies are and where to look for the relevant information.
