### ISSUE TITLE
It does not support java-library submodule

### ISSUE THREAD

**Issue by SetoKaiba** [JetBrains/gradle-intellij-plugin#451]
It does not support java-library submodule.
When you modify the plugin to java instead of java-library, it will work.
It does not contains the jar from java-library.

Here's a minimal reproduce project.
https://github.com/SetoKaiba/TestPlugin

**Comment by DreierF** [comment]
I ran into the same bug.

As a workaround you can explicitly depend on the `jar` task of all included `java-library` projects like so:
```
tasks.named('prepareSandbox') {
	dependsOn ':lib:myLib:jar'
}
```

**Comment by SetoKaiba** [comment]
Will this be fixed? It's inconvenience to add this after every module is created.

**Comment by zolotov** [comment]
@SetoKaiba if you're aware what should be done on gradle-intellij-plugin side, the PR is very welcome
