### ISSUE TITLE
Building Against Older Versions Isn't Documented Well Enough

### ISSUE THREAD

**Issue by opticyclic** [JetBrains/gradle-intellij-plugin#452]
[This commit](https://github.com/JetBrains/intellij-community/commit/fc76f3ac4c4cbc63415e44657103dba0abbd8dd1#diff-a6a7523f32cb60de85837636b52c542c) means that my old plugin code no longer compiles.

I should be able to find a build before Aug 8, 2014 to compile my code against.

The `version` block in `build.gradle` looks like this:

    // See https://github.com/JetBrains/gradle-intellij-plugin/
    intellij {
        version 'IC-2019.1'
        plugins 'ant'
    }

The readme here says:

> Acceptable Values:
> 
>     version #
>     '2017.2.5' or 'IC-2017.2.5'
>     build #
>     '172.4343' or 'IU-172.4343'
>     'LATEST-EAP-SNAPSHOT'
> 
> All available JetBrains IDEs versions can be found at[ Intellij Artifacts page](https://www.jetbrains.org/intellij/sdk/docs/reference_guide/intellij_artifacts.html).

That then links to this build number page https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html

Which then links to various github branches with no clear info on how to get the build numbers.

A list of previous build numbers can be found here https://www.jetbrains.com/idea/download/other.html

However, selecting versions from there results in the plugin not resolving.

e.g. 

* version '135.1229'
* version 'IU-135.1356'

```
> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Could not find com.jetbrains.intellij.idea:ideaIC:135.SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/jetbrains/intellij/idea/ideaIC/135.SNAPSHOT/ideaIC-135.SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/jetbrains/intellij/idea/ideaIC/135.SNAPSHOT/ideaIC-135.SNAPSHOT.jar
       - https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/135.SNAPSHOT/ideaIC-135.SNAPSHOT.pom
       - https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/135.SNAPSHOT/ideaIC-135.SNAPSHOT.jar
     Required by:
         project :
```

You can't browse the [jetbrains repo for available versions](https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC) either because it isn't a normal maven repo like maven central and you get `302` and `404` errors.

Where can I find the list of valid version/build numbers that I can put into the `intellij` block?

And which version/build number should I use for a build in Aug 2014?

**Comment by zolotov** [comment]
> All available JetBrains IDEs versions can be found at Intellij Artifacts page.

This page contains links to repo where all available versions are listed: https://www.jetbrains.com/intellij-repository/releases/, https://www.jetbrains.com/intellij-repository/snapshots

> Which then links to various github branches with no clear info on how to get the build numbers.

`Help | About` of a particular distribution contains the exact build number. Sources (git branches) cannot have a build number, they are not "builds".

> And which version/build number should I use for a build in Aug 2014?

I don't know what version you're talking about but the oldest version you can download using gradle is IntelliJ IDEA Community `14.0.1`.

**Comment by opticyclic** [comment]
Why did you close this?

The link in the readme should be updated to point to the link in your comment as it is more useful than the current link in the readme, or maybe have them both. As you can see from this issue, the current link is confusing and doesn't have the right info to enable building.

When searching that page for idea-IC.zip, the oldest I can find is `2014-10-09 02:11:36 MSK | 139.1.20` which is probably some version of `14` although it looks older than `14.0.1`.

Anyway, you should update the readme to specify what the oldest version of IDEA you can download with gradle, because as it stands, the documentation makes it look like you can use it for any version.

**Comment by zolotov** [comment]
> Why did you close this?

The issue doesn't contain any actions to do from my side, so I close it.

> The link in the readme should be updated to point to the link in your comment as it is more useful than the current link in the readme

Current link in the readme contains the links I mentioned in the comment: 
![image](https://user-images.githubusercontent.com/140920/71588001-f3630980-2b30-11ea-92ee-5d85d3dc894c.png)

> When searching that page for idea-IC.zip, the oldest I can find is 2014-10-09 02:11:36 MSK | 139.1.20 which is probably some version of 14 although it looks older than 14.0.1.

139.1.20 looks like one of the first builds of 139 branch and doesn't correspond to any release version, I'd not use it, as none of the users of your plugin will use this version. 14 is ok to use I think.

> Anyway, you should update the readme to specify what the oldest version of IDEA you can download with gradle, because as it stands, the documentation makes it look like you can use it for any version.

The documentation says that all versions that you can use are listed in the maven repo, there is nothing about supporting all possible versions. If you think that something should be changed there, I can consider PR.

**Comment by opticyclic** [comment]
The action the issue contains is to update the documentation.

FYI: I spent 4 hours trying to get it to work so clearly the documentation is lacking in this respect.

Reopen this issue so I can link a pull request to it.

**Comment by zolotov** [comment]
I don't really understand why do you need this issue to be open for a PR, but ok, reopened

**Comment by zolotov** [comment]
closing again due to lack of feedback

**Comment by opticyclic** [comment]
Opened on YouTrack as well because you keep aggressively closing issues before they are fixed.

https://youtrack.jetbrains.com/issue/IJSDK-757
