### ISSUE TITLE
Where Do I Get Distributions For localPath?

### ISSUE THREAD

**Issue by opticyclic** [JetBrains/gradle-intellij-plugin#453]
The readme for the `version` attribute states:

> All available JetBrains IDEs versions can be found at [Intellij Artifacts](https://www.jetbrains.org/intellij/sdk/docs/reference_guide/intellij_artifacts.html) page.

However, there is no such link for the `localPath` to find a list of valid distributions.

It isn't possible to browse the download directory https://download-cf.jetbrains.com/idea/ to see the list of downloads.

There is this page https://www.jetbrains.com/idea/download/other.html

However, I'm not sure if this page is correct or not as it says that certain versions are not available e.g. 2019.2.2

That isn't that old so why isn't it available?

Is there a page with all the versions available to download for the `localPath` and can you link it in the readme please.

**Comment by zolotov** [comment]
> However, there is no such link for the localPath to find a list of valid distributions.

You can use any distribution you have: from snap, from jetbrains.com, from maven repo, built from source

**Comment by opticyclic** [comment]
Does `localPath` also suffer from the same v14 limitation that https://github.com/JetBrains/gradle-intellij-plugin/issues/452 mentions?

**Comment by zolotov** [comment]
In theory, there are no limitations, you free to use any IDE distribution you download. But I think nobody actually tried to use it with v14 or older, so I cannot really guarantee that it will work.
