### ISSUE TITLE
runIde task fails when specifying local installation for DataGrip due to using "0xDBE" platform prefix

### ISSUE THREAD

**Issue by YannCebron** [JetBrains/gradle-intellij-plugin#458]
https://youtrack.jetbrains.com/issue/IJSDK-672#focus=streamItem-27-3877474.0-0

overriding via
`    jvmArgs '-Didea.platform.prefix=DataGrip'`
in `runIde` fixes it

see org.jetbrains.intellij.tasks.RunIdeBase#PREFIXES

it seems one possible solution could be "dynamic" switch depending on version?

**Comment by zolotov** [comment]
> it seems one possible solution could be "dynamic" switch depending on version?

do you think it makes sense? I'm not sure anybody develops plugins for DataGrip made in 2015.

**Comment by zolotov** [comment]
made it statically. please reopen if you think dynamic switching is important
