### ISSUE TITLE
instrumentCode task is slow

### ISSUE THREAD

**Issue by domartynov** [JetBrains/gradle-intellij-plugin#459]
For my plugin with **many** `.java`, `.kt` and `.form` files, the `instrumentCode` task takes **~15-20s** even for small changes, plus it updates many classes, so **reloading of classes is slow** as well. I'd like to make the task incremental, plus few other changes I hope the maintainers can help to assess:

1. Limit the scope of the task to `sourceSets.main.java`, do we really need to instrument a) kotlin classes, b) test classes?
2. The ant `InstrumentIdeaExtensions` task is not incremental (in the code i see it just loops over files  in `srcdir` unless i'm missing something). so, in the incremental mode instead of copying classes to `outputDir` directly, the task cleans up `tempDir`, copies there changed inputs (classes and `.form` files), runs the `InstrumentIdeaExtensions` with `srcdir=distdir=tempDir`, and then copies `.class` files from `tempDir` into `outputDir`.

**Comment by krasa** [comment]
Any plans on fixing it? 

There should be a big disclaimer, saying not to use Gradle for plugins with GUI forms, and vice versa.

**Comment by krasa** [comment]
Workaround:
![image](https://user-images.githubusercontent.com/1160875/158333969-97625619-5a3a-4832-b4f6-17d3fefe4360.png)

**Comment by hsz** [comment]
As for 1: 861c044437d741c87386d0a3c48f0d48dda81552

**Comment by YannCebron** [comment]
1) test classes must be instrumented, e.g. test utility methods with `@NotNull`

**Comment by hsz** [comment]
Implemented with https://github.com/JetBrains/gradle-intellij-plugin/pull/984
