### ISSUE TITLE
Disable automatic update check

### ISSUE THREAD

**Issue by Turbo87** [JetBrains/gradle-intellij-plugin#46]
Unless you're using a "latest" version it doesn't make much sense to have the IDE tell you about new updates all the time. I'm not sure if and how it could work, but I assume the setting if the IDE should check for updates is saved somewhere in the sandbox so it should be possible for this plugin to disable the update check by default.

**Comment by Turbo87** [comment]
looks like `config/options/updates.xml` needs to be set to:

```xml
<application>
  <component name="UpdatesConfigurable">
    <option name="CHECK_NEEDED" value="false" />
  </component>
</application>
```

**Comment by warjiang** [comment]
I used `IntelliJIdea2016.3`, for me the config file in under `~/.IntelliJIdea2016.3/config/options`.

**Comment by zolotov** [comment]
@warjiang what are you talking about? the issue is about disabling auto-update in debug-instance of IDE, local installation has nothing to do with this
