### ISSUE TITLE
feature request: use different IDE version for buildPlugin and runIde tasks

### ISSUE THREAD

**Issue by jonathanlermitage** [JetBrains/gradle-intellij-plugin#463]
I maintain a [plugin](https://github.com/jonathanlermitage/intellij-extra-icons-plugin) that works with IJ Ultimate and Community, but I added an [**optional** dependency (in `META-INF/plugin.xml`)](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/blob/master/resources/META-INF/plugin.xml#L78) to the Angular plugin, which is available in IJ Ultimate and other payed JetBrains IDE, not IJ Community.
* if I set version to IJ Ultimate (e.g. IU-2018.3), I can run both `buildPlugin` and `runIde` tasks
* if I set version to IJ Community (e.g. IC-2018.3), I can't run `buildPlugin` nor `runIde` because it cannot find Angular plugin (error: "Cannot find builtin plugin AngularJS for IDE:...").
I also tried to build and test with different IDE versions:
   ```
   gradlew buildPlugin -PideaVersion=IU-2019.3.3
   gradlew runIde -PideaVersion=IC-2019.3.3
   ```
   (where `ideaVersion` sets IDE version in [build.gradle](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/blob/master/build.gradle#L45)), but the `runIde` still fails with the same error.

**Question**: could you add options to let user choose different IDE versions for each task? This way I could build with IJ Ultimate, then test with IJ Community.  
Otherwise, is there a workaround for this issue?

**Comment by zolotov** [comment]
`intellij.version` is for building

for running you can use `runIde` with any IDE distribution (https://github.com/JetBrains/gradle-intellij-plugin#running-dsl), but you need to download it manually

for automatic downloading see #360
