### ISSUE TITLE
"Custom" prefixes for runtime versions

### ISSUE THREAD

**Issue by FirstTimeInForever** [JetBrains/gradle-intellij-plugin#465]
I was trying to set jbr version to `jbr_jcef-11_0_6b765.15`, but the plugin attempts to download `jbr-jcef-11_0_6-osx-x64-b765.15.tar.gz` (should start with `jbr_`).

```
> Task :runIde
Download https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-jbr/jbr-jcef-11_0_6-osx-x64-b765.15.tar.gz
[gradle-intellij-plugin :intellij-pdf-viewer:runIde] Cannot download JetBrains Java Runtime jbr-jcef-11_0_6-osx-x64-b765.15. Run with --debug option to get more log output.
[gradle-intellij-plugin :intellij-pdf-viewer:runIde] Cannot resolve JBR jbr-jcef-11_0_6b765.15. Falling back to builtin JBR.
Download https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-jbr/jbr-jcef-11_0_6-osx-x64-b765.15.tar.gz
[gradle-intellij-plugin :intellij-pdf-viewer:runIde] Cannot download JetBrains Java Runtime jbr-jcef-11_0_6-osx-x64-b765.15. Run with --debug option to get more log output.
[gradle-intellij-plugin :intellij-pdf-viewer:runIde] Cannot resolve JBR jbr-jcef-11_0_6b765.15. Falling back to builtin JBR.
Download https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-jbr/jbr-jcef-11_0_6-osx-x64-b765.15.tar.gz
[gradle-intellij-plugin :intellij-pdf-viewer:runIde] Cannot download JetBrains Java Runtime jbr-jcef-11_0_6-osx-x64-b765.15. Run with --debug option to get more log output.
[gradle-intellij-plugin :intellij-pdf-viewer:runIde] Cannot resolve JBR jbr-jcef-11_0_6b765.15. Falling back to builtin JBR.
```

**Comment by YannCebron** [comment]
see https://youtrack.jetbrains.com/issue/IDEA-231833#focus=streamItem-27-3993099.0-0

**Comment by FirstTimeInForever** [comment]
I saw this post. They suggest to manually select runtime with runtime select plugin. It would be nice if this task can be done with just build config.

**Comment by zolotov** [comment]
since 0.4.17 and the next 0.5.0-snapshot something like `jbrVersion 'jbr_jcef-11_0_6b795.3'` will work

**Comment by FirstTimeInForever** [comment]
Cool! Thank you very much for taking your time to implement this feature!
I managed to write my own tasks for downloading and setting up jcef jbr. As I was writing it, I discovered that gradle can't properly handle symlinks copy task. This bug with symlinks was discovered at least in 2010 and it is still present.
As you can guess, the `jbr_jcef-...` archive has symlinks inside (at least on OSX).  After extracting files from archive all symlinks are broken (zero-sized files):
```
.rwxr-xr-x 0 hans 24 Mar  3:17 Chromium Embedded Framework
.rwxr-xr-x 0 hans 24 Mar  3:17 Libraries
.rwxr-xr-x 0 hans 24 Mar  3:17 Resources
drwxr-xr-x - hans 24 Mar  3:17 Versions
```
This symlinks are actually very important as they are pointing to the CEF libs (IDE will crash then you try to open browser window).

In my tasks I was manually patching this symlinks with this brutal piece:
```kotlin
val target = File(buildDir, "jbr/Contents/Frameworks/Chromium Embedded Framework.framework")
Files.deleteIfExists(File(target, "Chromium Embedded Framework").toPath())
Files.deleteIfExists(File(target, "Libraries").toPath())
Files.deleteIfExists(File(target, "Resources").toPath())
Files.deleteIfExists(File(target, "Versions/Current").toPath())
Files.createSymbolicLink(File(target, "Chromium Embedded Framework").toPath(),
    File(target, "Versions/A/Chromium Embedded Framework").toPath())
Files.createSymbolicLink(File(target, "Libraries").toPath(), File(target, "Versions/A/Libraries").toPath())
Files.createSymbolicLink(File(target, "Resources").toPath(), File(target, "Versions/A/Resources").toPath())
Files.createSymbolicLink(File(target, "Versions/Current").toPath(), File(target, "Versions/A").toPath())
```

I don't know if there are symlinks present in the distributions for other platforms, and I don't know an easy fix for it. It is actually quite funny, as it seams this jcef versions are the first one with symlinks inside.

**Comment by zolotov** [comment]
Thanks for the update. Filed another issue: https://github.com/JetBrains/gradle-intellij-plugin/issues/468. I think I'll reimpement it with real `untar` executing on linux/mac OS.

Related https://github.com/gradle/gradle/issues/3982
