### ISSUE TITLE
 Cannot change dependencies of configuration ':idea' after it has been included in dependency resolution.

### ISSUE THREAD

**Issue by DSEyers** [JetBrains/gradle-intellij-plugin#467]
Getting the error below using the plugin and doing a build.  

 **Cannot change dependencies of configuration ':idea' after it has been included in dependency resolution.**

I tried a few things to exclude jar but no luck.  Gradle 4.4.1 being used.
Attached build file minus some internal libraries we use.

Occurs when following line 216 is present in the **jar task**:
configurations.testRuntime.files.collect { it.name },

[build_gradle_share.txt](https://github.com/JetBrains/gradle-intellij-plugin/files/4360850/build_gradle_share.txt)

**Comment by zolotov** [comment]
> configurations.testRuntime.files.collect { it.name },

I don't think I can help you here. You resolve all dependencies too soon, on gradle configuration phase, even before all tasks are configured. I believe you should do it when `jar` task is running, not when it's configuring.
