### ISSUE TITLE
Could not download ideaIC.zip (com.jetbrains.intellij.idea:ideaIC:2019.3.3)

### ISSUE THREAD

**Issue by venshine** [JetBrains/gradle-intellij-plugin#469]
```
A problem occurred configuring root project 'JDoc'.
> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Could not download ideaIC.zip (com.jetbrains.intellij.idea:ideaIC:2019.3.3)
      > Could not get resource 'https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2019.3.3/ideaIC-2019.3.3.zip'.
         > Could not GET 'https://d2cico3c979uwg.cloudfront.net/com/jetbrains/intellij/idea/ideaIC/2019.3.3/ideaIC-2019.3.3.zip'.
            > Received close_notify during handshake
```
I plan to develop a plugin by using idealU, but I get the problem.

**Comment by zolotov** [comment]
can you open https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2019.3.3/ideaIC-2019.3.3.zip in browser?

**Comment by venshine** [comment]
@zolotov I can open it

**Comment by venshine** [comment]
I use third proxy environment, and then it works.

**Comment by zolotov** [comment]
good to know it works for you. thank you for the update

**Comment by Shu-Ji** [comment]
Can I download this file manually?
My idea/gradle is slow to download ideaIC-2020.1.1.zip, I tried many many times, always timeout.
So I have downloaded this zip file by other tools successfully. 
But I don't know how to tell idea to use that file?

**Comment by zolotov** [comment]
all files here https://www.jetbrains.com/intellij-repository/releases

> But I don't know how to tell idea to use that file?

you don't need specifically that file. you can use regular ide distribution. anyway, please see the readme. I've written exactly not to answer the same questions over and over again

**Comment by davidhilton68** [comment]
Very sorry to disturb you zolotov, where is this readme located, I have the same issue, trying to write a plugin and can't seem to download (though I run out of heap space, after allocating 6GB, but I suspect its the same issue. If you could point us to the readme on this question thread, hopefully you want be asked again.

**Comment by YannCebron** [comment]
@davidhilton68 please upgrade your Gradle version to 6.1.1 or higher

**Comment by davidhilton68** [comment]
Many Thanks, will do :) <and the readme, if anyone else follow this path, is https://github.com/JetBrains/gradle-intellij-plugin/blob/master/README.md I think>

**Comment by davidhilton68** [comment]
I am on version Ultimate 2020.1, is updating the Gradle Version achieved by just intsalling your plugin (https://plugins.jetbrains.com/plugin/13112-gradle/versions), which would be in addtion to the bundled 'Gradle Extension 201.7223.91' or should I be installing Gradle independantly and linking your plugin to that installation? (or via the 'Use Gradle from' option on the Gradle Settings screen). Really sorry of this is a dumb question, I have to confess I am new to Gradle and currently using it because its the recommended route for developers who are theselves building plugins. I did look through the readme, and faq and a general Google across the Jetbrains site but could not nail down anything specific.

**Comment by davidhilton68** [comment]
And just a little more, I reinstalled **2019.3.5 Ultimate and there is no problem** (i.e. trying to create a simple gradle intellij plugin project does not result in a heap space failure), the problem only seems to be with 2020.1 (5GB heap, no custom properties, latest gradle plugin I could find).

**Comment by YannCebron** [comment]
I was talking about installing/defining (gradle-wrapper.properties) Gradle version itself www.gradle.org

**Comment by davidhilton68** [comment]
Ahh okies, is there a way I can check the gradle version being used by the plugin? again the log file hints at which version is used (I guess whatever is embedded in the IDE distribution)

**Comment by YannCebron** [comment]
it depends on the settings of Preferences | Build, Execution, Deployment | Build Tools | Gradle

**Comment by davidhilton68** [comment]
Okies, in my Intellij Preferences | Build, Execution, Deployment | Build Tools | Gradle exposes only a page that allows me to set 'Gradle user home' (currently my user\.gradle), it does not seem to indicate anything about the version of Gradle I have.

With regard to latest gradle - I have the latest gradle downloaded to my machine, but its not clear how I get Intellij to use it, I have looked over  various wikis and can see how I might upgrade external gradle setups, but in this case I think you are suggesting I override the gradle setup used by the Intellij plugin.

**Comment by YannCebron** [comment]
Please use gradle-wrapper.properties instead of some manual installation on your machine and define the version there. This is in general preferred solution.

**Comment by davidhilton68** [comment]
The only 2 gradle-wrapper.properties I can find are in 

C:\development\tools\IntelliJ IDEA 2020.1.1\plugins\android\lib\templates\gradle\wrapper\gradle\wrapper
C:\development\tools\IntelliJ IDEA 2019.3.5\plugins\android\lib\templates\gradle\wrapper\gradle\wrapper

When I look in Settings/Build, Execution, Deployment/Build Tools/Gradle I can see an error to the left of the 'Use Gradle from:' box 'gradle-wrapper.properties' not found

If I download the source code for your plugin from github, I can see some gradle-wrapper.properties files in

gradle-intellij-plugin-master\gradle\wrapper
gradle-intellij-plugin-master\examples\gradle\wrapper

I the idea here that I download your plugin manually i.e. not via Settings/Plugins ?

**Comment by YannCebron** [comment]
I was referring to the gradle-wrapper.properties that should be available in your own plugin project, please see https://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/gradle_guide.html#controlling-downloads-by-the-gradle-plugin

**Comment by aborn** [comment]
> Can I download this file manually?
> My idea/gradle is slow to download ideaIC-2020.1.1.zip, I tried many many times, always timeout.
> So I have downloaded this zip file by other tools successfully.
> But I don't know how to tell idea to use that file?

intellij.localPath  https://github.com/JetBrains/gradle-intellij-plugin/blob/master/README.md

**Comment by q258523454** [comment]
> Can I download this file manually?
> My idea/gradle is slow to download ideaIC-2020.1.1.zip, I tried many many times, always timeout.
> So I have downloaded this zip file by other tools successfully.
> But I don't know how to tell idea to use that file?

me too

**Comment by Nyainqentanglha** [comment]
> > Can I download this file manually?
> > My idea/gradle is slow to download ideaIC-2020.1.1.zip, I tried many many times, always timeout.
> > So I have downloaded this zip file by other tools successfully.
> > But I don't know how to tell idea to use that file?
> 
> me too

me too

**Comment by thomasbigger584** [comment]
me too

**Comment by scxkd2016** [comment]
> > > > Can I download this file manually?
> > > > My idea/gradle is slow to download ideaIC-2020.1.1.zip, I tried many many times, always timeout.
> > > > So I have downloaded this zip file by other tools successfully.
> > > > But I don't know how to tell idea to use that file?
> > > 
> > > 
> > > me too
> > 
> > 
> > me too
> 
> me too

intellij {
    localPath 'D:/Application/IntelliJ IDEA 2022.1'
    version '2018.3.6'
//    version '2020.2'
//    version '2021.2'
}
