### ISSUE TITLE
Run gradle test against with JBR

### ISSUE THREAD

**Issue by izhangzhihao** [JetBrains/gradle-intellij-plugin#473]
I want to run my tests against with JBR, but didn't found any docs about it.

**Comment by izhangzhihao** [comment]
I found to test against with jbr is to [set the jbr to be the java home](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.1/setup-jbr.sh) by jenv.

**Comment by zolotov** [comment]
It's more like a workaround, I think it's better to handle it on gradle-intellij-plugin side. So reopening
