### ISSUE TITLE
Bundled plugin not enabled when run test

### ISSUE THREAD

**Issue by izhangzhihao** [JetBrains/gradle-intellij-plugin#474]
I need the javascript plugin enabled when test running. but I found that, bundled plugin is not enabled even is already added to plugins dependencies:

```gradle
intellij {
    pluginName name
    version 'IU-201.6668.121'
    plugins 'java', 'org.intellij.scala:2020.1.27', 'JavaScriptLanguage', 'CSS'
}
```

A quick test(the second assert failed):

```kotlin
class RainbowJavaScriptTest : LightJavaCodeInsightFixtureTestCase() {
    fun testJavaScriptPluginEnabled() {
        assertTrue(PluginManagerCore.getPlugin(PluginId.getId("org.intellij.scala"))?.isEnabled!!) //true
        assertTrue(PluginManagerCore.getPlugin(PluginId.getId("JavaScript"))?.isEnabled!!) //failed
    }
}
```

Other info:

```
id "org.jetbrains.intellij" version "0.4.18"
```

**Comment by izhangzhihao** [comment]
I found https://github.com/JetBrains/gradle-intellij-plugin/compare/v0.4.12...v0.4.13#diff-277af990756d301d731d16aca2d8d10b , but didn't get how to use this...

**Comment by izhangzhihao** [comment]
Anyone can help? please...

**Comment by zolotov** [comment]
I'll take a look at the issue at some point. Meanwhile, you can to debug it yourself

**Comment by zolotov** [comment]
could you attach idea.log from testing sandbox (build/idea-sandbox/system-test)?

Probably the problem that CSS depends on `platform-images` and fails because it's not loaded in tests.

**Comment by izhangzhihao** [comment]
It works after adding 'platform-images' to plugins dependencies. but by the way, I'm also testing with ruby plugin, maybe there are still some other dependencies missing...

**Comment by izhangzhihao** [comment]
And I didn't find idea.log under sandbox dir

**Comment by izhangzhihao** [comment]
Nevermind, adding `yaml` fix the issue... Thanks~

**Comment by zolotov** [comment]
it still the problem that hard to discover, I'd like to address it, reopening

**Comment by baron1405** [comment]
I too experienced this issue running tests against a plugin with a dependency on the JavaScript ideaIU built-in plugin. Adding `platform-images` as a plugin dependency as suggested fixed the problem. Sure glad someone blazed this trail before me!

* gradle-intellij-plugin version 0.4.18
* Plugin SDK: ideaIU-2020.1
* Platform: CentOS 7.6
* IDE: IntelliJ IDEA Ultimate 2019.3.4

**Comment by YannCebron** [comment]
see "Incompatible Changes" docs https://www.jetbrains.org/intellij/sdk/docs/reference_guide/api_changes/api_changes_list_2020.html#changes-in-intellij-platform-20201 about `platform-images` change
