### ISSUE TITLE
Upgrading plugin from 0.3.12 version

### ISSUE THREAD

**Issue by Gweld** [JetBrains/gradle-intellij-plugin#482]
Hi, during upgrading your plugin to version 0.4.x in mu gradle script,  my Intellij plugin stopped loading to IJ idea. 
I debugged it a little and it looks like class loaders issues. Some of the classes are loading by UrlClassLoader and some are loaded by PluginClassLoader. And IJ does not recognizes classes from openapi. Here some stacktraces in IJ. 
[stacktraces.txt](https://github.com/JetBrains/gradle-intellij-plugin/files/4579853/stacktraces.txt)

**Comment by zolotov** [comment]
the exception doesn't tell anything to me. apparently the classpath is wrong. you should check runtime classpath construction and get know why there are two `com.intellij.openapi.wm.ToolWindowEP` classes in your runtime

**Comment by Gweld** [comment]
ok I checked in runtime and: 
1. During running my plugin, with gradle-intellij-plugin v.0.3.12 openapi classes location is in gradle cache's directory,  in libs of downloaded IJ, so location is the same as IJ binaries
2. 1. During running my plugin, with gradle-intellij-plugin v.0.4.x openapi classes location is in idea-sandbox directory.
Do you think it's the problem?

**Comment by zolotov** [comment]
> Do you think it's the problem?

Yes. And you need understand why they were put there.

**Comment by Gweld** [comment]
I wonder, is this a gradle-intellij-plugin decision, which jar put on classpath? From idea-sandbox or from downloaded IJ ?

**Comment by zolotov** [comment]
both classes should be in the classpath, the question is why did you put it in the sandbox

**Comment by Gweld** [comment]
In both cases: gradle-intellij-plugin v0.3.12 and v0.4.x my plugin jars are copied to idea-sandbox. So I am not sure that's the problem.

**Comment by zolotov** [comment]
I cannot know. Debug it yourself or provide code sample if you want me to help you

**Comment by zolotov** [comment]
> In both cases: gradle-intellij-plugin v0.3.12 and v0.4.x my plugin jars are copied to idea-sandbox. So I am not sure that's the problem.

I've re-read your message. It's not a problem that your plugin's jars are copied sandbox. the problem is that `openapi.jar` is there. Thus you have two `ToolWindowEP` in your classpath which are not equal to each other

**Comment by Gweld** [comment]
Ok, I will check that, thanks for help. But do you know what's changed between version v0.3.12 and 0.4, that earlier version works correctly?

**Comment by zolotov** [comment]
nope

**Comment by YannCebron** [comment]
please provide more details if problem reproduces with latest release (0.5)

**Comment by Gweld** [comment]
No it's still occurs in version 0.5.0. I am getting back to working on workaround

**Comment by Gweld** [comment]
Ok I am trying to refactor our dependencies. I switched to version 0.5.0 and i have problems w extensionPoints defined in plugin.xml. I got following error: 
java.lang.IllegalArgumentException: Missing extension point: com.parasoft.xtest.common.servicesProviderExtension in area null
    at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:328)
    at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:35)
    at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:101)
    at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:89)

On version 0.3.12 it works fine.
There was some changes in handling extension points in version 0.4.0 ?

**Comment by zolotov** [comment]
Gradle-intellij-plugin doesn’t handle extension points. You get the exception from the runtime. It means that it’s unlikely the plugin has something to do with it and that you can debug it.

**Comment by Gweld** [comment]
The problem was that on version 0.4.0+  probably gradle-intellij-plugin copies wrong jars to plugin lib folder. 
I have Base plugin and the plugin that extends base plugin, let's call it Extended plugin. 
On 0.3.12v Base plugin related jars are deployed to sandbox/plugins/Base/lib directory and Extended plugin related jars are correctly deployed to sandbox/plugins/Extended/lib directory. 
But since 0.4v+ I see that Based plugin jars are correctly deployed to sandbox/plugins/Base/lib but in sandbox/plugins/Extended/lib there are jars from both plugins, instead of jars related only to Extended plugin. 
Do you have any idea what changed between 0.3.12 v and 0.4.0v in plugin "to sandbox" deployment,  and how could I fix jars deployment?
