### ISSUE TITLE
Android 4.1 Canary 9 Broken, Corrupted Installation

### ISSUE THREAD

**Issue by Crdzbird** [JetBrains/gradle-intellij-plugin#486]
After update the Android Studio using Jetbrains Toolbox to the latest canary version, an error pop out when the program was starting. saying 

> Missing essential plugin:
> 
>   org.jetbrains.android
> 
> Please reinstall Android Studio from scratch.

![Error Message](https://user-images.githubusercontent.com/7727498/81433157-5852ef80-9121-11ea-8106-0cbe0f677c7f.jpeg)

THe reinstall didn't work and the issue is just for this version.

**Comment by zolotov** [comment]
how gradle-intellij-plugin is related to this?

**Comment by Tatook** [comment]
Hi, I had the sam problem, please help if someone can sovle this.
Thanks in advance

**Comment by somebodydie** [comment]
If you use Mac,
find this /Users/{user}/Library/Application Support/Google/AndroidStudio4.1/disabled_plugins.txt 
open the file and delete the line contains Kotlin plugin,
save it and try to start android studio again.

**Comment by vipul-git-07** [comment]
what if i am using ubuntu?
where will i find this file?

**Comment by hsz** [comment]
@vipul-git-07 Check the [Default IDE directories﻿](https://www.jetbrains.com/help/idea/tuning-the-ide.html#default-dirs) article.
