### ISSUE TITLE
NoClassDefFoundError: com/intellij/codeInspection/AbstractBaseJavaLocalInspectionTool IntelliJ IDEA 2020.1 plugin development

### ISSUE THREAD

**Issue by KrylovAlexeyA** [JetBrains/gradle-intellij-plugin#488]
Hello 
I'm trying to make plugin for static code analysis by JetBrains api , by inspections. 
When I use " intellij {version '2019.3' " in build.gradle settings everything is OK. 
But when I try " intellij {version '2020.1.1' " I get: 
Caused by: java.lang.NoClassDefFoundError: com/intellij/codeInspection/AbstractBaseJavaLocalInspectionTool 
Why idea can't load this class? 
Help , please
[errors.txt](https://github.com/JetBrains/gradle-intellij-plugin/files/4616809/errors.txt)
[build.gradle.txt](https://github.com/JetBrains/gradle-intellij-plugin/files/4616817/build.gradle.txt)

**Comment by YannCebron** [comment]
Please see https://blog.jetbrains.com/platform/2019/06/java-functionality-extracted-as-a-plugin/

Please ask questions in https://intellij-support.jetbrains.com/hc/en-us/community/topics/200366979-IntelliJ-IDEA-Open-API-and-Plugin-Development

**Comment by KrylovAlexeyA** [comment]
It can't help me. It is not that
