### ISSUE TITLE
support adding exclude using regex.

### ISSUE THREAD

**Issue by igreenfield** [JetBrains/gradle-intellij-plugin#490]
In module configuration there is:
![image](https://user-images.githubusercontent.com/5586356/82315469-05f0b900-99d4-11ea-99b9-52ad43b3f880.png)

it will be great if it can be configured from the plugin.

**Comment by YannCebron** [comment]
how is this related to gradle-intellij-plugin?

**Comment by igreenfield** [comment]
this is not the gradle plugin that set the modules?

**Comment by YannCebron** [comment]
please report here https://youtrack.jetbrains.com/issues/IDEA
