### ISSUE TITLE
Plugin does not respect Project_Default.xml

### ISSUE THREAD

**Issue by MatanSabag** [JetBrains/gradle-intellij-plugin#492]
Hello! 

**Details:**

- I am using the plugin version 0.3.2. 
- The idea version I configured is: "ideaIC:2019.1"
- InheritFromIdea=true.
- The project is a single(flat) Gradle project
- I have a custom ` .idea/inspectionProfiles/Project_Default.xml `. Looks like this: [Link](https://paste.googleplex.com/6411748351410176)

**The Issue:**
When I run inspectionsMain, the plugin does not respect the file.
I tried few changes, but no matter what I do the plugin does not care about the custom project_default.xml file.

**Debugging**
I tried to debug it with --info and what I see is: (relevant parts)
```
InspectionPlugin: Before SDK configuration
InspectionPlugin: Configuring JDK 1.8
InspectionPlugin: Home path is /Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home, version string is java version "1.8.0_221"
InspectionPlugin: Before project creation at '/private/tmp/health/eng-prod'
InspectionPlugin: Project SDK name: 1.8
InspectionPlugin: Project SDK: 1.8: java version "1.8.0_221" (/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home)
InspectionPlugin: Under analysis: pure Java module Module: 'eng-prod' with SDK: 1.8: java version "1.8.0_221" (/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home)
InspectionPlugin: Before psi manager creation
InspectionPlugin: Before virtual file manager creation
InspectionPlugin: Before inspections launched: total of 72 files to analyze
InspectionPlugin: InheritFromIdea = true
InspectionPlugin: Error inspections: []
InspectionPlugin: Warning inspections: []
InspectionPlugin: Info inspections: []
InspectionPlugin: Profile file = Project Default
InspectionPlugin: Registered inspections: {}
InspectionPlugin: Inspections from idea: <<<HUGE_LIST_OF_INSPECTION=SEVERITY>>
```

Is this a bug or am i doing something wrong? I tried to follow the exact instructions

**Comment by zolotov** [comment]
Hi, 

> InheritFromIdea=true.

What’s that mean?

> When I run inspectionsMain, the plugin does not respect the file.
I tried few changes, but no matter what I do the plugin does not care about the custom project_default.xml file.

I don’t know what’s the `inspectionsMain`. Links doesn’t work for me too.

Any details on how it’s related to gradle-intellij-plugin are welcome
`0.3.2` is very-very old, I wouldn’t recommend using it, as well as I cannot help you with that.

**Comment by MatanSabag** [comment]
Sorry! I wanted to open this issue for https://github.com/JetBrains/inspection-plugin

**Comment by zolotov** [comment]
ah, got it. I didn't know about that plugin :)
