### ISSUE TITLE
Any way to add dependency on IntelliJ classes without adding the `buildPlugin` etc. tasks?

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/gradle-intellij-plugin#494]
I tried something like 

```gradle
repositories {
  maven {
    url 'https://www.jetbrains.com/intellij-repository/releases'
  }
}

dependencies {
  compileOnly group: 'com.jetbrains.intellij.idea', name: 'ideaIC', version: '2020.1.1'
}
```

but this doesn't seem to actually add the dependency (classes still invisible to the compiler); so I ended up doing sth like:

```gradle
      apply plugin: 'org.jetbrains.intellij'

    // disable all tasks
      buildPlugin.enabled = false
      buildSearchableOptions.enabled = false
      downloadRobotServerPlugin.enabled = false
      jarSearchableOptions.enabled = false
      patchPluginXml.enabled = false
      prepareSandbox.enabled = false
      prepareTestingSandbox.enabled = false
      prepareUiTestingSandbox.enabled = false
      publishPlugin.enabled = false
      runIde.enabled = false
      runIdeForUiTests.enabled = false
      verifyPlugin.enabled = false

      intellij {
        version intellijVersion
     }
```

but this feels like an ugly workaround at best :/

**Comment by zolotov** [comment]
no, it's not supposed to remove tasks declared in the plugin and I don't think there should be a "pretty way" for doing this.

**Comment by PawelLipski** [comment]
Hmmm but what about subprojects of an IntelliJ plugin project? You only ever want to have `buildPlugin` etc. tasks available in the root project (and not in subprojects); but still, you most likely need access to IntelliJ APIs in some/all of the subprojects.

What would be the canonical/idiomatic setup for IntelliJ dependencies then? or is such project structure discouraged for IntelliJ plugins for some reason?

**Comment by zolotov** [comment]
>  You only ever want to have buildPlugin etc. tasks available in the root project (and not in subprojects);

There is nothing wrong with having `buildPlugin` task in subprojects, don't run it if you don't need it. Most of the tasks will be disabled anyway because of missing `plugin.xml`.

> What would be the canonical/idiomatic setup for IntelliJ dependencies then? 

IntelliJ dependency is not a thing actually. IntelliJ is a huge zip archive with many jars and binaries inside. If you need a particular small dependency (like testFramework from https://www.jetbrains.com/intellij-repository/releases, for example), you can depend on it as on a regular Maven-dependency.

> or is such project structure discouraged for IntelliJ plugins for some reason?

Sorry, I don't understand what's the structure you're talking about.

**Comment by PawelLipski** [comment]
Okay, that clarifies the issue, thanks for the quick response!

**Comment by zolotov** [comment]
no problem, sorry that couldn't help
