### ISSUE TITLE
allow multiple pluginsRepo

### ISSUE THREAD

**Issue by i-walker** [JetBrains/gradle-intellij-plugin#495]
Currently, the Gradle plugin only allows one plugin repo.

The use-case here is to load 3rd party plugins, which are not in the marketplace, but still allow the resolution of those from the marketplace. Here is the thread in [slack](https://jetbrains-platform.slack.com/archives/CPL5291JP/p1590653014109600)

Is it possible to enables this for all repositories, for instance - assuming my.plugin.X is in a private repository:
```
intellij {
  version '2020.1.1'
  plugins = ["java", "gradle", "com.jetbrains.edu:3.7-2020.1-5244", "my.plugin.X:<version>"]
  pluginsRepo += [ "http://<urlToBucket>/releases/" ] // in total ["plugins.jetbrains.com/maven", "http://<urlToBucket>/releases/"]
}
```

the same would be applicable for `intellijRepo`,  and `jreRepo`.

I'd be happy to contribute that if one maintainer could guide me through it.

**Comment by zolotov** [comment]
usually, self-hosted maven repos can be a proxy for other repositories (e.g. maven-central). isn't this the case for you? can you proxying plugins.jetbrains.com in your private repository?

Anyway, if you want to contribute, take a look at `org.jetbrains.intellij.IntelliJPluginExtension#pluginsRepo` and its the only usage. Converting string to array of string looks not complicated in that particular place.

**Comment by YannCebron** [comment]
this is fixed? https://github.com/JetBrains/gradle-intellij-plugin/#infrastructure-properties
