### ISSUE TITLE
How can you add configurations in kotlin script

### ISSUE THREAD

**Issue by elect86** [JetBrains/gradle-intellij-plugin#496]
As titled, I need to rewrite this groovy snippet in kts:

```
project.idea {
   module {
      scopes.TEST.plus += [project.configurations.jmh]
   }
}
```

So far I wrote:
```
val idea = project.plugins.getAt(IdeaPlugin::class.java)
idea.model.module {
   ..
}
```

but I have no idea how to continue..

`scopes` is a `MutableMap<String, MutableMap<String, MutableCollection<Configuration>>>`

any hint?

**Comment by zolotov** [comment]
It doesn't look like something that relates `gradle-intellij-plugin`, do you use it?

**Comment by elect86** [comment]
It's the jmh-gradle-plugin, it has a [function](https://github.com/melix/jmh-gradle-plugin/blob/master/src/main/groovy/me/champeau/gradle/JMHPlugin.groovy#L101-L104) that configures the configure ide support, by adding jmh custom configuration to the test scope and its files to the test sources.

Reading in the [docs](https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.idea.model.IdeaModule.html), it says that there are 

> two keys, plus and minus

Where do I find the keys itself definitions?

**Comment by zolotov** [comment]
I'm sorry but since you don't use `gradle-intellij-plugin`, it's not the right tracker to ask for help.

**Comment by elect86** [comment]
Sorry, my bad, I got confused

**Comment by zolotov** [comment]
No problem. Try gradle repo
