### ISSUE TITLE
Feature request: inspection task

### ISSUE THREAD

**Issue by hurricup** [JetBrains/gradle-intellij-plugin#500]
I'd like to be able to configure my tests to depend on task, which will check my codebase with configurable set of inspections provided with intellij idea.

I see this like a separate optional task like `inspectCode` with DSL describing inspections I'd like to run. Scopes should be configured too to be able to exclude some dirs at least.

**Comment by zolotov** [comment]
probably it should be a separate plugin as it solves a bit wider problem, and intellij-devkit inspection is just a `subset` of what should be done.

**Comment by hurricup** [comment]
Won't such a plugin depend on this one? It will need IDEA to run inspections and CI don't have one.

**Comment by YannCebron** [comment]
https://blog.jetbrains.com/idea/2021/02/early-access-program-for-qodana-a-new-product-that-brings-the-smarts-of-jetbrains-ides-into-your-ci-pipeline/ ?

**Comment by zolotov** [comment]
thanks. closing the issue in favor of qodana
