### ISSUE TITLE
idea.auto.reload.plugins not work?

### ISSUE THREAD

**Issue by lionoggo** [JetBrains/gradle-intellij-plugin#501]
When i develop a Intellij plugin, how configure the plugin to enable auto reload?the "idea.auto.reload.plugins" is for reloading IDE dynamic plugins, but after modifying the code and  runIde, the code does not take effect? Am I using it wrong?

build.gradle:
plugins {
  id 'java'
  id 'org.jetbrains.intellij' version '0.4.21'
}

group 'org.intellij.sdk'
version '2.0.0'

sourceCompatibility = 1.8

repositories {
  mavenCentral()
}

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
  version = '2020.1'

}

buildSearchableOptions {
  enabled = false
}

patchPluginXml {
  version = project.version
  sinceBuild = '201'
  untilBuild = '201.*'
}

**Comment by YannCebron** [comment]
check your sandbox `idea.log` https://www.jetbrains.org/intellij/sdk/docs/basics/ide_development_instance.html#the-development-instance-sandbox-directory for any errors

**Comment by lionoggo** [comment]
> check your sandbox `idea.log` https://www.jetbrains.org/intellij/sdk/docs/basics/ide_development_instance.html#the-development-instance-sandbox-directory for any errors

Now it works fine. Thanks!
