### ISSUE TITLE
Platform SDK 2020.1 uses kotlin-reflect incompatible with Kotlin 1.4-M2

### ISSUE THREAD

**Issue by abelkov** [JetBrains/gradle-intellij-plugin#503]
Please see the original issue and sample project: https://youtrack.jetbrains.com/issue/KT-39428.

When the user project has a dependency on "org.jetbrains.kotlin:kotlin-reflect:1.4-M2", the build issues a warning:

```
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/belkov/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2020.1/cbeeb1f1aebd4c9ea8fb5ab990c5904a676fc41a/ideaIC-2020.1/lib/kotlin-reflect-1.3.70.jar (version 1.3)
    /home/belkov/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4-M2/f5c715a2d22ea3366efc7091eb8e99afd27a63e0/kotlin-reflect-1.4-M2.jar (version 1.4)
    /home/belkov/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.4-M2/b104b1e104def0bfede384d62d838a1fac83cdf7/kotlin-stdlib-jdk8-1.4-M2.jar (version 1.4)
    /home/belkov/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.4-M2/c7b7714375635f2c4e7756260d245b7d8630c7d1/kotlin-stdlib-jdk7-1.4-M2.jar (version 1.4)
    /home/belkov/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4-M2/fe202588710b343e23b63fcca12d2dcae77608eb/kotlin-stdlib-1.4-M2.jar (version 1.4)
    /home/belkov/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4-M2/83a2b1b2994ac4f8857864ba98987a246e2e9a18/kotlin-stdlib-common-1.4-M2.jar (version 1.4)
w: Consider providing an explicit dependency on kotlin-reflect 1.4 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
```

It doesn't seem possible to exclude the 1.3.70 dependency via usual Gradle means.

**Comment by ingokegel** [comment]
In general, specifying an explicit Kotlin dependency should remove the built-in Kotlin libraries from the classpath.

**Comment by mikesamuel** [comment]
@ingokegel Where should that dependency go?

**Comment by ingokegel** [comment]
There is a Kotlin version in the IDEA library. If you then add the Kotlin plugin explicitly, you now have 2 Kotlin versions on the compile classpath. If the minor versions are different, like 1.3 and 1.4, the Kotlin compiler complains.

**Comment by rgoldberg** [comment]
1. With what versions of Kotlin is this plugin compatible?
2. If the build has a dependency on Kotlin outside this plugin, can this plugin be changed to depend on Kotlin artifacts that are the same version as the external dependency?  Possibly by using a Gradle platform dependency?

I tried adding the following to my `dependencies` lambda, but it didn't solve the problem:

```kotlin
implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.4.10"))
```

**Comment by henryju** [comment]
Tested with plugin version 0.7.3 and I still have the problem.

**Comment by zolotov** [comment]
@henryju according to your comment on another issue, the problem you have is not the one described here

**Comment by zored** [comment]
My current walkaround in `build.gradle.kts`:
```
dependencies {
    implementation(platform("org.jetbrains.kotlin:kotlin-reflect:1.5.0-RC"))
}
```

**Comment by Ancham** [comment]
You can force kotlin-reflect version like this by adding resolutionStrategy in build.gradle
`configurations.all {
    resolutionStrategy {
        force "org.jetbrains.kotlin:kotlin-reflect:1.4.30"
    }
}`
