### ISSUE TITLE
untilBuild implicitly set

### ISSUE THREAD

**Issue by ArtsiomCh** [JetBrains/gradle-intellij-plugin#505]
untilBuild implicitly set to the Idea version plugin is built against. Is this a bug or a feature?
I.e. if I only specify `sinceBuild 192` and not untilBuild then in patched plugin.xml I see `until-build="201.*"` inserted (when I build plugin under 201). 
I would expect if untilBuild is not set explicitly then it means I would like to have plugin available in all future versions of Idea and nothing should be placed into plugin.xml.

PS `id 'org.jetbrains.intellij' version '0.4.18'`

**Comment by zolotov** [comment]
This is the documented feature, overwriting is also represented in the build log.

> I would expect if untilBuild is not set explicitly then it means I would like to have plugin available in all future versions of Idea and nothing should be placed into plugin.xml.

In my experiences, it ends with broken plugins that in the best case just doesn't work and irritates users, and in the worst – breaks the entire IDE. So the default behavior is to limit plugin compatibility withing a single major release. But if you're experienced plugin-writer, you always can redefined the behavior by modifying `patchPluginXml` task

**Comment by ArtsiomCh** [comment]
For the complicated plugin I would agree with you. 
But for the simple "enhancement" plugins I will just set 
`untilBuild 999` 
and keep it until it actually breaks.
