### ISSUE TITLE
Can not set up open-end `until-version` with patchPluginXml task

### ISSUE THREAD

**Issue by iBavtovich** [JetBrains/gradle-intellij-plugin#506]
There is a next information in [docs](https://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/gradle_guide.html#patching-the-plugin-configuration-file):
> Or, for independent control, set patchPluginXml.sinceBuild(null) and patchPluginXml.untilBuild(null) depending on whether the intention is to disable one or both substitutions.

But in my case setting `patchPluginXml.untilBuild(null)` is translated to `until-build="_PLACEHOLDER_"` in plugin.xml file. But I expect this attribute should not be present in the file at all. 
Gradle plugin version: 0.4.21

Is the documentation outdated or there is some bug in gradle plugin?

**Comment by ForNeVeR** [comment]
[This `build.gradle`](https://github.com/ForNeVeR/file-link-executor/blob/ac1f11790b083d3ac09ea05f9bdd1cc37c23ce3b/build.gradle#L21-L22) seem to work well for me. Could you check it out and find any significant discrepancies from yours?

**Comment by iBavtovich** [comment]
Thanks. I found that in my plugins `plugin.xml` there is next line:
` <idea-version since-build="_PLACEHOLDER_" until-build="_PLACEHOLDER_" />`
After removing this line completely, the new one was generated without `until-build` value. 
So know clear: plugin only overrides/adds attributes value, not remove from the resulting file in case if value is `null`.
