### ISSUE TITLE
RunIde project dependency not working from inntellij

### ISSUE THREAD

**Issue by Jonatha1983** [JetBrains/gradle-intellij-plugin#508]
Hi 

We have a 2 modules in our plugins. Project A is the plugin and it depends on another project B. 

When we do some changes do module B  and we run the runIde task  of module A from within Intellij we don't see those changes. 

When checking the taskTree of runIdee we see this:
```
:**moduleA**:runIde
\--- :**moduleA**:prepareSandbox
     \--- :**moduleA**:jar
          +--- :**moduleA**:classes
          |    +--- :**moduleA**:compileJava
          |    |    \--- :**moduleB**:compileJava
          |    \--- :**moduleA**:processResources
```
can it be that the runIde take the jar of B in the classPath and since it is not repack we dont see it ? 

IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on June 1, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
Gradle 6.5
Plugin 0.4.21

Thanks ahead

**Comment by zolotov** [comment]
Hi. 

> can it be that the runIde take the jar of B in the classPath and since it is not repack we dont see it ?

Probably, how do you declare a dependency on `project B`

**Comment by Jonatha1983** [comment]
> Probably, how do you declare a dependency on `project B`?

implementation project(":B")

**Comment by kobi26c** [comment]
+1
