### ISSUE TITLE
After running runIde, how to Change Memory Settings in IDE Development Instances

### ISSUE THREAD

**Issue by scil** [JetBrains/gradle-intellij-plugin#516]
The `Change Memory Settings`  is gray, as following 

![image](https://user-images.githubusercontent.com/2786775/86952252-4a533680-c185-11ea-98a9-ba2a9b2dff10.png)

How can I edit it?

**Comment by YannCebron** [comment]
Set VM properties as explained here https://github.com/JetBrains/gradle-intellij-plugin/blob/master/FAQ.md#how-to-modify-jvm-arguments-of-runide-task

**Comment by scil** [comment]
Thank you.

It works

``` 
// build.gradle.kts
tasks{
    runIde {
        jvmArgs("-Xmx2000m")
    }
}
```
