### ISSUE TITLE
What Is The Oldest Version Supported By This Plugin?

### ISSUE THREAD

**Issue by opticyclic** [JetBrains/gradle-intellij-plugin#517]
I can't tell from the README what is the oldest version supported by this plugin.
Please update the README with details of the oldest version of IDEA supported.

**Comment by YannCebron** [comment]
duplicate of #452 and already answered there

**Comment by opticyclic** [comment]
Bug reports are not documentation.
I can't work out what is the oldest version supported from the current documentation.
Hence this issue.

**Comment by YannCebron** [comment]
The answer was given very detailed in the other bug report already.
It was also added to the README, section "IntelliJ Platform Properties":

> All available JetBrains IDEs versions can be found at IntelliJ Artifacts page.

I've also replicated this information into the Gradle SDK Docs Guide
https://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/gradle_guide.html under "IntelliJ Platform Configuration"
