### ISSUE TITLE
Support running single test

### ISSUE THREAD

**Issue by dlsniper** [JetBrains/gradle-intellij-plugin#52]
Hi,

Gradle supports running a single test like this:
- specific class:
```
./gradlew cleanTest test --tests com.goide.inspections.GoHighlightingTest
```
- specific test method:
```
./gradlew cleanTest test --tests com.goide.inspections.GoHighlightingTest.testSimple
```

Is there anyway for the plugin to override the test running functionality of the IDE when the project is managed via Gradle so that this functionality can be used? Right now the IDE will try it to run in a classic way and it makes running / debugging a single a bit inconvenient.

And I guess since the IDE doesn't recognize that the project is managed with Gradle it doesn't allow UI interaction such as running / debugging a test from the test UI, no?

Thank you.

**Comment by zolotov** [comment]
> Is there anyway for the plugin to override the test running functionality of the IDE when the project is managed via Gradle so that this functionality can be used? 

This plugin has nothing to do with IDE. It's plugin for gradle, not for IDEA.

> Right now the IDE will try it to run in a classic way

What's a classic way?
