### ISSUE TITLE
help building and running plugin

### ISSUE THREAD

**Issue by rishabhdeepsingh** [JetBrains/gradle-intellij-plugin#523]
When I use `runIde` command the plugin works perfectly, but then after `buildPlugin` and installing from disk I am not able to open/create any project. CLion just blinks and does nothing. After removing the plugin from CLion it is working perfectly.

- My CLion - 2020.2
- Build CLion - 2020.2

`build.gradle`
```
plugins {
    id 'java'
    id 'org.jetbrains.intellij' version '0.4.21'
}

group 'com.example.plugin'
version '0.19'

repositories {
    mavenCentral()
}


sourceSets {
    main.java.srcDirs = ['src']
    main.resources.srcDirs = ['resources', 'lib']
}

runIde {
    jvmArgs '--add-exports', 'java.base/jdk.internal.vm=ALL-UNNAMED'
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile fileTree(dir: 'lib', include: 'jar_to_added.jar')
}

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
    version '2020.2'
    updateSinceUntilBuild false
    type 'CL'
}
```

**Comment by zolotov** [comment]
Check the logs of CLion

**Comment by zolotov** [comment]
```
runIde {
    jvmArgs '--add-exports', 'java.base/jdk.internal.vm=ALL-UNNAMED'
}
```

Is this required? If so, do you think that CLion that you run also has this arguments?

**Comment by rishabhdeepsingh** [comment]
how do I check logs? as there is no error that I am getting.
when I run it on Intellij Idea. it was showing an error that you should add this to the VM Options

**Comment by zolotov** [comment]
`Help | Collect Logs and Diagnostic Data` menu item

**Comment by rishabhdeepsingh** [comment]
looks like I installed the wrong one. I installed the one in the `build/lib` folder.
The actual folder should be `build/distribution`
