### ISSUE TITLE
RFE: Implement task configuration avoidance as recommended for Gradle 5.1 and later

### ISSUE THREAD

**Issue by roofpig95008** [JetBrains/gradle-intellij-plugin#524]
Recommendation is here: https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

I find I specifically need this in Gradle 6.0 and later, because I have a multi-project environment and need to disable the runIde tasks on the 'subprojects.' I was doing this by redefining the task, but in 6.0 I cannot do that anymore unless configuration avoidance is implemented.

The compilation avoidance APIs are available for min. version 4.9, and there are techniques for being backward compatible with earlier versions of Gradle: https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:task_configuration_avoidance_backward_compatibility_migration

**Comment by rgoldberg** [comment]
What is the oldest version of Gradle that this plugin must still support?

**Comment by zolotov** [comment]
@rgoldberg now 4.9 is the minimal supported version

**Comment by rgoldberg** [comment]
@zolotov Thanks. So it sounds like configuration avoidance might be able to be used here without requiring any workarounds for older versions of Gradle that don't support it, because those versions aren't supported by this plugin.

**Comment by YannCebron** [comment]
according to survey https://twitter.com/JBPlatform/status/1349293135172669440?s=20 nearly everyone is using  Gradle 6.x

**Comment by hsz** [comment]
Implemented with 1.0
