### ISSUE TITLE
publishPlugin: Any way to publish multiple?

### ISSUE THREAD

**Issue by matkoch** [JetBrains/gradle-intellij-plugin#526]
For Rider/ReSharper plugins a build should upload both plugin archives (nupkg + zip). Is there any way to get there?

This is the general repository structure: https://github.com/matkoch/resharper-cognitivecomplexity

**Comment by zolotov** [comment]
all rider plugins require that? Where should it be uploaded and why?

**Comment by ForNeVeR** [comment]
No, not all of them. Let's say it's for ReSharper plugins that also got ported to Rider. You may call them "ReSharper+Rider": they release their builds for both R# and Rider simultaneously.

**Comment by matkoch** [comment]
And they'll go to https://resharper-plugins.jetbrains.com/ Afaik, the endpoint is the same.

**Comment by zolotov** [comment]
AFAIK, the plugin doesn't fit for developing resharper plugins. If you want to upload something, I don't think it should be part of gradle-intellij-plugin. I think creating your own task for that or creating a separate `gradle-resharper-uploader` plugin are better solutions.

**Comment by matkoch** [comment]
@zolotov it's already there... the only thing missing is the upload: https://github.com/matkoch/resharper-cognitivecomplexity/blob/master/build.gradle#L55-L63

**Comment by matkoch** [comment]
And from user perspective, I only want to call for publishing once.

**Comment by zolotov** [comment]
> And from user perspective, I only want to call for publishing once.

It's your build script, you free to configure in any way you want

Publishing code is already shared via org.jetbrains.intellij:plugin-repository-rest-client library, feel free to use

```
def repoClient = PluginRepositoryFactory.create(host, getToken())
repoClient.uploader.uploadPlugin(pluginId, distributionFile, channel && 'default' != channel ? channel : null, null)
```

**Comment by zolotov** [comment]
Resolution is the following:

- multiple uploads are possible as gradle allows to create as many tasks you need of particular type (e.g. PublishTask)
- gradle-intellij-plugin doesn't fit for uploading arbitrary file to plugins.jetbrains.com. There is a dedicated library for that

won't fix
