### ISSUE TITLE
 Cannot resolve JBR at alternativeIdePath 

### ISSUE THREAD

**Issue by myfirenze** [JetBrains/gradle-intellij-plugin#531]
I set the localPath and  alternativeIdePath to local AS path .
  intellij {
        plugins = ['android', "IntelliLang", 'gradle', 'Groovy', 'properties', 'smali', 'junit', 'java']
        buildSearchableOptions.enabled = false
        updateSinceUntilBuild false
        downloadSources Boolean.valueOf(sources)
        sameSinceUntilBuild Boolean.valueOf(isEAP)
        if (project.hasProperty('localIdePath')) {
            localPath property('localIdePath')
            alternativeIdePath localPath
        } else {
            if (System.getenv().containsKey("localIdePath")) {
                localPath System.getenv("localIdePath")
                alternativeIdePath localPath
            } else {
                version ideaVersion
            }
        }
It cannot resolve JBR in AS path when executing task ‘runIde'

[gradle-intellij-plugin :build-system:runIde] Cannot resolve JBR at D:\Program Files\Android\Android Studio\jbr\bin\java. Falling back to builtin JBR.
[gradle-intellij-plugin :build-system:runIde] Cannot resolve JBR at D:\Program Files\Android\Android Studio\jbr\bin\java. Falling back to builtin JBR.
[gradle-intellij-plugin :certificate-mgmt:runIde] Cannot resolve JBR at D:\Program Files\Android\Android Studio\jbr\bin\java. Falling back to builtin JBR.
[gradle-intellij-plugin :certificate-mgmt:runIde] Cannot resolve JBR at D:\Program Files\Android\Android Studio\jbr\bin\java. Falling back to builtin JBR.
'
![image](https://user-images.githubusercontent.com/37723136/92562482-a4b56400-f2a8-11ea-8ba2-ae29c13eb475.png)

The java excutable file is 'jbr/bin/java.exe' in windows 
![image](https://user-images.githubusercontent.com/37723136/92563513-438e9000-f2aa-11ea-893d-b723d9d89963.png)

**Comment by zolotov** [comment]
We do not control the AS distribution and its layout, as well as any other IDE that can be set in `alternativeIdePath`. Fallback to current JDK is expected. If you want to use another jbr, you can set it via [Running DSL](https://github.com/JetBrains/gradle-intellij-plugin#running-dsl)
