### ISSUE TITLE
Resolve plugin dependencies against an enterprise plugin repository

### ISSUE THREAD

**Issue by baron1405** [JetBrains/gradle-intellij-plugin#535]
Hello @zolotov, hope all is well with you in these crazy times. In our company we have an Enterprise plugin repository in which we have all our proprietary plugins. Our IntelliJ users have that repository URL added to their IDEs so they can install our plugins and receive notifications of new plugins. The need has come up for our plugin development to depend on plugins that are in our Enterprise repository. I know that the gradle-intellij-plugin can resolve built-in plugin dependencies as well as third party plugin dependencies from the JetBrains plugin repository. Is it possible to resolve dependencies from additional plugin repositories such as our Enterprise repository? Thanks in advance for any guidance on this question.

**Comment by zolotov** [comment]
Hi Baron. Please check out the `pluginsRepo` block here https://github.com/JetBrains/gradle-intellij-plugin#infrastructure-properties. Since 0.5-SNAPSHOT it supports specifying several repos, including Enterprise ones.

the instruction about using the snapshot here: https://github.com/JetBrains/gradle-intellij-plugin#snapshot-version

**Comment by baron1405** [comment]
Thanks for the quick reply, that is great news! Any estimate as to when 0.5 will be released?

**Comment by zolotov** [comment]
I hope to publish it on this or on the next week

**Comment by zolotov** [comment]
duplicates #15

**Comment by zolotov** [comment]
sorry for the delay, the release was blocked by #537. going to give snapshot a couple more days and then publish 0.5 release

**Comment by baron1405** [comment]
Thanks @zolotov for the 0.5.0 release. The pluginsRepo feature is exactly what we needed and it works great!

Cheers,
Baron

**Comment by zolotov** [comment]
Good to hear that. Thanks for the update. Kudos to @piotrtomiak :)
