### ISSUE TITLE
0.4.25 depends on missing blockmap 1.0.5

### ISSUE THREAD

**Issue by jonathanlermitage** [JetBrains/gradle-intellij-plugin#537]
0.4.25 release depends on blockmap 1.0.5, which is not published yet on regular repositories.

```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.jetbrains.intellij:blockmap:1.0.5.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/jetbrains/intellij/blockmap/1.0.5/blockmap-1.0.5.pom
       - file:/C:/Users/jonat/.m2/repository/org/jetbrains/intellij/blockmap/1.0.5/blockmap-1.0.5.pom
       - https://jcenter.bintray.com/org/jetbrains/intellij/blockmap/1.0.5/blockmap-1.0.5.pom
       - https://plugins.gradle.org/m2/org/jetbrains/intellij/blockmap/1.0.5/blockmap-1.0.5.pom
     Required by:
         project : > org.jetbrains.intellij:org.jetbrains.intellij.gradle.plugin:0.4.25 > gradle.plugin.org.jetbrains.intellij.plugins:gradle-intellij-plugin:0.4.25 > org.jetbrains.intellij:plugin-repository-rest-client:2.0.15
```

**Comment by zolotov** [comment]
as a workaround, please add this to your buildscript

```
buildscript {
  repositories {
    maven { 
      url 'https://jetbrains.bintray.com/intellij-plugin-service' 
    }
}
```

**Comment by ziscloud** [comment]
0.4.26 also has this issue

**Comment by zolotov** [comment]
yes, we know the reason, working on the fix

**Comment by aoidev** [comment]
is there any solution to temp fix this？

**Comment by aoidev** [comment]
> as a workaround, please add this to your buildscript
> 
> ```
> buildscript {
>   repositories {
>     maven { 
>       url 'https://jetbrains.bintray.com/intellij-plugin-service' 
>     }
>   }
> }
> ```

I use this，but dont work.

**Comment by hannesa2** [comment]
This works on my side

```
// workaround for https://github.com/JetBrains/gradle-intellij-plugin/issues/537
pluginManagement {
    repositories {
        maven{
            url 'https://jetbrains.bintray.com/intellij-plugin-service'
        }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        mavenCentral()
    }
}
```

**Comment by zolotov** [comment]
fixed

**Comment by hannesa2** [comment]
> fixed

Please can you link to the commit, currently the last commit is 3 h in advance of your message

**Comment by zolotov** [comment]
there is no commit

**Comment by hannesa2** [comment]
but why it's fixed then ?

**Comment by zolotov** [comment]
well, because it's fixed. if you still have any problems with that, please file the new issue with logs and steps to reproduce the problem.

**Comment by hannesa2** [comment]
> well, because it's fixed. 

Sorry, it's a rumor https://github.com/JetBrains/gradle-intellij-plugin/issues/537#issuecomment-699594212

**Comment by zolotov** [comment]
We have fixed it an hour ago minutes ago, your comment has nothing to do with that
