### ISSUE TITLE
Add plugin without specifying version

### ISSUE THREAD

**Issue by olivernybroe** [JetBrains/gradle-intellij-plugin#543]
## Description
It would be so awesome if I could add plugins without having to specify their version also.  
e.g.
```
setPlugins('com.jetbrains.php')
```
### Issue
So I basically only develop plugins for phpstorm and I often wanna run them against EAP. However doing that is a gigantic hazel.  
Using EAP version of IntelliJ is easy, that's just setting the version to `LATEST-EAP-SNAPSHOT`.
However then I want to use a compatible php plugin version, so I have to go to the plugin website, find a matching version and copy the version number.  

Then the next day when I want to continue working on it, a new EAP was released and I then have to go to the plugin website to get the new matching version. It would be sooo nice if it found the latest compatible version automatically 👍 

My current workflow is just to not test against EAP as that is to much extra work.

**Comment by YannCebron** [comment]
There could be several compatible plugin versions available at the same time

**Comment by olivernybroe** [comment]
@YannCebron Yes, but I think a sensible default would be to use the newest version? 

For example if I install a plugin in the IDE, I would expect it to install the newest version. If I wanted to use an older version than the newest, I should specify that specifically.

**Comment by hsz** [comment]
@olivernybroe What if the latest released version doesn't cover the IDE you use for building the plugin?

**Comment by olivernybroe** [comment]
Then I should get an error maybe.

My thoughts were just if this change would make sense as that is how the IDE handles it normally.

@hsz I totally get your point though, and might still just give a bunch of other problems when using `LATEST-EAP-SNAPSHOT`. 

I guess my real issue is just that I find that I have to go through a lot of steps to find a compatible version with the IDE version I am using. And it would be nice if we in some way could simplify this process.

**Comment by hsz** [comment]
Maybe we can handle it within the DevKit plugin instead with some kind of autocomplete?
It'll already know the current target version, so we can ask the Marketplace API (some implementation would be necessary on their side as well) for the matching plugin versions.
What do you think about that @YannCebron?

**Comment by hsz** [comment]
Ok, in fact we already have such endpoint available:
```
curl -X POST -H "Content-Type: application/json" https://plugins.jetbrains.com/api/search/compatibleUpdates --data "{\"pluginXMLIds\": [\"com.jetbrains.php\"], \
"build\": \"IU-202.7706\"}"
```

**Comment by olivernybroe** [comment]
I think that would be amazing solution and help a lot of users out!

Just a note on that, versions are defined in the properties file when using the plugin template 👍

**Comment by funivan** [comment]
I have the same problem. Figuring out what PHP plugin is compatible with LATEST-EAP-SNAPSHOT is a pain.
Would be great if there will be any solution.

**Comment by YannCebron** [comment]
There's this issue regarding code insight/validation for plugin.xml/Gradle within the IDE https://youtrack.jetbrains.com/issue/IDEA-252797.

**Comment by YannCebron** [comment]
There is no clear solution to this issue. Closing for now.
