### ISSUE TITLE
Allow configuration of sandbox directory per task

### ISSUE THREAD

**Issue by dlsniper** [JetBrains/gradle-intellij-plugin#55]
As per discussion from https://youtrack.jetbrains.com/issue/IDEA-149799 it would be nice if the plugin could allow setting of different sandbox folders per task.

It could come with a few predefined folders such as:

- `build/runIdea-sandbox` for the `runIdea` task
- `build/test-sandbox` for the `test` task.

Thank you.

**Comment by Turbo87** [comment]
I don't think it makes much sense to have one for *every* task... `build/clean-sandbox` obviously wouldn't make much sense and there are many others like that too. I would make sense though to have one for testing and one for production/debugging.

**Comment by zolotov** [comment]
@Turbo87 I agree. Also there will be prepareTestSandbox and prepareSandbox tasks in order to have separate clean-tasks for them.
