### ISSUE TITLE
runPluginVerifier: release 2020.1 seems to be resolved to build 202.7660.26 rather than 201.6668.121

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/gradle-intellij-plugin#553]
See https://github.com/VirtusLab/git-machete-intellij-plugin/pull/637/files for a sample PR where this happens.

Full build logs can be seen under https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/3675/workflows/8c46c821-3518-4a1b-be9e-c03268609d37/jobs/3851 , step `Verify binary compatibility with supported IntelliJ versions` (failure of this pipeline is expected and **not** related to this very issue).

First we get:

```
2020-10-29T18:41:08 [main] INFO  verification - Reading IDE /root/.pluginVerifier/ides/IC-2020.1
2020-10-29T18:41:12 [main] INFO  verification - Reading IDE /root/.pluginVerifier/ides/IC-2020.1.4
2020-10-29T18:41:15 [main] INFO  verification - Reading IDE /root/.pluginVerifier/ides/IC-2020.2.3
2020-10-29T18:41:18 [main] INFO  verification - Reading IDE /root/.pluginVerifier/ides/IC-203.5251.39
```

which is expected, but later the actual verification runs against:

```
Scheduled verifications (4):
com.virtuslab.git-machete:0.8.1-32-SNAPSHOT+git.a833b4c against IC-202.7660.26,
com.virtuslab.git-machete:0.8.1-32-SNAPSHOT+git.a833b4c against IC-201.8743.12,
com.virtuslab.git-machete:0.8.1-32-SNAPSHOT+git.a833b4c against IC-202.7660.26,
com.virtuslab.git-machete:0.8.1-32-SNAPSHOT+git.a833b4c against IC-203.5251.39
```

so 201.6668.121 (2020.1) seems to be missing and, surprisingly, replaced with one more instance of 202.7660.26 (2020.2.3)... which also happens to be the version against which the plugin is being built.

**Comment by hsz** [comment]
Ok, it appears that there's an issue with the service that resolves IDE download URLs - for major versions, like `2020.1`, there's the latest stable returned - `2020.2.3` as for now.

Anyway, I've got in touch with the team lead responsible for that and I got also confirmation, that some IDEs are removed i.e. due to security reasons: `WS-2019.1.2`, `PY-2019.1.2` + all major releases, so `2020.1` is not present on CDN anyway.

Please keep in mind that these versions are not listed within the Marketplace dashboard as well:
![image](https://user-images.githubusercontent.com/108333/97718428-3762ca00-1ac6-11eb-9bac-f8b4c70986ed.png)

I'll try to find out the best way to provide an up-to-date list of the IDE versions available for testing with the Plugins Verifier.

**Comment by PawelLipski** [comment]
Ok! good to know, thanks :)
This implies that possibly caring for compatibility with 2020.1 specifically isn't that important... also, are there any guarantees by design like `if, for the given release A.B (e.g. 2020.1), plugin is compatible with any A.B.C (e.g. 2020.1.4), then it's compatible all A.B.*`?

**Comment by hsz** [comment]
Minor releases introduce rather bug fixes and should not introduce breaking changes like the method signatures modifications of the `2020.1`.

FYI: there's [Incompatible Changes in IntelliJ Platform and Plugins API](https://jetbrains.org/intellij/sdk/docs/reference_guide/api_changes_list.html) section in SDK Docs available that utilizes all breaking changes introduced in time.

**Comment by hsz** [comment]
The proper fix is provided. When there'll be a source of truth available regarding the available IDE versions that can be provided to the Plugin Verifier, it'll be linked within the stack trace and documentation.

**Comment by PawelLipski** [comment]
@hsz is there an ETA for v0.6.2 that would include this fix? ;)

**Comment by gamerson** [comment]
> @hsz is there an ETA for v0.6.2 that would include this fix? ;)

Also trying to add 0.7.0-SNAPSHOT seems to not work.  Last few snapshots here are missing the jar file: https://oss.sonatype.org/content/repositories/snapshots/org/jetbrains/intellij/plugins/gradle-intellij-plugin/org.jetbrains.intellij.plugins.gradle-intellij-plugin/0.7.0-SNAPSHOT/

**Comment by hsz** [comment]
The list of the available products that can be used for testing is here: https://jb.gg/intellij-platform-builds-list

**Comment by AlexPl292** [comment]
Wow, cool! What is the proposed usage of this link? Just open it and find the products or there is some integration with the plugin?
Also, I may be wrong, but last time I've tried to check against 2020.2.1, 2020.1.2, and 2020.1.1 they were unavailable, but they are presented in this list.

**Comment by hsz** [comment]
_Probably shortened URL is not yet refreshed - valid target URL is_:
> https://data.services.jetbrains.com/products?fields=code,name,releases.downloads,releases.version,releases.build&code=DG,PS,DL,MPS,MPSIIP,RDCPPP,WS,AC,IIC,IIE,GO,CL,PCD,PCC,RD,PCE,IIU,RM,PCP

That's a raw dataset from the data.services - the quickest solution I could provide for the listing of available product versions.
Each item contains, i.e.:

```
{
  type: "release",
  downloads: {
    sourcesArchive: {
      link: "https://github.com/JetBrains/intellij-community/archive/idea/201.8538.31.zip",
      size: 0,
      checksumLink: "https://github.com/JetBrains/intellij-community/archive/idea/201.8538.31.zip.sha256"
    },
    linux: {
      link: "https://download.jetbrains.com/idea/ideaIC-2020.1.3.tar.gz",
      size: 641212612,
      checksumLink: "https://download.jetbrains.com/idea/ideaIC-2020.1.3.tar.gz.sha256"
    },
    linuxWithoutJBR: {
      link: "https://download.jetbrains.com/idea/ideaIC-2020.1.3-no-jbr.tar.gz",
      size: 529511746,
      checksumLink: "https://download.jetbrains.com/idea/ideaIC-2020.1.3-no-jbr.tar.gz.sha256"
    },
    thirdPartyLibrariesJson: {
      link: "https://download.jetbrains.com/idea/ideaIC-2020.1.3-third-party-libraries.json",
      size: 35811,
      checksumLink: "https://download.jetbrains.com/idea/ideaIC-2020.1.3-third-party-libraries.json.sha256"
    },
    windows: {
      link: "https://download.jetbrains.com/idea/ideaIC-2020.1.3.exe",
      size: 572771320,
      checksumLink: "https://download.jetbrains.com/idea/ideaIC-2020.1.3.exe.sha256"
    },
    windowsZip: {
      link: "https://download.jetbrains.com/idea/ideaIC-2020.1.3.win.zip",
      size: 633144712,
      checksumLink: "https://download.jetbrains.com/idea/ideaIC-2020.1.3.win.zip.sha256"
    },
    mac: {
      link: "https://download.jetbrains.com/idea/ideaIC-2020.1.3.dmg",
      size: 634690438,
      checksumLink: "https://download.jetbrains.com/idea/ideaIC-2020.1.3.dmg.sha256"
    }
  },
  version: "2020.1.3",
  build: "201.8538.31"
}
```

The `downloads` property points out that the version is available via CDN - but we're not going to rely on these URLs.

If `type` is `release` - use `2020.1.3§, otherwise - `build` property should be used.

**Comment by hsz** [comment]
`v0.6.2` is now available.
