### ISSUE TITLE
"Duplicate bundled template ..." after updating from 0.5.0 to 0.6.1

### ISSUE THREAD

**Issue by jansorg** [JetBrains/gradle-intellij-plugin#554]
I updated the gradle-intellij plugin from 0.5.0 to 0.6.1.
Tests of my plugin now fail with an exception on duplicate file templates.

The file is stored at `src/main/resources/fileTemplates/internal` in a project with mixed java/kotlin sources. It seems to build at these locations:
- `build/resources/main/fileTemplates/internal/BashSupport Pro Bash.bash.ft`
- `jar:file:/projectdir/build/idea-sandbox/plugins-test/bashsupport-pro/lib/bashsupport-pro-1.5.10.201-SNAPSHOT.jar!/fileTemplates/internal/BashSupport Pro Bash.bash.ft`

The duplicate inclusion seems to break the file templates. 0.5.0 is working fine with the same build.gradle setup.

The exception is thrown in a test here:
```
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:182)
	at com.intellij.ide.fileTemplates.impl.FTManager.createAndStoreBundledTemplate(FTManager.java:198)
	at com.intellij.ide.fileTemplates.impl.FTManager.setDefaultTemplates(FTManager.java:187)
	at com.intellij.ide.fileTemplates.impl.FileTemplatesLoader.<init>(FileTemplatesLoader.java:93)
	at com.intellij.ide.fileTemplates.impl.FileTemplateSettings.<init>(FileTemplateSettings.java:32)
	at com.intellij.ide.fileTemplates.impl.ExportableFileTemplateSettings.<init>
```

**Comment by hsz** [comment]
Can you please check it with `v0.5.1`?

**Comment by zolotov** [comment]
what's the platform version?

**Comment by jansorg** [comment]
I'm building against `IC-2020.1`. 
The tests are also failing with `0.5.1`, while everything is fine with `0.5.0`.

**Comment by zolotov** [comment]
could you check whether it works on 2020.3 eap for you, please? thanks

**Comment by jansorg** [comment]
with `IC-203.4818.26-EAP-SNAPSHOT` the same tests are still failing.

with the current eap `IC-203.5251.39-EAP-SNAPSHOT`, I'm unable to run the tests, because almost all are failing with weird classloader/classcast exceptions.
Just in case that it's related:
```
java.lang.ClassCastException: 
class pro.bashsupport.shell.interpreter.UnixShellInterpreterService cannot be cast to class 
pro.bashsupport.shell.interpreter.ShellInterpreterService 
(pro.bashsupport.shell.interpreter.UnixShellInterpreterService is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @62be14ee;
pro.bashsupport.shell.interpreter.ShellInterpreterService is in unnamed module of loader 'app')
```

**Comment by zolotov** [comment]
Thanks! 4818 a bit old for the experiments, could you try 203.5419-EAP-CANDIDATE-SNAPSHOT please?

**Comment by jansorg** [comment]
With 0.6.1 and 203.5419-EAP-CANDIDATE-SNAPSHOT I'm not seeing the classloader issue anymore, but I'm still seeing the "duplicate bundled template" exception.

```text
java.lang.Throwable: Assertion failed: Duplicate bundled template BashSupport Pro Bash.bash [file:/project/bashsupport-pro/build/resources/main/fileTemplates/internal/BashSupport Pro Bash.bash.ft, jar:file:/project/bashsupport-pro/build/idea-sandbox/plugins-test/bashsupport-pro/lib/bashsupport-pro-1.5.10.203-SNAPSHOT.jar!/fileTemplates/internal/BashSupport Pro Bash.bash.ft]
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:195)
	at com.intellij.ide.fileTemplates.impl.FTManager.createAndStoreBundledTemplate(FTManager.java:210)
	at com.intellij.ide.fileTemplates.impl.FTManager.setDefaultTemplates(FTManager.java:199)
	at com.intellij.ide.fileTemplates.impl.FileTemplatesLoader.loadConfiguration(FileTemplatesLoader.java:170)
	at com.intellij.ide.fileTemplates.impl.FileTemplatesLoader.lambda$new$0(FileTemplatesLoader.java:64)
[...]
```

**Comment by zolotov** [comment]
thanks, we'll investigate
