### ISSUE TITLE
Please provide the list of `failureLevel` options

### ISSUE THREAD

**Issue by AlexPl292** [JetBrains/gradle-intellij-plugin#557]
Could you please list all possible options of `failureLevel` in docs? By some reason, IJ doesn't resolve `FailureLevel` enum.

**Comment by izhangzhihao** [comment]
Usage: 

```
import static org.jetbrains.intellij.tasks.RunPluginVerifierTask.FailureLevel.*


...

runPluginVerifier {
    ideVersions = ["PCP-2020.2", "WS-2020.3", "IIC-2021.1"]
    failureLevel = COMPATIBILITY_PROBLEMS
}

```

**Comment by YannCebron** [comment]
https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#runpluginverifier-task-failurelevel
