### ISSUE TITLE
runPluginVerifier task downloads wrong IDE

### ISSUE THREAD

**Issue by gharrma** [JetBrains/gradle-intellij-plugin#559]
When I set up the verifier task like this:
```kotlin
tasks.runPluginVerifier {
    ideVersions(listOf("IC-2019.3"))
}
```
then the wrong IDE is downloaded. It downloads 2020.2.3, even though it thinks it downloaded 2019.3:
```
$ cat ~/.pluginVerifier/ides/IC-2019.3/build.txt
IC-202.7660.26
```

Here is the URL is tries to download from:
```
https://data.services.jetbrains.com/products/download?code=IC&platform=linux&type=release&majorVersion=2019.3
```

It looks correct, but in fact that link downloads 2020.2.3. My guess is that the `majorVersion` parameter is unknown or misspelled(?), and instead of returning an error the server just defaults to returning the latest stable IntelliJ version(!)

In fact, this link downloads 2020.2.3 as well:
```
https://data.services.jetbrains.com/products/download?code=IC&platform=linux&type=release&majorVersion=123412341234123412341234123412341234
```

**Comment by hsz** [comment]
Thanks, Matthew for a detailed report. It's a known issue already fixed with #553
Please check my last comments in there.

**Comment by gharrma** [comment]
Thanks! (Sorry, I should have looked harder for the duplicate issue!)

**Comment by hsz** [comment]
No worries!

**Comment by hsz** [comment]
The list of the available products that can be used for testing is here: https://jb.gg/intellij-platform-builds-list
