### ISSUE TITLE
"Class to bind does not exist" warnings during compileTestJava execution

### ISSUE THREAD

**Issue by sergeykad** [JetBrains/gradle-intellij-plugin#56]
I am getting the error for all *.form files in my project during `compileTestJava` execution.
It is apparently comes from `com.intellij.ant.Javac2` and looks like the following: `[ant:instrumentIdeaExtensions] C:\IntelliJ-plugin\src\main\java\com\foo\Bar.form: Class to bind does not exist: com.foo.Bar`

Environment:
org.jetbrains.intellij" version "0.0.35"
Java 6
IntelliJ IDE 13

**Comment by zolotov** [comment]
Did it work in previous versions of plugin?

**Comment by sergeykad** [comment]
I don't think so. I checked it with 0.0.32 and it does not work either.

**Comment by zolotov** [comment]
Well, it works for me on IDEA >=14 and I cannot reproduce it on IDEA 13 because there is no IDEA 13 distribution in repo, sorry. Maybe it's some misconfiguration, so if you could reproduce this on IDEA 14 I can try to fix it.

**Comment by sergeykad** [comment]
It works for me with IDEA 14 too, but I have to support 13.

I am using IDEA 13 zip from https://confluence.jetbrains.com/display/IntelliJIDEA/Previous+IntelliJ+IDEA+Releases Just had to add it to my local repo.

**Comment by zolotov** [comment]
> Just had to add it to my local repo.

This is what I'm talking about,  the plugin doesn't support IDEA <14, it should be clear because IDEA <14 builds are missing in the maven repo. I don't mind if you make a pull request here but hacking the plugin for IDEA 13 is definitely is not on my plan.

**Comment by sergeykad** [comment]
Do you know if JetBrains can add the missing builds to the repo?

I doubt I will have time work on this issue, especially since I have very little knowledge about IDEA build internals.

**Comment by zolotov** [comment]
> Do you know if JetBrains can add the missing builds to the repo?

JetBrains has no such plans.

> I will have time work on this issue, especially since I have very little knowledge about IDEA build internals.

So am I. I'll ping you in this issue if something would change.

**Comment by jtonic** [comment]
Hi,

Regarding my previous comment, it was my mistake, the java/form files were in the src/kotlin, instead of being in src/java. Moving the files in the later fixed the problem

Please disregard it.
