### ISSUE TITLE
Exclude kotlin-runtime from the dependencies loaded from IDEA lib directory

### ISSUE THREAD

**Issue by yole** [JetBrains/gradle-intellij-plugin#57]
If a plugin is built with Kotlin, it usually uses its own Kotlin runtime library, specified as a separate dependency in build.gradle. This dependency may conflict with the Kotlin runtime which is bundled with IDEA and shipped in the 'lib' directory, so there should be an option to exclude the bundled Kotlin runtime from the classpath.

**Comment by alexeykudinkin** [comment]
:+1:

**Comment by zolotov** [comment]
Please try 0.0.36, kotlin-runtime.jar should be excluded from classpath for any project that has explicit kotlin-runtime dependency

**Comment by alexeykudinkin** [comment]
Yep, works now, thanks!

**Comment by ingokegel** [comment]
Why only for explicit dependencies and not for transitive dependencies? In Kotlin 1.1 it is an error to have a language level mismatch between two Kotlin libraries on the classpath. It's easy enough to add an explicit Kotlin dependency to the project, but it would be less confusing if this would work for a transitive Kotlin dependency as well.
