### ISSUE TITLE
Plugin incompatible with IntelliJ 203

### ISSUE THREAD

**Issue by benwatson528** [JetBrains/gradle-intellij-plugin#574]
Hello,

I maintain a [plugin](https://plugins.jetbrains.com/plugin/12281-avro-and-parquet-viewer), and it has stopped working as of this morning's release with the error:

```
Plugin 'Avro and Parquet Viewer' (version 'null') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IU-203.5981.155
```
 It's a fairly vanilla Tool Window plugin, so I would expect it to always work with the latest version of IntelliJ. My [build.gradle](https://github.com/benwatson528/intellij-avro-parquet-plugin/blob/master/build.gradle) contains:

```java
patchPluginXml {
    sinceBuild("171")
    changeNotes """
      Some LogicalTypes (such as dates) are not written as valid JSON, which was causing some files to not be displayed at all. This update ensures that such files can still be viewed in the raw pane."""
}
```

so I'm under the impression that the plugin should always be compatible with the latest version. However on the JetBrains Marketplace page I can see:

![image](https://user-images.githubusercontent.com/6214761/100852745-cfb1ed00-347e-11eb-900b-cd1495ea8555.png)

If I try to update the compatibility range then I get the error: "You cannot set an until-build value greater than the until-build value in plugin.xml".

If I manually schedule verifications than I can see that my plugin is compatible:

![image](https://user-images.githubusercontent.com/6214761/100852816-e5bfad80-347e-11eb-95bf-a2a97aa7889f.png)

As things stand it isn't even appearing in the marketplace. How can I get my plugin working again?

Any help greatly appreciated.

**Comment by benwatson528** [comment]
I am currently updating to `id 'org.jetbrains.intellij' version '0.6.5'` from `0.4.21`, and that should fix it, but it would still be good to know what causes these incompatibilities.

**Comment by YannCebron** [comment]
I don't see any `intellij` block in your build.gradle? How is this supposed to work?
Please see https://jetbrains.org/intellij/sdk/docs/tutorials/build_system/gradle_guide.html#patching-the-plugin-configuration-file for a detailed guide on how to setup Gradle and specifying/overriding since/until-build attributes.

**Comment by benwatson528** [comment]
Thanks for the quick reply. The plugin has worked in every JetBrains product for about a year without the inclusion of an `intellij` block. `patchPluginXml` is where I specify the `sinceBuild` and not `untilBuild` (because I want it to continue being compatible automatically with each new release). It's difficult for me to play with different settings, because the only way to see if anything truly works is to release it, which isn't exactly ideal for the users of my plugin.

If I replace `patchPluginXml` with the following then should I be good?

```
intellij {
  version 'LATEST-EAP-SNAPSHOT
  updateSinceUntilBuild false
}
```

**Comment by YannCebron** [comment]
If you want your plugin to be compatible with 171 and later, you should build against 171 and not "LATEST-EAP-SNAPSHOT".
`patchPluginXml` task LGTM

**Comment by benwatson528** [comment]
Thanks a lot for your help. I'll give this a go.
