### ISSUE TITLE
Cannot Resolve JBR at

### ISSUE THREAD

**Issue by Cjesus20** [JetBrains/gradle-intellij-plugin#575]
i found this problem and i dont know how to fix it.. anyone have had ths same problem..?
![image](https://user-images.githubusercontent.com/28987825/101012665-72dc3280-3563-11eb-8c9d-d8f815871324.png)

**Comment by hsz** [comment]
Since that's not an error but a warning and it's falling back to the built-in JBR, is that really a problem?
You can ignore it.

Also, please upgrade your dependency to the latest version.

**Comment by Cjesus20** [comment]
sry but where do u upgrade it..? :/

**Comment by hsz** [comment]
```
plugins {
  id "org.jetbrains.intellij" version "0.6.5"
}
```

**Comment by Cjesus20** [comment]
thx, sry if i ask but can u help me.. i dont understand why i have this Error.. 
![image](https://user-images.githubusercontent.com/28987825/101060511-c9f7fc80-358f-11eb-85f4-6b37a0b7326d.png)
