### ISSUE TITLE
Cannot resolve plugin 'com.intellij.modules.cidr.lang' or 'com.intellij.modules.clion' in dependencies

### ISSUE THREAD

**Issue by GoBigorGoHome** [JetBrains/gradle-intellij-plugin#577]
gradle-intellij-plugin cannot resolve plugin 'com.intellij.modules.cidr.lang' or 'com.intellij.modules.clion' in dependencies if I change intellij.version from 2020.2 to 2020.3. Are there some breaking changes? How can I start working on my CLion plugin for CLion 2020.3?

**Comment by YannCebron** [comment]
please watch https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010009159-CLion-plugin-broken-after-update-to-2020-3

SDK Docs page https://jetbrains.org/intellij/sdk/docs/products/clion.html will reflect new status when available
