### ISSUE TITLE
runIde task in IJ community: License Activation dialog is activated.

### ISSUE THREAD

**Issue by shenqianjin** [JetBrains/gradle-intellij-plugin#578]
runIde task in IJ community: License Activation dialog is activated when my plugin depends optionally on  IJ Ultimate plugin.

How should I deactivate it ?

Thanks!

**Comment by hsz** [comment]
That's expected behavior since you have no license provided for your main Community Edition IDE.
If you'd work on the IU with the activation code provided, IDE run via the Gradle plugin will inherit it automatically.

**Comment by shenqianjin** [comment]
Thanks for you quickly response, hsz.

My plugin is supported for Community and Ultimate Editions. And my IDE is a Community one. What I expected is I can run/debug my plugin by runIde task in my Community IDE.

**Comment by shenqianjin** [comment]
In other words, how can I specify different IJ types/versions for my "buildPlugin" and "runIde" tasks like below?

"buildPlugin" -- **IU**-*.*
BUT "runIde" -- **IC**-*.*

**Comment by hsz** [comment]
Please follow the [Running DSL](https://github.com/JetBrains/gradle-intellij-plugin#running-dsl) section in the README. There's `ideDirectory` property available.

**Comment by shenqianjin** [comment]
Yes. I tried "ideDirectory" properties. It works like what I expected.
