### ISSUE TITLE
The plugin ignores configuration in certain scenario

### ISSUE THREAD

**Issue by sergeykad** [JetBrains/gradle-intellij-plugin#58]
Adding the attached file using `apply from: 'common.txt'` in build.gradle causes the plugin to download LATEST-EAP-SNAPSHOT with sources regarding of the configuration.

[common.txt](https://github.com/JetBrains/gradle-intellij-plugin/files/76987/common.txt)

Environment:
org.jetbrains.intellij" version "0.0.35"
Java 6
IntelliJ IDE 13

**Comment by zolotov** [comment]
Are you sure that this is the problem of plugin and not misconfiguration of you `build.gradle`?

**Comment by sergeykad** [comment]
I have the following configuration:
``` Groovy
intellij {
    version '13.1.6'
    pluginName 'MyPlugin'
    intellij.downloadSources false
    intellij.updateSinceUntilBuild false
    intellij.instrumentCode true
    intellij.type 'IU'
    systemProperty 'idea.is.internal', 'false'   
}
```

What can be misconfigured?

**Comment by zolotov** [comment]
I don't see any `apply from` in your configuration

**Comment by sergeykad** [comment]
I am not sure if it was an actual problem. I am unable to reproduce it so far after computer restart :/
