### ISSUE TITLE
Can not resolve plugin dependencies, sometimes.

### ISSUE THREAD

**Issue by BrianPin** [JetBrains/gradle-intellij-plugin#581]
I am developing two intellij plugins. Plugin A and Plugin B, B uses A's extension points. So in B's gradle.build file, I use something like this to state the dependency:
```
intellij.plugins = ['gradle-java', 'java', 'com.linkedin.pegasus-intellij-plugin.pegasusplugin:0.1.38']
```
This build succeeded a while ago, and now it didn't work.
It says
```
* What went wrong:
Could not determine the dependencies of task ':annotation:prepareSandbox'.
> Cannot resolve plugin com.linkedin.pegasus-intellij-plugin.pegasusplugin version 0.1.38

```

I wonder where does the intellij.plugin goes for searching my dependency?
And if there is any help on solving this issue will be appreciated

**Comment by zolotov** [comment]
> I wonder where does the intellij.plugin goes for searching my dependency?

It goes to plugins.jetbrains.com. Are you sure that the plugin with a particular version is published at the moment you're requesting it?

> And if there is any help on solving this issue will be appreciated

As you're developing both plugins, I think it's easier to depend on sources rather than binaries: `intellij.plugins = [project(":pluginB")]`

**Comment by zolotov** [comment]
I cannot find any versions of pegasusplugin at plugins.jetbrains.com: https://plugins.jetbrains.com/search?products=androidstudio&products=clion&products=dbe&products=go&products=idea&products=idea_ce&products=idea_edu&products=mps&products=objc&products=phpstorm&products=pycharm&products=pycharm_ce&products=pycharm_edu&products=rider&products=ruby&products=webstorm&search=pegasus

**Comment by ciez** [comment]
somewhat similar problem in my (simpler) case:

[prepareSandbox-annotations.txt](https://github.com/JetBrains/gradle-intellij-plugin/files/5743341/prepareSandbox-annotations.txt)

build.gradle has:
```
buildscript {
	repositories {
        flatDir {dirs 'repository'}
        maven {url "https://plugins.gradle.org/m2/"}
        maven {url "https://repo1.maven.org/maven2/"}
    }
}

...

dependencies {
    compile 'org.jetbrains:annotations:19.0.0'
    runtimeClasspath 'org.jetbrains:annotations:19.0.0'
}
```

java 15.0.1 2020-10-20
gradle 6.7.1

**Comment by zolotov** [comment]
@ciez there is nothing similar here, the issue is about plugin dependency and your script doesn't contain it. Please in such cases create new issues.

As for your problem, it works as expected, you haven't defined a repository for your project. Just add this to the top level

```
repositories {
        maven {url "https://repo1.maven.org/maven2/"}
}
```

Read more about repositories here: https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by ciez** [comment]
Appreciate your very prompt answer @zolotov! Cheers, mate.

Will create a new issue tomorrow. Will then also try the solution you (@zolotov) suggested.

Happy holidays all :)

**Comment by BrianPin** [comment]
> > I wonder where does the intellij.plugin goes for searching my dependency?
> 
> It goes to plugins.jetbrains.com. Are you sure that the plugin with a particular version is published at the moment you're requesting it?

Yeah, I am quite sure, because my version: 0.1.36, 0.1.37 used to be working for Plugin B

> 
> > And if there is any help on solving this issue will be appreciated
> 
> As you're developing both plugins, I think it's easier to depend on sources rather than binaries: `intellij.plugins = [project(":pluginB")]`

I would take that into consideration in the future, right now, the fact is that the two plugins are  belonging to different repository in my org. So it is kind of like to go through some significant change for this. But I will keep this option in mind, for now I still hope that we can use the repo-way to make it work.

**Comment by BrianPin** [comment]
> I cannot find any versions of pegasusplugin at plugins.jetbrains.com: https://plugins.jetbrains.com/search?products=androidstudio&products=clion&products=dbe&products=go&products=idea&products=idea_ce&products=idea_edu&products=mps&products=objc&products=phpstorm&products=pycharm&products=pycharm_ce&products=pycharm_edu&products=rider&products=ruby&products=webstorm&search=pegasus

I think this is probably the scenario:
We use the custom repository feature from the intelij gradle plugin. It started from this issue: https://github.com/JetBrains/gradle-intellij-plugin/issues/535
So after that issue is resolved, I started to be able to build.
It is probably is like this scanrio:

Intellij Plugin B configures to depend on Intellij plugin A by setting:
```
intellij.plugins = ['gradle-java', 'java', 'com.linkedin.pegasus-intellij-plugin.pegasusplugin:0.1.39']
```

And you guys, aka the `intellij.plugins` are instructed to find `com.linkedin.pegasus-intellij-plugin.pegasusplugin:0.1.39`
Somehow, in my org, we have another gradle plugin which sets enterprise plugin repository feature for you guys.

So the whole build gradle file looks like
```
apply plugin: 'li-intellij-plugin'

intellij.plugins = ['gradle-java', 'java', 'com.linkedin.pegasus-intellij-plugin.pegasusplugin:0.1.39']

```
That probably explains why you can not find my plugin in market place

**Comment by BrianPin** [comment]
FWIW, the real relationship among this is that
We do have a gradle plugin call li-intellij-plugin which will set the custom repo with an XML file called `updatePlugins.xml`
In my case, the dependency plugin A is have it like this
```
<plugin id="com.linkedin.pegasus-intellij-plugin.pegasusplugin" version="0.1.39" url="http://artifactory.corp.linkedin.com:8081/artifactory/intellij-plugins-internal/com/linkedin/pegasus-intellij-plugin/pegasusplugin/0.1.39/pegasusplugin-0.1.39.zip">
<name>pegasusplugin</name>
<description>
<![CDATA[ IntelliJ plugin for the Pegasus Data system ]]>
</description>
<vendor email="" url="http://go/pd%20pegasus-intellij-plugin">LinkedIn</vendor>
</plugin>
```
It has 0.1.39 coded in there, I wonder if it is the reason that I can not use 0.1.38 and older ones.

**Comment by BrianPin** [comment]
The issue kind of resolved by itself now. 
What I did is erasing all my gradle cache in my local machine, and restart building again, I think that my local cache might been corrupted by me somehow. I was updating plugin A and trying to overwrite the cache instead of release it to the plugin repo (our internal custom repository)

**Comment by zolotov** [comment]
ok, thanks for the update. ping me here if you face the problem again

**Comment by derdampflok** [comment]
@zolotov don't know if this is the right place but can you elaborate on the `intellij.plugins = [project(":pluginB")]` option? I managed to make it work with normal dependencies but not with plugin dependencies.
