### ISSUE TITLE
Enforce plugin name in publish task

### ISSUE THREAD

**Issue by ChrisCarini** [JetBrains/gradle-intellij-plugin#583]
Hello!

There have been a few times now where I have attempted to publish a plugin to the marketplace, and had someone respond to the "pending approval" email with something along the lines of below:

> Please change the name of your plugin. It should not contain such words as 'Plugin', 'IntelliJ', 'JetBrains'.

It would be great if these naming enforcements were programmatically caught as part of the publish step / workflow, so that the developer(s) get a fast feedback they can iterate upon, do not have to wait several hours / days, and manual intervention / process is not necessary to catch (and, fwiw, most recently, this plugin has been published with one of these words before, and this is the 3rd publish that its being caught in).

Seems like it would be easy enough to implement, and would improve the experience IMO. What does the team think? :)

**Comment by YannCebron** [comment]
this is actually a feature request for Plugin Verifier, tracking in https://youtrack.jetbrains.com/issue/MP-3369 resp. https://youtrack.jetbrains.com/issue/IDEA-260371 to highlight directly in IDE

**Comment by ChrisCarini** [comment]
Thanks @YannCebron - I saw you just opened those this morning; I will watch those for updates.
