### ISSUE TITLE
Gradle downloading ideaC-2020.1.1.zip forever and never finish

### ISSUE THREAD

**Issue by gileli121** [JetBrains/gradle-intellij-plugin#584]
I created using the built-in wizard gradle project with the option to develop plugin for intellij.
The project is loading forever this:
![image](https://user-images.githubusercontent.com/17680514/103448414-02c7e600-4ca2-11eb-92f8-f8ca8a82aff6.png)

It never stop.
It runs more that 40 minutes...
When I download intellij myself from the offical website, it finish after 10 minutes so my internet should not be so slow.

It should finish to load it at some time but it never finish and I have no idea how to set it up.

The generated build.gradle file is:
```
plugins {
    id 'java'
    id 'org.jetbrains.intellij' version '0.6.5'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
    version '2020.1.1'
}
patchPluginXml {
    changeNotes """
      Add change notes here.<br>
      <em>most HTML tags may be used</em>"""
}
```

Please help.

Thanks.

**Comment by YannCebron** [comment]
Can you download https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2020.1.1/ideaIC-2020.1.1.zip manually in browser faster or same problem? Are you behind firewall/proxy?

**Comment by scxkd2016** [comment]
> > 您可以在浏览器中手动下载[https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2020.1.1/ideaIC-2020.1.1.zip更快还是同样的问题？你在防火墙/代理后面吗？](https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2020.1.1/ideaIC-2020.1.1.zip%E6%9B%B4%E5%BF%AB%E8%BF%98%E6%98%AF%E5%90%8C%E6%A0%B7%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%9F%E4%BD%A0%E5%9C%A8%E9%98%B2%E7%81%AB%E5%A2%99/%E4%BB%A3%E7%90%86%E5%90%8E%E9%9D%A2%E5%90%97%EF%BC%9F)
> > How to bind to gradle after manual download? In addition, this does not seem to be an official solution....

intellij {
    localPath 'D:/Application/IntelliJ IDEA 2022.1'
    version '2018.3.6'
//    version '2020.2'
//    version '2021.2'
}
