### ISSUE TITLE
[Fatal Error] updates.xml:1:1: Premature end of file.

### ISSUE THREAD

**Issue by sergeykad** [JetBrains/gradle-intellij-plugin#59]
The error is printed during `:prepareSandbox`

The updates.xml itself looks ok and has the following content:
``` XML
<application>
  <component name="UpdatesConfigurable">
    <option name="CHECK_NEEDED" value="false"/>
  </component>
</application> 
```

Nevertheless the build finishes successfully.

Environment:
org.jetbrains.intellij" version "0.0.35"
Java 6
IntelliJ IDE 13

**Comment by zolotov** [comment]
0.0.37 is uploaded
