### ISSUE TITLE
Allow wildcard version for non-bundled plugin dependencies.

### ISSUE THREAD

**Issue by baron1405** [JetBrains/gradle-intellij-plugin#590]
A blocking issue for us is that we must specify the version of a plugin that we wish to have resolved from a custom repository. We will be passing the IntelliJ API version to our Enterprise repository and thus want the latest version compatible with that API version. I know that using a version signals a dependency on a non-bundled plugin but for Enterprise repositories there should be the flexibility to say any version (presumes, like the JetBrains repo that a `build=<intellij build version>` will be passed as a query parameter). I propose that you allow the use of a `*` to act as a version wildcard. The presence of the `*` would signal a non-bundled dependency, but the version would be up to the Enterprise repository. With this proposal, a plugin could be specified as `'org.intellij.scala:*`. Of course, the use of `*` as the wildcard character is just a suggestion but that character does have a pretty well understood meaning from other use cases.

In terms of implementation, the `*` character would make the plugin treated as non-bundled. For custom repository searches you would simply compare the plugin identifier and ignore the version during the resolve. For the JetBrains plugin repository you would take the `since-build` value as use it in the `?build=<since-build value>` query parameter when you form the JetBrains repository URL. This is essentially what the JetBrains plugin repository does when queried. I am likely making this sound easier than it really is but hopefully I am making the idea clear.

**Comment by YannCebron** [comment]
related #543?
