### ISSUE TITLE
Dynamic plugin reloading not working

### ISSUE THREAD

**Issue by vjpr** [JetBrains/gradle-intellij-plugin#596]
Repost: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010163299-How-to-Trigger-Dynamic-Plugin-Reload?page=1

How is the dynamic plugin reloading suppose to work in a development workflow?

My code at the moment gets HotSwapped when I change method bodies. But when I change the `plugin.xml` file or something else, I would expect the plugin to be reloaded without having to re-run the entire IDE.

I have tried running `buildPlugin` and `runIDE` but nothing works.

```
  id("org.jetbrains.intellij") version "0.6.5"
```

**Comment by YannCebron** [comment]
answered in forum and clarified docs
