### ISSUE TITLE
Exclude kotlin-* from the dependencies loaded from IDEA lib directory

### ISSUE THREAD

**Issue by benqs** [JetBrains/gradle-intellij-plugin#60]
Explicit kotlin dependencies conflicts with bundled with IDEA.

ex.
 compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

There should similar solution as in issue #57.

**Comment by zolotov** [comment]
0.0.37 is uploaded

**Comment by benqs** [comment]
Solution doesn't seem to work.
Both kotlin-reflect and runtime are still added to dependencies.
![kotlin-dependencies](https://cloud.githubusercontent.com/assets/6899180/12109890/aa8fbd1e-b386-11e5-90bb-2517c523002d.png)

**Comment by zolotov** [comment]
Have you synced gradle after updating plugin version? Also why is kuka_idea has plugin icon? It should be java gradle module.

**Comment by benqs** [comment]
Yes, I've synced. Removed kotlin-reflect/runtime manually from dependencies, but after sync it added again.
It has plugin icon because of obsolete changes in .iml when I wasn't using this gradle plugin for development.

**Comment by benqs** [comment]
Just to be sure removed unnecesary things in .iml.
Sync still is adding idea kotlin dependencies.

**Comment by zolotov** [comment]
Ok, and how do `kotlin-reflect` and `kotlin-runtime` dependencies look like in `build.gradle`?

**Comment by benqs** [comment]
compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

root build.gradle: ... ext.kotlin_version = '1.0.0-beta-4583' ...

**Comment by zolotov** [comment]
what kind of transitive dependencies? Could you share project sample to recreate the issue?

**Comment by benqs** [comment]
Dependency from other project module.
ex.

+--- project :cre
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.0.0-beta-2423
|    |    \--- org.jetbrains.kotlin:kotlin-runtime:1.0.0-beta-2423
|    +--- org.jetbrains.kotlin:kotlin-reflect:1.0.0-beta-2423
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.0.0-beta-2423 (*)
...

**Comment by zolotov** [comment]
Still don't get it. Could you create a project sample please?
