### ISSUE TITLE
Upgrade to 0.7.1: Parameter 'directory' is not a directory

### ISSUE THREAD

**Issue by matkoch** [JetBrains/gradle-intellij-plugin#602]
I started updating my ReSharper/Rider plugins and got the following:

> A problem occurred evaluating project ':protocol'.
> Parameter 'directory' is not a directory: /Users/matt/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2021.1-EAP4-SNAPSHOT/c5868e69b7a5064f95dc1ea103c865483e4fc9a7/riderRD-2021.1-EAP4-SNAPSHOT/lib/ant/lib

Everything is working on the old 0.6.x. If you need any particular logs, please let me know which one.

**Comment by hsz** [comment]
Thanks for reporting, Matthias.
Issue is already fixed and will be released soon with 0.7.2

https://github.com/JetBrains/gradle-intellij-plugin/commit/876008b69366bd51088cba8b6f5a67fd9b942b14#diff-ac48c8d8df65750fc94bd65f5b103769e90f2708736533bc0b9131ba079cca6bR224
