### ISSUE TITLE
Version 0.7.2 isn't available in Gradle's plugin portal

### ISSUE THREAD

**Issue by ris58h** [JetBrains/gradle-intellij-plugin#604]
The README states that we should add `id "org.jetbrains.intellij" version "0.7.2"` in `plugins` section and that's all, but it leads to a build error
```
* What went wrong:
Plugin [id: 'org.jetbrains.intellij', version: '0.7.2'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.intellij:org.jetbrains.intellij.gradle.plugin:0.7.2')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```

According to [Gradle's plugin portal](https://plugins.gradle.org/plugin/org.jetbrains.intellij) the latest version is 0.7.1.

**Comment by hsz** [comment]
The version was bumped in the `gradle.properties` file (and README consumed it), but we're still testing it before the actual release to the production.

**Comment by ris58h** [comment]
Thank you for quick response. I got the reason, but I find it a little bit confusing for newcomers, when instructions from README lead to an error. Is it possible to provide some note explaining it or link to the latest version?

**Comment by hsz** [comment]
In general, such a situation should be avoided. Anyway, 0.7.2 is now available in the repository.
