### ISSUE TITLE
Using 2021.1-eap-3 and the JavaScriptLanguage JB plugin, the built in transitive dependency CSS is not activated at runtime

### ISSUE THREAD

**Issue by hunterwerlla** [JetBrains/gradle-intellij-plugin#608]
Using version v0.7.2 of the gradle-intellij-plugin and 2021-eap-3:
```
intellij {
    ...
    plugins 'JavaScriptLanguage'
}
```
Fails at runtime because it does not pull the required transitive `CSS` plugin. Using a 2020.3 profile with v0.7.2 of the gradle-intellij-plugin, this works as expected.

**Comment by hsz** [comment]
@hunterwerlla Could you please provide your Gradle configuration file?

**Comment by hunterwerlla** [comment]
Yep, here is where we specify the plugins: https://github.com/aws/aws-toolkit-jetbrains/blob/master/buildSrc/src/software/aws/toolkits/gradle/IdeVersions.kt#L80
And here is where they are applied: https://github.com/aws/aws-toolkit-jetbrains/blob/28244203b9acd17eea5f31626f01a8a94b51801c/jetbrains-ultimate/build.gradle.kts#L23
Which we just OR together from the list: https://github.com/aws/aws-toolkit-jetbrains/blob/28244203b9acd17eea5f31626f01a8a94b51801c/buildSrc/src/software/aws/toolkits/gradle/IdeVersions.kt#L132

**Comment by YannCebron** [comment]
is this still an issue with 2021.1 final?

**Comment by abrooksv** [comment]
> is this still an issue with 2021.1 final?

I will check Yann after the Rider 2021.1.0 sdk issue is resolved, see https://github.com/aws/aws-toolkit-jetbrains/pull/2551

**Comment by abrooksv** [comment]
Yes, it still appears to be an issue:

```
    2021-04-12 15:52:39 WARN  PluginManager:26 - Problems found loading plugins:
      The JavaScript and TypeScript (id=JavaScript, path=/codebuild/local-cache/custom/e3753f6254b925d6ff833e213fc1705723cd512ae537636977eeb06cc91c3c94/root/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/2021.1/fb73193bad7ac7619a8bfac40db2cb035e38bd13/ideaIU-2021.1/plugins/JavaScriptLanguage) plugin Plugin 'JavaScript and TypeScript' requires plugin 'com.intellij.css' to be installed
      The JavaScript Debugger (id=JavaScriptDebugger, path=/codebuild/local-cache/custom/e3753f6254b925d6ff833e213fc1705723cd512ae537636977eeb06cc91c3c94/root/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/2021.1/fb73193bad7ac7619a8bfac40db2cb035e38bd13/ideaIU-2021.1/plugins/JavaScriptDebugger) plugin Plugin 'JavaScript Debugger' requires plugin 'JavaScript and TypeScript' to be enabled
```
