### ISSUE TITLE
The filename or extension is too long

### ISSUE THREAD

**Issue by Socolin** [JetBrains/gradle-intellij-plugin#610]
Hello

I'm getting an error when trying to build this plugin https://github.com/SpecFlowOSS/SpecFlow.Rider/tree/upgrade-gradle on Windows 10 (If you want to try checkout the branch `upgrade-gradle` for the latest version of this plugin and gradle, it's failing as well on `master`)

[build.gradle](https://github.com/SpecFlowOSS/SpecFlow.Rider/blob/upgrade-gradle/build.gradle)
```
    id 'org.jetbrains.kotlin.jvm' version '1.3.61'
    id 'org.jetbrains.intellij' version '0.7.2' 
```

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> java.io.IOException: Cannot run program "C:\Program Files\Java\jdk-15.0.2\bin\java": CreateProcess error=206, The filename or extension is too long

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 15s
2 actionable tasks: 2 executed
```

```
$ .\gradlew.bat --version

------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          15.0.2 (Oracle Corporation 15.0.2+7-27)
OS:           Windows 10 10.0 amd64
```

```
$ java --version
java 15.0.2 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
```

I also tried with other versions of java 11

**Comment by zolotov** [comment]
Hi. Exception is thrown from kotlin-plugin, not from gradle-intellij-plugin. It looks like the issue https://youtrack.jetbrains.com/issue/KT-34487 and looks like it's fixed in Kotlin 1.4.

The problem might be in the mismatching Kotlin plugin version and Kotlin version that is used for compilation (taken from IntelliJ SDK if you do not define it explicitly). You may try to arrange versions.
Similar problem: https://discuss.kotlinlang.org/t/gradle-error-when-updating-kotlin-version/10184/2

**Comment by Socolin** [comment]
Hi,

I was able to solve my problem, I tried to upgrade to Kotlin 1.4 but I was getting an error, the problem was an old version of rd-gen
Now it works (I upgrade to kotlin 1.4 and com.jetbrains.rd:rd-gen:0.1831.17)

**Comment by zolotov** [comment]
got it, thank you for the update
