### ISSUE TITLE
Warning while executing task :compileKotlin - Kotlin runtime not completely excluded

### ISSUE THREAD

**Issue by L2jLiga** [JetBrains/gradle-intellij-plugin#612]
When I run "build" gradle task it logs warning into console

**repository**: https://github.com/L2jLiga/fastify-decorators-plugin
**github actions run**: https://github.com/L2jLiga/fastify-decorators-plugin/runs/2092584876?check_suite_focus=true

**Addtional details**:
- Issue appeared in this PR https://github.com/L2jLiga/fastify-decorators-plugin/pull/8
- Switching from `IU-LATEST-EAP-SNAPSHOT` to `IU-2020.3.2` fixes issue

<details>
<summary>Console output</summary>

12:57:03: Executing task 'build'...

> Task :compileKotlin
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath
w: C:\Users\user\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIU\LATEST-EAP-SNAPSHOT\14ed4e191a397850ef06d2c35c842ded7cdda455\ideaIU-LATEST-EAP-SNAPSHOT\lib\kotlin-stdlib-jdk8.jar: Library has Kotlin runtime bundled into it

> Task :compileJava NO-SOURCE
> Task :patchPluginXml
> Task :processResources
> Task :classes
> Task :instrumentCode
> Task :postInstrumentCode
> Task :inspectClassesForKotlinIC
> Task :jar
> Task :prepareSandbox
> Task :buildSearchableOptions SKIPPED
> Task :jarSearchableOptions SKIPPED
> Task :buildPlugin
> Task :assemble
> Task :detekt
> Task :compileTestKotlin NO-SOURCE
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :instrumentTestCode NO-SOURCE
> Task :postInstrumentTestCode
> Task :loadKtlintReporters
> Task :prepareTestingSandbox
> Task :runKtlintCheckOverTestSourceSet NO-SOURCE
> Task :ktlintTestSourceSetCheck SKIPPED
> Task :test NO-SOURCE
> Task :runKtlintCheckOverKotlinScripts
> Task :ktlintKotlinScriptCheck
> Task :runKtlintCheckOverMainSourceSet
> Task :ktlintMainSourceSetCheck
> Task :check
> Task :build

BUILD SUCCESSFUL in 10s
17 actionable tasks: 17 executed
12:57:13: Task execution finished 'build'.
</details>

**Comment by zolotov** [comment]
The warning looks correct. As you do not have a runtime dependencies on Kotlin, then kotlin runtime from intellij will be taken. So the plugin will be compiled with `id("org.jetbrains.kotlin.jvm") version "1.4.32"` that you set explicitly, but when you run the IDE it will work on the kotlin-runtime bundled into IDE. If versions will be different, it really may cause difficult to debug problems, as warning claims.

**Comment by henryju** [comment]
Adding an explicit dependency on kotlin-stdlib helped to remove some warnings, but I can't manage to remove the one about `kotlin-reflect`, even after adding `implementation("org.jetbrains.kotlin:kotlin-reflect:1.4.30")` to my dependencies:

```
> Task :compileKotlin
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/julien/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2020.1.3/c3f2e29c000d9af81b0c76d04408f2cee2a4e2df/ideaIC-2020.1.3/lib/kotlin-reflect-1.3.70.jar (version 1.3)
    /home/julien/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.30/a9116fbe28a0514671787df95133f28e65fdac25/kotlin-reflect-1.4.30.jar (version 1.4)
    /home/julien/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.30/d10d1e10f47006ee08162dde039e38ac487de4ac/kotlin-stdlib-1.4.30.jar (version 1.4)
    /home/julien/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.30/bb9a3173350f55732416ee27956ea8f9b81f4dbb/kotlin-stdlib-common-1.4.30.jar (version 1.4)
w: Consider providing an explicit dependency on kotlin-reflect 1.4 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
```

Any idea?

**Comment by zolotov** [comment]
@henryju what version do you use? `kotlin-reflect` hasn't been handled up before 0.7.3.

> Adding an explicit dependency on kotlin-stdlib helped to remove some warnings

You need to understand the consequences. Adding dependency means that your plugin distribution will include kotlin, which means much bigger distribution. That's probably not what you want.

**Comment by henryju** [comment]
I use version 0.7.3. You can see the code in this branch: https://github.com/SonarSource/sonarlint-intellij/tree/feature/remove_gradle_deprecation

> Adding dependency means that your plugin distribution will include kotlin, which means much bigger distribution. That's probably not what you want.

Hum, before adding the dependency, I had warnings telling me I should add it :) So not sure what to do...

**Comment by zolotov** [comment]
> I use version 0.7.3. You can see the code in this branch: https://github.com/SonarSource/sonarlint-intellij/tree/feature/remove_gradle_deprecation

Looks like I don't have permission to see it

> Hum, before adding the dependency, I had warnings telling me I should add it :) So not sure what to do...

Warnings are legit too. It's up to you how to proceed. The choice is between the risk of having unexpected runtime and distribution size. If you control the risk (e.g. you're sure about the IDE versions your plugin is running on or you're sure the API you use is the same in different runtimes) – ignore the warning. If you do not control it – it's safer to include your own runtime.

**Comment by henryju** [comment]
> Looks like I don't have permission to see it

I created a different branch to also test the 1.0-SNAPSHOT: https://github.com/SonarSource/sonarlint-intellij/tree/feature/try_snapshot

Let say we choose to control the version of the Kotlin runtime, instead of depending on the one provided by the platform. Is there a way to have a warning free build?

I have declared (I think) all dependencies:
```
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.4.30")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.4.30")
```
but still I have the warning when I build:
```
> Task :compileKotlin
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/julien/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2020.1.3/c3f2e29c000d9af81b0c76d04408f2cee2a4e2df/ideaIC-2020.1.3/lib/kotlin-reflect-1.3.70.jar (version 1.3)
    /home/julien/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.30/a9116fbe28a0514671787df95133f28e65fdac25/kotlin-reflect-1.4.30.jar (version 1.4)
    /home/julien/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.30/d10d1e10f47006ee08162dde039e38ac487de4ac/kotlin-stdlib-1.4.30.jar (version 1.4)
    /home/julien/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.30/bb9a3173350f55732416ee27956ea8f9b81f4dbb/kotlin-stdlib-common-1.4.30.jar (version 1.4)
w: Consider providing an explicit dependency on kotlin-reflect 1.4 to prevent strange errors
```

**Comment by zolotov** [comment]
> Let say we choose to control the version of the Kotlin runtime, instead of depending on the one provided by the platform. Is there a way to have a warning free build?

yes, the way you're trying to do it should give you warningless build. I'll take a look at your branch
