### ISSUE TITLE
future request

### ISSUE THREAD

**Issue by zcg** [JetBrains/gradle-intellij-plugin#613]
![Snipaste_2021-03-14_20-52-02](https://user-images.githubusercontent.com/68289686/111069394-cd6f1e00-84c4-11eb-8fae-1f47424f7acd.png)
in gradle project ，when use build.gradle ，we can see this triangle
![Snipaste_2021-03-14_20-53-13](https://user-images.githubusercontent.com/68289686/111069397-d102a500-84c4-11eb-97b5-b91c7db0f6ab.png)

build.gradle.kts , i can not see it

**Comment by zolotov** [comment]
This repository is about plugin for Gradle. Please use IntelliJ tracker for reporting on plugins for IntelliJ IDEA: https://youtrack.jetbrains.com/issues
