### ISSUE TITLE
JDK compatibility issues, whether support can be provided

### ISSUE THREAD

**Issue by RunRunAllen** [JetBrains/gradle-intellij-plugin#614]
(com/intellij/notification/Notification.class)
    类文件具有错误的版本 55.0, 应为 52.0
    请删除该文件或确保该文件位于正确的类路径子目录中。

**Comment by zolotov** [comment]
please provide detailed description and steps to recreate the problem.

**Comment by YannCebron** [comment]
it seems you have mismatch in JDK version of your project vs. Java version of target platform
see https://blog.jetbrains.com/platform/2020/09/intellij-project-migrates-to-java-11/
