### ISSUE TITLE
buildSearchableOptions keeps downloading latest jbr build

### ISSUE THREAD

**Issue by henryju** [JetBrains/gradle-intellij-plugin#616]
Hi,

I noticed that my plugin build download a new JBR build multiple time a day. This seems to be cause by the buildSearchableOptions task:
```
> Task :buildSearchableOptions
Download https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-jbr/jbr-11_0_7-linux-x64-b765.64.tar.gz
```
Shouldn't the task use a fixed version, based on the IJ version we are targeting in the build?

**Comment by YannCebron** [comment]
seems same as #568

**Comment by hsz** [comment]
See https://github.com/JetBrains/gradle-intellij-plugin/issues/568#issuecomment-851681387
