### ISSUE TITLE
publishPlugin not not in found in 0.7.2

### ISSUE THREAD

**Issue by pelletier197** [JetBrains/gradle-intellij-plugin#618]
Hello!

I'm facing a small issue when using KotlinDSL with version 0.7.2 of this plugin. The `publishPlugin` extension doesn't seem to be available, but the documentation says it should be. Here's the issue and what I did to work around

```kotlin

// This doesn't work. The extension doesn't exist
publishPlugin {
     setToken(System.getenv("PUBLISH_TOKEN"))
     setChannels("Stable")
}

// This did work as a workaround
tasks.withType<org.jetbrains.intellij.tasks.PublishTask> {
    setToken(System.getenv("PUBLISH_TOKEN"))
    setChannels("Stable")
}
```

**Comment by zolotov** [comment]
this is expected if you use kotlin script for configuring gradle

https://docs.gradle.org/current/userguide/migrating_from_groovy_to_kotlin_dsl.html#configuring-tasks
