### ISSUE TITLE
'cleanIdea' task doesn't delete all files 'idea' task generates

### ISSUE THREAD

**Issue by deadok22** [JetBrains/gradle-intellij-plugin#62]
* ```cleanIdea``` doesn't remove ```*.iws``` files
* ```cleanIdea``` doesn't remove ```*.iml``` files from subprojects

**Comment by zolotov** [comment]
Hi Sergey!

I'm afraid that `cleanIdea` task is a part of [gradle idea plugin](https://docs.gradle.org/current/userguide/idea_plugin.html)

**Comment by deadok22** [comment]
Thank you, @zolotov! 

Apparently, not removing ```*.aws``` files is a feature: https://issues.gradle.org/browse/GRADLE-1602?jql=text%20~%20%22idea%20iws%22

As to the second one - I've started a discussion on gradle forum: https://discuss.gradle.org/t/cleanidea-task-in-idea-plugin-doesnt-remove-iml-in-subprojects/13624
