### ISSUE TITLE
Plugin should download aarch64 IDE versions on Apple M1

### ISSUE THREAD

**Issue by fkistner** [JetBrains/gradle-intellij-plugin#622]
Since Rosetta 2 does impose some overhead, it likely makes sense to offer and default to downloading the aarch64 version, when on Apple M1. A way to be able to request the x86_64 may still be useful for compatibility testing.

**Comment by zolotov** [comment]
It was added some time ago. what version do you use? could you provide more details on what works not in a way you expect?

https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/groovy/org/jetbrains/intellij/jbr/JbrResolver.groovy#L182

**Comment by fkistner** [comment]
When targeting 2020.3 on M1, user reported errors, since they are getting the x86_64 variant (in 203, the darwin_arm64 variant uses different dependencies, namely a compatible JNA version): https://youtrack.jetbrains.com/issue/IDEA-265943

I don't think we need to implement special casing for 203.
But is it guaranteed that there no differences from 211 on, except for JBR?

**Comment by zolotov** [comment]
I'm not aware of any special compiling of intellij for different architectures. Do you think jna library is somehow different in "IntelliJ 2020.3 M1 version"? Who (I mean code, not person) put the right version there?

**Comment by fkistner** [comment]
Yes, all the IntelliJ 2020.3 M1 version are built separately from the `_darwin_arm64` branches and is using a different JNA version than 2020.3 x86_64. Feel free to ping me for details.
Anyways, seems like I was mistaken and this shouldn't be an issue going forward, so I'll close here, since it probably doesn't make sense to build a bespoke solution just for 203.

**Comment by Chaosinflesh** [comment]
This depends on your JDK - you've added the test using System.getProperty("os.arch") - but several 'arm64' JDKs (including openjdk14 that ships with Big Sur on the M1, and all the AdoptOpenJDKs I've tested) still return "x86_64" instead of "aarch64". So far only Zulu JDK has returned the correct string in my testing.

For our own software, we use a System call to 'uname -m' on a mac to identify the architecture.

**Comment by trespasserw** [comment]
@Chaosinflesh despite the name, the "os.arch" property is expected to return the architecture of a JVM process. Those JDKs you probed, are they natively built for ARM?

**Comment by Chaosinflesh** [comment]
Good question - now that I look closer, AdoptOpenJDK only offers x64 builds for MacOS (which includes the default JDK 14 that came preinstalled with Big Sur on the M1, it would seem).
Which explains why some M1 users (myself included) are encountering this problem.
