### ISSUE TITLE
plugins dependency conflict

### ISSUE THREAD

**Issue by qingmo** [JetBrains/gradle-intellij-plugin#623]
when i try to add kotlin support for a plugin.

```
buildscript {
    repositories {
...
    }
    dependencies {
        classpath("org.jetbrains:annotations") {
            version {
                strictly("19.0.0")
            }
        }
        classpath("org.jetbrains.intellij.plugins:gradle-intellij-plugin:0.7.2")
    }
}
plugins {
    java
    id("org.jetbrains.intellij") version "0.7.2"
}
intellij {
    version = "2019.2"
    type = "IU" 
    setPlugins(
        "java",
        "Kotlin",
        "Spring",
        "SpringBoot",
        "DatabaseTools"
    ) //Bundled plugin dependencies
...
}
```

Dependency path ':MybatisX:unspecified' --> 'org.jetbrains:annotations:{strictly 19.0.0}'
           Constraint path ':MybatisX:unspecified' --> 'org.jetbrains:annotations:{strictly 13.0}' because of the following reason: Pinned to the embedded Kotlin
           Dependency path ':MybatisX:unspecified' --> 'org.jetbrains.intellij.plugins:gradle-intellij-plugin:0.7.2' --> 'org.jetbrains:annotations:19.0.0'
           Dependency path ':MybatisX:unspecified' --> 'org.jetbrains.intellij.plugins:gradle-intellij-plugin:0.7.2' --> 'org.jetbrains.intellij.plugins:structure-base:3.139' --> 'org.jetbrains:annotations:13.0'
           Dependency path ':MybatisX:unspecified' --> 'org.jetbrains.intellij.plugins:gradle-intellij-plugin:0.7.2' --> 'org.jetbrains.intellij.plugins:structure-base:3.139' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.70' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.70' --> 'org.jetbrains:annotations:13.0'

**Comment by YannCebron** [comment]
why do you add this dependency explicitly?
```
 classpath("org.jetbrains:annotations") 
```

for `setPlugins`, please switch to use Plugin ID notation instead of plugin directory name (deprecated)
