### ISSUE TITLE
task compileJava error when I use @NotNull on exception param

### ISSUE THREAD

**Issue by sirnple** [JetBrains/gradle-intellij-plugin#625]
Today I update my gradle-intellij-plugin from `0.4.10` to `0.7.2`，I get an compile error like this:

```
compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.7, {1}, {2}, {3}, {4}, {5}, {6}, {7}
```

More detail in attatched file [error log.txt](https://github.com/JetBrains/gradle-intellij-plugin/files/6284358/error.log.txt)

And I checked my code that I find when I remove annotation `@NotNull` on exception param, this error disappear. The code like this:

```
public static void input(InputStream in) {
        Runnable runnable = () -> {
            try {
                in.read();
            } catch (@NotNull IOException exception) {
                exception.printStackTrace();
            }
        };
    }
```

Moreover, I tried code below, and it work well:

```
public static void input(InputStream in) {
        try {
            in.read();
        } catch (@NotNull IOException exception) {
            exception.printStackTrace();
        }
    }
```

**Comment by zolotov** [comment]
the exception is from gradle itself. have you updated it too?

**Comment by sirnple** [comment]
I have tried with an normal gradle and maven project (not a Intellij plugin project), I got the same error.

Moreover, I find that this error just occur when I use annotations in `org.jetbrains.annotations` of artifact `org.jetbrains:annotations:20.1.0`; if I use `org.jetbrains.annotations:13.0`, everything works well.

**Comment by YannCebron** [comment]
obsolete version
