### ISSUE TITLE
IntrumentCode Failed

### ISSUE THREAD

**Issue by Littlearphone** [JetBrains/gradle-intellij-plugin#629]
Since my IDEA was updated to 2021.1, I have encountered a problem.
My plug-in project cannot be built, and the error message is as follows:

> Configure project :
Repository https://repo.maven.apache.org/maven2/ replaced by https://maven.aliyun.com/repository/public.
Repository https://repo.maven.apache.org/maven2/ replaced by https://maven.aliyun.com/repository/public.

> Task :compileJava UP-TO-DATE
> Task :patchPluginXml UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :instrumentCode FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':instrumentCode'.
> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Could not resolve com.jetbrains.intellij.java:java-compiler-ant-tasks:211.6693.111.
     Required by:
         project :
      > Could not resolve com.jetbrains.intellij.java:java-compiler-ant-tasks:211.6693.111.
         > Could not get resource 'https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/java/java-compiler-ant-tasks/211.6693.111/java-compiler-ant-tasks-211.6693.111.pom'.
            > Could not GET 'https://d2cico3c979uwg.cloudfront.net/com/jetbrains/intellij/java/java-compiler-ant-tasks/211.6693.111/java-compiler-ant-tasks-211.6693.111.pom'.
               > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.jetbrains.intellij.java:java-compiler-ant-tasks:211.6693.111.
         > Could not get resource 'https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-third-party-dependencies/com/jetbrains/intellij/java/java-compiler-ant-tasks/211.6693.111/java-compiler-ant-tasks-211.6693.111.pom'.
            > Could not GET 'https://dtahfujkndrht.cloudfront.net/packages.jetbrains.team/maven/p/ij/intellij-dependencies/com/jetbrains/intellij/java/java-compiler-ant-tasks/211.6693.111/java-compiler-ant-tasks-211.6693.111.pom'.
               > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.jetbrains.intellij.java:java-compiler-ant-tasks:211.6693.111.
         > Could not get resource 'https://cache-redirector.jetbrains.com/repo1.maven.org/maven2/com/jetbrains/intellij/java/java-compiler-ant-tasks/211.6693.111/java-compiler-ant-tasks-211.6693.111.pom'.
            > Could not GET 'https://dtahfujkndrht.cloudfront.net/repo1.maven.org/maven2/com/jetbrains/intellij/java/java-compiler-ant-tasks/211.6693.111/java-compiler-ant-tasks-211.6693.111.pom'.
               > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Hellllllllllllllllllllp, please

**Comment by kana112233** [comment]
> Since my IDEA was updated to 2021.1, I have encountered a problem.
> My plug-in project cannot be built, and the error message is as follows:
> 
> > Configure project :
> > Repository https://repo.maven.apache.org/maven2/ replaced by https://maven.aliyun.com/repository/public.
> > Repository https://repo.maven.apache.org/maven2/ replaced by https://maven.aliyun.com/repository/public.
> 
> > Task :compileJava UP-TO-DATE
> > Task :patchPluginXml UP-TO-DATE
> > Task :processResources UP-TO-DATE
> > Task :classes UP-TO-DATE
> > Task :instrumentCode FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':instrumentCode'.
> 
> > Could not resolve all files for configuration ':detachedConfiguration1'.
> > Could not resolve com.jetbrains.intellij.java:java-compiler-ant-tasks:211.6693.111.
> > Required by:
> > project :
> > > Could not resolve com.jetbrains.intellij.java:java-compiler-ant-tasks:211.6693.111.
> > > Could not get resource 'https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/java/java-compiler-ant-tasks/211.6693.111/java-compiler-ant-tasks-211.6693.111.pom'.
> > > Could not GET 'https://d2cico3c979uwg.cloudfront.net/com/jetbrains/intellij/java/java-compiler-ant-tasks/211.6693.111/java-compiler-ant-tasks-211.6693.111.pom'.
> > > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> > > Could not resolve com.jetbrains.intellij.java:java-compiler-ant-tasks:211.6693.111.
> > > Could not get resource 'https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-third-party-dependencies/com/jetbrains/intellij/java/java-compiler-ant-tasks/211.6693.111/java-compiler-ant-tasks-211.6693.111.pom'.
> > > Could not GET 'https://dtahfujkndrht.cloudfront.net/packages.jetbrains.team/maven/p/ij/intellij-dependencies/com/jetbrains/intellij/java/java-compiler-ant-tasks/211.6693.111/java-compiler-ant-tasks-211.6693.111.pom'.
> > > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> > > Could not resolve com.jetbrains.intellij.java:java-compiler-ant-tasks:211.6693.111.
> > > Could not get resource 'https://cache-redirector.jetbrains.com/repo1.maven.org/maven2/com/jetbrains/intellij/java/java-compiler-ant-tasks/211.6693.111/java-compiler-ant-tasks-211.6693.111.pom'.
> > > Could not GET 'https://dtahfujkndrht.cloudfront.net/repo1.maven.org/maven2/com/jetbrains/intellij/java/java-compiler-ant-tasks/211.6693.111/java-compiler-ant-tasks-211.6693.111.pom'.
> > > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 
> Hellllllllllllllllllllp, please

Upgrade the plugin to 0.7.2
```
plugins {
    id 'org.jetbrains.intellij' version '0.7.2'
}
```

**Comment by YannCebron** [comment]
duplicates #592
