### ISSUE TITLE
buildDir property is not respected

### ISSUE THREAD

**Issue by olsh** [JetBrains/gradle-intellij-plugin#630]
I've specified `buildDir` in `gradle.build` file like this
```
buildDir = 'gradle-build'
```

But some folders (`idea-sandbox`, `searchableOptions`) are still created in the default `build` directory.

**Comment by zolotov** [comment]
The plugin doesn't use anything but `project.buildDir` for settings output directories. Please attach the entire build script and steps to recreate the problem.

**Comment by olsh** [comment]
Hi @zolotov,

Here is the build script
https://github.com/olsh/resharper-structured-logging/blob/master/build.gradle

Steps to reproduce:
1. Clone the repo
  a) Run `build.cmd pack-rider-plugin --is-rider-host`
  or self-manually
  b) Build `ReSharper.Structured.Logging.sln` and run `gradlew.bat buildPlugin -PPluginVersion=2021.1.1 -PProductVersion=2021.1.1`

**Comment by zolotov** [comment]
thanks. looks like gradle-intellij-plugin remembers value `buildDir` while applying plugin: `id 'org.jetbrains.intellij' version '0.4.19'`, so setting it on the 9th line doesn't take effect.

I'll see what I can do here. Meanwhile, I think you can workaround it like this (I haven't checked that):

```
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.3.61'
    id 'org.jetbrains.intellij' version '0.4.19' apply false
}

sourceCompatibility = 1.8
targetCompatibility = 1.8
buildDir = 'gradle-build'

apply plugin: 'org.jetbrains.intellij'
```

**Comment by olsh** [comment]
Thanks, the workaround works! 👍🏻

**Comment by YannCebron** [comment]
on a sidenote, 0.4.19 is an ancient version, please keep this up-to-date
