### ISSUE TITLE
JbrResolver doesn't support Windows WSL

### ISSUE THREAD

**Issue by hsz** [JetBrains/gradle-intellij-plugin#631]
> Hi, all. I installed the java environment on the Windows sub-platform wsl. After opening the plugin project today,
> the gradle compilation failed and the error message was:
> Gradle sync failed: The supplied javaHome seems to be invalid. I cannot find the java executable.
> Tried location: `\\wsl$\Ubuntu\opt\java\jdk1.8.0_181\bin\java.exe` (63 ms)
> I tried to solve it, and found that this path has more than the last `.exe` suffix.
> The path      `\\wsl$\Ubuntu\opt\java\jdk1.8.0_181\bin\java` exists.
> But the path `\\wsl$\Ubuntu\opt\java\jdk1.8.0_181\bin\java.exe` not exists! If i type this path in Windows File Manager.
> I got a error message:  Windows can not access `\\wsl$\Ubuntu\opt\java\jdk1.8.0_181\bin\java.exe`.
> So how to build gradle plugin project in WSL enviroment?

Issue reported via JBPlatform Slack: https://jetbrains-platform.slack.com/archives/CPL5291JP/p1618751907085400

Java path is built based on the OS, and there’s an assumption made that if you’re on Windows, there’s `.exe` suffix put at the end.

The safest choice for Windows would be checking if the file with the `.exe` suffix exists – otherwise fallback to the non-exe path.

https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/groovy/org/jetbrains/intellij/jbr/JbrResolver.groovy#L96

**Comment by zolotov** [comment]
JbrResolver doesn't participate in compilation phase. What makes you think that the problem is there?

**Comment by hsz** [comment]
You're right. That's an issue in IJ integration with WSL: https://youtrack.jetbrains.com/issue/IDEA-263599
