### ISSUE TITLE
PluginVerifier fails to download IDE

### ISSUE THREAD

**Issue by mvilliger** [JetBrains/gradle-intellij-plugin#632]
This is a followup issue to #606 and issue #585. 

The release download of e.g. IU 2020.2.4 fails with the following log message: `Cannot download IDE 'IU-2020.2.4' from release channel. Trying another channel...`.
As far as I can see this messages comes from [RunPluginVerifierTask.groovy:622](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/groovy/org/jetbrains/intellij/tasks/RunPluginVerifierTask.groovy#L622).
Unfortunately the exception is ignored and not logged so it is hard to tell why the [DownloadAction](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/groovy/org/jetbrains/intellij/tasks/RunPluginVerifierTask.groovy#L659) actually failed.

Would it be possible to include the IOException in the debug log to get more details to find the root cause?

**Comment by hsz** [comment]
@mvilliger Thanks for reporting. 
I've extended exceptions logging with: 8ca6e91
Do you run your test on GitHub Actions?

**Comment by mvilliger** [comment]
@hsz Thank you very much. Then hopefully I know more as soon as a new snapshot is available :)

**Comment by hsz** [comment]
@mvilliger THe latest snapshot should be already available (also as 0.8.0).

**Comment by mvilliger** [comment]
@hsz I think I found the root cause of the problem:

The [RunPluginVerifierTask](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/groovy/org/jetbrains/intellij/tasks/RunPluginVerifierTask.groovy#L659) uses the [gradle-download-task](https://github.com/michel-kraemer/gradle-download-task) with the option `tempAndMove(true)`.

This might fail for gradle-download-task versions older than 4.0.4 because of [issue 146](https://github.com/michel-kraemer/gradle-download-task/issues/146). The gradle-intellij-plugin declares the fixed version 4.0.4 in its [build.gradle.kts](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/build.gradle.kts#L37).
Next to the gradle-intellij-plugin the affected project also includes the Kotlin JVM plugin in version 1.4.31. This plugin also has a dependency to gradle-download-task [but in the older version 4.0.2](https://github.com/JetBrains/kotlin/blob/v1.4.31/libraries/tools/kotlin-gradle-plugin/build.gradle.kts#L59).

When calculating the 'RequiredBy' build dependencies on the affected project for 'gradle-download-task' it shows the following:

```
de.undercouch:gradle-download-task:4.0.2
    org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.31
        org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:1.4.31
            build.gradle.kts
```

So in the affected build gradle-download-task version 4.0.2 is used as required by kotlin-gradle-plugin. Unfortunately on the system where the build is executed (a company internal Kubernetes cluster) the directories are on different partitions and that's why the move from the temp dir to the user home dir fails (because of [issue 146](https://github.com/michel-kraemer/gradle-download-task/issues/146)).

To force the build to use gradle-download-task version 4.0.4 I added the following to the build.gradle.kts:

```
buildscript {
    dependencies {
        classpath("de.undercouch:gradle-download-task:4.0.4")
    }
}
```

This fixes the issue for us.

As far as I can see the dependency to gradle-download-task version 4.0.4 of the gradle-intellij-plugin has no effect during the build because this dependency is not declared in the [pom of the deployed artifact](https://oss.sonatype.org/service/local/repositories/snapshots/content/org/jetbrains/intellij/plugins/gradle-intellij-plugin/0.8.0-SNAPSHOT/gradle-intellij-plugin-0.8.0-20210420.191125-28.pom).
Therefore the gradle build cannot know that the gradle-intellij-plugin actually requires version 4.0.4 and therefore chooses version 4.0.2 from the Kotlin plugin?

Maybe the runtime dependencies of the gradle-intellij-plugin should also be reflected in the [created pom](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/build.gradle.kts#L131)? What do you think?

**Comment by hsz** [comment]
@mvilliger, thanks for a detailed investigation!
In general, snapshot channels have that issue with dependencies (see https://github.com/JetBrains/gradle-intellij-plugin#snapshot-version), and exact dependencies have to be specified manually.
We'll take care of it!

**Comment by mvilliger** [comment]
@hsz Yes I am aware of that and I have included the dependencies as documented. Then there might be some dependencies missing in the readme?

**Comment by hsz** [comment]
@mvilliger No, even otherwise – we shouldn't require adding such dependencies if you'd like to use snapshot release. And that's something that should be fixed on our side.

**Comment by zolotov** [comment]
should be fixed on the latest 0.8-SNAPSHOT. @mvilliger could you confirm please?

**Comment by mvilliger** [comment]
@zolotov Sorry for the delay. I tested with 0.8.0-SNAPSHOT without any buildscript dependencies and the build was successful.
So I can confirm the issue is fixed. Thank you all for your efforts and your help!

**Comment by zolotov** [comment]
@mvilliger thank you very much for the investigation and checking the results!
