### ISSUE TITLE
[0.7.3] Could not find org.jetbrains.intellij.plugins:structure-base:3.169

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/gradle-intellij-plugin#633]
Java: OpenJDK Runtime Environment 18.9 (build 11.0.8+10)
Gradle: 7.0

After bumping the plugin to 0.7.3, I'm getting:

```
$ ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'git-machete-intellij-plugin'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.jetbrains.intellij.plugins:structure-base:3.169.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/org/jetbrains/intellij/plugins/structure-base/3.169/structure-base-3.169.pom
       - https://plugins.gradle.org/m2/org/jetbrains/intellij/plugins/structure-base/3.169/structure-base-3.169.pom
     Required by:
         project :
         project : > org.jetbrains.intellij:org.jetbrains.intellij.gradle.plugin:0.7.3 > org.jetbrains.intellij.plugins:gradle-intellij-plugin:0.7.3
   > Could not find org.jetbrains.intellij.plugins:structure-intellij:3.169.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/org/jetbrains/intellij/plugins/structure-intellij/3.169/structure-intellij-3.169.pom
       - https://plugins.gradle.org/m2/org/jetbrains/intellij/plugins/structure-intellij/3.169/structure-intellij-3.169.pom
     Required by:
         project :
         project : > org.jetbrains.intellij:org.jetbrains.intellij.gradle.plugin:0.7.3 > org.jetbrains.intellij.plugins:gradle-intellij-plugin:0.7.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

That's suspicious since according to README, adding `org.jetbrains.intellij.plugins:structure-intellij` to Gradle buildscript dependencies is only required for snapshot builds of the plugin. Also, README mentions version `3.139` while Gradle is complaining about `3.169`... looks suspiciously like a typo somewhere 🤔

**Comment by PawelLipski** [comment]
Actually, adding the `buildscript` and `pluginManagement` blocks didn't help either for 0.7.3, I'm getting the same error :/

**Comment by zolotov** [comment]
removed 0.7.3 so far, will investigate how to properly publish plugins these dayas without jcenter

**Comment by hsz** [comment]
The problem is caused because the plugin depends on `org.jetbrains.intellij.plugins:structure-base:3.169`, which is hosted on Space Packages: https://github.com/JetBrains/gradle-intellij-plugin/blob/master/build.gradle.kts#L19
As a workaround, we have to provide that repository in `pluginManagement`:

```
pluginManagement {
    repositories {
        maven("https://cache-redirector.jetbrains.com/plugins.gradle.org")
        maven("https://cache-redirector.jetbrains.com/packages.jetbrains.team/maven/p/intellij-plugin-verifier/intellij-plugin-structure")
    }
}
```

Unfortunately, that's not the solution.

**Comment by hsz** [comment]
`org.jetbrains.intellij.plugins:structure-base:3.169` and `org.jetbrains.intellij.plugins:structure-intellij:3.169` libraries are now available in Maven Central.
No action would be required.
