### ISSUE TITLE
Swing UI Designer form class instrumentation

### ISSUE THREAD

**Issue by azurvii** [JetBrains/gradle-intellij-plugin#642]
What should be the suggested way to instrument Swing UI Designer forms? I am not able to find detailed instructions on how to use this plugin with instrumenting forms created from Swing UI Designer. And simply adding a form with a binding class does not allow the app to run. My `build.gradle`:
```groovy
plugins {
    id "application"
    id "idea"
    id "org.jetbrains.intellij" version "0.7.3"
}

group "org.example"
version "1.0-SNAPSHOT"

mainClassName = "TestDialog"

repositories {
    mavenCentral()
}

dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter-api:5.7.0"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.7.0"
}

test {
    useJUnitPlatform()
}
```

The log of `gradle run`:
```log
20:03:36: Executing task 'TestDialog.main()'...

> Task :wrapper

BUILD SUCCESSFUL in 164ms
1 actionable task: 1 executed
> Task :compileJava UP-TO-DATE
> Task :patchPluginXml NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :instrumentCode UP-TO-DATE
> Task :postInstrumentCode

> Task :TestDialog.main() FAILED
4 actionable tasks: 2 executed, 2 up-to-date
Error: Unable to initialize main class TestDialog
Caused by: java.lang.NoClassDefFoundError: com/intellij/uiDesigner/core/Spacer

FAILURE: Build failed with an exception.
```

I guess that means the class is not properly instrumented?

And I found if I include a dependency of `com.intellij:forms_rt:7.0.3`, the run starts to work. `forms_rt` was released in 2008, according to mvnrepository. (Not saying it's obsolete, since Swing has been basically the same; however I'm not sure if this should be the right library to include.)

My IntelliJ:
```
IntelliJ IDEA 2021.1 (Community Edition)
Build #IC-211.6693.111, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
```

The `TestDialog` form was a vanilla form created from `New > Swing UI Designer > Create Dialog Class`.

**Comment by zolotov** [comment]
> gradle run

What task is it?

**Comment by azurvii** [comment]
> > gradle run
> 
> What task is it? How do you build a classpath for it?

That is from gradle's own `application` plugin: https://docs.gradle.org/current/userguide/application_plugin.html. Quoting its text:

> You can run the application by executing the run task (type: JavaExec). This will compile the main source set, and launch a new JVM with its classes (along with all runtime dependencies) as the classpath and using the specified main class.

For our concern, it should include all gradle runtime dependencies and compiled classes in the project source sets in its runtime classpath. I had the assumption that the `org.jetbrains.intellij` plugin would include the needed classes in the gradle build system, but it seems it does not. `gradle run` seems to behave the same as `ctrl+shift+f10`. My `Build and run using` setting is `Gradle (Default)`, and not `IntelliJ IDEA`.

Generally I use `gradle run` for development tests, and `gradle distZip` for distribution. How do you launch the application? And how do you package it?

**Comment by zolotov** [comment]
> That is from gradle's own application plugin: https://docs.gradle.org/current/userguide/application_plugin.html. Quoting its text:

`gradle-intellij-plugin` has nothing to do with this task. It's on you to fill its runtime with any needed dependencies.

> Generally I use gradle run for development tests, and gradle distZip for distribution. How do you launch the application? And how do you package it?

Sorry, but it's not the concern of the gradle-intellij-plugin. The plugin is about running IntelliJ IDEA and your plugin inside it. `run`, `distZip` and other type of applications different from IntelliJ plugins are out of scope.

**Comment by azurvii** [comment]
> Sorry, but it's not the concern of the gradle-intellij-plugin. The plugin is about running IntelliJ IDEA and your plugin inside it. `run`, `distZip` and other type of applications different from IntelliJ plugins are out of scope.

Oh, I see. So this `gradle-intellij-plugin` plugin is solely for IntelliJ plugins, not for general app dev. Thanks for pointing this out.

**Comment by zolotov** [comment]
You can use this for instrumenting UI classes for general app, even though it might be an overkill to download the entire IntelliJ SDK for that, but you still have to fill the classpath manually.

Alternatively, you can implement your own task that will do the same thing as this one: https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/kotlin/org/jetbrains/intellij/tasks/IntelliJInstrumentCodeTask.kt#L29

**Comment by azurvii** [comment]
Thanks for the pointers. I had a quick look at the `forms_rt.jar` from the sdk and from the maven repo (dated 2008), and the changes seem to be not major. This plugin with the forms rt dependency seems to be the easiest setup I could find.

I'll take a closer look at the ant task, which seems to have some dependencies as well other than the sdk, but lighter I guess.

I do hope that the newer `forms_rt.jar` could be uploaded to maven central or some other public repo, so that the manual process could be easier.

**Comment by zolotov** [comment]
> I do hope that the newer forms_rt.jar could be uploaded to maven central or some other public repo, so that the manual process could be easier.

It's somewhere in this maven repo https://www.jetbrains.com/intellij-repository/releases

**Comment by azurvii** [comment]
> It's somewhere in this maven repo https://www.jetbrains.com/intellij-repository/releases

Appreciated. So it's `java-gui-forms-rt` now.
