### ISSUE TITLE
Duplicate JARs in distribution zip using intellij-plugin 0.6.3

### ISSUE THREAD

**Issue by davsclaus** [JetBrains/gradle-intellij-plugin#649]
When I build the Apache Camel IDEA plugin then the distribution zip has duplicate JARS (2 or more) of dependencies such as Camel JARs and slf4j etc.

This can be reproduced by checking out the git repo at
https://github.com/camel-tooling/camel-idea-plugin

And then run

    ./gradlew clean build

And then see inside the zip file in 

     camel-idea-plugin/build/distributions/camel-idea-plugin-0.7.3-SNAPSHOT.zip

That there are multiple JARs like

```
├── camel-allcomponents-3.9.0.pom
├── camel-api-3.9.0.jar
├── camel-api-3.9.0_1.jar
├── camel-catalog-3.9.0.jar
├── camel-catalog-3.9.0_1.jar
├── camel-catalog-maven-3.9.0.jar
├── camel-core-catalog-3.9.0.jar
├── camel-core-catalog-3.9.0_1.jar
├── camel-idea-plugin-0.7.2.jar
├── camel-tooling-model-3.9.0.jar
├── camel-tooling-model-3.9.0_1.jar
├── camel-tooling-model-3.9.0_2.jar
├── camel-util-3.9.0.jar
├── camel-util-3.9.0_1.jar
├── camel-util-3.9.0_2.jar
├── camel-util-json-3.9.0.jar
├── camel-util-json-3.9.0_1.jar
├── camel-util-json-3.9.0_2.jar
├── camel-util-json-3.9.0_3.jar
├── commons-codec-1.15.jar
├── commons-logging-1.2.jar
├── groovy-3.0.7.jar
├── httpclient-4.5.13.jar
├── httpcore-4.4.13.jar
├── ivy-2.5.0.jar
├── searchableOptions-0.7.2.jar
├── slf4j-api-1.7.30.jar
├── slf4j-api-1.7.30_1.jar
└── slf4j-api-1.7.30_2.jar
```

**Comment by davsclaus** [comment]
These duplicate JARs is causing classloading problems for the plugin - I have to manually delete the duplicate JARs in the zip file.

**Comment by zolotov** [comment]
Should I check some particular version of the camel-idea-plugin? I cannot recreate that on master.

**Comment by davsclaus** [comment]
Oh not in particular, I run

./gradlew clean build

The unit test fails, but the distributions is built, and if I unzip it I get those duplicate JARs, such as

-rw-r--r--   1 davsclaus  staff    41472 May  3 13:03 slf4j-api-1.7.30.jar
-rw-r--r--   1 davsclaus  staff    41472 May  3 13:03 slf4j-api-1.7.30_1.jar
-rw-r--r--   1 davsclaus  staff    41472 May  3 13:03 slf4j-api-1.7.30_2.jar


I am using gradle 6.0.1, and its on Java 11 on macos M1

openjdk 11.0.10 2021-01-19 LTS
OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.45+27-CA (build 11.0.10+9-LTS, mixed mode)

**Comment by davsclaus** [comment]
Okay so using older idea plugin works, eg

This is OK (no duplicate)

```
plugins {
    id "org.jetbrains.intellij" version "0.6.5"
}
```

And this fails (duplicates)

```
plugins {
    id "org.jetbrains.intellij" version "0.7.3"
}
```

**Comment by zolotov** [comment]
thanks. recreated on 6.0.1 and looks like updating gradle up to 6.8 fixes the problem. Unfortunately, I cannot check my fix because I cannot compile `gradle-intellij-plugin` using 6.0.1 :)

**Comment by davsclaus** [comment]
Ah thanks, yeah we can surely upgrade gradle - it is rather old.

**Comment by zolotov** [comment]
I will push my blindly fix anyway. For you it's probably easier to upgrade gradle than waiting for the next version of gradle-intellij-plugin

**Comment by davsclaus** [comment]
Thanks for the speedy help, you are welcome to close this ticket
