### ISSUE TITLE
Unable to collect coverage with JaCoCo plugin using agent > 0.7.2

### ISSUE THREAD

**Issue by henryju** [JetBrains/gradle-intellij-plugin#65]
We have added some tests to [our plugin](https://github.com/SonarSource/sonar-intellij/) and decided to compute coverage using official JaCoCo Gradle plugin with default configuration. It was working fine. Then we tried to update version of JaCoCo agent to a more recent version (default one is 0.7.2) and from this point coverage was always 0%.

Looking at content of JaCoCo report (test.exec) our plugin classes were missing.

After some exchange with JaCoCo guys we found that starting from version 0.7.3 they are automatically excluding classes that "look" to be generated classes without source files. For that they rely on nullity of Object.class.getProtectionDomain().getCodeSource(). ([more background](https://github.com/jacoco/jacoco/pull/272#issuecomment-70125944))

As we don't have any issue with [another non IntelliJ Gradle project](https://github.com/SonarSource/sonar-gradle) I guess the gradle-intellij-plugin may have some influence on this.

Note that [a parameter](https://github.com/jacoco/jacoco/pull/288) will be added to the next JaCoCo agent release to force it to restore all behavior (instrument all files). But not sure this is the perfect solution.

**Comment by zolotov** [comment]
Hi @henryju,

Sorry for the late answer.

>  I guess the gradle-intellij-plugin may have some influence on this.

Indeed it instrument classes with `@NotNull/@Nullable` annotations and forms, so these files might be considered as generated by JaCoCo I suppose. Please try to set `intellij.instrumentCode` to `false`. If it was that, I don't think I can do something with it

**Comment by henryju** [comment]
I tried to put intellij.instrumentCode to false but it doesn't seem to change the result: there is still no coverage in JaCoCo report with version 0.7.6.

**Comment by Godin** [comment]
@zolotov @henryju upgrade of gradle-intellij-plugin to version 0.30.0 solves issue with coverage, most likely because of commit e134dcea85ec2afec72637f2657d309469e878fc - https://github.com/SonarSource/sonarlint-intellij/pull/35 as a proof

**Comment by zolotov** [comment]
@Godin thank you for update. Still unclear to me what was wrong.

@Godin @henryju could you check 0.1.10 version? If I broke this again it's better to know now.

**Comment by henryju** [comment]
Works fine with 0.1.10.

**Comment by Godin** [comment]
@zolotov all fine with `0.1.10` as it doesn't set `java.system.class.loader` to `com.intellij.util.lang.UrlClassLoader`. And my best guess - is that `ProtectionDomain` is not set by `com.intellij.util.lang.UrlClassLoader` when it defines classes, what might be considered as a flaw in it and not in gradle-intellij-plugin.

**Comment by zolotov** [comment]
Thanks!
