### ISSUE TITLE
Consider using Gradle APIs to download JBR instead of DownloadAction

### ISSUE THREAD

**Issue by vlsi** [JetBrains/gradle-intellij-plugin#660]
The issues with DownloadAction are:
* It does not support dependency verification (see https://docs.gradle.org/current/userguide/dependency_verification.html)
* It does not play nicely with caching and removing stale cached artifacts

I guess the relevant Gradle API is to pretend that JBR distribution site is Ivy repository with a custom pattern: https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:defining_custom_pattern_layout_for_an_ivy_repository

**Comment by hsz** [comment]
Hey, Vladimir!
Thanks for putting that on the table. I've been recently looking for some alternatives to the DownloadAction, but I didn't even consider Ivy repositories as a way to go.
I've just got rid of it and replaced it with Ivy, and it seems to be working well.
Thanks for that!

**Comment by vlsi** [comment]
That was fast!
