### ISSUE TITLE
WDYT of adding a "bundle your own standalone IDE" feature?

### ISSUE THREAD

**Issue by vlsi** [JetBrains/gradle-intellij-plugin#663]
There's a use-case to package a standalone IDE based on top of JetBrains Platform.
For instance, it could be an MPS-based IDE with plugins.

The case not really the same as "building Intellij plugin", however, I think it is related, so I ask here.

The steps to build an IDE requires:
a) Download the relevant JBR
b) Bundle it and sign appropriately
c) Prepare patches (e.g. for incremental updates)

I have no idea if the official JBR binaries would be publicly available, however, it would be nice if the plugin could accommodate the use case.

---

I know mps-gradle-plugin exists (even two of them!), and I even tried to refactor the logic to build dmg in https://github.com/mbeddr/mps-gradle-plugin/pull/70
However, it looks like the case is not really MPS-specific, and it is more like "building IntelliJPlatform-based IDE", which might better be placed here.

Consider an example:

```kotlin
plugins {
    // Here we build a standalone IDE 
    id("org.jetbrains.intellij.standalone-ide") version "..."
}
```

```kotlin
plugins {
    // Here we do not build plugins, but we just want to download JBR
    id("org.jetbrains.intellij.jbr-downloader") version "..."
}
```

```kotlin
plugins {
    // Here's how we build Intellij-plugin
    id("org.jetbrains.intellij.plugin") version "..."
}
```

```kotlin
plugins {
    // Here's how we build IDEA plugin (e.g. with extra convenient conventions)
    id("org.jetbrains.intellij.idea-plugin") version "..."
}
```

WDYT?

PS. My personal use case is bundling an MPS-based IDE https://hardella.com/

**Comment by YannCebron** [comment]
this is not planned
