### ISSUE TITLE
Consider adjusting the plugin name: org.jetbrains.intellij has too broad meaning

### ISSUE THREAD

**Issue by vlsi** [JetBrains/gradle-intellij-plugin#664]
The current plugin name is `org.jetbrains.intellij`, and it says literally nothing to the build script reader.

The rule of thumb is that an unprepared reader should understand what the build script is about.
In other words:

```
plugins {
    `java-library` // <-- oh, this makes the project to be a java library
    `signing` // <-- this adds signing feature
    id("org.jetbrains.intellij") // ?? What features does it add?
}
```

There might be lots of Gradle plugins shared by IntelliJ team, and it would be sad if they all were named `org.jetbrains.intellij`.

Here are some ideas:
* `org.jetbrains.intellij-plugin`
* `org.jetbrains.intellij-platform-plugin`
* `org.jetbrains.jbr-download` (JBR download might be useful on its own without adding all the rest tasks)

Note: multiple plugins can go in the very same jar, so the renaming is not really disruptive.

Here's a relevant Gradle documentation section: https://docs.gradle.org/current/userguide/designing_gradle_plugins.html#capabilities-vs-conventions
I agree it might be hard to understand from the first read, so here's my issue to improve the doc :) https://github.com/gradle/gradle/issues/17198

**Comment by hsz** [comment]
Sorry, we don't have a plan for changing the name.

**Comment by turansky** [comment]
`org.jetbrains.intellij` looks like fine **group** for plugins

**Comment by hsz** [comment]
The base name will be changed to _IntelliJ Platform Gradle Plugin_
That could automatically lead to the ID change to `org.jetbrains.intellij.platform`

**Comment by hsz** [comment]
Yes, the repository name can be adjusted as well.
GitHub handles redirections nicely, so there won't be any issues here.

**Comment by hsz** [comment]
As mentioned above, the 2.0 release introduces:
- new name: **IntelliJ Platform Gradle Plugin**
- new ID: `org.jetbrains.intellij.platform`
- new repository name: https://github.com/JetBrains/intellij-platform-gradle-plugin
