### ISSUE TITLE
Cannot find builtin plugin JavaScript with 212 (2021.2 EAP) IDE dependency

### ISSUE THREAD

**Issue by Undin** [JetBrains/gradle-intellij-plugin#674]
The plugin shows error when I try to load a plugin project
```
Cannot create plugin from file (/Users/Arseniy.Pendryak/Programming/intellij-rust/deps/ideaIU-212.3116-EAP-CANDIDATE-SNAPSHOT/plugins/JavaScriptLanguage):
Invalid plugin descriptor 'plugin.xml': failed to resolve <xi:include>.
Not found document 'intellij.javascript.web.xml' referenced in <xi:include href="intellij.javascript.web.xml", xpointer="xpointer(/idea-plugin/*)"/>.
<xi:fallback> element is not provided. (at plugin.xml)
```

As a result, it's impossible to build plugins for 212 EAPs using `gradle-intellij-plugin`

Important details:
- `gradle-intellij-plugin` 0.7.3
- 212 IDEA Ultimate dependency (`212.3116-EAP-CANDIDATE-SNAPSHOT`)
- `JavaScript` plugin dependency

Test project can be found [here](https://github.com/Undin/java-script-loading-issue)

I suppose the root of the problem is a movement of `META-INF/web-platform.xml` to `intellij.javascript.web.xml` (i.e. to top level in the corresponding jar file).
As a result, `com.jetbrains.plugin.structure.intellij.plugin.IdePluginManager#createPlugin(java.nio.file.Path, boolean, java.lang.String)` fails to find `intellij.javascript.web.xml`. Not sure, it's an issue of the platform or  `org.jetbrains.intellij.plugins:structure-intellij` dependency

Related to #608

**Comment by zolotov** [comment]
> I suppose the root of the problem is a movement of META-INF/web-platform.xml to intellij.javascript.web.xml (i.e. to top level in the corresponding jar file).

I think all of them should be in the same jar
![image](https://user-images.githubusercontent.com/140920/119691459-e1cb8180-be4a-11eb-8c10-fe8e3a5aeed1.png)


@serejke @hsz any ideas?

**Comment by Undin** [comment]
> I think all of them should be in the same jar

They are in the same jar.
But there is a difference between 211 and 212. Although, I am not sure if it matters.
| 211 | 212 |
| - | - |
| ![image](https://user-images.githubusercontent.com/2539310/119695134-9028f400-be56-11eb-88d6-66418c8a5fc9.png) | ![image](https://user-images.githubusercontent.com/2539310/119695595-03cb0100-be57-11eb-9da4-479b62f8e438.png) |
| ![image](https://user-images.githubusercontent.com/2539310/119695007-6f609e80-be56-11eb-963a-627c6721c9e4.png) | ![image](https://user-images.githubusercontent.com/2539310/119695036-77204300-be56-11eb-8fdb-523e42fdf32f.png) |

**Comment by zolotov** [comment]
I think it should be inside `META-INF` or to be referenced in some other way rather than just `intellij.javascript.web.xml`. I suppose it may not work in the IntelliJ production as well. @piotrtomiak what do you think?

**Comment by piotrtomiak** [comment]
@zolotov The change has been introduced by @develar in commit from 27.03.2021 and it's possible that there were some other changes to plugin classloading rules recently, which resulted in the aforementioned issue. I don't really know how to fix this, or why @develar moved the plugin descriptor out of META-INF, as `intellij.javascript.web` is a "virtual" module. In the build it's merged with JavaScript plugin and IMHO `intellij.javascript.web.xml` should be located in the same place as `js-css.xml` and other additional descriptors included from `plugin.xml`.

**Comment by zolotov** [comment]
My point is that it's an unlikely problem for the gradle-intellij-plugin and probably even the problem of the JavaScript plugin for IntelliJ. @piotrtomiak could you please investigate that together with @develar, or probably you know the better candidate to take this over?

**Comment by piotrtomiak** [comment]
@zolotov, agreed that this is most likely not a Gradle plugin problem. @develar, can you have a look?

**Comment by ARostovsky** [comment]
I also faced this issue, @develar ping

**Comment by Undin** [comment]
Any updates?
ping @develar

**Comment by izhangzhihao** [comment]
Any progress?

**Comment by hsz** [comment]
The fix is now available in `v1.1.3`.

**Comment by changety** [comment]
My IDEA version is 2022.1，  I also meet this issue ：
Cannot find builtin plugin 'JavaScript' for IDE: ~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2021.2/b0727ceddea2b62b16825db9308e14a470198e7f/ideaIC-2021.2

Just new a plugin project, and add 
```
    <depends>JavaScript</depends> in plugin.xml
```
```
    plugins.set(listOf("JavaScript")) in build.gradle.ktx
```
this issue can be recurrence

Any Solution？

**Comment by Super1Windcloud** [comment]
IC is not suitable for plug-in development, many functions are not available
