### ISSUE TITLE
212.3116.29-EAP-SNAPSHOT can be resolved when used for intellij.version, but not in runPluginVerifier

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/gradle-intellij-plugin#676]
gradle-intellij-plugin version: 0.7.3

I'm successfully building the project against `212.3116.29-EAP-SNAPSHOT`, but plugin verifier can't resolve it when I include this version among `runPluginVerifier.ideVersions`:

```
$ ./gradlew runPluginVerifier 

> Task :runPluginVerifier
Download https://cache-redirector.jetbrains.com/download.jetbrains.com/idea/ideaIC-2020.3.4.tar.gz
Download https://data.services.jetbrains.com/products/download?code=IC&platform=linux&type=release&build=212.3116.29
Download https://data.services.jetbrains.com/products/download?code=IC&platform=linux&type=rc&build=212.3116.29
Download https://data.services.jetbrains.com/products/download?code=IC&platform=linux&type=eap&build=212.3116.29
Download https://data.services.jetbrains.com/products/download?code=IC&platform=linux&type=beta&build=212.3116.29

> Task :runPluginVerifier FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runPluginVerifier'.
> IDE '212.3116.29' cannot be downloaded. Please verify the specified IDE version against the products available for testing: https://jb.gg/intellij-platform-builds-list
```

**Comment by YannCebron** [comment]
EAP for 2021.2 has not started yet.

**Comment by PawelLipski** [comment]
Ok... so if you could clarify:
1. the 212-EAP is available at https://www.jetbrains.com/intellij-repository/snapshots/
2. as I direct consequence of (1.) I can build against this 212-EAP
3. but as for now the event of **_EAP start_** (?) has not happened? how is the moment of EAP start determined/is it only after a blogpost (like this one: https://blog.jetbrains.com/idea/2021/01/intellij-idea-2021-1-eap-1/) is published on JetBrains blog?

**Comment by YannCebron** [comment]
Official start of EAPs are announced for each product on Twitter and Blog separately.
All released versions are available here https://jb.gg/intellij-platform-builds-list
