### ISSUE TITLE
Migrating `intellij { ... }` block to 1.0 in Groovy code?

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/gradle-intellij-plugin#677]
I've the following piece of Groovy code in my top-level build.gradle:

```
intellij {
  instrumentCode false
  pluginName 'git-machete-intellij-plugin'
  version intellijVersions.buildTarget

  plugins 'git4idea'
}
```

I've tried changing to `.set(...)` as well:

```
intellij {
  instrumentCode.set(false)
  pluginName.set('git-machete-intellij-plugin')
  version.set(intellijVersions.buildTarget)

  plugins.set('git4idea') // Needed solely for ArchUnit
}
```

but in both cases I'm getting a rather cryptic error:

```
$ ./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/plipski/git-machete-intellij-plugin/build.gradle' line: 549

* What went wrong:
A problem occurred evaluating root project 'git-machete-intellij-plugin'.
> No signature of method: build_71t1r5scvek2m5kjli0kayru9.intellij() is applicable for argument types: (build_71t1r5scvek2m5kjli0kayru9$_run_closure8) values: [build_71t1r5scvek2m5kjli0kayru9$_run_closure8@16bd0443]
```

Is Groovy still supported as of 1.0? I can't find any Groovy-specific migration guide at https://lp.jetbrains.com/gradle-intellij-plugin/

**Comment by hsz** [comment]
From the _Breaking changes - Lazy Properties_ section:

> To access a lazy property call `.get()`, like: `intellij.version.get()`.
No changes in Groovy are required.

**Comment by PawelLipski** [comment]
Hmmm okay so hence no changes in Groovy are required... what could be the source of `No signature of method: build_71t1r5scvek2m5kjli0kayru9.intellij() ` in the **unchanged** version? 🤔 

I've even reduced the `intellij { ... }` to just:

```gradle
intellij {
  pluginName 'git-machete-intellij-plugin'
}
```

and I'm still getting the very same error.

This doesn't happen only for a no-op empty block, tho: `intellij { ... }` 🤔 

Look like the way of passing the `{...}` closure to `intellij` has changed (?)

**Comment by hsz** [comment]
```

intellij {
  pluginName = 'git-machete-intellij-plugin'
}

```

Well, `pluginName` is a property.
Previous syntax was a function call, not even documented. 😉

**Comment by PawelLipski** [comment]
Whoops... even the first mentioned example, Go plugin uses that syntax 😅 https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/build.gradle#L51

**Comment by hsz** [comment]
Not for long. 😋

**Comment by PawelLipski** [comment]
Thanks, this seems the fix the problem indeed :)
