### ISSUE TITLE
Val cannot be reassigned when trying reassign value of `version` propererty in `intellij` block

### ISSUE THREAD

**Issue by MairwunNx** [JetBrains/gradle-intellij-plugin#683]
I've just created project from project wizard and I got incorrect template

```
IntelliJ IDEA 2021.2 EAP (Ultimate Edition)
Build #IU-212.3116.43, built on May 27, 2021
```

**Comment by MairwunNx** [comment]
The same problem when I using Gradle Groovy DSL.

**Comment by hsz** [comment]
Pavel, please go through the migration guide:

https://lp.jetbrains.com/gradle-intellij-plugin/

**Comment by MairwunNx** [comment]
@hsz Huh.. Thanks! I hope plugin template bundled in IntelliJ IDEA will updated.

**Comment by MairwunNx** [comment]
Thanks for very quickly response. It was awesome!

**Comment by hsz** [comment]
At the bottom of the _How to upgrade?_ section, there's a link to the commit with all changes required to be done in the IntelliJ Platform Plugin Template project.
