### ISSUE TITLE
`intellij { version }` not work

### ISSUE THREAD

**Issue by caiqichang** [JetBrains/gradle-intellij-plugin#684]
whatever i change in `build.gradle`  (like '2020.3.4' or 'IU-211.7124.45')
```groovy
intellij {
    version '2021.1.1'
}
```
it always show this when i rebuild and install the plugin
```
not compatible with the current version of the IDE, because it requires build 212.3116 or newer but the current build is IU-211.7142.45
```

**Comment by hsz** [comment]
What did you set to the `untilBuild` property?

**Comment by caiqichang** [comment]
@hsz 
sinceBuild is 202
untilBuild is 221.*

**Comment by caiqichang** [comment]
i change to version 0.7.3 and everything work well.

**Comment by hsz** [comment]
From which one?
