### ISSUE TITLE
Migrating patchpatchPluginXml.changeNotes property to 1.0 in Groovy code?

### ISSUE THREAD

**Issue by bric3** [JetBrains/gradle-intellij-plugin#686]
I was using the plugin in 0.7.3 and used the following syntax, however migrating to 1.0 this doesn't work anymore.

```groovy
changeNotes = {
                Jsoup.parse(file('build/docs/CHANGELOG.html').getText('UTF-8'))
                        .select("#releasenotes")
                        .get(0)
                        .nextElementSibling()
                        .children()
                        .stream()
                        .map { e ->
                            e.html().replaceAll('\\(preview, available from GitHub releases\\)', '')
                                    .replaceAll('#([0-9]+)', '<a href="https://github.com/bric3/jd-intellij/issues/$1">#$1</a>')
                            // regex for GitHub user names from https://github.com/shinnn/github-username-regex
                                    .replaceAll('(?i)@([a-z\\d](?:[a-z\\d]|-(?=[a-z\\d])){0,38})', '<a href="https://github.com/$1">@$1</a>')
                        }
                        .collect()
                        .join("\n")
}
```

The task is now expecting a `Property` object for this property:

https://github.com/JetBrains/gradle-intellij-plugin/blob/231a7ea4270511b385a70bc71c4f25ecfeb8aa83/src/main/kotlin/org/jetbrains/intellij/tasks/PatchPluginXmlTask.kt#L51-L53

Although I don't quite get how to do that with the groovy DSL. The [migration guide](https://lp.jetbrains.com/gradle-intellij-plugin/) only gives Kotlin DSL example.

Using `changeNotes({ "a".repeat(2) })` raises the following :

```
A problem occurred evaluating root project 'jd-intellij'.
> No signature of method: build_8h1qj0kzsdfx7b5wv4gh8bj8n.patchPluginXml() is applicable for argument types: (build_8h1qj0kzsdfx7b5wv4gh8bj8n$_run_closure6) values: [build_8h1qj0kzsdfx7b5wv4gh8bj8n$_run_closure6@5985014]
```

And due the `changeNotes` being a `Property` I cannot perform that operation in a `doLast` block

This is somewhat similar to #677

**Comment by hsz** [comment]
@bric3 Thanks for asking!

In the migration guide, we've mentioned:

> Using the Gradle Changelog Plugin requires delaying of the `changelog.getLatest()` method invocation to make its output available for the `patchPluginXml.changeNotes` property. Now it is available to use the built-in `Provider` from the Gradle API.

That applies also to your case and Gradle as well. Try with:

```
changeNotes = provider {
  ...
}
```

**Comment by bric3** [comment]
The gradle [documentation on lazy init](https://docs.gradle.org/current/userguide/lazy_configuration.html#working_with_maps) is barely mentioning this very important API I found this API in their _map example_ via `providers.provider({ ... })`.

Since the example are in Kotlin I assumed that `provider` was specific to Kotlin DSL (just as `closure` is). 

I am neither a Groovy/ Gradle or Kotlin expert, I think the migration guide could be a bit more explicit in this matter and offer  groovy based DSL example as well.

Regardless it works. Thanks a lot.

**Comment by hsz** [comment]
Thanks for pointing it out, I'll update the guide page!

**Comment by bric3** [comment]
@hsz Cool thank you !

**Comment by bric3** [comment]
@hsz By the way I also noticed a small difference with `untilBuild`.  Before 1.0 setting untilBuild to null (`untilBuild null`), had the effect to not output the `until-build` attribute in `plugin.xml`; with 1.0 setting it to null (`untilBuild = null`), does not have this effect.

https://github.com/JetBrains/gradle-intellij-plugin/blob/cc1f4672d7e5762e0439ceb1d90089c312f45a0d/src/main/kotlin/org/jetbrains/intellij/tasks/PatchPluginXmlTask.kt#L72-L74

In order to disable `until-build` output one has to write `untilBuild = providers.provider({ null })`. Maybe there's a simpler way.

**Comment by casid** [comment]
@bric3 thank you so much, this finally worked!
