### ISSUE TITLE
After update to 1.0 'version' property inside 'intellij' configuration specifies version of plugin, not IDE, if used without '=' sign

### ISSUE THREAD

**Issue by chashnikov** [JetBrains/gradle-intellij-plugin#687]
Before 1.0 the standard way (it was used in DevKit plugin's template for example) to specify version of the IDE in builld.gradle was the following:
```
intellij {
  version 2021.1
}
```
After updating to version 1.0 of gradle-intellij-plugin, such construction is still valid, but now it specifies version of your project (and therefore the plugin version), not version of the IDE. gradle-intellij-plugin will use some default version of the IDE (`LATEST-EAP-SNAPSHOT` in my case). It may be confusing (I think #684 is actually caused by that). I actually noticed that only when I prepared the plugin archive for deployment.

I think we should at least emphasize in the migration guide that such constructs should be changed to 
```
intellij {
  version = 2021.1
}
```
(currently the guide says nothing about Groovy-based Gradle scripts).
But it may be even better to somehow override `version` function inside `intellij` to show error message in such cases.

**Comment by hsz** [comment]
@chashnikov, thanks for pointing it out – in fact, I've updated Migration Guide with a proper section related to Gradle syntax yesterday:
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/108333/120310600-d9ee6000-c2d6-11eb-9524-fcc478002a7d.png">

WDYT?

**Comment by chashnikov** [comment]
> Any other variations are now forbidden

Well, if the plugin now reports an error for `intellij { version 2020.1}` this is great indeed.

**Comment by gregsh** [comment]
FTR I found this issue only because I knew @chashnikov had some troubles with migration. 
Adding '=' indeed fixed the following problem:

```
intellij {
  version ideaVersion
  type 'IU'
  plugins 'uml', 'java'
  updateSinceUntilBuild false
}


$ gradle clean build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/greg/repos/grammar-kit/build.gradle' line: 46

* What went wrong:
A problem occurred evaluating root project 'grammar-kit'.
> No signature of method: build_apz6tc0dap65l55ne6rb0ac0x.intellij() is applicable for argument types: (build_apz6tc0dap65l55ne6rb0ac0x$_run_closure4) values: [build_apz6tc0dap65l55ne6rb0ac0x$_run_closure4@1a1aa086]
```
