### ISSUE TITLE
1.1.3: `ideaIC-LATEST-EAP-SNAPSHOT/lib/kotlin-stdlib-jdk8.jar: Library has Kotlin runtime bundled into it`

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/gradle-intellij-plugin#691]
I know it's a problem of a snapshot version, so feel free to ignore the issue if you're already aware.

I'm getting the following:

```
> Task :frontendActions:compileKotlin FAILED
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath
e: warnings found and -Werror specified
w: /root/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/f86e416ceecaf64be9309591fffe0ad60c43d486/ideaIC-LATEST-EAP-SNAPSHOT/lib/kotlin-stdlib-jdk8.jar: Library has Kotlin runtime bundled into it

> Task :frontendGraphImpl:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':frontendActions:compileKotlin'.
> Compilation error. See log for more details
```

even though I do NOT depend on LATEST-EAP-SNAPSHOT - I'm building against 2021.1.1.
Actually, why did the plugin even download LATEST-EAP-SNAPSHOT in the first place? 🤔 

This error does NOT happen under 1.0.
It does happen under 1.1 onwards.

**Repro**: https://github.com/VirtusLab/git-machete-intellij-plugin, branch `repro/gip-issue-691`, run `./gradlew buildPlugin` from command line (Java 11 required)

**Comment by hsz** [comment]
The `LATEST-EAP-SNAPSHOT` version is used, because no value was (properly) provided in:

https://github.com/VirtusLab/git-machete-intellij-plugin/blob/439611aab8495a3ae2019bef217a9b6d4f879b2b/build.gradle#L322

You should use `=` sign to correctly assign the value:
```
intellij {
  version = intellijVersions.buildTarget
}
```

**Comment by PawelLipski** [comment]
Right! didn't notice that, fixed and pushed :) still, the same problem now happens with 2021.1.2 :/

```
> Task :frontendActions:compileKotlin FAILED
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath
e: warnings found and -Werror specified
w: /home/plipski/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2021.1.2/47f24d1ca2495e8de3daf528703b86325ee500b1/ideaIC-2021.1.2/lib/kotlin-stdlib-jdk8.jar: Library has Kotlin runtime bundled into it
```

**Comment by PawelLipski** [comment]
Ok, for the record &mdash; not sure now what exact change fixed the issue, but it was some of the changes to Gradle Kotlin config on https://github.com/VirtusLab/git-machete-intellij-plugin/pull/745/files (esp. see `applyKotlinConfig` in build.gradle)

**Comment by qiujiangkun** [comment]
> Ok, for the record — not sure now what exact change fixed the issue, but it was some of the changes to Gradle Kotlin config on https://github.com/VirtusLab/git-machete-intellij-plugin/pull/745/files (esp. see `applyKotlinConfig` in build.gradle)

I found out. It's the removal of the following
```gradle
  tasks.withType(KotlinCompile) {
    // Note that unlike `options.release` for `JavaCompile` tasks,
    // there seems to be no good way to prevent the compiled Kotlin code from using the APIs
    // of whatever Java version is used to run the compiler
    // (https://stackoverflow.com/questions/61266285/set-kotlins-java-api-version-with-gradle).
    kotlinOptions.jvmTarget = javaMajorVersion
  }

```

**Comment by PawelLipski** [comment]
Wow okay, good to know 👍🏻
