### ISSUE TITLE
Unable to build Rider Plugin with 1.0

### ISSUE THREAD

**Issue by Unthrottled** [JetBrains/gradle-intellij-plugin#692]
I'm currently trying to migrate a Rider Plugin of mine from `0.7.3` to `1.0`. There is an issue that started to appear when I tried to build the plugin. Some variant of

```
2021-06-05 12:52:11,152 [   2644]  ERROR - ntellij.idea.ApplicationLoader - Cannot run program "/home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2021.1.3/9afc70d25c6c7730b23aa954766cdaf1460bf480/riderRD-2021.1.3/lib/ReSharperHost/linux-x64/dotnet/dotnet": error=13, Permission denied 
java.io.IOException: Cannot run program "/home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2021.1.3/9afc70d25c6c7730b23aa954766cdaf1460bf480/riderRD-2021.1.3/lib/ReSharperHost/linux-x64/dotnet/dotnet": error=13, Permission denied
```

Shows up in the log, and it fails during `buildSearchableOptions`. When I run `chmod +x /home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2021.1.3/9afc70d25c6c7730b23aa954766cdaf1460bf480/riderRD-2021.1.3/lib/ReSharperHost/linux-x64/dotnet/dotnet": error=13, Permission denied 
java.io.IOException: Cannot run program "/home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2021.1.3/9afc70d25c6c7730b23aa954766cdaf1460bf480/riderRD-2021.1.3/lib/ReSharperHost/linux-x64/dotnet/dotnet` the next time I run the build, it passes. [Here is the suspect build](https://github.com/ani-memes/amii-rider-extension/runs/2752918107?check_suite_focus=true) and [pr](https://github.com/ani-memes/amii-rider-extension/pull/20)

I didn't know where to put this. This didn't happen [in a previous pr](https://github.com/ani-memes/amii-rider-extension/pull/23), however I don't know if I should have put this in youtrack under issues with rider, or if it belongs here. Any clarity/insights are welcome!

**Comment by hsz** [comment]
Thanks for reporting, Alex!
That's a known issue with extracting mechanism of the SDK artifact – no permissions are preserved, so if you try to run any binaries provided with the SDK, it'll fail.
The issue is already fixed – check #681 for more details.
