### ISSUE TITLE
what is listOf?

### ISSUE THREAD

**Issue by XenoAmess** [JetBrains/gradle-intellij-plugin#698]
in https://lp.jetbrains.com/gradle-intellij-plugin/
in ![https://lp.jetbrains.com/static/2021/05/11/112240-0.69247895.png](https://lp.jetbrains.com/static/2021/05/11/112240-0.69247895.png)
 
you said I should use `    plugins.set(listOf("com.intellij.java"))`

but it fails.

The correct answer is `    plugins.set(Arrays.asList("com.intellij.java"))`

please fix the picture, as I don't want another people's 10 minutes wasted like me.

**Comment by hsz** [comment]
@XenoAmess What do you mean by it fails? Any stack trace would be helpful here.
`plugins` property accepts `Iterable`, so both syntaxes are correct – and `listOf` is still a valid one.

**Comment by XenoAmess** [comment]
@hsz
![image](https://user-images.githubusercontent.com/17455337/122086652-7e73b480-ce36-11eb-839c-d780f08c19c4.png)
![image](https://user-images.githubusercontent.com/17455337/122086738-90edee00-ce36-11eb-831f-48f80daea16c.png)
repo at https://github.com/XenoAmess/x8l_idea_plugin

**Comment by hsz** [comment]
Your using Groovy-based Gradle configuration file. `listOf()` is a function available in Kotlin.

As described in the migration guide - _ Restrictive Groovy syntax_, for `build.gradle` the assigning method changed to the `=` only.

In your case that'd be:

```
intellij {
     plugins = ['com.intellij.java']
     version = "202-EAP-SNAPSHOT"
     updateSinceUntilBuild = false
}
````

**Comment by XenoAmess** [comment]
(sigh) seems I must make a choice between shitty groovy and shitty kotlin...
OK, I will stay groovy for a while, until it become fully removed...
I just, hate kotlin more.

**Comment by XenoAmess** [comment]
@hsz thanks for your descriptions anyway.
