### ISSUE TITLE
Will 15.0.3 be available on the jetbrains repo?

### ISSUE THREAD

**Issue by loosebazooka** [JetBrains/gradle-intellij-plugin#70]
Trying to build our plugin against 15.0.3 but get

```
Error:Could not find com.jetbrains.intellij.idea:ideaIC:15.0.3.
Searched in the following locations:
    https://repo1.maven.org/maven2/com/jetbrains/intellij/idea/ideaIC/15.0.3/ideaIC-15.0.3.pom
    https://repo1.maven.org/maven2/com/jetbrains/intellij/idea/ideaIC/15.0.3/ideaIC-15.0.3.jar
    https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/15.0.3/ideaIC-15.0.3.pom
    https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/15.0.3/ideaIC-15.0.3.jar
```

Any idea when it'll be up on the jetbrains repository?

Perhaps this is an issue for the ideac repository?

**Comment by zolotov** [comment]
Hi Appu,

> Any idea when it'll be up on the jetbrains repository?

IDEA 15.0.3 will be available on the jetbrains repository when it will be released.

For release candidate you should you build its build number: 143.1821.5

**Comment by yole** [comment]
It has been released: http://blog.jetbrains.com/idea/2016/01/intellij-idea-15-0-3-update-is-available/

**Comment by zolotov** [comment]
Indeed, thanks @yole

**Comment by zolotov** [comment]
Should be available now, thanks for report
