### ISSUE TITLE
Question: How to configure idea / plugin log severity ?

### ISSUE THREAD

**Issue by bric3** [JetBrains/gradle-intellij-plugin#708]
Hi

I would like to use the logging facility in IDEA, eg in my code use 

```kotlin
package com.github.bric3.plugin.editor;

import com.intellij.openapi.diagnostic.Logger
import com.jetbrains.rd.util.lifetime.Lifetime

class WebView(val lifetime: Lifetime) {
    companion object {
        val logger = Logger.getInstance(WebView::class.java)
```

I understand the run configuration already watches 

```
/Users/brice/opensource/plugin/build/idea-sandbox/system/log/idea.log
```

Ideally this would be in a `prepareSandbox` task ?!

**Comment by halirutan** [comment]
Your question is still a bit vague. So you want to set the log-level for the sandbox from within your Gradle build file? I'm not sure this is possible, but you can set it in the sandbox. Have you read the following [forum post](https://intellij-support.jetbrains.com/hc/en-us/community/posts/203855890-com-intellij-openapi-diagnostic-Logger-debug-statements-are-not-visible-in-the-console)?

**Comment by bric3** [comment]
Hi @halirutan, 

Sorry for the lack of clarity. I know that you can enable debug logs for a category, via this menu of the sand-boxed IDE (got to _Help | Diagnostic Tools | Debug Log Settings..._ then enter `#com.github.bric3.excalidraw`). Yet this is a manual step.

But what I meant is that I would prefer a way to avoid this manual step, and instead generate the necessary config by a gradle task.

I have been looking at the configuration files of the sand-boxed IDE, and this file `./build/idea-sandbox/config/options/other.xml` the entered debug configuration ends up in the element descrabied by this xpath:

```xpath
/application/component[@name='PropertiesComponent']/property[@name='log.debug.categories']
```

In particular for the above setting

```xml
<application>
  <!-- ... -->
  <component name="PropertiesComponent">
    <!-- ... -->
    <property name="log.debug.categories" value="#com.github.bric3.excalidraw" />
  </component>
</application>
```


This could be neat if the `prepareSandbox` task had an api to tweak these settings.

**Comment by halirutan** [comment]
The `DebugLogManager` also reads a system property if it is set. So what you can use in your `gradle.build.kts` is 

```
    runIde {
        systemProperties.put("idea.log.debug.categories", "#de.halirutan.keypromoterx")
    }
```

to turn on debug-logging for the package `de.halirutan.keypromoterx`. Just tested it locally and works like a charm.

**Comment by bric3** [comment]
Ah cool I didn't knew about that !

So I looked at the code, IDEA support passing multiple categories, separated either by a comma or a newline. Source : 
https://github.com/JetBrains/intellij-community/blob/0e2aa4030ee763c9b0c828f0b5119f4cdcc66f35/platform/platform-impl/src/com/intellij/diagnostic/DebugLogManager.kt#L67-L78

**Comment by hsz** [comment]
Thanks, @halirutan, @bric3 – noted with #716
