### ISSUE TITLE
Provide IntelliJ 12.1.7, 13.1.6 builds in the jetbrains intellij-repository

### ISSUE THREAD

**Issue by mplushnikov** [JetBrains/gradle-intellij-plugin#71]
Hello Alexander, great plugin!
I want to use it for my own plugin ([lombok-intellij-plugin](https://github.com/mplushnikov/lombok-intellij-plugin)) build and it works already for IntelliJ 14.1.6, 15.0.3 and EAP builds.
Unfortunatelly I also want to support some previous versions of Intellij, like 12.1.7 or 13.1.6. Currently your plugin can not find and download artifacts for this versions.
Can you please upload it to intellij-repository?

**Could not find com.jetbrains.intellij.idea:ideaIC:13.1.6.**
Searched in the following locations:
    https://repo1.maven.org/maven2/com/jetbrains/intellij/idea/ideaIC/13.1.6/ideaIC-13.1.6.pom
    https://repo1.maven.org/maven2/com/jetbrains/intellij/idea/ideaIC/13.1.6/ideaIC-13.1.6.jar
    https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/13.1.6/ideaIC-13.1.6.pom
    https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/13.1.6/ideaIC-13.1.6.jar

**Comment by yole** [comment]
As stated in #28 we don't plan to support IDEA earlier than version 14 in the plugin.
