### ISSUE TITLE
non-windows builds fail for `RD-` plugin after switch to version 1.0

### ISSUE THREAD

**Issue by nils-a** [JetBrains/gradle-intellij-plugin#711]
After switching to version 1.0 all builds on non-Windows systems fail on with an error [like this](https://github.com/cake-build/cake-rider/pull/158/checks?check_run_id=2922227774#step:9:338):

```
2021-06-26 19:34:55,246 [   2730]  ERROR - ntellij.idea.ApplicationLoader - Cannot run program "/Users/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2020.2.3/f8acdbde5cb99ef34f574da5999989b41406833c/riderRD-2020.2.3/lib/ReSharperHost/macos-x64/dotnet/dotnet": error=13, Permission denied 
java.io.IOException: Cannot run program "/Users/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2020.2.3/f8acdbde5cb99ef34f574da5999989b41406833c/riderRD-2020.2.3/lib/ReSharperHost/macos-x64/dotnet/dotnet": error=13, Permission denied
```

This happens on CI systems, as well as locally. 

The problem seems to be that the file in question is missing the `x` flag; If I run `chmod +x ~/.gradle/caches/modules-2/[...]/dotnet/dotnet` all subsequent builds run successfully. (As long as the cache is valid).

Is it possible version 1.0 does not preserve execute permissions on extraction of the IDE?

**Comment by hsz** [comment]
Fixed with #681
