### ISSUE TITLE
loader constraint violation:  A different class with the same name was previously loaded by com.intellij.ide.plugins.cl.PluginClassLoader

### ISSUE THREAD

**Issue by echopairs** [JetBrains/gradle-intellij-plugin#712]
1. I have two plugins A and B

2. Plugin A depends on B. Both A and B depend on FastJSON 1.2.75.

3. FastJSON 1.2.75 is included in the plugins for A and B. This error is reported at runtime

`com.intellij.diagnostic.PluginException: Cannot load class com.alibaba.fastjson.JSONArray (
  error: loader constraint violation: loader com.intellij.ide.plugins.cl.PluginClassLoader @5feec0b6 wants to load class com.alibaba.fastjson.JSONArray. A different class with the same name was previously loaded by com.intellij.ide.plugins.cl.PluginClassLoader @596d5363. (com.alibaba.fastjson.JSONArray is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @596d5363, parent loader 'bootstrap'),
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Ascend Dev model, id=com.huawei.mindstudio.ascend.ascendModel, descriptorPath=plugin.xml, path=~/code_0604/ascend-ide-plugins/ascend-model/build/idea-sandbox/plugins/ascend-model, version=1.0, package=null), packagePrefix=null, instanceId=41, state=active)
)`

**Comment by YannCebron** [comment]
please report bug at https://youtrack.jetbrains.com/issues/IDEA and include IDE version information
