### ISSUE TITLE
Broken links in FAQ

### ISSUE THREAD

**Issue by aesy** [JetBrains/gradle-intellij-plugin#717]
Hey, I just want to let you know that the `Logs` and `Gradle run configuration` links at the bottom of the [FAQ.md](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/FAQ.md) file are broken. I'd really appreciate if those were updated!

**Comment by rendner** [comment]
The images are correctly displayed when viewing the markdown page in IntelliJ.

Github uses camo to anonymize links as described here: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls
Camo urls are used for the two non working imgaes `Logs` and `Gradle run configuration`.

I checked the steps [described here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls#an-image-is-not-showing-up) for the non working images of the `FAQ.md`.

It looks like the `Content-Type` served by `https://intellij-support.jetbrains.com` for these images causes the problem.

The curl for the `Logs` image:
```console
curl -sI https://intellij-support.jetbrains.com/hc/user_images/GazJhC54rML33MBauVXrww.png | grep -i "^Content-Type:"
```
gives `content-type: text/html; charset=UTF-8`

The curl for the `Gradle run configuration` image:
```console
curl -sI https://intellij-support.jetbrains.com/hc/user_images/qPiO-BjDP_fSIPKJ5VePJA.png | grep -i "^Content-Type:"
```
gives `content-type: text/html; charset=UTF-8`


`text/html` is not an image and isn't in the [list of types supported by Camo](https://github.com/atmos/camo/blob/master/mime-types.json).


The curl for the correct displayed image `Debug Gradle run configuration`:
```console
curl -sI https://cloud.githubusercontent.com/assets/140920/9789780/ca31d9f2-57da-11e5-804b-087b06a6eda9.png | grep -i "^Content-Type:"
```
gives `content-type: image/png`

**Comment by YannCebron** [comment]
Information has been added in textual form to new FAQ page located in SDK docs https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin-faq.html#how-to-show-log-file-of-sandbox-instance
