### ISSUE TITLE
Using other plugins as project dependencies

### ISSUE THREAD

**Issue by alexeykudinkin** [JetBrains/gradle-intellij-plugin#72]
[That](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/groovy/org/jetbrains/intellij/PrepareSandboxTask.groovy#L116) particular line breaks our flow of having 2 separate plugins for Rust and Toml and reusing the latter one as runtime dependency for the former one.

Are there any pitfalls of enabling plugins to embed other plugins into dependency chain?

**Comment by zolotov** [comment]
> Are there any pitfalls of enabling plugins to embed other plugins into dependency chain?

@alexeykudinkin IDEA's class-loader is responsible for loading all plugins and loading their plugin.xml files, and it does it according to certain rules. E.g. if you built-in one plugin into another then plugin.xml of nested plugin won't be loaded. So I guess you're doing something wrong if that line breaks anything. Let's meet today and try to handle this. I'm in 404 room and available after 16:00.

**Comment by zolotov** [comment]
Won't fix. Added extra logging for such cases
