### ISSUE TITLE
The plugin should support the Gradle configuration cache

### ISSUE THREAD

**Issue by eskatos** [JetBrains/gradle-intellij-plugin#725]
The configuration cache is a feature that significantly improves build performance by caching the result of the configuration phase and reusing this for subsequent builds.

Implementing support for the configuration cache in this plugin would improve users experience.

See https://docs.gradle.org/nightly/userguide/configuration_cache.html

The configuration cache was introduced in Gradle 6.6.

**Comment by eskatos** [comment]
Here's a report of the problems found when running with the configuration cache enabled:
![image](https://user-images.githubusercontent.com/132773/124629237-8a74f400-de81-11eb-8057-a137db0c6e73.png)

This is the generated html report that allows you to browse all problems:
[configuration-cache-report.html.zip](https://github.com/JetBrains/gradle-intellij-plugin/files/6771187/configuration-cache-report.html.zip)

**Comment by hsz** [comment]
Fixed with f4da1c8aa59489f4bdf9ee3954b39078ba595a75
