### ISSUE TITLE
Failed to download alternative jbrVersion

### ISSUE THREAD

**Issue by nizienko** [JetBrains/gradle-intellij-plugin#748]
I've tried to `runIde` with a custom jbr version specified in the build.gradle:
```
runIde {
    jbrVersion.set("jb11_0_11-b1568")
}
```
Could not HEAD 'https://d2xrhe97vsfxuc.cloudfront.net/jbr_jcef-jb11_0_11--osx-x64-b1568.tar.gz'. Received status code 403 from server

**Comment by qiujiangkun** [comment]
I'm using `8u202b1483.24`, and it's fine.
Maybe you can use another jbr

**Comment by hsz** [comment]
Looks like, the version you pass shouldn't contain `-` before the `b` part: `jb11_0_11b1568`
However, this build doesn't seem to be available.
