### ISSUE TITLE
Configure buildPlugin to add resulting zip as an archive

### ISSUE THREAD

**Issue by JakeWharton** [JetBrains/gradle-intellij-plugin#75]
We want to retain released versions of the plugin alongside other artifacts built in the project. By configuring the zip as an archive, publishing the project's artifacts to a Maven repo lets the resulting plugin zip to live alongside the released jars from sibling projects in the same build.

It's also a handy way to provide access to the latest "snapshot" zip of the plugin since we auto-publish artifacts from the master branch.

An example is provided by "Example 30.3" here: https://docs.gradle.org/current/userguide/artifact_management.html#fileArtifact

**Comment by JakeWharton** [comment]
Currently achievable via:
```groovy
afterEvaluate {
  def buildPluginTask = tasks.getByName('buildPlugin')
  artifacts {
    archives(buildPluginTask.archivePath) {
      builtBy buildPluginTask
    }
  }
}
```
but it would be nice to have it done automatically.

**Comment by zolotov** [comment]
Hi Jake,

I don't really understand how the plugin could be related to publishing something to maven. The result archive of `buildPlugin` task has no maven structure and is not supposed to be published in any repo but IntelliJ Plugins repository.

So what exactly do you want me to change in the plugin and why should it be a part of `gradle-intellij-pluign`?

**Comment by JakeWharton** [comment]
> The result archive of buildPlugin task has no maven structure and is not supposed to be published in any repo but IntelliJ Plugins repository.

The former is incorrect as it's a binary (and that's all Maven repositories, or Gradle for that matter care about). And I disagree strongly with the latter. Just like when building anything else that's both revision controlled and released, we want to archive old versions. There's tons of good reasons for this: we can install old plugins to verify bugs, users building old versions of projects reliant on IDE integration can install old versions for a hermetic build, and as I mentioned in the original issue we can provide snapshots of the latest zip using a mechanism that's already in place.

Put more simply: Gradle has a mechanisms of informing the build system of the binary outputs of a module and the resulting zip is one of those outputs. Whether it's for archiving in a Maven repository or using to create distribution bundles I think it would make a logical addition to the plugin.

**Comment by zolotov** [comment]
> There's tons of good reasons for this

None of these reasons makes this plugin related to maven publishing. So I repeat the question: what exactly do you want me to change in the plugin and why should it be a part of gradle-intellij-pluign?

**Comment by JakeWharton** [comment]
I already gave reasons and told you what was needed. Declare the zip as an
output artifact of the module.

**Comment by JakeWharton** [comment]
Another positive side-effect: Gradle's standard `assemble` task actually creates the zip instead of having to run a specific task.

**Comment by zolotov** [comment]
> Gradle's standard assemble task actually creates the zip instead of having to run a specific task.

Current plugin version also creates archive on `assemble` task so it doesn't affect this behavior at all.

Well, I made some copy-paste from java plugin, not sure if it works because I still don't understand what exactly you want to achieve so I cannot check how it works.
