### ISSUE TITLE
Frequent "Native file watcher is not executable" warning

### ISSUE THREAD

**Issue by fcurts** [JetBrains/gradle-intellij-plugin#751]
Every time I start a dev instance with the `runIde` task, the following warning pops up:

```
External file changes sync may be slow.
Native file watcher is not executable:
/Users/fcurts/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2020.3.4/b86eac6c6a0550d0f4deca1e3592f7d675034e11/ideaIC-2020.3.4/bin/mac/fsnotifier
```

Can this be fixed?

Plugin version 1.1.4, macOS 11.4

**Comment by hsz** [comment]
Could you please remove the following directory:
```
/Users/fcurts/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2020.3.4
```

It should redownload 2020.3.4, which - as I assume - could be extracted by the plugin in version containing an issue failing on preserving the files permissions.

**Comment by fcurts** [comment]
Deleting `/Users/fcurts/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2020.3.4` didn't suffice (and didn't redownload), but deleting `/Users/fcurts/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea` did.

I think this can be closed. Thanks!
