### ISSUE TITLE
Bundled JBR not being used when runIde task is run with ideDir argument

### ISSUE THREAD

**Issue by grmoon** [JetBrains/gradle-intellij-plugin#756]
**OS:** Mac OS X
**Plugin Version:** 1.1.3

On Mac OS X, running the `runIde` task with `ideDir` param does not automatically use bundled JBR as specified [here](https://plugins.jetbrains.com/docs/intellij/ide-development-instance.html#determining-a-jetbrains-runtime-version).

Using `alternativeIdePath` before it was replaced with `ideDir` in the 1.x release correctly resolved the JBR bundled with the specified IDE and ran the development instance using that JBR.

From what I can tell, this is a result of changes made to `IntelliJPlugin.groovy/IntelliJPlugin.kt`

#### IntelliJPlugin.groovy (Old)

https://github.com/JetBrains/gradle-intellij-plugin/blob/3a07e1ea7cdab9bbec6ab3e7b0c95239fcc62e0b/src/main/groovy/org/jetbrains/intellij/IntelliJPlugin.groovy#L436-L463

#### IntelliJPlugin.kt (New)

https://github.com/JetBrains/gradle-intellij-plugin/blob/530bd504d94960c039222367882addecaa98d522/src/main/kotlin/org/jetbrains/intellij/IntelliJPlugin.kt#L699-L718

**Comment by hsz** [comment]
Thanks for reporting, Gregory! It's fixed and will be available with the upcoming release.
