### ISSUE TITLE
At the very least, should it be more stable according to the official tutorial?

### ISSUE THREAD

**Issue by djif007** [JetBrains/gradle-intellij-plugin#759]
i simply follow the step by this https://plugins.jetbrains.com/docs/intellij/gradle-prerequisites.html ,but it
 cant work ,error are 

> A problem occurred configuring root project 'idea-plugin-v1'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.1.4.
     Required by:
         project : > org.jetbrains.intellij:org.jetbrains.intellij.gradle.plugin:1.1.4
      > No matching variant of org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.1.4 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
          - Variant 'apiElements' capability org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.1.4 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
          - Variant 'runtimeElements' capability org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.1.4 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

my idea is 2021.1.2  and my gradle file is :
plugins {
    id 'java'
    id 'org.jetbrains.intellij' version '1.1.4'
}

group 'org.alibaba.dc.delivery.support'
version '1.0-SNAPSHOT'
//sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
}

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
    version '2021.1.2'
}
patchPluginXml {
    changeNotes """
      Add change notes here.<br>
      <em>most HTML tags may be used</em>"""
}
test {
    useJUnitPlatform()
}

**Comment by diklimchuk** [comment]
I had the same problem when building my library with jitpack: https://jitpack.io/com/github/vivid-money/elmslie/coroutines-support-34f5ff5bd6-1/build.log
I managed to fix it by instructuing jitpack to build with jdk 11. It seems to me that this issue is not releated to the plugin.

**Comment by cherryleafroad** [comment]
I am also encountering this issue. Lowering the version to `1.1.2` has no problem at all. The plugin builds fine for me using `gradlew buildPlugin`, but `gradlew verifyPlugin` crashes with this error

**Comment by cherryleafroad** [comment]
For future Googlers. The solution is this.

----
Make sure your gradle JVM is set to "jbr-11" in IntelliJ, AND **_make sure you have JDK 11 installed on your computer and the env vars pointing to it._**. It may not have been clear enough in some documentations to do this, or for current devs that just updated to new versions (since it was changed abruptly and everything worked before)

Beginning from 1.1.3 this plugin requires JDK 11 on the command line.

**Comment by YannCebron** [comment]
Indeed, Java 11 is now required. README has been updated accordingly.
