### ISSUE TITLE
`RunIdeBase` doesn't resolve `idea.platform.prefix` for PhpStorm

### ISSUE THREAD

**Issue by hsz** [JetBrains/gradle-intellij-plugin#782]
`RunIdeBase` in its `configureSystemProperties` method can't resolve `idea.platform.prefix` using `.sh` files located inside of the IDE instance, i.e. for PhpStorm: 
```
/Users/hsz/Library/ApplicationSupport/JetBrains/Toolbox/apps/PhpStorm/ch-0/212.5080.71/PhpStorm.app/Contents/bin/
```
there are no `.sh` files containing `"-Didea.platform.prefix=([A-z]+)"`

However, there's `Info.plist` file in the `Contents` directory containing:

```
Info.plist:134:        <key>idea.platform.prefix</key>
Info.plist-135-        <string>PhpStorm</string>
```

Maybe that could be used as an alternative way for getting that value?

**Comment by georrge1994** [comment]
same stuff:
`runIde {
    ideDir = file('C:\\Program Files\\Android\\Android Studio')
}`

ext.kotlin_version = "1.4.10"
gradleVersion = "7.0.2"
id 'org.jetbrains.intellij' version '1.1.6'
version = '2020.3.3'

**Comment by yougusen** [comment]
runIde {
       ideDir.set(file("C:\\Program Files\\JetBrains\\PhpStorm 2020.3.2"))
    }
Execution failed for task ':runIde'.
> Cannot find IDE platform prefix. Please create a bug report at https://github.com/jetbrains/gradle-intellij-plugin. As a workaround specify `idea.platform.prefix` system property for task `runIde` manually.

**Comment by ekvedaras** [comment]
Tmp solution:

```kotlin
runIde {
    // ...

    systemProperty("idea.platform.prefix", "PhpStorm") // or other IDE prefix
}
```

**Comment by zolotov** [comment]
duplicates #772
