### ISSUE TITLE
Automatically detect bundled sources in plugin dependency

### ISSUE THREAD

**Issue by artspb** [JetBrains/gradle-intellij-plugin#786]
The Go plugin has a separate `go-openapi.jar` and ships it together with its sources. The plugin now has the following structure:

```
go
  | go-openapi.jar
  | src
    | go-openapi-src.jar
```

I know that some other plugins have the same structure. It'd be great if we can we make gradle-intellij-plugin attach sources automatically.

**Comment by zolotov** [comment]
relates to #207

**Comment by artspb** [comment]
Oh, nice. Might be even a duplicate.

**Comment by YannCebron** [comment]
I like this approach, as it would allow us to provide "open api" sources for _any_ plugin used as dependency, including 3rd party. Without need of Marketplace to provide source artifacts separately.
