### ISSUE TITLE
runPluginVerifier: investigate builtin support for resolving Android Studio as verification target

### ISSUE THREAD

**Issue by YannCebron** [JetBrains/gradle-intellij-plugin#791]
currently, it supports only JB IDEs out of the box

**Comment by mutcianm** [comment]
Has this been implemented?

**Comment by hsz** [comment]
Yes, it's there: https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/test/kotlin/org/jetbrains/intellij/tasks/RunPluginVerifierTaskSpec.kt#L82-L97
