### ISSUE TITLE
Feature: Configuration to download / setup mockJDK

### ISSUE THREAD

**Issue by bric3** [JetBrains/gradle-intellij-plugin#792]
For some tests, a plugin developer has to checkout the intellij-community repository in order to be able to access _mock jdks_. While this checkout can be optimized with `--depth=1`, it still require a significative time and network traffic.

I believe _mock jdks_ should be available on some artefact repository, and this plugin could make them available.

**Current approach**

```shell
git clone --depth 1 https://github.com/JetBrains/intellij-community.git
```

```kotlin
tasks {
    withType<Test> {
        systemProperty("idea.home.path", System.getenv("IDEA_SOURCES") ?: "")
    }
}
```

----------
Official documentation : https://plugins.jetbrains.com/docs/intellij/tests-prerequisites.html#set-the-run-configuration-parameters

**Comment by YannCebron** [comment]
this requires changes in the product/distribution IJSDK-321

**Comment by bric3** [comment]
Indeed, but shouldn't this be tracked on the gradle-intellij-plugin as well ?

**Comment by YannCebron** [comment]
actually it is #477

**Comment by bric3** [comment]
Ahhh thanks, I was searching for "mock JDK" in the issues / PR.
