### ISSUE TITLE
Custom `buildDir` is not respected by gradle-intellij-plugin

### ISSUE THREAD

**Issue by matthewmichihara** [JetBrains/gradle-intellij-plugin#793]
**Repro steps**
1. Clone https://github.com/matthewmichihara/sample-intellij-plugin
2. Run `./gradlew buildPlugin`.

**Expected**
All generated files appear in `/tmp/sample-intellij-plugin/...` because the `buildDir` is set: https://github.com/matthewmichihara/sample-intellij-plugin/blob/main/build.gradle#L13-L15

**Actual**
Most generated files are in `/tmp/sample-intellij-plugin/...`. However, files generated by [intellij.instrumentCode](https://github.com/matthewmichihara/sample-intellij-plugin/blob/main/build.gradle#L25) and [buildSearchableOptions](https://github.com/matthewmichihara/sample-intellij-plugin/blob/main/build.gradle#L37) appear directly in the project's `build` dir instead of in `/tmp/sample-intellij-plugin/...`.

**Comment by hsz** [comment]
Thanks for reporting and providing all the details, Matthew!
It's fixed with 665d410c248dafc738c0a4490f6907386e765dca and should be released very soon.
