### ISSUE TITLE
PluginVerifier: Experimental API method ConfigurableWithId.getId() is overridden

### ISSUE THREAD

**Issue by mvilliger** [JetBrains/gradle-intellij-plugin#800]
When running the PluginVerifier with IU-213.4293.20 I am getting the following errors:

```
Experimental API method com.intellij.openapi.options.ConfigurableWithId.getId() is overridden
Internal method com.intellij.openapi.options.ConfigurableWithId.getId() is overridden
```

I actually implemented com.intellij.openapi.options.SearchableConfigurable and I did override "getId" in there.

As far as I can see in [SearchableConfigurable.java](https://github.com/JetBrains/intellij-community/blob/master/platform/ide-core/src/com/intellij/openapi/options/SearchableConfigurable.java#L112) this method is not marked as experimental and existed since several releases.

But instead its super interface "ConfigurableWithId.java" is [annotated accordingly](https://github.com/JetBrains/intellij-community/blob/master/platform/ide-core/src/com/intellij/openapi/options/ConfigurableWithId.java#L8). It seems that the PluginVerifier reports this because of this? But on "SearchableConfigurable" itself this method seems to be stable? Is this a problem with the verifier or how should this be migrated?

Thanks

**Comment by YannCebron** [comment]
this result was indeed not intended, and will be reverted ASAP. Thanks for reporting
