### ISSUE TITLE
Publish gradle-intellij-plugin sources

### ISSUE THREAD

**Issue by jonnyzzz** [JetBrains/gradle-intellij-plugin#810]
Related to https://youtrack.jetbrains.com/issue/IDEA-280494

I use the IntelliJ plugin SDK plugin in the Gradle project.
Navigation to symbols opens the decompiled declarations, rather than sources.
It breaks us from reading the code comments in the plugin sources, killing all the benefits of `build.gradle.kts`.

It actually seems like we do not publish sources at all, just take a look at:
https://plugins.gradle.org/m2/org/jetbrains/intellij/plugins/gradle-intellij-plugin/1.2.0/

![image](https://user-images.githubusercontent.com/256431/137576881-843e0efb-7ba2-45c3-acaf-df2f7715d341.png)

**Comment by kagof** [comment]
It looks like the `archiveClassifier` lines were removed in [this commit](https://github.com/JetBrains/gradle-intellij-plugin/commit/4363dd6ec08f49436a9c3e0a11cf3d0a2356d936) (perhaps accidentally?). @hsz would it be possible to add these lines back in? 

I'd be happy to raise a PR to do so if you're busy.

**Comment by hsz** [comment]
@kagof Both `sourcesJar` and `javadocJar` have the `archiveClassifier` specified in the upper scope:

https://github.com/JetBrains/gradle-intellij-plugin/blob/master/build.gradle.kts#L124-L135

**Comment by kagof** [comment]
Ah, my mistake, sorry. So I guess it's unknown why the sources aren't being published then?

**Comment by hsz** [comment]
Yeah, TBH I'm confused about that.

**Comment by hsz** [comment]
It turned out this was an issue in `com.gradle.plugin-publish` plugin.
After upgrading it to `1.0.0-rc-2`, all additional artifacts – sources and docs – are now considered.
