### ISSUE TITLE
Impossible to use DCEVM passed as JVM through jbrVersion configuration option

### ISSUE THREAD

**Issue by valb3r** [JetBrains/gradle-intellij-plugin#818]
It is not possible to use DCEVM-based JDK in `runIde` task when configuring it through `jbrVersion` option. 
Version parser:
https://github.com/JetBrains/gradle-intellij-plugin/blob/6e5cf07b634100165f21eb039dd85ed24f32e0b6/src/main/kotlin/org/jetbrains/intellij/jbr/JbrResolver.kt#L204
does not seem to support correct prefix

**Comment by bric3** [comment]
By the way in order to work the plugin should also provision the hotswap agent, right ?

Eg the one downloadable at this location: https://github.com/HotswapProjects/HotswapAgent/releases

**Comment by bric3** [comment]
@hsz I believe this one can be closed as it was delivered in 1.3.0 ?

**Comment by hsz** [comment]
Right, right – housecleaning. :-)
