### ISSUE TITLE
Allow text substitution in plugin.xml values

### ISSUE THREAD

**Issue by cursive-ide** [JetBrains/gradle-intellij-plugin#82]
I've just migrated my plugin to Gradle. One thing that my current Ant build does is to substitute some values (git build info, build date) into the `description` tag. It would be nice to be able to do this automatically. This could probably be generalised to allow substitution into other fields too.

**Comment by zolotov** [comment]
Will be available in `0.2-SNAPSHOT` in few days. There you can customize `description` tag with the following configuration:

```
patchPluginXml {
  pluginDescription = "My description"
}
```
