### ISSUE TITLE
Is it possible to configure multiple `runIde` tasks with different intellij version or type

### ISSUE THREAD

**Issue by bric3** [JetBrains/gradle-intellij-plugin#829]
E.g. I would like to create multiple `runIde` tasks.

And in particular I would to have one that runs with particular settings

Eg one with IntelliJ Ultimate in some versions, one with IU in another version, and one another with  IntelliJ Community, etc.

I don't think it's possible in the current state.

**Comment by hsz** [comment]
Actually, that's possible. If you're reading values for `intellij.version` and `intellij.type` from `gradle.properties` file, like:

```
intellij {
    version.set(project.findProperty("platformVersion").toString())
    type.set(project.findProperty("platformType").toString())
}
```

Then you can pass these values via CLI instead, and it will take precedence over what's stored in the properties file.
```
./gradlew runIde -PplatformType=IU -PplatformVersion=2021.2.2
```

**Comment by bric3** [comment]
Ah indeed. I took the Gradle task definition angle but this looks flexible enough.

**Comment by anusreelakshmi934** [comment]
Instead of passing these values via CLI, can we configure it in build.gradle? 
I Tried the below method but doesn't seem to work:

```
runIde {
    version = "2024.2.4"
}
```

**Comment by bric3** [comment]
For future reference, in 2.x a new task has to be defined this way, (here the created task will be named `runIntelliJUltimate`).

```kotlin
intellijPlatformTesting {
    runIde {
        val runIntelliJUltimate by registering {
            type = IntelliJPlatformType.IntellijIdeaUltimate
            version = "${iuVersion}"

            // or specify a local path
        }
    }
}
```

More here : https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-testing-extension.html#task

**Comment by anusreelakshmi934** [comment]
Thankyou @bric3 . Solved the issue
