### ISSUE TITLE
Could not determine target platform version, please check project setup (bug?)

### ISSUE THREAD

**Issue by Nthily** [JetBrains/gradle-intellij-plugin#841]
Hi, I wrote a `project listener`, but ide have an error `Could not determine target platform version, please check project setup`

![image](https://user-images.githubusercontent.com/31311826/142365845-d7cfba18-ad90-41fd-9b92-abda7296b746.png)

i saw this in the community forum, but my ide is version 2021.3, is this still a bug?

![0517632B247B23D6B37D327E1442F436](https://user-images.githubusercontent.com/31311826/142366012-790f6afb-dcc6-42c6-8545-d04dd7d3d09b.png)

![image](https://user-images.githubusercontent.com/31311826/142366035-37cbd159-27ba-43e8-b090-a86cc79dd4e5.png)

**Comment by hsz** [comment]
@Nthily Which version of the Gradle IntelliJ Plugin do you use? What is your target SDK version?

**Comment by Nthily** [comment]
sorry, I forgot to explain these important things, I am using loadpath to load the idea

plugin.org.jetbrains.intellij = 1.2.1

Local idea information: 

IntelliJ IDEA 2021.2 (Community Edition)
Build #IC-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1900M
Cores: 16
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.github.nthily (1.0.1), com.markskelton.one-dark-theme (5.3.0), com.mallowigi (38.0.0), com.github.copilot (1.0.3), net.mamoe.mirai-console (2.7-M1), org.jetbrains.compose.desktop.ide (1.0.0-beta6-dev462), com.chrisrm.idea.MaterialThemeUI (6.7.2-2021.2)
Kotlin: 212-1.5.10-release-IJ4746.92

**Comment by hsz** [comment]
Could you please provide your Gradle configuration?
BTW, we've released 1.3.0 this week.

**Comment by Nthily** [comment]
`build.gradle.kts`

```
@file:Suppress("SpellCheckingInspection")

plugins {
  kotlin
  id("org.jetbrains.intellij")
  id("org.jetbrains.compose")
  id("idea")
}

repositories {
  maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
  mavenCentral()
  google()
}

intellij {
  pluginName.set(rootProject.name)
  updateSinceUntilBuild.set(false)
  plugins.add("Kotlin")
  // If the intellij path is defined in 'gradle.properties' or 'local.properties' or environment variables, use it.
  findPropertyOrEnv("intellij.path")?.toString()?.let(localPath::set) ?: version.set("2020.3")
}

dependencies {
  implementation(compose.desktop.currentOs)
}
```

**Comment by Nthily** [comment]
https://github.com/compose-museum/compose-code-helper

**Comment by hsz** [comment]
Ok, I've reproduced it – thanks for reporting!
This is a slightly different issue than the one you've mentioned – that one was related to using `LATEST-EAP-SNAPSHOT`, when you're referring to the local instance of the IDE.

**Comment by YannCebron** [comment]
https://youtrack.jetbrains.com/issue/IDEA-274609
