### ISSUE TITLE
Plugin version 1.3.0 depends on org.jetbrains.intellij:blockmap:2.0.16, which doesn't exist in Maven Central

### ISSUE THREAD

**Issue by fcurts** [JetBrains/gradle-intellij-plugin#851]
1.3.0 bumps blockmap from 1.0.5 (which exists in Maven Central) to 2.0.16 (which doesn't). Hence our Gradle build fails to resolve the latter and we can't use 1.3.0.

**Comment by bric3** [comment]
I think this one can be closed since 1.3.1 is released
