### ISSUE TITLE
Instead of using `jbrVersion` to use a JBR variant I propose a `jbrVariant`

### ISSUE THREAD

**Issue by bric3** [JetBrains/gradle-intellij-plugin#852]
Since 1.3.0 we can use multiple variant of the JBR, see #818. However the current approach allow this by specifying the whole version.

This approach has some drawback as it requires plugin developers to make sure the JBR is compatible with the base IntelliJ version, point in case :

If I want to use the latest Java 11 with DCEVM I will likely enter this version `jbr_dcevm-11_0_13b1751.19`, however IntelliJ 2021.1 isn't compatible with this JBR (there's no access to application Preferences). For IntelliJ 2021.1.3 you need to use `jbr_dcevm-11_0_11b1341.60`.

This makes the whole development brittle as this require to constantly check the JBR version matches with current IntelliJ version.

I believe a simpler approach for us to consume is to be able to indicate the runtime _variant_ (`dcevm`, `fastdebug`, etc), and let gradle-intellij-plugin find the correct runtime version.

**Comment by hsz** [comment]
@bric3 Thanks for the suggestion – it's now implemented and will be available with the following `1.4.0` release.

**Comment by bric3** [comment]
Cool thank you @hsz 
Now I'll keep my eyes on the 1.5 hot swap agent (@skybber awesomely added support for IJ).
