### ISSUE TITLE
runPluginVerifier task hardcoded repositories

### ISSUE THREAD

**Issue by 1azyman** [JetBrains/gradle-intellij-plugin#855]
`runPluginVerifier` has hardcoded repository urls:

1. verifier latest version is obtained from `https://cache-redirector.jetbrains.com/packages.jetbrains.team/maven/p/intellij-plugin-verifier/intellij-plugin-verifier/org/jetbrains/intellij/plugins/verifier-cli/maven-metadata.xml`
2. verifier-cli downloaded from `https://cache-redirector.jetbrains.com/packages.jetbrains.team/maven/p/intellij-plugin-verifier/intellij-plugin-verifier`
Could we make these non hardcoded? Whole build can use private nexus repository (using proxy/group repositories via configured `repositories`, `intellijRepository`, `jreRepository`, `pluginsRepositories`. But verifier still goes directly somewhere else.

Can verifier use repositories defined in build.gradle.kts?

**Comment by hsz** [comment]
Thanks for the suggestion, Viliam!
It's implemented and will be released with `1.4.0`.
