### ISSUE TITLE
Custom sandbox directory loses plugin

### ISSUE THREAD

**Issue by ripla** [JetBrains/gradle-intellij-plugin#86]
It seems that defining a custom sandbox directory (e.g. 'sandbox') makes runIdea not to include my plugin. With the default path everything works fine. My original problem which I tried to solve with the custom directory is described by #19.

**Comment by zolotov** [comment]
Cannot recreate, please provide a project sample

**Comment by zolotov** [comment]
@ripla

**Comment by ripla** [comment]
@zolotov see https://github.com/ripla/intellij-plugin-example for an example. Maybe I'm just configuring it wrong?

**Comment by zolotov** [comment]
@ripla use absolute paths for sandbox directory, e.g. `sandboxDirectory "${projectDir.path}/idea-sandbox"`. I'll add the logging about this

**Comment by ripla** [comment]
@zolotov that works, thanks!
