### ISSUE TITLE
Plugin unresolved is not available in Marketplace

### ISSUE THREAD

**Issue by cooker** [JetBrains/gradle-intellij-plugin#866]
Dependencies of cjava 1.1.0 specified in plugin.xml are resolved with respect to IntelliJ IDEA Ultimate IU-213.6461.48. Java 11.0.13 was used for verification.

com.github.cooker.cjava 1.1.0
+--- com.intellij.java 213.6461.48
| +--- com.intellij 213.6461.48 [declaring module com.intellij.modules.platform]
| | +--- (failed) (optional) unresolved: Plugin unresolved is not available in Marketplace https://plugins.jetbrains.com
| | \--- (optional) com.intellij.java 213.6461.48 (*)
| +--- (optional) com.intellij.copyright 213.6461.48
| | \--- com.intellij 213.6461.48 (*) [declaring module com.intellij.modules.lang]
| +--- (optional) com.intellij.platform.images 213.6461.48
| | +--- (failed) (optional) unresolved: Plugin unresolved is not available in Marketplace https://plugins.jetbrains.com
| | +--- com.intellij 213.6461.48 (*) [declaring module com.intellij.modules.lang]
| | \--- (optional) com.intellij.copyright 213.6461.48 (*)
| \--- (optional) training 213.6461.48
| \--- com.intellij 213.6461.48 (*) [declaring module com.intellij.modules.lang]
\--- com.intellij 213.6461.48 (*) [declaring module com.intellij.modules.platform]

**Comment by cooker** [comment]
> plugin.xml



<idea-plugin url="https://plugins.jetbrains.com/plugin/18238-cjava" require-restart="true">

  <id>com.github.cooker.cjava</id>
  <name>cjava</name>
  <vendor url="https://github.com/cooker">Grant</vendor>
  <idea-version since-build="202"/>

  
  <depends>com.intellij.java</depends>
  <depends>com.intellij.modules.platform</depends>
  <depends>com.intellij.modules.lang</depends>
  
  <description>
    <![CDATA[
      Text to display as description on Preferences/Settings
     ]]>
  </description>
  <change-notes>
    <![CDATA[
      <ul>
        <li><b>1.0.0</b> init.</li>
      </ul>
    ]]>
  </change-notes>

  <resource-bundle>messages.CJavaBundle</resource-bundle>

  <actions>
    <group id="EditGroup" class="com.github.cooker.cjava.CustomEditGroup" text="🐟" icon="CJavaIcons.Sdk_default_icon" popup="true">
      <add-to-group group-id="GenerateGroup" anchor="after" relative-to-action="JavaGenerateGroup2"/>
    </group>

    <action id="BeanCopyAction" class="com.github.cooker.cjava.code.BeanCopyAction" icon="CJavaIcons.Sdk_default_icon">
      <add-to-group group-id="EditGroup"/>
    </action>
    <action id="SerialAction" class="com.github.cooker.cjava.code.GenerateSerialVersionUIDAction" text="serialVersionUID">
      <add-to-group group-id="EditGroup"/>
    </action>
    
    <action id="MybatisXmlAction" class="com.github.cooker.cjava.simple.MybatisXmlAction">
      <add-to-group group-id="EditGroup"/>
    </action>
    <action id="LogbackXmlAction" class="com.github.cooker.cjava.simple.LogbackXmlAction">
      <add-to-group group-id="EditGroup"/>
    </action>
    <action id="Log4jXmlAction" class="com.github.cooker.cjava.simple.Log4jXmlAction">
      <add-to-group group-id="EditGroup"/>
    </action>

  </actions>

  <extensions defaultExtensionNs="com.intellij">
    <codeInsight.inlayProvider language="JAVA" implementationClass="com.github.cooker.cjava.code.HintProvider"/>
  </extensions>

</idea-plugin>

**Comment by sczerwinski** [comment]
I think I'm experiencing the same issue, and it starts with IntelliJ platform v2021.2.

All plugin sources from latest release: https://github.com/sczerwinski/wavefront-obj-intellij-plugin/tree/v1.1.0

Results from IntelliJ Plugin Verifier (from https://plugins.jetbrains.com/plugin/14843-wavefront-obj/versions/stable/153175 seen as the plugin author):

Output for v2020.3.4:
```
Dependencies of Wavefront OBJ 1.1.0 specified in plugin.xml are resolved with respect to IntelliJ IDEA Ultimate IU-203.8084.24 (2020.3.4). Java 11.0.10 was used for verification.

it.czerwinski.intellij.wavefront 1.1.0
\--- com.intellij 203.8084.24 [declaring module com.intellij.modules.platform]
```

Output for v2021.1.3:
```
Dependencies of Wavefront OBJ 1.1.0 specified in plugin.xml are resolved with respect to IntelliJ IDEA Ultimate IU-211.7628.21 (2021.1.3). Java 11.0.11 was used for verification.

it.czerwinski.intellij.wavefront 1.1.0
\--- com.intellij 211.7628.21 [declaring module com.intellij.modules.platform]
```

Output for v2021.2.4:
```
Dependencies of Wavefront OBJ 1.1.0 specified in plugin.xml are resolved with respect to IntelliJ IDEA Ultimate IU-212.5712.43 (2021.2.4). Java 11.0.13 was used for verification.

it.czerwinski.intellij.wavefront 1.1.0
\--- com.intellij 212.5712.43 [declaring module com.intellij.modules.platform]
+--- (failed) (optional) unresolved: Plugin unresolved is not available in Marketplace https://plugins.jetbrains.com
\--- (optional) com.intellij.java 212.5712.43
+--- com.intellij 212.5712.43 (*) [declaring module com.intellij.modules.platform]
+--- (optional) com.intellij.copyright 212.5712.43
| \--- com.intellij 212.5712.43 (*) [declaring module com.intellij.modules.lang]
+--- (optional) com.intellij.platform.images 212.5712.43
| +--- com.intellij 212.5712.43 (*) [declaring module com.intellij.modules.lang]
| \--- (optional) com.intellij.copyright 212.5712.43 (*)
\--- (optional) training 212.5712.43
\--- com.intellij 212.5712.43 (*) [declaring module com.intellij.modules.lang]
```

Output for v2021.3.1:
```
Dependencies of Wavefront OBJ 1.1.0 specified in plugin.xml are resolved with respect to IntelliJ IDEA Ultimate IU-213.6461.79 (2021.3.1). Java 11.0.13 was used for verification.

it.czerwinski.intellij.wavefront 1.1.0
\--- com.intellij 213.6461.79 [declaring module com.intellij.modules.platform]
+--- (failed) (optional) unresolved: Plugin unresolved is not available in Marketplace https://plugins.jetbrains.com
\--- (optional) com.intellij.java 213.6461.79
+--- com.intellij 213.6461.79 (*) [declaring module com.intellij.modules.platform]
+--- (optional) com.intellij.copyright 213.6461.79
| \--- com.intellij 213.6461.79 (*) [declaring module com.intellij.modules.lang]
+--- (optional) com.intellij.platform.images 213.6461.79
| +--- (failed) (optional) unresolved: Plugin unresolved is not available in Marketplace https://plugins.jetbrains.com
| +--- com.intellij 213.6461.79 (*) [declaring module com.intellij.modules.lang]
| \--- (optional) com.intellij.copyright 213.6461.79 (*)
\--- (optional) training 213.6461.79
\--- com.intellij 213.6461.79 (*) [declaring module com.intellij.modules.lang]
```

My `gradle.properties` declares no plugin dependencies:
```properties
# Plugin Dependencies -> https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html
# Example: platformPlugins = com.intellij.java, com.jetbrains.php:203.4449.22
platformPlugins =
```

My `plugin.xml` depends only on IntelliJ platform:
```xml
    <depends>com.intellij.modules.platform</depends>
```

It seems more like an issue in Plugin Verifier, or maybe `com.intellij.modules.platform` has some dependencies of its own, which cannot be resolved.

**Comment by cooker** [comment]
> 

// Copyright 2000-2020 JetBrains s.r.o. and other contributors. Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.

plugins {
  id 'java'
  id 'org.jetbrains.intellij' version '1.3.0'
  id "org.jetbrains.kotlin.jvm" version "1.6.10"
}

group 'com.github.cooker'
version '1.1.5'

sourceCompatibility = 11
targetCompatibility = 11

repositories {
  mavenCentral()
  gradlePluginPortal()
}

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
  version = '2021.1.3'
  plugins = ['java']
}

buildSearchableOptions {
  enabled = false
}

patchPluginXml {
  version = project.version
  sinceBuild = '211'
  untilBuild = '213.*'
}

publishPlugin {
  token = System.getenv('ORG_GRADLE_PROJECT_intellijPublishToken')
  channels = ['stable']
}


sourceSets {
  main.kotlin.srcDirs += 'src/main/java'
}

tasks.withType(JavaCompile) {
  options.encoding = "UTF-8"
}

dependencies {
  compile "org.jetbrains.kotlin:kotlin-stdlib"
//  implementation 'org.freemarker:freemarker:2.3.31'
  implementation 'commons-io:commons-io:2.11.0'
  implementation 'org.projectlombok:lombok:1.18.8'
  annotationProcessor 'org.projectlombok:lombok:1.18.8'
}

**Comment by pikachugb** [comment]
Hi @YannCebron,

I have the latest plugin version (1.5.3) and changed from java to ['com.intellij.java'] in the _intellij_ block and still have the same problem:

`Dependencies used on verification
  com.hpe.adm.octane.ideplugins.intellij:2020.2-16.0.400.1
  +--- com.intellij:221.5080.210 [declaring module com.intellij.modules.lang]
   | +--- (failed) unresolved (optional): Plugin unresolved is not available in Marketplace https://plugins.jetbrains.com`

Do you have any ideas why could this still happen? 
Thanks!

**Comment by YannCebron** [comment]
Please continue in https://youtrack.jetbrains.com/issue/MP-4676/Plugin-unresolved-is-not-available-in-Marketplace-bogus-warning
