### ISSUE TITLE
signPlugin fails with NullPointerException

### ISSUE THREAD

**Issue by mwalter** [JetBrains/gradle-intellij-plugin#870]
I followed the tutorial to set up everything needed to publish a plugin to the marketplace. So I added the PUBLISH_TOKEN, PRIVATEE_KEY, CERTIFICATE_CHAIN and PRIVATE_KEY_PASSWORD to the environment variables of the Run Configuration.
When the signPlugin task is executed I always get a NullPointerException: pemObject must not be null.

`
Exception in thread "main" java.lang.NullPointerException: pemObject must not be null
	at org.jetbrains.zip.signer.signer.PrivateKeyUtils.loadKeyPair(PrivateKeyUtils.kt:62)
	at org.jetbrains.zip.signer.signer.PrivateKeyUtils.loadKeyPair(PrivateKeyUtils.kt:48)
	at org.jetbrains.zip.signer.signer.SignerInfoLoader.loadSignerInfoFromText(SignerInfoLoader.kt:30)
	at org.jetbrains.zip.signer.ZipSigningTool.sign(ZipSigningTool.kt:58)
	at org.jetbrains.zip.signer.ZipSigningTool.main(ZipSigningTool.kt:29)
[gradle-intellij-plugin :MavenDependencyChecker:signPlugin] Error during Marketplace ZIP Signer CLI execution:
Exception in thread "main" java.lang.NullPointerException: pemObject must not be null
	at org.jetbrains.zip.signer.signer.PrivateKeyUtils.loadKeyPair(PrivateKeyUtils.kt:62)
	at org.jetbrains.zip.signer.signer.PrivateKeyUtils.loadKeyPair(PrivateKeyUtils.kt:48)
	at org.jetbrains.zip.signer.signer.SignerInfoLoader.loadSignerInfoFromText(SignerInfoLoader.kt:30)
	at org.jetbrains.zip.signer.ZipSigningTool.sign(ZipSigningTool.kt:58)
	at org.jetbrains.zip.signer.ZipSigningTool.main(ZipSigningTool.kt:29)
`

**Comment by hsz** [comment]
@mwalter I have tried reproducing this error, but with no luck. 
After generating `chain.crt` and `private.pem` files as described in [Plugin Signing](https://plugins.jetbrains.com/docs/intellij/plugin-signing.html#generate-private-key) article, everything works well.

Could you please provide more information regarding your setup?

**Comment by mwalter** [comment]
@hsz  thank you very much for your support!

I added the generated chain.crt and private.pem to the IntelliJ Run Configuration by copy & pasting the file contents to the environment section. I found a discussion in a [Jetbrains forum about the problem](https://intellij-support.jetbrains.com/hc/en-us/community/posts/4408839632146-Signing-Plugin-always-throws-NullPointerException-pemObject-must-not-be-null). It has something to do with multiline parsing. The file contents span over multiple lines and and the gradle-intellij-plugin is not able to read the multiline contents from the Run Configuration. I tried to remove all line breaks and still it did not work (same error).

I now use the workaround stated in the forum:
`certificateChain.set(File(System.getenv("CERTIFICATE_CHAIN") ?: "./certs/chain.crt").readText(Charsets.UTF_8))`

But it would be very nice if I could use the Gradle plugin task for signing.

**Comment by hsz** [comment]
This conversion is required – SDK Docs were properly modified.
Thanks for the update, Marc.

**Comment by dinbtechit** [comment]
> @hsz thank you very much for your support!
> 
> I added the generated chain.crt and private.pem to the IntelliJ Run Configuration by copy & pasting the file contents to the environment section. I found a discussion in a [Jetbrains forum about the problem](https://intellij-support.jetbrains.com/hc/en-us/community/posts/4408839632146-Signing-Plugin-always-throws-NullPointerException-pemObject-must-not-be-null). It has something to do with multiline parsing. The file contents span over multiple lines and and the gradle-intellij-plugin is not able to read the multiline contents from the Run Configuration. I tried to remove all line breaks and still it did not work (same error).
> 
> I now use the workaround stated in the forum: `certificateChain.set(File(System.getenv("CERTIFICATE_CHAIN") ?: "./certs/chain.crt").readText(Charsets.UTF_8))`
> 
> But it would be very nice if I could use the Gradle plugin task for signing.

Interesting.. The does not work... checkout the full log here.

```
* What went wrong:
Could not determine the dependencies of task ':publishPlugin'.
> Could not create task ':signPlugin'.
   > valueof(EnvironmentVariableValueSource) (No such file or directory)
```

**Comment by nabato** [comment]
The problem wasn't solved. 

`Exception in thread "main" java.lang.NullPointerException: pemObject must not be null`

**Comment by dinbtechit** [comment]
@nabato - are you facing this issue in github actions or in your local environment?

**Comment by nabato** [comment]
> @nabato - are you facing this issue in github actions or in your local environment?

Both. With base64 encoded private key and with not encoded private key.

**Comment by dinbtechit** [comment]
# To fix github actions. (Follow the below steps)

So basically your certs needs to be base64 encoded. The [documentation](https://plugins.jetbrains.com/docs/intellij/plugin-signing.html#cli-tool) mentions that however, this information is subtle and easy to overlook. 

![image](https://github.com/JetBrains/gradle-intellij-plugin/assets/17984781/82f7d937-c142-4990-8204-d42a8d8aa20d)

### To Convert pem and crt files to base64 string

> Note - Below commands are for MacOS. But could work in other OS if you have openssl installed.

1. create private.pem to Base64 encoded string.
```
openssl enc -A -base64 -in private.pem -out private_base64.pem
cat private_base64.pem
```
**output:**
```
Use copy paste the contents into github -> settings -> security -> secrets and variables -> Respository Sercrets -> PRIVATE_KEY 
```
> Note - Ensure there is no new lines `\n` at the end of each line
----

2. create  chain.crt to Base64 encoded string. 
```
openssl enc -A -base64 -in chain.crt -out chain-base64.crt 
cat private_base64.pem
```
**output:**
```
Use copy paste the contents into github -> settings -> security -> secrets and variables -> Respository Sercrets ->  CERTIFICATE_CHAIN
```

---- 

![image](https://github.com/JetBrains/gradle-intellij-plugin/assets/17984781/dfbb1757-079b-4eea-b6d4-f3c8f593ac79)

**Comment by nabato** [comment]
@dinbtechit, thank you for trying to help. But:
 
> Both. With base64 encoded private key and with not encoded private key.

**Comment by dinbtechit** [comment]
Sorry I misread your comment. 

Let's tackle this with github actions first. For github actions it needs to be base64 encoded. Can you confirm if you have set the PRIVATE key in the right place?

Github Repo -> settings -> security -> secrets and variables -> Repository Secrets -> PRIVATE_KEY

**Comment by nabato** [comment]
@dinbtechit, confirm. I checked that encoded strings don't contain anything like newline characters with https://www.soscisurvey.de/tools/view-chars.php.

<img src="https://github.com/JetBrains/gradle-intellij-plugin/assets/8669892/4e6dbea0-4a49-4d99-90c8-7349b9ce60d3" style="max-width: 100%;" alt="">

**Comment by nabato** [comment]
https://github.com/nabato/alabaster-themes/actions/runs/6619320521/job/17979588487

<img src="https://github.com/JetBrains/gradle-intellij-plugin/assets/8669892/01aac8e8-05b5-42ae-907d-aa90faebf547" alt="" style="max-width: 100%;"/>

**Comment by nabato** [comment]
@dinbtechit, I encoded it on Linux with:

`openssl enc -A -base64 -in private.pem -out private_base64.pem`
`openssl enc -A -base64 -in chain.crt -out chain-base64.crt `

<img src="https://github.com/JetBrains/gradle-intellij-plugin/assets/8669892/6115f9c7-30bf-45fc-99e5-81b0fb187026" alt="" style="max-width: 100%;"/>

**Comment by nabato** [comment]
This issue must be reopened by the plugin team.

**Comment by dinbtechit** [comment]
Someone else on the slack at the same problem because of the encoder. Maybe it is causing due to some other reason then.

![image](https://github.com/JetBrains/gradle-intellij-plugin/assets/17984781/788709b0-0020-4156-8f23-553f4faf94d1)
![image](https://github.com/JetBrains/gradle-intellij-plugin/assets/17984781/a1780eaf-a84a-4dd1-ac67-3ae275760df0)

**Comment by nabato** [comment]
@dinbtechit, I also tried https://www.base64encode.org with no luck. I'm of the opinion that it's not my job to fix @hsz's buggy plugin by trying different random stuff. That's a terrbile work on Jetbrains part and they must fix it.

**Comment by YannCebron** [comment]
@nabato There is no need to call names publicly. Please keep a professional attitude.

**Comment by Drjacky** [comment]
@YannCebron  I still get the error: pemObject must not be null 

gradle plugin version: 1.16.1
