### ISSUE TITLE
Tries to build non-gradle project as gradle proejct and fails every time 

### ISSUE THREAD

**Issue by sryze** [JetBrains/gradle-intellij-plugin#878]
I have a simple Java project that I open in IntelliJ IDEA Ultimate. 

Every time I open it, even after cleaning the .idea folder and all *.iml files, IDEA still tries to build it using Gradle for whatever reason and **fails every single time** because I don't have any Gradle build files in my project at all.

This is annoying...

Here is an example:

```
Starting Gradle Daemon...
Gradle Daemon started in 1 s 364 ms

FAILURE: Build failed with an exception.

* What went wrong:
Executing Gradle tasks as part of a build without a settings file is not supported. Make sure that you are executing Gradle from a directory within your Gradle project. Your project should have a 'settings.gradle(.kts)' file in the root directory.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3sStarting Gradle Daemon...
Gradle Daemon started in 1 s 364 ms

FAILURE: Build failed with an exception.

* What went wrong:
Executing Gradle tasks as part of a build without a settings file is not supported. Make sure that you are executing Gradle from a directory within your Gradle project. Your project should have a 'settings.gradle(.kts)' file in the root directory.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

**Comment by hsz** [comment]
How is that related to the Gradle IntelliJ Plugin?

**Comment by sryze** [comment]
Well, sorry if it's not related, I thought that this plugin handles all Gradle related stuff in IDEA?

**Comment by sryze** [comment]
Sorry, wrong repo 🤦

**Comment by hsz** [comment]
Not really. This project is about the tool used by developers for creating plugins for the IntelliJ-based IDEs.
If your issue is related to how IntelliJ handles the Gradle build system, please file an issue in YouTrack:
https://youtrack.jetbrains.com/newIssue?project=IDEA&c=Subsystem%20Build.%20Gradle
