### ISSUE TITLE
The value of a manifest attribute must not be null (Key=Build-SDK).

### ISSUE THREAD

**Issue by jeppeman** [JetBrains/gradle-intellij-plugin#881]
When configuring prepareSandbox we add some attributes to the jar
manifest, one of which being "Build-SDK" - when using `localPath`, the value of the attribute
is constructed from the contents of product-info.json (a metadata file located in the target IDE directory).
However, when the target IDE is Android Studio, this file does not exist (in recent versions at least), and the value thereby resolves to null; this causes the following error:

> Could not determine the dependencies of task ':prepareSandbox'.
> Failed to query the value of task ':prepareSandbox' property 'pluginJar'.
> The value of a manifest attribute must not be null (Key=Build-SDK).

**Comment by ishepard** [comment]
@jeppeman do you have a quick fix for this while we wait for the PR to be accepted? I'm currently facing this problem and I'm blocked 😄  thanks!

**Comment by ishepard** [comment]
Ah OK got it. For everyone else in this situation: instead of using localpath, use `version: ANDROID_STUDIO_VERSION`.

**Comment by jeppeman** [comment]
@ishepard I've published a version with the fix to an internal artifactory while waiting for a review, otherwise a temporary fix that works is to create a `product-info.json` file in the `Resources` folder of the AS distribution (this could be automated in the build script).

Seems like you found a solution though, which is great, not sure I understand it however :) Is `ANDROID_STUDIO_VERSION` a gradle property, if so, where does it come from?

**Comment by ishepard** [comment]
I followed this tutorial here: https://plugins.jetbrains.com/docs/intellij/android-studio.html#matching-versions-of-the-intellij-platform-with-the-android-studio-version

My version of Android Studio is 2020.3.1, which correspond to build 203.7717.56. So at the end, my build.gradle is:
```
intellij {
    updateSinceUntilBuild = false
//    localPath = '/Applications/Android Studio.app'
    version = '203.7717.56'
}

runIde {
    jvmArgs '-Xmx4g', '-Xms1g'
    ideDir = file('/Applications/Android Studio.app/Contents')
}
```
I don't use localpath anymore, just version.

**Comment by jeppeman** [comment]
Gotcha, yeah - that works too. Although I remember having issues when using `version` previously, it would compile correctly but then certain methods / classes would be missing at runtime when running against an Android Studio distribution. Might have been me just specifying the wrong version though, I'll probably give that another go now.
Thanks!
