### ISSUE TITLE
better idea project generation

### ISSUE THREAD

**Issue by eprst** [JetBrains/gradle-intellij-plugin#89]
Currently `gradle idea` builds a working project, but module's type is set to `JAVA_MODULE`, not `PLUGIN_MODULE` and SDK is set to plain JDK, not Platform Plugin SDK. This means that make works, but there's no way to run/debug it directly from Idea.

Would be nice to have a way to generate fully correct Idea project.

**Comment by zolotov** [comment]
>  module's type is set to JAVA_MODULE
> SDK is set to plain JDK

This is fully correct IDEA project. Actually this is the point of this plugin to avoid using intellij-specific terms and build it on CI/cli/other IDEs/etc.

>This means that make works, but there's no way to run/debug it directly from Idea.

Create gradle run configuration with `runIdea` task and run/debug it directly from IDEA.

**Comment by zolotov** [comment]
See project examples from README, some of them have idea project in VCS with shared run configurations (e.g. intellij-go plugin)
