### ISSUE TITLE
Plugin [id: 'org.jetbrains.intellij', version: '0.7.3'] was not found in any of the following sources:

### ISSUE THREAD

**Issue by yihchu** [JetBrains/gradle-intellij-plugin#893]
`* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'org.jetbrains.intellij', version: '0.7.3'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.intellij:org.jetbrains.intellij.gradle.plugin:0.7.3')
  Searched in the following repositories:
    maven(https://jetbrains.bintray.com/intellij-plugin-service)
    maven2(https://plugins.gradle.org/m2/)`

And I have tried '0.7.2', the error is still here.

**Comment by YannCebron** [comment]
These versions are deprecated. Please _always_ use the latest available version, currently 1.3.1.

**Comment by yihchu** [comment]
> These versions are deprecated. Please _always_ use the latest available version, currently 1.3.1.

Emmm.... Ok, thank you.
