### ISSUE TITLE
Regression: Task runPluginVerifier fails due to using wrong JDK path

### ISSUE THREAD

**Issue by fcurts** [JetBrains/gradle-intellij-plugin#895]
After updating from 1.2.1 to 1.3.1, task `runPluginVerifier` always fails with the following error:

> [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.io.IOException: Cannot run program "/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/jdk/Contents/Home/bin/java" (in directory "/Users/xxx"): error=2, No such file or directory

The correct path is `/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java`. This is the default install location for Temurin (https://adoptium.net) on macOS.

Gradle 7.4 (same problem with 7.3), macOS 12.2

**Comment by hsz** [comment]
Thanks for reporting! It's fixed and will be released with `1.4.0`.
