### ISSUE TITLE
How to make IntelliJ import such Gradle project as PLUGIN_MODULE

### ISSUE THREAD

**Issue by henryju** [JetBrains/gradle-intellij-plugin#9]
I have converted my plugin to use a Gradle build + this plugin. In my company we don't push IDE specific metadata into the SCM so I was trying to clone from scratch.

The problem is when I import such project into IntelliJ it is considered as JAVA_MODULE. What should I do to have it considered as PLUGIN_MODULE?

Is there no way to make IntelliJ "know" this is a plugin project? Maybe we would need a dedicated IntelliJ plugin similar to https://plugins.jetbrains.com/plugin/7127?pr=?

**Comment by zolotov** [comment]
> What should I do to have it considered as PLUGIN_MODULE?

The question is why do you want IDE considers module as PLUGIN_MODULE? :)

**Comment by henryju** [comment]
If it is not typed as "PLUGIN_MODULE" then in module settings there is no "Plugin Deployment" tab (allowing to select src/main/resources/META-INF/plugin.xml as user manifest).

Also and most important, when I try to "run" the project (using a Plugin Run/Debug configuration) then a new IntelliJ instance starts but my plugin doesn't seem to be loaded. Changing manually type of the plugin to PLUGIN_MODULE in .iml file and restarting IntelliJ fix the issue.

**Comment by zolotov** [comment]
> If it is not typed as "PLUGIN_MODULE" then in module settings there is no "Plugin Deployment" tab (allowing to select src/main/resources/META-INF/plugin.xml as user manifest).

It will be implemented in gradle-intelllij-plugin

> Also and most important, when I try to "run" the project (using a Plugin Run/Debug configuration) then a new IntelliJ instance starts but my plugin doesn't seem to be loaded. Changing manually type of the plugin to PLUGIN_MODULE in .iml file and restarting IntelliJ fix the issue.

There is `runIdea` task in this plugin for that

**Comment by henryju** [comment]
> It will be implemented in gradle-intelllij-plugin. Actually there is buildPlugin task that assembles plugin for deployment and I'll implement uploading task later.

OK, cool!

> There is `runIdea` task in this plugin for that

Just tested from command line and that's great. I'm just wondering why this task doesn't appear in IntellIJ? Would be convenient to run it in debug mode (having debugger automatically attached). http://hpics.li/339d984

**Comment by zolotov** [comment]
> Just tested from command line and that's great. I'm just wondering why this task doesn't appear in IntellIJ? 

There is a bug with tasks that contain `idea` substring in the name, fixed in IDEA 15 EAP

> Would be convenient to run it in debug mode (having debugger automatically attached). http://hpics.li/339d984

Running gradle tasks from IDEA produces `Gradle` run configuration and it can be run in debug mode just as any other run configuration.
<img width="535" alt="screenshot 2015-09-10 16 41 16" src="https://cloud.githubusercontent.com/assets/140920/9789780/ca31d9f2-57da-11e5-804b-087b06a6eda9.png">

I believe this issue can be closed, right?

**Comment by henryju** [comment]
Yep, thanks for the details!
