### ISSUE TITLE
Enabling "downloadSources" option leads to plugin test failures

### ISSUE THREAD

**Issue by kshchepanovskyi** [JetBrains/gradle-intellij-plugin#90]
In continue to https://github.com/JetBrains/gradle-intellij-plugin/issues/88

Steps to reproduce:

1. Clone https://github.com/protostuff/protostuff-jetbrains-plugin
2. Run `./gradlew clean build` - build should succeed
3. Comment line `downloadSources = false` in `build.gradle`
4. Run `./gradlew clean build` - build should fail

```
:test

io.protostuff.jetbrains.plugin.formatter.FormatterTest > testDefaultFormatter FAILED
    java.lang.AssertionError

io.protostuff.jetbrains.plugin.formatter.FormatterTest > testTab FAILED
    java.lang.RuntimeException

io.protostuff.jetbrains.plugin.formatter.FormatterTest > testDisableSpaceAroundAssignmentOperator FAILED
    java.lang.RuntimeException

io.protostuff.jetbrains.plugin.formatter.FormatterTest > testCustomIndent FAILED
    java.lang.RuntimeException
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0

10 tests completed, 4 failed, 1 skipped
:test FAILED

FAILURE: Build failed with an exception.
```

Test report: http://ksprojects.org/~ks/temp/jetbrains-test-issue/tests/

**Comment by zolotov** [comment]
Here is dependency tree of test classpath of your project:

```
~/tmp/protostuff-jetbrains-plugin (master) ᐅ gradle dependencies --configuration=testRuntime
:dependencies

------------------------------------------------------------
Root project - Protobuf Plugin for JetBrains IDEs
------------------------------------------------------------

testRuntime - Runtime dependencies for source set 'test'.
+--- org.antlr:antlr4-runtime:4.5.1 -> 4.5.2
+--- org.antlr:antlr4-jetbrains-adapter:1.0.0
|    +--- com.jetbrains:idea:143.381.42 -> 145.258.11
|    +--- org.antlr:antlr4-runtime:4.5.2
|    \--- org.antlr:antlr4:4.5
|         +--- org.antlr:antlr4-runtime:4.5 -> 4.5.2
|         +--- org.antlr:antlr-runtime:3.5.2
|         \--- org.antlr:ST4:4.0.8
|              \--- org.antlr:antlr-runtime:3.5.2
+--- com.google.guava:guava:19.0
+--- io.protostuff:protostuff-parser:2.0.0-alpha17
|    +--- commons-io:commons-io:2.4
|    +--- org.antlr:antlr4:4.5 (*)
|    +--- com.google.guava:guava:18.0 -> 19.0
|    +--- com.google.inject:guice:4.0
|    |    +--- javax.inject:javax.inject:1
|    |    +--- aopalliance:aopalliance:1.0
|    |    \--- com.google.guava:guava:16.0.1 -> 19.0
|    +--- com.google.inject.extensions:guice-multibindings:4.0
|    |    \--- com.google.inject:guice:4.0 (*)
|    +--- com.google.inject.extensions:guice-assistedinject:4.0
|    |    \--- com.google.inject:guice:4.0 (*)
|    \--- org.slf4j:slf4j-api:1.7.10
\--- com.jetbrains:idea:145.258.11

(*) - dependencies omitted (listed previously)

BUILD SUCCESSFUL

Total time: 1.64 secs
```

As you can see `org.antlr:antlr4-jetbrains-adapter` dep requires some `com.jetbrains.idea` dependency which leads to adding sources-jar to runtime classpath. I have no idea what this dependency is but pom-file for `antr4-jetbrains-adapter` indeed contains this dependency (see https://bintray.com/antlr/maven/antlr4-jetbrains-adapter/1.0.0/view#files/org/antlr/antlr4-jetbrains-adapter/1.0.0).

For further investigation please contact @parrt and ping me if some changes on `gradle-intellij-plugin` part are required.

**Comment by kshchepanovskyi** [comment]
No, that is not correct. Neither `build.gradle` or `antr4-jetbrains-adapter` have a runtime dependency on `com.jetbrains:idea::sources`. They do have a dependency on `com.jetbrains:idea`, but it is expected.

**Comment by zolotov** [comment]
```
cat ~/Downloads/antlr4-jetbrains-adapter-1.0.0.pom

<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.antlr</groupId>
  <artifactId>antlr4-jetbrains-adapter</artifactId>
  <version>1.0.0</version>
  <dependencies>
    <dependency>
      <groupId>com.jetbrains</groupId>
      <artifactId>idea</artifactId>
      <version>143.381.42</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.antlr</groupId>
      <artifactId>antlr4-runtime</artifactId>
      <version>4.5.2</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.jetbrains</groupId>
      <artifactId>idea</artifactId>
      <version>143.381.42</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.antlr</groupId>
      <artifactId>antlr4</artifactId>
      <version>4.5</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
```

**Comment by zolotov** [comment]
> They do have a dependency on com.jetbrains:idea, but it is expected.

Why is it expected? What the dependency is it?

**Comment by kshchepanovskyi** [comment]
Create an empty gradle project with `gradle-intellij-plugin`, you will see it there too. It is IntelliJ IDEA dependency, it is added by plugin here: https://github.com/JetBrains/gradle-intellij-plugin/blob/ee9484d358f32cf93ffc5f0a709b3eb8282529a8/src/main/groovy/org/jetbrains/intellij/IntelliJPlugin.groovy#L86

**Comment by zolotov** [comment]
> Create an empty gradle project with gradle-intellij-plugin, you will see it there too.

Empty project works fine. See projects from example section of README, they all work fine with downloading sources, adding `antr4-jetbrains-adapter` leads to the error.

> https://github.com/JetBrains/gradle-intellij-plugin/blob/ee9484d358f32cf93ffc5f0a709b3eb8282529a8/src/main/groovy/org/jetbrains/intellij/IntelliJPlugin.groovy#L86

This line adds source to custom configuration, not in runtime or testRuntime. You can easily check it with `gradle dependencies --configuration=testRuntime
:dependencies` command

**Comment by kshchepanovskyi** [comment]
Normal IDEA dependency:

```groovy
project.dependencies.add(configuration.name, "com.jetbrains.intellij.idea:idea$extension.type:$extension.version")
```

Dependency on sources:
```groovy
project.dependencies.add(sourcesConfiguration.name, "com.jetbrains.intellij.idea:ideaIC:$extension.version:sources@jar")
```

**Comment by kshchepanovskyi** [comment]
Ok, I will try to reproduce it with empty project, trying to isolate problem.

**Comment by zolotov** [comment]
> Normal IDEA dependency

The only reason that this dependency is not attached to your runtime is that it's `zip` dependency

**Comment by zolotov** [comment]
I still don't get what is the `com.jetbrains:idea` in antlr-adapter. If it's real library I can just change idea/ideaSource dependency signature to avoid any conflict, I believe it will fix the problem

**Comment by kshchepanovskyi** [comment]
It comes from here: https://github.com/antlr/jetbrains/pull/7/files#diff-c197962302397baf3a4cc36463dce5ea

https://github.com/kshchepanovskyi/jetbrains/blob/gradle-integration/build.gradle

**Comment by kshchepanovskyi** [comment]
@zolotov sorry, you was right, adding dependency to 

```groovy
dependencies {
    compile 'org.antlr:antlr4-runtime:4.5.1'
    compile 'org.antlr:antlr4-jetbrains-adapter:1.0.0'
}
```

makes tests fail too. Now I have more information, will try to understand what is wrong.

**Comment by kshchepanovskyi** [comment]
Maybe it is related to different `com.intellij:idea` versions.

**Comment by kshchepanovskyi** [comment]
Okay, fixed issue by excluding transitive dependency on different `idea`:

```groovy
dependencies {
    compile ('org.antlr:antlr4-runtime:4.5.1')
    compile ('org.antlr:antlr4-jetbrains-adapter:1.0.0') {
        exclude module: 'idea'
    }
}
```

I will also change https://github.com/antlr/jetbrains/pull/7 to not depend on `idea` in `runtime` scope, it should be something like `provided` scope in maven.

Thank you for assistance!
