### ISSUE TITLE
Can't pass JVM arguments to runIde task

### ISSUE THREAD

**Issue by derteufelqwe** [JetBrains/gradle-intellij-plugin#900]
**Expected behaviour**
I can somehow add arguments to the JVM.

**Actual behaviour**
Tells me that my Argument is unrecognized

**Reproduce the issue**
- Download a DCEVM java 11 jvm from here https://github.com/JetBrains/JetBrainsRuntime/releases
- Download HotswapAgent from here https://github.com/HotswapProjects/HotswapAgent/releases and place it in your java DCEVM install under lib/hotswap/hotswap-agent.jar
- In your plugiin under build.gradle.kts add the following
```
tasks {
    ...
    runIde {
        jvmArgs = listOf("-XX:HotswapAgent=fatjar")
    }
    ...
}
```

What this should do is to enable hotswap agent for the IDE project for advanced code hotswapping.
But with this setup, I get the error that the VM option `HotswapAgent` is not recognized

**Comment by derteufelqwe** [comment]
I've taken a look ath jbr and when specifying it correctly, everything works. Thanks.
Doesn't the IDE get launched with the same JRE I run the gradle / guild tasks with?

**Comment by hsz** [comment]
Would you be able to provide the valid config?

`runIde` task, as well as other ones based on the `RunIdeBase`, use `JbrResolver` to find out which Java Runtime to use.
There are the following cases checked:
- if `runtimeDir` property was provided and exists
- if `jbrVersion` (and optionally `jbrVariant`) is set - then download it
- if `ideDir` is set - use bundled JBR
- if `ideDir` is set - download JBR matching the IDE version
- and if all of the above cases fail - use the JVM used for running Gradle.
