### ISSUE TITLE
intellij plugin development and build.gradle and plugin.xml

### ISSUE THREAD

**Issue by MohaAmiry** [JetBrains/gradle-intellij-plugin#907]
i'm learning intellij plugin development but i can't grasp the REAL different between build.gradle and plugin.xml files for intellij plugin development..

like what are the differences between their dependecies and plugin properities, and relationships between them, and what do i need to learn specifically in gradle to develop intellij plugins, because from plugins i saw, they all have almost the same build.gradle components and fields.

what i need to know:

- the difference between build.gradle dependencies and plugin.xml similarly named properities (dependecies,plugins).
- what dependencies should be wrote in plugin.xml and build.gradle?
- what do i need to study in gradle to start developing intellij plugins ? (It is a HUGE tool).
- any step by step sources for newbies in intellij plugin development? the intellij plugin docs are competelely useless for newbies because of the enormous dipersion in information..

Thanks! :D

**Comment by YannCebron** [comment]
This bugtracker is not suitable for filing support requests, please use channels listed in https://plugins.jetbrains.com/docs/intellij/getting-help.html#problems-with-code-support-issues

Regarding getting started with Gradle, all details are given step-by-step in SDK Docs https://plugins.jetbrains.com/docs/intellij/gradle-build-system.html and following pages. We recommend using https://github.com/JetBrains/intellij-platform-plugin-template which also has extensive documentation of all necessary steps.
