### ISSUE TITLE
Deprecated Gradle features - but I cant figure them out.

### ISSUE THREAD

**Issue by DasLixou** [JetBrains/gradle-intellij-plugin#908]
Hi there!
I created a fresh gradle project with a `build.gradle.kts`:
```kotlin
plugins {
    java
}

group = "de.lixou"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}

tasks.getByName<Test>("test") {
    useJUnitPlatform()
}
```

but i have a problem. When i run my programm with a simple hello world via gradlew.bat, there is no problem.
**BUT:** when I use IntelliJ's Run (Application Configuration) - it throws this warning:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
```

I even upgraded my gradle from 7.2 to 7.4 but it still doenst work. And i also dont have the option to pass the '--warning-mode all' to the **Application Run Configuration**.

**So my question / feature request**: Make it possible to add gradle attributes / tasks to **Application Run Configuration** so I can run _'--warning-mode all'_ to see what i did wrong.

Thanks 😄

**Comment by DasLixou** [comment]
Also its possible that im just stupid and its even possible but i dont know 😆

**Comment by YannCebron** [comment]
This bugtracker is for gradle-intellij-plugin only, not generic Gradle questions. Please use https://intellij-support.jetbrains.com/hc/en-us/community/topics/200382555-IntelliJ-IDEA-Users support forum. AFAIU, these warnings are not critical and cannot be avoided.
