### ISSUE TITLE
listProductsReleases is empty if no until build version is set

### ISSUE THREAD

**Issue by olivernybroe** [JetBrains/gradle-intellij-plugin#909]
I am using the https://github.com/JetBrains/intellij-platform-plugin-template template and I don't have an until build set in my properties file.  
By not doing this, my plugin is installable on all versions that are after the since version.  
However running the `listProductsReleases` results in an empty file when doing this.

**Comment by olivernybroe** [comment]
@hsz Alright, so when I have my properties file the following way
```
pluginSinceBuild = 212
pluginUntilBuild =
```

and then run `patchPluginXml`, it will generate the following `plugin.xml`
```
  <idea-version since-build="212" />
```

When publishing this to the marketplace, it ends up like this
https://plugins.jetbrains.com/plugin/14636-pest/versions/stable/150186
![image](https://user-images.githubusercontent.com/5870441/160086360-e440bc92-232d-4ac2-bd49-1b368e13fff6.png)

Saying that all versions after 212 is supported.  

This now means the plugin can be installed on 212, 213 etc..



However if I run the `listProductsReleases`, my `listProductsReleases.txt` is empty.

**Comment by hsz** [comment]
Thanks for the details – I was able to reproduce it and fix it.

**Comment by madneal** [comment]
@hsz the issue seems not had been fixed

**Comment by hsz** [comment]
Why? Could you please provide more details?

**Comment by madneal** [comment]
@hsz Sorry, I cannot reproduce the issue. But I did came across the same issue as config like the above.  And I have another issue, I am not sure if it's approriate to make it here.
I want to [my plugin](https://github.com/madneal/sec-dog) to compatible with the latest goland release.
![image](https://user-images.githubusercontent.com/12164075/166440911-72f5f596-481a-4718-8fb3-4ae1c983c302.png)
I define as the following:
```
pluginSinceBuild = 211
pluginUntilBuild = 221.*
```
But it generates the error:
```
* What went wrong:
Execution failed for task ':runPluginVerifier'.
> Error while evaluating property 'ides' of task ':runPluginVerifier'
   > Failed to calculate the value of task ':runPluginVerifier' property 'ides'.
      > IDE 'GO-2022.1.2' cannot be downloaded. Please verify the specified IDE version against the products available for testing: https://jb.gg/intellij-platform-builds-list
```
I am not sure why 2022.1.2 version is created by listProductsReleasese. Is there any wrong with the defination. And I really know how `listProductsReleases` generate the versions.
