### ISSUE TITLE
How to exclude `junit.jar` from the IntelliJ SDK

### ISSUE THREAD

**Issue by tangcent** [JetBrains/gradle-intellij-plugin#917]
`build.gradle`:

```gradle
intellij {
    version '2021.1.3'
    pluginName plugin_name
    updateSinceUntilBuild false
    downloadSources true
    sandboxDirectory "idea-sandbox"
    updateSinceUntilBuild false
    sameSinceUntilBuild false

    plugins = ['java']
}
```

I find two jars in the IntelliJ SDK:
<img width="336" alt="image" src="https://user-images.githubusercontent.com/17569144/157152821-6ddd3585-2fb4-41bf-8176-8d2efa8d2fe1.png">
I want to remove the `junit.jar` from the IntelliJ SDK, And keep the `junit4.jar`.
Any help would be very much appreciated. Thank you.

**Comment by hsz** [comment]
@tangcent This is not possible. All libraries provided by the IntelliJ IDEA are delivered within the zip archive with no possibility for exclusion, as in the case of regular Maven dependencies.
However, if you'd even be able to do that – there's no point in doing that. Both `junit.jar` and `junit4.jar` files will be in the classpath anyway during the runtime – when a testing plugin or running in an end-user environment, provided by IDE.
