### ISSUE TITLE
Installation error: Fail to load plugin descriptor from file

### ISSUE THREAD

**Issue by felipewarrener** [JetBrains/gradle-intellij-plugin#926]
When I attempt to install gradle-intellij-plugin-1.4.0.jar using the plugin manager's 'install from disk' option, I get the error:

'Fail to load plugin descriptor from file gradle-intellij-plugin-1.4.0.jar'

This also happens with the 1.3.1 JAR. What could I be doing wrong? There is no 'install' section in the README... Only 'Usage'...

![image](https://user-images.githubusercontent.com/22444578/159938246-a434d193-7a78-4177-88f7-1356f2c9d61e.png)

**Comment by hsz** [comment]
This is not a plugin for IDE but a plugin for Gradle dedicated to plugin development.
