### ISSUE TITLE
Download intellij-jbr/jbr-11_0_2-osx-x64-b159.tar.gz too slow

### ISSUE THREAD

**Issue by CoXier** [JetBrains/gradle-intellij-plugin#946]
I execute ./gradlew runIde in terminal.

> Task :xxxx:runIde
Download https://cache-redirector.jetbrains.com/intellij-jbr/jbr-11_0_2-osx-x64-b159.tar.gz
<============-> 94% EXECUTING [8m 21s]
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> :xxx:runIde > 5.29 MB/111.97 MB downloaded

As you see, the download speed is very slow.

Then I open the link in my browser, it takes me 10s to finish the task.

**Comment by YannCebron** [comment]
do you have some proxies defined in your browser, or any other networking settings?
