### ISSUE TITLE
Check the platformVersion against sinceBuild

### ISSUE THREAD

**Issue by hsz** [JetBrains/gradle-intellij-plugin#950]
Introduce a new check for checking if the major part of the `platformVersion` isn't higher than the `sinceBuild`.

Reason: SDK may bring incompatibility changes between major versions. When targeting higher version, plugin run on the lower platform may crash due to the missing methods used for the implementation.

Examples:

```
platformVersion=2021.1     since build=211 OK
platformVersion=2021.1.3   since build=211 OK
platformVersion=2021.2.1   since build=211 NOT OK
platformVersion=2021.1.3   since build=213 NOT OK
```

**Comment by YannCebron** [comment]
done in 1.9.0 https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#tasks-verifypluginconfiguration
