### ISSUE TITLE
Version 2022.1 will cause a memory leak if the local version is used

### ISSUE THREAD

**Issue by mdddj** [JetBrains/gradle-intellij-plugin#967]
my configuration

```gradle
intellij {
     ....
    localPath = '/Applications/IntelliJ IDEA.app'  // 2022.1
}
```

When my plug-in runs some background tasks and some Ctrip tasks in the background, these processes cannot be killed after restarting the plug-in, which finally causes my computer to freeze

**Comment by hsz** [comment]
@mdddj Could you please provide a minimal reproducible example?

**Comment by mdddj** [comment]
Sorry, I can't reproduce it, now I have switched to the online version and it can be used normally
