### ISSUE TITLE
Is there a  tutorial or quick start?

### ISSUE THREAD

**Issue by Rhain** [JetBrains/gradle-intellij-plugin#97]
I want to learn how to write plugins for Intellij-IDEA, then I find you plugin for IDEA-plugin.

I have read the README of gradle-intellij-plugin,while I wonder is there a tutorial that I can learn how to use you plugin .

Thanks!

**Comment by zolotov** [comment]
Check out [IntelliJ SDK documentation](http://www.jetbrains.org/intellij/sdk/docs/) and Examples section in README
