### ISSUE TITLE
Hot update failure

### ISSUE THREAD

**Issue by mdddj** [JetBrains/gradle-intellij-plugin#973]
Hello, every time I modify the code, and then execute the `runide` command, the UI interface does not change, I don't know what is wrong, the community can't find similar problems

--

Later I tried to use `Tasks->build->clean` before executing `runIde`, it works and the ui interface will also change. However, it will start from scratch, I don't want to be so troublesome, what is the solution method?

**Comment by YannCebron** [comment]
Please specify
- what is "the UI interface"
- version of gradle-intellij-plugin
- ideally, link to your plugin sources to reproduce

**Comment by mdddj** [comment]
I think it has something to with this problem.    https://github.com/JetBrains/gradle-intellij-plugin/issues/959

**Comment by YannCebron** [comment]
thanks, please reopen this issue in other case
