### ISSUE TITLE
Kotlin-generated classes aren't packed into the plugin distribution

### ISSUE THREAD

**Issue by ForNeVeR** [JetBrains/gradle-intellij-plugin#978]
We use 1.6.0-SNAPSHOT, and this version turned out to be problematic.

[This commit](https://github.com/JetBrains/gradle-intellij-plugin/commit/264312c84c91c8b6293fa5d1f1c1fdcc5c9bb322) seems to have broken `buildPlugin`. Only Java-generated classes are now packed, and Kotlin classes aren't.

**Comment by hsz** [comment]
Thanks for reporting, fixed.
