### ISSUE TITLE
Cannot download source for IDEA IC 2016.1.2

### ISSUE THREAD

**Issue by baron1405** [JetBrains/gradle-intellij-plugin#98]
The plugin is failing because it cannot pull down the sources for IntelliJ IDEA 2016.1.2. Specifically, the URL https://s3-eu-west-1.amazonaws.com/intellij-releases/com/jetbrains/intellij/idea/ideaIC/2016.1.1/ideaIC-2016.1.1-sources.jar returns an error whereas the URL for the previous version 2016.1.1 https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2016.1.1/ideaIC-2016.1.1-sources.jar works fine.
I don't think this is a problem with the plugin but it manifests itself there because we are requesting source download. As part of JetBrains, perhaps you can check into this.

**Comment by zolotov** [comment]
@baron1405 it's temporary problem. Use `intellij.downloadSources = false` as a workaround for a while. The sources will be available in two weeks.

**Comment by baron1405** [comment]
Thanks for the quick reply. I also opened YouTrack [IDEA-155966](https://youtrack.jetbrains.com/issue/IDEA-155966)

**Comment by baron1405** [comment]
Just got notified that the source code is now available. Thanks @zolotov for your help.
