### ISSUE TITLE
Must clean before changes are applied for another runIde task

### ISSUE THREAD

**Issue by ng-galien** [JetBrains/gradle-intellij-plugin#990]
I notice I need to run the clean task after some modifications on the plugin.
For example the source code is not up to date when debugging the plugin.
This is painful, especially if the plugin needs some configuration, we have to redo it every time.

The problem appears since I've updated the platform version from 2022.1 to 2022.1.1

**Comment by hsz** [comment]
Alexandre, thanks for raising this issue!
Do I understand it correctly – if you fire the `runIde` task, the plugin gets compiled and run; then you change, i.e., the `platformVersion`, and the plugin isn't recompiled, but it should, right?

**Comment by ng-galien** [comment]
@hsz, since I've updated to platform version 2022.1.1 the plugin is not up to date in the IDE, the I have to run gradle :clean before gradle runIde. Also, running compilation task does not solves the problem anymore.

**Comment by hsz** [comment]
I'm not sure if I reproduce that issue. When invoking the `runIde` on a clean project, we can see:

```
19:14:54: Executing 'runIde'...

> Task :setupDependencies
> Task :patchPluginXml
> Task :processResources
> Task :compileKotlin
> Task :compileJava NO-SOURCE
> Task :classes
> Task :instrumentCode
> Task :postInstrumentCode
> Task :inspectClassesForKotlinIC
> Task :jar
> Task :prepareSandbox

> Task :runIde
```

So sources were compiled and IDE run. Then I update `intellij.version` to `2022.1.1` from any other version and refresh Gradle (we can see this elephant refresh icon in editor):

```
19:19:02: Executing 'setupDependencies'...

> Task :setupDependencies

BUILD SUCCESSFUL in 254ms
1 actionable task: 1 executed
19:19:03: Execution finished 'setupDependencies'.
```

And then `runIde` again:

```
19:19:49: Executing 'runIde'...

> Task :setupDependencies
> Task :patchPluginXml
> Task :processResources
> Task :compileKotlin
> Task :compileJava NO-SOURCE
> Task :classes
> Task :instrumentCode
> Task :postInstrumentCode
> Task :inspectClassesForKotlinIC
> Task :jar
> Task :prepareSandbox

> Task :runIde
```

As you can see, `compileKotlin` was triggered successfully. Any further run skips such a task due to no changes available, like:

```
19:22:06: Executing 'runIde'...

> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :setupDependencies
> Task :patchPluginXml UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :instrumentCode UP-TO-DATE
> Task :postInstrumentCode
> Task :inspectClassesForKotlinIC UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :prepareSandbox UP-TO-DATE

> Task :runIde
```

Maybe you have skipped the Gradle refresh part?

**Comment by ng-galien** [comment]
Mote feedback about the problem, the code changes is updated

> Change on line 40, "test" -> "test_run_after_code_change"

# First run

<img width="635" alt="image" src="https://user-images.githubusercontent.com/33391039/168449470-c8918ae0-0d05-4615-869c-488965c74fb8.png">

- The inline variable is not correct

# Second run (with clean)

<img width="635" alt="image" src="https://user-images.githubusercontent.com/33391039/168449761-44287d9a-ba0e-435c-9958-c3e346be61d2.png">

My code is here on branch 221-dev

https://github.com/ng-galien/idea-plpgdebugger/tree/221-dev

**Comment by mdddj** [comment]
I also have this problem,https://github.com/JetBrains/gradle-intellij-plugin/issues/973  and I have been waiting for the author to update and solve it. It seems that the hot update does not work. When you modify the plug-in code, execute `runide`, but `sandbox ide` has not changed, that is, your The modification didn't work. Using the `clean runide` command can do it, but it doesn't make sense to start over every time 

I hope the author can solve this problem as soon as possible, the development progress has been stagnant,thank you

**Comment by ng-galien** [comment]
@mdddj 
I did not check the closed issues before, the problem looks similar for sure

**Comment by hsz** [comment]
What version of the plugin do you use?
Could you please try the latest `1.6.0-SNAPSHOT` release?

How-to: https://github.com/JetBrains/gradle-intellij-plugin#snapshot-version

**Comment by ng-galien** [comment]
@hsz thanks, will try out

```
plugins {
    // Java support
    id("java")
    // Kotlin support
    id("org.jetbrains.kotlin.jvm") version "1.6.20"
    // Gradle IntelliJ Plugin
    id("org.jetbrains.intellij") version "1.5.3"
    // Gradle Changelog Plugin
    id("org.jetbrains.changelog") version "1.3.1"
    // Gradle Qodana Plugin
    id("org.jetbrains.qodana") version "0.1.13"
}
```

**Comment by mdddj** [comment]
@hsz  `1.6.0-SNAPSHOT` Thanks, everything works fine with this version

**Comment by hsz** [comment]
Thanks for the confirmation!
It'll be publicly released next week.

**Comment by ng-galien** [comment]
@hsz The problem is solved! Thanks for your hard work on it, especially today.
